### ISSUE TITLE
VEP can't detect input format, complaining about start POS or end ID coordinate

### ISSUE THREAD

**Issue by claudiadast** [Ensembl/ensembl-vep#535] opened 2019-07-18 17:59 UTC
VEP is complaining about my input file format. The error I'm getting is:
```
WARNING: Start POS or end ID coordinate invalid on line 1
ERROR: Can't detect input format
```
And the input file looks like:
```
2       22653473        22653473        T/-     +       chr2:22653472:AT:A|.|.|HSB194
2       22653473        22653473        T/-     +       chr2:22653472:AT:A|.|.|HSB195
2       22653473        22653473        T/-     +       chr2:22653472:AT:A|.|.|HSB221
2       22653473        22653473        T/-     +       chr2:22653472:AT:A|.|.|HSB222
2       22653473        22653473        T/-     +       chr2:22653472:AT:A|.|.|HSB223
2       22653473        22653473        T/-     +       chr2:22653472:AT:A|.|.|HSB238
2       22653473        22653473        T/-     +       chr2:22653472:AT:A|.|.|HSB248
2       22653473        22653473        T/-     +       chr2:22653472:AT:A|.|.|HSB260
```

**Comment by ens-lgil** [comment] 2019-07-19 08:15
Dear @claudiadast,

I run VEP with the example you provided ([test_535.txt](https://github.com/Ensembl/ensembl-vep/files/3410089/test_535.txt)) and I didn't get the error.
Please, could you send your command line ? 

Best regards,
Laurent

**Comment by claudiadast** [comment] 2019-07-19 16:03
Sure, my command line looks like:

```
/home/ec2-user/ensembl-vep/vep --assembly GRCh38 --offline --fork 4 --force_overwrite --buffer_size 500 -i tmp.chrY.vcf -o output.vep.chrY.vcf --vcf --no_stats --polyphen p --ccds --numbers --canonical --protein --biotype --uniprot --tsl --appris --per_gene --pick --pick_order canonical,appris,tsl,biotype,ccds,rank,length --distance 1000000 --nearest symbol --symbol -custom /home/ec2-user/custom/phastCons46way.vertebrate.hg19ToHg38.bw,phastCons46wayVt,bigwig,overlap,0 -custom /home/ec2-user/custom/phyloP46way.vertebrate.hg19ToHg38.bw,phyloP46wayVt,bigwig,overlap,0 --plugin LoF
```

**Comment by aparton** [comment] 2019-07-22 14:32
Hi @claudiadast,

I've taken a look at this issue today and I am unable to reproduce it with the file that @ens-lgil linked in his previous response. The only way I am able to reproduce it is if I add an empty line to the start of the input file.

Could you please check if you have a new line at the start of your input file, and if so please remove it and try again? If not, could you please send me the whole input file?

Kind Regards,
Andrew

**Comment by claudiadast** [comment] 2019-07-22 23:27
Hi @aparton,

Thank you for your help! Attached is the first 10 lines of the file (the whole input is too large to attach).

Best,

Claudia
[file.txt](https://github.com/Ensembl/ensembl-vep/files/3419459/file.txt)

**Comment by aparton** [comment] 2019-07-23 10:57
Hi Claudia,

Unfortunately I'm still unable to reproduce this issue with the attached file. I have a couple of questions/suggestions that should help us to diagnose the problem:

1) Which operating system and Perl version are you using?

2) Can you please try adding `--format ensembl` to your input command and trying again? Preventing VEP from having to detect which input format you're using may help in certain situations.

3) If you remove the first few lines of your input file (e.g. `tail -n +5 file.txt > newFile.txt` and run VEP on the new file, what happens?

4) What happens if you run a basic vep command, without all of the extra parameters, with your input file (i.e. `perl vep -i file.txt --cache --force_overwrite`

Kind Regards,
Andrew

**Comment by claudiadast** [comment] 2019-07-24 23:34
Hi @aparton,

1. The OS is an Amazon Linux AMI (launched on AWS) which is `ID_LIKE="rhel fedora"`. The Perl version is `perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux-thread-multi`.

2. When I try this, it says `WARNING: Start START or end END coordinate invalid on line 1`.

3. When I try this, it says `WARNING: Start START or end END coordinate invalid on line 1`.
 
4. When I try this, I get `Exiting the program. The input file appears to be unsorted. Please sort by chromosome and by location and re-submit.`

Best,

Claudia

**Comment by claudiadast** [comment] 2019-07-25 19:03
@aparton, perhaps the script I used to format my VCF into the default VEP format did something wrong. In the following line, are the start and end positions correctly marking a deletion, given the SNP in the last column? 

`2       22653473        22653473        T/-     +       chr2:22653472:AT:A|.|.|HSB194`

**Comment by aparton** [comment] 2019-07-26 09:25
Hi Claudia,

Excellent, we're getting somewhere! The error given when running a basic VEP command (suggestion 4) can be overridden with the flag `--no_check_variants_order`. 

Could you please run your full query with all flags except your two custom annotations and the LoF plugin, while also adding the `--no_check_variants_order` flag. If this is successful, could you please add the custom annotations back in one-by-one to try and identify which of these files is causing your problem.

Kind Regards,
Andrew

**Comment by claudiadast** [comment] 2019-07-26 16:08
Hi Andrew,

So I actually kicked off the following command yesterday and it's still running, which is a good sign! 

```
vep --assembly GRCh38 --offline --fork 4 --force_overwrite --buffer_size 500 -i sorted_segment_aa_2.txt -o sorted_segment_aa_2.annotated.txt --no_stats --polyphen p --ccds --numbers --canonical --protein --biotype --uniprot --tsl --appris --per_gene --pick --pick_order canonical,appris,tsl,biotype,ccds,rank,length --distance 1000000 --nearest symbol --symbol --custom /home/ec2-user/custom/phastCons46way.vertebrate.hg19ToHg38.bw,phastCons46wayVt,bigwig,overlap,0 --custom /home/ec2-user/custom/phyloP46way.vertebrate.hg19ToHg38.bw,phyloP46wayVt,bigwig,overlap,0 --plugin LoF 
```
If that fails, I will try your suggestions above.

Best,
Claudia

**Comment by aparton** [comment] 2019-08-29 14:55
Hi Claudia,

I'm assuming that your VEP command ran successfully - as such I'm going to close this issue now. If you have any other questions, issues or comments, please feel free to reopen it.

Kind Regards,
Andrew

**Closed by aparton** 2019-08-29 14:55 UTC
