### ISSUE TITLE
the gtf  parameter is unavailable

### ISSUE THREAD

**Issue by ghost** [Ensembl/ensembl-vep#666] opened 2019-12-27 03:37 UTC
## Describe the issue

when using GFF/GTF transcript annotations as an annotation source, the VEP cannot proceed.
Error:
Can't locate object method "new" via package "Bio::EnsEMBL::VEP::AnnotationSource::File::GFF" at ~/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/File.pm line 167.

## Additional information
Please fill in the following sections to help us find the source of your issue as quickly as possible.

### System
- VEP version: 98 
- VEP Cache version: 98
- Perl version:  5.26
- OS: Ubuntu
- tabix installed ? y

### Full VEP command line
```
./vep -i input.txt --gtf gtf.gz  -o output.txt ...
```

### Full error message
Can't locate object method "new" via package "Bio::EnsEMBL::VEP::AnnotationSource::File::GFF" at ~/vep/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/File.pm line 167.

**Comment by aparton** [comment] 2020-01-02 11:36
Hi,

Thank you for your query. I've had a look this morning and I'm unable to reproduce this issue. 

Could you please try running your query with this GTF file - ftp://ftp.ensembl.org/pub/release-98/gtf/homo_sapiens/Homo_sapiens.GRCh38.98.gtf.gz - and let me know if you get any errors?

If this file works successfully, could you please send me a sample of your GTF file that reproduces this issue?

Kind Regards,
Andrew

**Comment by liangdyGao** [comment] 2020-01-03 00:45
Sir，&nbsp;
thanks for your anwer&nbsp;


&nbsp; The gtf file I used was download​ from gencode, the version is&nbsp;GRCh37(32). The gtf file the you suggested cannot&nbsp; seem to improve the&nbsp; situation, although the version isnot suitable for my annotation And the problem remains.


&nbsp; I think that the big thing is not the gtf or gff file, but the module which can't create variables via the package.&nbsp;the VEP software was automatically downloaded and installed by git.&nbsp;Therefore, there is room for doubt that&nbsp; the software was not installed correctly.


&nbsp; I am sorry that the problem puzzles you.
Sincerely yours

**Comment by aparton** [comment] 2020-01-03 17:32
Hi,

It looks as if VEP can find some modules within Bio::EnsEMBL::VEP, but not others, which leads me to suspect that something has gone wrong within the installation process. Could you please reinstall the ensembl api by running:

 perl INSTALL.pl --AUTO a

and send me the full output of this command?

Kind Regards,
Andrew

**Comment by liangdyGao** [comment] 2020-01-07 01:18
Sir，

I  reinstalled the ensembl api by running: perl INSTALL.pl --AUTO a. Unfortunately, something went wrong. I had no idea what was happening.

The output is shown below.
        
        I'm sorry that I caused you any trouble.

Sincerely yours
Liangdy



-------------------- EXCEPTION --------------------
MSG: ERROR: Cannot use format gff without Bio::DB::HTS::Tabix module installed

STACK Bio::EnsEMBL::VEP::AnnotationSource::File::new /home/biosoft/soft/lib/vep/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/File.pm:162
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all_custom /home/biosoft/soft/lib/vep/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:228
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all /home/biosoft/soft/lib/vep/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:93
STACK Bio::EnsEMBL::VEP::BaseRunner::get_all_AnnotationSources /home/biosoft/soft/lib/vep/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:175
STACK Bio::EnsEMBL::VEP::Runner::init /home/biosoft/soft/lib/vep/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:123
STACK Bio::EnsEMBL::VEP::Runner::next_output_line /home/biosoft/soft/lib/vep/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:356
STACK toplevel ./t/Runner.t:748
Date (localtime)    = Tue Jan  7 00:19:05 2020
Ensembl API version = 98
---------------------------------------------------
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 255 just after 73.
./t/Runner.t ......................................... Dubious, test returned 255 (wstat 65280, 0xff00)
All 73 subtests passed 
./t/AnnotationSource.t ............................... Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource.t ............................... ok    
./t/Parser_Region.t .................................. Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/Parser_Region.t .................................. ok    
./t/AnnotationSource_Database_StructuralVariation.t .. Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_Database_StructuralVariation.t .. ok    
./t/version.t ........................................ ok   
./t/AnnotationSource_Cache.t ......................... Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_Cache.t ......................... ok   
./t/Utils.t .......................................... ok    
./t/AnnotationSource_Cache_Transcript.t .............. Possible precedence issue with control flow operator at Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_Cache_Transcript.t .............. ok    

Test Summary Report
-------------------
./t/Runner.t                                       (Wstat: 65280 Tests: 73 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
Files=41, Tests=1670, 93 wallclock secs ( 0.22 usr  0.03 sys + 89.17 cusr  2.59 csys = 92.01 CPU)
Result: FAIL
Failed 1/41 test programs. 0/1670 subtests failed.
biosoft@bigsys:~/soft/lib/vep/ensembl-vep$ 




liangdy1314@foxmail.com
 
From: Andrew Parton
Date: 2020-01-04 01:32
To: Ensembl/ensembl-vep
CC: liangdyGao; Author
Subject: Re: [Ensembl/ensembl-vep] the gtf parameter is unavailable (#666)
Hi,
It looks as if VEP can find some modules within Bio::EnsEMBL::VEP, but not others, which leads me to suspect that something has gone wrong within the installation process. Could you please reinstall the ensembl api by running:
perl INSTALL.pl --AUTO a
and send me the full output of this command?
Kind Regards,
Andrew
―

**Comment by aparton** [comment] 2020-01-09 12:09
Hi,

Happy to help! Could you please:

1) Check that the Bio::DB::HTS::Tabix module is located in the ensembl-vep directory at:  /home/biosoft/soft/lib/vep/ensembl-vep/Bio/DB/HTS/Tabix.pm

2) Check that your ensembl-vep folder is included within your PERL5LIB. If not, you can add it with:

export PERL5LIB=${PERL5LIB}:/home/biosoft/soft/lib/vep/ensembl-vep

3) Rerun your initial command, and send me the output if it's still not working correctly?

Kind Regards,
Andrew

**Comment by aparton** [comment] 2021-08-20 09:30
Hi,

I'm going to close this issue now. If you have any further questions, please feel free to reopen it or create a new issue.

Kind Regards,
Andrew

**Closed by aparton** 2021-08-20 09:30 UTC
