### ISSUE TITLE
documentation update (calculated consequences)

### ISSUE THREAD

**Issue by thedam** [Ensembl/ensembl-vep#1132] opened 2022-03-16 10:11 UTC
Hey in new VEP version 105 (Dec 2021) you have added:
3 new Sequence Ontology terms are reported for more detailed splice consequence annotation
splice_donor_5th_base_variant
splice_donor_region_variant
splice_polypyrimidine_tract_variant

however you didn't update this schema: https://grch37.ensembl.org/info/genome/variation/prediction/predicted_data.html

Cheers:)

**Comment by nuno-agostinho** [comment] 2022-03-16 10:20
Hello @thedam,

Thanks for pointing that out! We will update the documentation in release 107.

As this is a duplicate of issue #1128, I will now close this ticket. Please feel free to suggest any more changes you may find appropriate.

Best,
Nuno

**Closed by nuno-agostinho** 2022-03-16 10:20 UTC
Labels: duplicate, documentation
