### ISSUE TITLE
Problem with --pick option and human refseq cache

### ISSUE THREAD

**Issue by nliorni** [Ensembl/ensembl-vep#1180] opened 2022-05-16 09:27 UTC
## Describe the issue
I am using VEP with human refseq caches (v.104 for hg19 and v.106 for hg38).
I am having problems with the --pick option. In particular I am calling and annotating variants on the slc2a1 gene. 
Here I report a minimal example of my output:

when **not** using --pick option (default order)

**Consequence** | **IMPACT** | **SYMBOL**| **Gene**| **BIOTYPE**
intron_variant,intron_variant | MODIFIER,MODIFIER | ,SLC2A1 | CCDS477.1,6513 | protein_coding,protein_coding

when  using --pick option 

**Consequence** | **IMPACT**  | **SYMBOL** | **Gene** | **BIOTYPE**
intron_variant | MODIFIER |                    |  CCDS477.1  | protein_coding

As can be seen, the SYMBOL is not annotated (as if it was not the first choice).

I have tried all --pick-order options without success.

### System
- VEP version: 105
- VEP Cache version: 104
- Perl version: 5.32
- OS: Ubuntu, CentOS
- tabix installed: v0.2.5

**Comment by diegomscoelho** [comment] 2022-05-16 11:50
Hi @nliorni,

I'm not able to reproduce your error yet. Can you provide me:
* Full VEP command;
* Input (if small);

Regards, @diegomscoelho

**Comment by nliorni** [comment] 2022-05-16 11:57
Full VEP command: 
`bcftools view results/MGM08-1562-II_S2/MGM08-1562-II_S2.filter.vcf | vep --per_allele --everything --custom /software/dataseq/databases/ClinVar/hg19/clinvar.vcf.gz,ClinVar,vcf,exact,0,CLNSIG,CLNVCSO,CLNREVSTAT,CLNDN,CLNVC,CLNVI,CLNDISDB,CLNHGVS,ORIGIN,MC,AF_EXAC,AF_ESP,AF_TGP --fork 8 --format vcf --vcf --offline --cache --dir_cache /software/dataseq/databases/vep/hg19_refseq/vep/cache --cache_version 104 --species homo_sapiens_refseq --assembly GRCh37 --dir_plugins /software/dataseq/databases/vep/plugins --plugin dbNSFP,/software/dataseq/databases/dbNSFP/4.1a/hg19/dbNSFP4.1a_grch37.gz,ALL --plugin CADD,/software/dataseq/databases/CADD/hg19/whole_genome_SNVs.tsv.gz --output_file STDOUT --stats_file /path/to/statsfile | bcftools view -Ov > results/{sample}.vep.vcf)  2> logs/vep/{sample}.vepanno.log' 
`
the input vcf:

[sample.filter.vcf.gz](https://github.com/Ensembl/ensembl-vep/files/8699779/sample.filter.vcf.gz)

**Comment by diegomscoelho** [comment] 2022-05-16 15:14
Hi @nliorni,

I saw you used: `--species homo_sapiens_refseq`. This should not be possible (we will look for a fix for that).
You should use: `--species homo_sapiens --refseq` instead. By doing this I was able to get SYMBOL results with or without `--pick` option flag.

Besides that, you are going to need a FASTA assembly for GRCh37 since you are using `--everything`:
http://ftp.ensembl.org/pub/grch37/release-104/fasta/homo_sapiens/dna/

Other tip you don't need to use `bcftools view <your.vcf> | vep`. You can simply use:

`vep -i <your.vcf>`. To be even faster you might bgzip + tabix your VCF.

Regards, @diegomscoelho

**Comment by nliorni** [comment] 2022-05-17 07:03
Thank you so much for your time and help @diegomscoelho, it now seems to work properly.

**Comment by diegomscoelho** [comment] 2022-05-17 07:20
Hi @nliorni,

I will close this issue now. Any other question related to this problem, please, feel free to reopen this issue or open a new one.

Regards, @diegomscoelho

**Closed by diegomscoelho** 2022-05-17 07:20 UTC
