### ISSUE TITLE
VEP version 112 outputs HGVSg substitution instead of deletion for one out of the two alternative allele deletions

### ISSUE THREAD

**Issue by jperales** [Ensembl/ensembl-vep#1653] opened 2024-04-09 14:15 UTC
VEP 111 uses wrongly substitution to describe a deletion of a single nucleotide for the HGVSg notation when the genotype is two alternative allele deletions in the given position. For instance, the genotype (in VCF format):

### Input
```
chr14 103576804 . GG -,G . . 
```

### Using the VEP command line
```
./vep --no_stats --fasta [PATH]/GRCh37.p5_all.fa -id "chr14 103576804 . GG -,G . . ." -o "STDOUT" --tab --assembly GRCh37 --hgvs --hgvsg --offline
```

### It outputs the following HGVSg annotation:
```
#Uploaded_variation     Location        Allele  HGVSg
chr14_103576804_GG/-/G  chr14:103576804-103576805       -       chr14:g.103576804_103576805del
chr14_103576804_GG/-/G  chr14:103576804-103576805       G       chr14:g.103576805G>-
```

As far as I understand from the HGVS documentation, the second one "chr14:g.103576805G>-" must be "chr14:g.103576805Gdel". The substitution must involve 1 nucleotide for another nucleotide and the "-" character is only used for alignments (https://hgvs-nomenclature.org/stable/background/standards/#dna). Thus, deletions of a single nucleotide for genomic notations must be represented as a deletion (https://hgvs-nomenclature.org/stable/recommendations/DNA/deletion/).

I notice that this bug (substitutions for del) does not happen if the genotype is presented for each alternative allele once at a time:

```
❯ ./vep --no_stats --fasta [PATH]/GRCh37.p5_all.fa -id "chr14 103576804 . GG - . . ." -o "STDOUT" --tab --assembly GRCh37 --hgvs --hgvsg --offline | grep -v '##' | cut -f 1,2,3,21 | sort | uniq
#Uploaded_variation     Location        Allele  HGVSg
chr14_103576804_GG/-    chr14:103576804-103576805       -       chr14:g.103576811_103576812del
```
```
❯ ./vep --no_stats --fasta [PATH]/GRCh37.p5_all.fa -id "chr14 103576805 . G - . . ." -o "STDOUT"
 --tab --assembly GRCh37 --hgvs --hgvsg --offline | grep -v '##' | cut -f 1,2,3,21 | sort | uniq
#Uploaded_variation     Location        Allele  HGVSg
chr14_103576805_G/-     chr14:103576805 -       chr14:g.103576812del
```

However, besides deletions, the HGVSg position (coordinates) changes as compared to the previous output. Probably this change is to follow the 3'rule of HGVS (see examples at https://hgvs-nomenclature.org/stable/recommendations/DNA/deletion/). I guess the reported position should always follow the 3'rule regardless of the number of alternative alleles. Is this related to the same or a new issue?

Thank you very much for your great work.
Kind regards,
Javier

### System
- VEP version: 111
- VEP Cache version: none
- Perl version: 5.22
- OS: CentOS
- tabix installed

### Full error message
None

### Data files (if applicable)
Inline examples are provided above.

**Comment by nuno-agostinho** [comment] 2024-04-09 15:57
Hi @jperales, thanks for pointing out this issue. I can reproduce it and will look into it.

Best regards,
Nuno

**Comment by nuno-agostinho** [comment] 2024-04-10 15:50
Hi @stephan-hutter,

Yes, thanks for mentioning that the VCF specifications does not allow to use `-` in the ALT field. I think that there aren't tools that output alleles with `-`.

Anyway, VEP allows `-` in the ALT field because:

1) Other valid input formats in VEP allow `-` (like the [VEP default input](https://grch37.ensembl.org/info/docs/tools/vep/vep_formats.html#default): `chr14 103576804 103576805 GG/-/G +`), so we already take that into account anyway.

2) We do not enforce all VCF rules given that some tools output non-standard VCF files, specially in the case of structural variants. Such is the case for [breakend variants from Illumina Manta](https://github.com/Ensembl/ensembl-vep/pull/1491), where we even accommodate for these non-standard differences.

Hope this helps a bit, but tell me if you want to discuss anything further!

Best regards,
Nuno

**Comment by jperales** [comment] 2024-04-11 04:36
Hi @stephan-hutter & @nuno-agostinho ,
Apologies for bringing the candidate test with wrong VCF specifications. Actually the variant in the original VCF file (GATK Haplotypecaller) follows the correct VCF specifications - as described by @stephan-hutter :

```
chr14 103576803 . CGG C,CG . . .
```

Unfortunately the issue still persists on the variant with the correct specifications (VEP version 111): the use of a substitution to describe a deletion (`chr14:g.103576805G>-`). Could you please reproduce this output below? Please note that I use the corrected input variant now. Interestingly, the issue does NOT happen in VEP version 104. See below for details.

## Output version and annotation by VEP version 111

```
❯ ./vep | head
#----------------------------------#
# ENSEMBL VARIANT EFFECT PREDICTOR #
#----------------------------------#

Versions:
  ensembl              : 111.a6cc543
  ensembl-funcgen      : 111.5327cdd
  ensembl-io           : 111.dbba8d6
  ensembl-variation    : 111.d616b1e
  ensembl-vep          : 111.0

❯ ./vep --no_stats --fasta [PATH]/GRCh37.p5_all.fa -id "chr14 103576803 . CGG C,CG . . ." -o "STDOUT" --tab --assembly GRCh37 --hgvs --hgvsg --offline | grep -v '##' | cut -f 1,2,3,21 | sort | uniq
#Uploaded_variation     Location        Allele  HGVSg
chr14_103576804_GG/-/G  chr14:103576804-103576805       -       chr14:g.103576804_103576805del
chr14_103576804_GG/-/G  chr14:103576804-103576805       G       chr14:g.103576805G>-
```

##  Output version and annotation by VEP version 104

```
❯ ./vep | head
#----------------------------------#
# ENSEMBL VARIANT EFFECT PREDICTOR #
#----------------------------------#

Versions:
  ensembl              : 104.1af1dce
  ensembl-funcgen      : 104.59ae779
  ensembl-io           : 104.1d3bb6e
  ensembl-variation    : 104.6154f8b
  ensembl-vep          : 104.3
❯ ./vep --no_stats --fasta [PATH]/GRCh37.p5_all.fa -id "chr14 103576803 . CGG C,CG . . ." -o "STDOUT" --tab --assembly GRCh37 --hgvs --hgvsg --offline | grep -v '##' | cut -f 1,2,3,21 | sort | uniq
#Uploaded_variation     Location        Allele  HGVSg
chr14_103576804_GG/-/G  chr14:103576804-103576805       -       chr14:g.103576804_103576805del
chr14_103576804_GG/-/G  chr14:103576804-103576805       G       chr14:g.103576805del
```

**Comment by stephan-hutter** [comment] 2024-04-11 08:03
Thanks for the insights @nuno-agostinho.
This is very interesting, as we actually use Manta in our workflows. We haven't tried VEP on it yet, however.

Concerning @jperales variant and to avoid confusion:
I mentioned in my last post that I got correct HGVSg output when entering the variant using the format following VCF specifications.
However, that was using VEP v94, v111 does seem to be broken.

Looking forward to v112!

Best,
Stephan

**Comment by nuno-agostinho** [comment] 2024-04-11 12:19
Hi @jperales,

Yes, `chr14 103576803 . CGG C,CG . . .` is also showing the wrong HGVSg in VEP 111, but the bug fix Ensembl/ensembl-variation#1077 is returning the expected result for that input as well!

Cheers,
Nuno

**Comment by nuno-agostinho** [comment] 2024-05-30 13:31
Hi @jperales,

Unfortunately, we couldn't yet merge the bug fix for those two bugs (https://github.com/Ensembl/ensembl-variation/pull/1077), so VEP 112 still shows the issue reported, as you mention. We intend to fix this for 113.

Sorry for the inconvenience.

Best regards,
Nuno

**Comment by nuno-agostinho** [comment] 2024-09-04 13:37
Hi @jperales and @stephan-hutter,

I hope you are having a great day!

The bug fix https://github.com/Ensembl/ensembl-variation/pull/1077 has now been included in VEP 113, which will be released in a few weeks.

In case you face further problems in VEP, feel free to report them in a new issue.

Best regards,
Nuno

**Closed by nuno-agostinho** 2024-09-04 13:37 UTC
Labels: bug, hgvs, e111, e112
