### ISSUE TITLE
Create fasta index file error

### ISSUE THREAD

**Issue by Lypzero** [Ensembl/ensembl-vep#358] opened 2018-12-24 07:09 UTC
I'd like to run vep on different cluster nodes. However, the fa.index file vep generated on one node always cause error on another node.
The ERROR message：
   
![default](https://user-images.githubusercontent.com/16380457/50392978-cc3f6280-078d-11e9-8089-96a79a273ffa.png)

and this is the linux version of two node:
Linux version 2.6.32-696.30.1.el6.x86_64 (mockbuild@c1bl.rdu2.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-18) (GCC) )

Linux version 2.6.32-696.30.1.el6.x86_64 (mockbuild@c1bl.rdu2.centos.org) (gcc v8) (GCC) )

**Comment by aparton** [comment] 2019-01-04 16:44
Hi,

Thank you for your interest in VEP. Unfortunately I’ve been unable to reproduce your issue.

If your node cannot access your indexed fasta file, you can download a pre-indexed top-level fasta file from our ftp site: ftp://ftp.ensembl.org/pub/release-92/fasta/homo_sapiens/dna_index/ <ftp://ftp.ensembl.org/pub/release-92/fasta/homo_sapiens/dna_index/> 

Failing that, could you please give me some more information on the issue, including:

1) The command you ran to generate this issue
2) How you downloaded the cache and fasta files to be used by VEP.

Kind Regards,
Andrew

**Comment by ens-lgil** [comment] 2019-02-01 10:57
I will close this issue. Please reopen it if you have further questions or start a new issue thread.

**Closed by ens-lgil** 2019-02-01 10:57 UTC
