### ISSUE TITLE
Installation failing for v104

### ISSUE THREAD

**Issue by genomics-geek** [Ensembl/ensembl-vep#1025] opened 2021-07-14 15:38 UTC
I have been trying to install vep, but keep getting this error:

```
 - unpacking ./Bio/tmp/biodbhts.zip to ./Bio/tmp/
./Bio/tmp/Bio-DB-HTS-2.11 - moving files to ./biodbhts
 - making Bio::DB:HTS
Can't exec "/tmp/build/80754af9/perl_1527832170752/_build_env/bin/x86_64-conda_cos6-linux-gnu-gcc": No such file or directory at /home/mag36030/.conda/envs/vep/lib/site_perl/5.26.2/ExtUtils/CBuilder/Base.pm line 342.
Warning: ExtUtils::CBuilder not installed or no compiler detected
Proceeding with configuration, but compilation may fail during Build
```

I am using the latest version 104 and running:

```
perl INSTALL.pl --CONVERT --AUTO acf --CACHEDIR ./.cache/ --SPECIES homo_sapiens --ASSEMBLY GRCh37,GRCh38
```

**Comment by aparton** [comment] 2021-07-15 14:12
Hi @genomics-geek,

Thanks for your query. While I can probably point you in the right direction, we don't officially support installation through Bioconda. While an ensembl-vep Bioconda recipe exists, it wasn't set up by us so you may have more luck asking them for assistance. 

Having said that, it looks as if your setup is unable to find a working C compiler. VEP requires gcc, g++ and make to install correctly, so ensuring that your setup has access to these should fix your issue.

If there's anything else we can do to help, please don't hesitate to ask.

Kind Regards,
Andrew

**Comment by genomics-geek** [comment] 2021-07-15 14:47
Hi @aparton - I am actually not installing the bioconda version.  I was just trying to install using the instructions here:https://useast.ensembl.org/info/docs/tools/vep/script/index.html

I just was trying to install it within a conda environment.  Seems like conda is trying to use a different gcc complier

**Comment by genomics-geek** [comment] 2021-07-15 15:44
So I tried to install it outside of the conda environment, now I get this error:

Downloading required Ensembl API files
 - fetching ensembl
 - unpacking ./Bio/tmp/ensembl.zip
 - moving files
 - getting version information
 - fetching ensembl-variation
 - unpacking ./Bio/tmp/ensembl-variation.zip
 - moving files
 - getting version information
 - fetching ensembl-funcgen
 - unpacking ./Bio/tmp/ensembl-funcgen.zip
 - moving files
 - getting version information
 - fetching ensembl-io
 - unpacking ./Bio/tmp/ensembl-io.zip
 - moving files
 - getting version information

Testing VEP installation
ERROR: Testing VEP script failed with the following error
Attempt to reload Bio/EnsEMBL/IO/Parser.pm aborted.
Compilation failed in require at /usr/share/perl5/vendor_perl/parent.pm line 20.
BEGIN failed--compilation aborted at /local/home/prd_rdip_gene/tools/ensembl-vep/Bio/EnsEMBL/IO/TextParser.pm line 45.
Compilation failed in require at /usr/share/perl5/vendor_perl/parent.pm line 20.
BEGIN failed--compilation aborted at /local/home/prd_rdip_gene/tools/ensembl-vep/Bio/EnsEMBL/IO/ColumnBasedParser.pm line 36.
Compilation failed in require at /usr/share/perl5/vendor_perl/parent.pm line 20.
BEGIN failed--compilation aborted at /local/home/prd_rdip_gene/tools/ensembl-vep/Bio/EnsEMBL/IO/Parser/BaseVCF4.pm line 45.
Compilation failed in require at /usr/share/perl5/vendor_perl/parent.pm line 20.
BEGIN failed--compilation aborted at /local/home/prd_rdip_gene/tools/ensembl-vep/Bio/EnsEMBL/IO/Parser/VCF4.pm line 41.
Compilation failed in require at /local/home/prd_rdip_gene/tools/ensembl-vep/modules/Bio/EnsEMBL/VEP/Parser/VCF.pm line 79.
BEGIN failed--compilation aborted at /local/home/prd_rdip_gene/tools/ensembl-vep/modules/Bio/EnsEMBL/VEP/Parser/VCF.pm line 79.
Compilation failed in require at /local/home/prd_rdip_gene/tools/ensembl-vep/modules/Bio/EnsEMBL/VEP/Parser.pm line 71.
BEGIN failed--compilation aborted at /local/home/prd_rdip_gene/tools/ensembl-vep/modules/Bio/EnsEMBL/VEP/Parser.pm line 71.
Compilation failed in require at /local/home/prd_rdip_gene/tools/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm line 83.
BEGIN failed--compilation aborted at /local/home/prd_rdip_gene/tools/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm line 83.
Compilation failed in require at ./vep line 20.
BEGIN failed--compilation aborted at ./vep line 20.

**Comment by aparton** [comment] 2021-07-22 04:06
Hi @genomics-geek,

I suspect this could be caused by one of two things - either multiple perl versions on your machine, or an issue with the Try::Tiny dependancy.

Could you please try the following and let me know the results?
- Install the Try::Tiny library (you can do this with cpan with the command `cpan install Try::Tiny`
- Check if there are multiple perl versions in your $PATH with `which -a perl`

Kind Regards,
Andrew

**Comment by genomics-geek** [comment] 2021-07-31 14:13
Hi Andrew, yup installing Try:Tiny worked. Thanks!

**Comment by aparton** [comment] 2021-08-06 09:41
Excellent, I'm glad to hear that everything is now up and running. 

I'm going to close this issue now, if you have any further questions please feel free to reopen it, or submit a new issue.

Kind Regards,
Andrew

**Closed by aparton** 2021-08-06 09:41 UTC
