### ISSUE TITLE
VEP installation error with Bio::DB::HTS 

### ISSUE THREAD

**Issue by GenomicsPrograms** [Ensembl/ensembl-vep#733] opened 2020-04-12 23:40 UTC
I have all the pre-requisite packages installed g++, etc and bioperl but nothing resolves this error.

root@avi:/home/ensembl-vep/# perl INSTALL.pl --SPECIES homo_sapiens,homo_sapiens_refseq --ASSEMBLY GRCh38 --AUTO alcfp --PLUGINS all
curl failed (000), trying to fetch using LWP::Simple

Setting up directories
 - fetching BioPerl
 - unpacking ./Bio/tmp/release-1-6-924.zip
 - moving files
Attempting to install Bio::DB::HTS and htslib.

>>> If this fails, try re-running with --NO_HTSLIB

 - checking out HTSLib
fatal: destination path 'htslib' already exists and is not an empty directory.
 - building HTSLIB in ./htslib
In /home/ensembl-vep/htslib
make: Nothing to be done for 'all'.
 - unpacking ./Bio/tmp/biodbhts.zip to ./Bio/tmp/
./Bio/tmp/Bio-DB-HTS-2.11 - moving files to ./biodbhts
 - making Bio::DB:HTS
Created MYMETA.yml and MYMETA.json
Creating new 'Build' script for 'Bio-DB-HTS' version '2.11'
Building Bio-DB-HTS
ERROR: Shared Bio::DB:HTS library not found

## Additional information
Please fill in the following sections to help us find the source of your issue as quickly as possible.

### System
- VEP version: 99
- VEP Cache version: 99
- Perl version: [e.g. 5.26]
- OS: Ubuntu 18.04
 tabix installed Yes

### Full VEP command line
```
perl INSTALL.pl --SPECIES homo_sapiens,homo_sapiens_refseq --ASSEMBLY GRCh38 --AUTO alcfp --PLUGINS all
```

**Comment by aparton** [comment] 2020-04-14 11:08
Hi,

Thanks for this report, VEP seems to be unable to build Bio::DB::HTS, and I suspect that this is caused by one of two issues.

1) Could you please check that the path to your manually downloaded BioPerl is included in your PERL5LIB?

2) Could you please check that you have the perl module Module::Build installed with:

_perl -MModule::Build -le 'print $Module::Build::VERSION'_

Thanks,
Andrew

**Comment by mudappathir** [comment] 2020-07-02 20:13
Hi,

I get same error while installing VEP on GNU/linux.
error building lib/Bio/DB/HTS.o from 'lib/Bio/DB/HTS.c' at /.../perl/perl-5.28.3/lib/5.28.3/ExtUtils/CBuilder/Base.pm line 185.
ERROR: Shared Bio::DB:HTS library not found

As suggested I have checked for the BioPerl path included in PERL5LIB. Here is the output of perl -MModule::Build -le 'print $Module::Build::VERSION' > 0.4231

**Comment by aparton** [comment] 2020-07-06 13:19
Hi @mudappathir,

Thanks for your query. It looks at if the installer is unable to build Bio::DB::HTS for some reason. Could you please send me the full output of INSTALL.pl and I can take a closer look?

Kind Regards,
Andrew

**Comment by nitha26** [comment] 2020-09-30 11:25
@aparton 
I am trying to install VEP in Centos7, but i am getting the same error. I had checked the following things

##installed bioperl by 
``perl -MCPAN -e 'install Bio::Perl'``

``ensembl-vep]# perl -MModule::Build -le 'print $Module::Build::VERSION'``
``0.4005``

`` [root@bratatilab Bio-DB-HTS]# cpan Bio::DB::HTS
Reading '/root/.cpan/Metadata'
  Database was generated on Wed, 30 Sep 2020 00:17:03 GMT
Bio::DB::HTS is up to date (3.01).``


Could you help me what is going wrong while installing VEP

Thank you,
Nitha

**Comment by aparton** [comment] 2020-09-30 12:54
Hi @nitha26,

Could you please update your Module::Build to version 4.2 or higher, and then try again?

If this doesn't work, if you send me the output of your input script then I can take a closer look.

Kind Regards,
Andrew

**Comment by aparton** [comment] 2021-08-20 09:54
Hi,

I'm going to close this issue now. If you have any further questions, please feel free to reopen it or create a new issue.

Kind Regards,
Andrew

**Closed by aparton** 2021-08-20 09:54 UTC
