### ISSUE TITLE
Error while running VEP with singularity SIF file

### ISSUE THREAD

**Issue by kiranpatil222** [Ensembl/ensembl-vep#1430] opened 2023-06-09 09:16 UTC
Hi I tried run VEP through this [Singularity](https://asia.ensembl.org/info/docs/tools/vep/script/vep_download.html#docker)

i used command as follows

```
vcf="/data/shared/clinical/shubham/vep/SRR9306348_Final_filtered.vcf"
Genome_Hg38="/data/shared/clinical/ExomeAnalysis/clinical/Scratch/Resources/Genome/Homo_sapiens_assembly38.fasta"
VEPAnnotation="/data/shared/clinical/LongRead/Programs/VEP/vep_data/"
taskcpus=8
VEPVersion=109

singularity exec vep.sif \
 vep    --species homo_sapiens --assembly GRCh38 --cache_version $VEPVersion \
        --cache --offline --buffer_size 5000 --fork $taskcpus --force_overwrite \
        --input_file $vcf --individual Test_Anno \
        --vcf --output_file Test_Anno_VEP.vcf \
        --dir $VEPAnnotation \
        --variant_class --total_length \
        --sift p --polyphen p --domains \
        --transcript_version --xref_refseq --symbol \
        --hgvs --hgvsg --no_escape \
        --canonical --biotype --mane --numbers \
        --pick --pick_order canonical,mane_select,rank,appris,tsl,biotype,ccds,length

```
I got error as follows
`Unknown option: no_update
Ignoring unsupported option 'no_update' found via ENV variable or INI file
Unknown option: pluginsdir
Ignoring unsupported option 'pluginsdir' found via ENV variable or INI file
Unknown option: no_plugins
Ignoring unsupported option 'no_plugins' found via ENV variable or INI file
Unknown option: no_htslib
Ignoring unsupported option 'no_htslib' found via ENV variable or INI file
ERROR: No valid sample IDs given at /opt/vep/src/ensembl-vep/Bio/EnsEMBL/IO/Parser/BaseVCF4.pm line 844.
        Bio::EnsEMBL::IO::Parser::BaseVCF4::_get_sample_index_list(Bio::EnsEMBL::IO::Parser::VCF4=HASH(0x55cef4f62378), ARRAY(0x55cef4bc6428)) called at /opt/vep/src/ensembl-vep/Bio/EnsEMBL/IO/Parser/BaseVCF4.pm line 804
        Bio::EnsEMBL::IO::Parser::BaseVCF4::get_raw_samples_info(Bio::EnsEMBL::IO::Parser::VCF4=HASH(0x55cef4f62378), ARRAY(0x55cef4bc6428)) called at /opt/vep/src/ensembl-vep/Bio/EnsEMBL/IO/Parser/BaseVCF4.pm line 876
        Bio::EnsEMBL::IO::Parser::BaseVCF4::get_samples_info(Bio::EnsEMBL::IO::Parser::VCF4=HASH(0x55cef4f62378), ARRAY(0x55cef4bc6428), "GT") called at /opt/vep/src/ensembl-vep/Bio/EnsEMBL/IO/Parser/BaseVCF4.pm line 910
        Bio::EnsEMBL::IO::Parser::BaseVCF4::get_samples_genotypes(Bio::EnsEMBL::IO::Parser::VCF4=HASH(0x55cef4f62378), ARRAY(0x55cef4bc6428), 0) called at /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Parser/VCF.pm line 543
        Bio::EnsEMBL::VEP::Parser::VCF::create_individual_VariationFeatures(Bio::EnsEMBL::VEP::Parser::VCF=HASH(0x55cef4f33e68), Bio::EnsEMBL::Variation::VariationFeature=HASH(0x55cef4f634c8), HASH(0x55cef4857000)) called at /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Parser/VCF.pm line 358
        Bio::EnsEMBL::VEP::Parser::VCF::create_VariationFeatures(Bio::EnsEMBL::VEP::Parser::VCF=HASH(0x55cef4f33e68)) called at /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Parser/VCF.pm line 191
        Bio::EnsEMBL::VEP::Parser::VCF::next(Bio::EnsEMBL::VEP::Parser::VCF=HASH(0x55cef4f33e68)) called at /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/InputBuffer.pm line 210
        Bio::EnsEMBL::VEP::InputBuffer::next(Bio::EnsEMBL::VEP::InputBuffer=HASH(0x55cef4f337a8)) called at /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm line 454
        Bio::EnsEMBL::VEP::Runner::_forked_buffer_to_output(Bio::EnsEMBL::VEP::Runner=HASH(0x55cef1303f70), Bio::EnsEMBL::VEP::InputBuffer=HASH(0x55cef4f337a8), undef) called at /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm line 366
        Bio::EnsEMBL::VEP::Runner::next_output_line(Bio::EnsEMBL::VEP::Runner=HASH(0x55cef1303f70)) called at /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm line 207
        Bio::EnsEMBL::VEP::Runner::run(Bio::EnsEMBL::VEP::Runner=HASH(0x55cef1303f70)) called at /opt/vep/src/ensembl-vep/vep line 46`

**Comment by kiranpatil222** [comment] 2023-06-09 09:36
I removed --individual Test_Anno and it wroked

**Comment by nuno-agostinho** [comment] 2023-06-09 10:34
Hey @kiranpatil222, thanks for your question.

You can try giving the full path to `Test_Anno` in Singularity. Tell me if you are having issues making it work.

Best,
Nuno

**Comment by kiranpatil222** [comment] 2023-06-09 10:40
Test_anno for `--individual` is just specifying Sample ID from VCF, its nothing to do with path, if its mutiple Sample in VCF need to give it as all

**Comment by nuno-agostinho** [comment] 2023-06-09 10:49
Hey @kiranpatil222, you are right, I misread the issue, sorry. Is everything working as intended then?

**Comment by kiranpatil222** [comment] 2023-06-09 10:51
Yes it is, thanks

**Comment by nuno-agostinho** [comment] 2023-06-09 11:44
Great! I will close this issue, but feel free to open a new one if you face any other problems.

Have a great day!

Best,
Nuno

**Closed by nuno-agostinho** 2023-06-09 11:44 UTC
Labels: docker/singularity
