### ISSUE TITLE
homo_sapiens not found in --offline mode

### ISSUE THREAD

**Issue by MCH74** [Ensembl/ensembl-vep#680] opened 2020-01-27 09:34 UTC
Hi,
I'm trying to run vep in offline mode on a non-model organism, for which I have GFF and genome sequence files stored locally:
~ensembl-vep/vep --offline -i total_filtered.vcf --gff ~GCF_000214255.1_Bter_1.0_genomic.gff --fasta ~/GCF_000214255.1_Bter_1.0_genomic.fna

But I get this error:
-------------------- EXCEPTION --------------------
MSG: ERROR: Cache directory /home/h/harrisom/.vep/homo_sapiens not found

STACK Bio::EnsEMBL::VEP::CacheDir::dir /local/home/harrisom/Leicester/ensembl-vep/modules/Bio/EnsEMBL/VEP/CacheDir.pm:311
STACK Bio::EnsEMBL::VEP::CacheDir::init /local/home/harrisom/Leicester/ensembl-vep/modules/Bio/EnsEMBL/VEP/CacheDir.pm:227
STACK Bio::EnsEMBL::VEP::CacheDir::new /local/home/harrisom/Leicester/ensembl-vep/modules/Bio/EnsEMBL/VEP/CacheDir.pm:111
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all_from_cache /local/home/harrisom/Leicester/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:115
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all /local/home/harrisom/Leicester/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:91
STACK Bio::EnsEMBL::VEP::BaseRunner::get_all_AnnotationSources /local/home/harrisom/Leicester/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:175
STACK Bio::EnsEMBL::VEP::Runner::init /local/home/harrisom/Leicester/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:123
STACK Bio::EnsEMBL::VEP::Runner::run /local/home/harrisom/Leicester/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:194
STACK toplevel /home/h/harrisom/Leicester/ensembl-vep/vep:224
Date (localtime)    = Mon Jan 27 10:27:27 2020
Ensembl API version = 99
---------------------------------------------------
Thanks for your help,
Mark

**Comment by aparton** [comment] 2020-01-27 12:01
Hi,

Could you please try running VEP without the --offline flag? Running VEP with --gff and --fasta does not require an internet connection, however I suspect that the offline flag is leading to VEP looking for a cache file.

Kind Regards,
Andrew

**Comment by aparton** [comment] 2020-03-24 13:09
Hi,

I'm going to close this ticket now - please feel free to reopen it or create a new one if you have any further questions.

Kind Regards,
Andrew

**Closed by aparton** 2020-03-24 13:09 UTC

**Comment by rollf** [comment] 2020-06-03 15:28
Hi @aparton,

I can confirm the same behaviour. With ``--offline --gff --fasta`` the error is raised ("MSG: ERROR: Cache directory <...>/.vep/homo_sapiens not found"). Without ``--offline`` but with ``--gff --fasta`` it "works". I also want to run in offline mode but do not want to have a cache available.

**Comment by aparton** [comment] 2020-06-03 15:57
Hi @rollf,

Thank you for this report. When you run with `--gff` and `--fasta` without `--offline`, then you are currently working offline as long as you do not also specify `--cache`.

Having just had a look at the documentation, it implies otherwise though, so I'll make some edits to the documentation for the next release.

If you have any more questions, please feel free to open a new ticket.

Kind Regards,
Andrew

**Comment by rollf** [comment] 2020-06-03 15:59
Perfect, thanks for the quick reply!

**Comment by williambrandler** [comment] 2022-02-25 00:50
I am getting the same issue

```
/opt/vep/src/ensembl-vep/vep 
-i $output_vcf_local 
--dir_cache $dircache_file_path_local 
--fasta $dircache_file_path_local/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz 
--plugin AncestralAllele,$dircache_file_path_local/homo_sapiens_ancestor_GRCh38.fa.gz 
--assembly GRCh38 
--format vcf 
--output_file $annotated_vcf_local 
--no_stats 
--vcf 
--hgvs 
--cache 
--offline 
--force_overwrite
```

`MSG: ERROR: Cache directory /root/.vep/homo_sapiens not found
`


On Databricks using Docker to manage the environment. 
Note: this used to work before and now it does not with no changes to the code. 
I assume something has changed in Databricks but I was wondering what the root cause it so I can figure out how to solve the issue
