### ISSUE TITLE
STACK: Error::throw +▒▒I▒..' is 987 != 876 chars.

### ISSUE THREAD

**Issue by masaver** [Ensembl/ensembl-vep#924] opened 2021-02-05 09:27 UTC
Hello ensembl-vep team,

I'm trying to  run the vcf2maf tool (https://github.com/mskcc/vcf2maf), which uses VEP under the hood. The comand vcf2maf is trying to run is this:
`/home/ensembl-vep/vep --species homo_sapiens--ncbi-build --assembly GRCh38 --no_progress --no_stats --buffer_size 5000 --sift b --ccds --uniprot --hgvs --symbol --numbers --domains --gene_phenotype --canonical --protein --biotype --uniprot --tsl --variant_class --shift_hgvs 1 --check_existing --total_length --allele_number --no_escape --xref_refseq --failed 1 --vcf --flag_pick_allele --pick_order canonical,tsl,biotype,rank,ccds,length --dir /home/.vep --fasta /home/.vep/homo_sapiens--ncbi-build/102_GRCh38/ref_fasta/Homo_sapiens.GRCh38.dna.primary_assembly.fa.bgz --format vcf --input_file /home/data/somatic_snvs.vcf --output_file /home/data/somatic_snvs.vep.vcf --offline --pubmed --fork 4 --regulatory`

When running the previous command i get the following error:
`+▒▒I▒..' is 987 != 876 chars.
STACK: Error::throw
STACK: Bio::Root::Root::throw /home/ensembl-vep/Bio/Root/Root.pm:449
STACK: Bio::DB::Fasta::_calculate_offsets /home/ensembl-vep/Bio/DB/Fasta.pm:207
STACK: Bio::DB::IndexedBase::_index_files /home/ensembl-vep/Bio/DB/IndexedBase.pm:648
STACK: Bio::DB::IndexedBase::index_file /home/ensembl-vep/Bio/DB/IndexedBase.pm:484
STACK: Bio::DB::IndexedBase::new /home/ensembl-vep/Bio/DB/IndexedBase.pm:364
STACK: Bio::EnsEMBL::Variation::Utils::FastaSequence::_get_fasta_db /home/ensembl-vep/Bio/EnsEMBL/Variation/Utils/FastaSequence.pm:341
STACK: Bio::EnsEMBL::Variation::Utils::FastaSequence::setup_fasta /home/ensembl-vep/Bio/EnsEMBL/Variation/Utils/FastaSequence.pm:212
STACK: Bio::EnsEMBL::VEP::BaseVEP::fasta_db /home/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseVEP.pm:477
STACK: Bio::EnsEMBL::VEP::Runner::init /home/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:138
STACK: Bio::EnsEMBL::VEP::Runner::run /home/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:203
STACK: /home/ensembl-vep/vep:229
`
What could be the problem here ?

Best,

-Mathias

**Comment by ima23** [comment] 2021-02-05 18:38
Hi @masaver,

Based on the error it looks like there is an issue with retrieving data from the fasta file. Looking at the command I see you are using a custom species `homo_sapiens--ncbi-build` provided by NCBI or vcf2maf. They might be able to help out.
Can  you share an example that reproduces the error using the data provided with VEP? This would help to check if it is an input data issue or not.

Thanks,
Irina

**Comment by ima23** [comment] 2021-03-11 10:37
I will close this issue now. If you have any related questions please feel free to reopen it.

Kind regards,
Irina

**Closed by ima23** 2021-03-11 10:37 UTC
