### ISSUE TITLE
Why running time in 1 cpu core faster than 2 or 3 cpu cores?

### ISSUE THREAD

**Issue by vinhdc10998** [Ensembl/ensembl-vep#1456] opened 2023-07-21 02:48 UTC
## Describe the issue
I was wondering why running time in 1 cpu core faster than 2 or 3 cpu cores with the common command and devices.

Moreover, I tested with ```--fork``` but it slower than without it a lot of times
### System
- VEP version: 108.2
- VEP Cache version: 108
- Perl version: 5, version 26,
- OS: Ubuntu 22.04

### Full VEP command line
Command in 1 cpu core: 
```
time /vagrant/ensembl-vep/vep --offline --cache --no_stats --force_overwrite --dir_cache /vagrant/.vep --vcf --af --appris --biotype --check_existing --distance 5000 --mane --polyphen b --pubmed --regulatory --sift b --species homo_sapiens --symbol --transcript_version --tsl --fasta /vagrant/Homo_sapiens_assembly38.fasta -i /vagrant/Data/1KGP.chr22.vcf.gz  -o /vagrant/1kgp.chr22.vep_1.vcf.gz
```
Command in 2/ 3 cpu cores:
```
time /vagrant/ensembl-vep/vep --offline --cache --no_stats --force_overwrite --dir_cache /vagrant/.vep --vcf --af --appris --biotype --check_existing --distance 5000 --mane --polyphen b --pubmed --regulatory --sift b --species homo_sapiens --symbol --transcript_version --tsl --fasta /vagrant/Homo_sapiens_assembly38.fasta -i /vagrant/Data/1KGP.chr22.vcf.gz  -o (/vagrant/1kgp.chr22.vep_2/ 3.vcf.gz)
```

### Data files (if applicable)
- The input file: 1KGP - chromosome 22 - grch38 with 1 sample

Thanks in advance!

**Comment by nuno-agostinho** [comment] 2023-07-21 15:51
Hey @vinhdc10998, I hope your day is going great!

There a lot of factors that affect multi-core settings, such as overhead time to setup, manage and combine data between multi-core processing, as well as core availability/differences if using a computing cluster.

I will try running some tests based on your input and commands to see if something unexpected is going on.

Thanks for your question and have a nice weekend!

Best regards,
Nuno

**Comment by nuno-agostinho** [comment] 2024-08-28 16:00
Hi @vinhdc10998,

I couldn’t find any issues with using multi-core settings. However, running in multi-core mode with a low number of variants may take longer than single-core mode due to the overhead associated with parallel processing. We would recommend avoiding running in multiple cores in such cases.

I'll go ahead and close this issue, but please feel free to reply if you encounter any specific, reproducible problems you'd like to discuss further.

Thanks,
Nuno

**Closed by nuno-agostinho** 2024-08-28 16:00 UTC
