### ISSUE TITLE
ERROR: Failed last resort of using HTTP::Tiny to download 

### ISSUE THREAD

**Issue by yueli8** [Ensembl/ensembl-vep#1037] opened 2021-08-14 14:03 UTC
Hello

Thank you for developing so nice software.

May I ask you a question?

I think my ensembl-vep version is 104, but still can not install it.

What can I do in this step?

Thank you in advance for your great help!

Best,

Yue

```
Inspiron-3670:~/ensembl-vep$ git pull
remote: Enumerating objects: 16, done.
remote: Counting objects: 100% (16/16), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 16 (delta 7), reused 14 (delta 6), pack-reused 0
Unpacking objects: 100% (16/16), done.
From https://github.com/Ensembl/ensembl-vep
   5a1b2d6..32062c1  master             -> origin/master
   8e7c835..1c0a85a  postreleasefix/105 -> origin/postreleasefix/105
   143aaca..ea084f8  release/105        -> origin/release/105
Already up to date.

Inspiron-3670:~/ensembl-vep$ git checkout release/104
Already on 'release/104'
Your branch is up to date with 'origin/release/104'.

Inspiron-3670:~/ensembl-vep$ perl INSTALL.pl
curl failed (000), trying to fetch using LWP::Simple
LWP::Simple failed (500), trying to fetch using HTTP::Tiny
ERROR: Failed last resort of using HTTP::Tiny to download https://raw.githubusercontent.com/Ensembl/ensembl-vep/release/104/modules/Bio/EnsEMBL/VEP/Constants.pm```

**Comment by NavenM** [comment] 2021-08-16 16:08
Hi,

it looks like you may be having connection issues. Could you please try running the following command:
`curl https://raw.githubusercontent.com/Ensembl/ensembl-vep/release/104/modules/Bio/EnsEMBL/VEP/Constants.pm`

If that works then you can connect successfully and can try running `perl INSTALL.pl` again. If not, let me know and we'll look for other solutions.

Thanks,
Marc

**Comment by yueli8** [comment] 2021-08-17 14:20
Hello NavenM,

Thank you so much for your response!

It does not connect successfully by the following command. What can I do in this step?

Thank you so much for your great help and really appreciated!

Best Regards,

Yue

```
Inspiron-3670:~$ curl https://raw.githubusercontent.com/Ensembl/ensembl-vep/release/104/modules/Bio/EnsEMBL/VEP/Constants.pm
curl: (7) Failed to connect to raw.githubusercontent.com port 443: Connection refused
```

**Comment by NavenM** [comment] 2021-08-18 09:47
Hi Yue,

I'm not seeing the errors that you are, so it could be that you have a firewall issue. Disabling your firewall (or asking your network admin) would be a good step to try. Alternatively, you could try using a proxy server if disabling the firewall isn't an option. Once done, rerun the curl command to see if you can connect - if you can, then you can go ahead and run your original `perl INSTALL.pl` command.

Could you try the above suggestions and let me know the outcome?

Thanks,
Marc

**Comment by yueli8** [comment] 2021-08-18 14:08
Hello Marc,

Thank you so much for your response!

I really do not know how to do it because I am in China, and the firewall setup here (blocking of google, facebook, youtube...).

Do you have any other ideas that can solve this problem?

Thank you again and really appreciated!

Best Regards,

Yue

**Comment by NavenM** [comment] 2021-08-19 16:54
Hi Yue,

There's a couple of things you could try:

1. there may be a way to run INSTALL.pl if you have access to a VPN or proxy server, but unfortunately I can't provide much support with these.

2. Given that you were able to check out the ensembl-vep repository, you can technically already run VEP with some of its features. You can test this if you `cd` into your ~/ensembl-vep directory and run `./vep --help` - you should see a usage message displayed. If you want to run using the --offline option, you'll have to [download the appropriate cache](https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#cache) and [fasta files](https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#fasta). There are also some [additional components](https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#additional) and [plugins](https://www.ensembl.org/info/docs/tools/vep/script/vep_plugins.html) you may also want to use, depending on your requirements.

If you have any issues or questions, please let me know.

Thanks,
Marc

**Comment by yueli8** [comment] 2021-08-22 04:18
Hello Marc.

Thank you so much for your response!

I still have problem when use `./vep --help` command.

Thank you again and really appreciated!

Best Regards.

Yue


```
Inspiron-3670:~/ensembl-vep$ git pull
Already up to date.
Inspiron-3670:~/ensembl-vep$ git checkout release/104
Already on 'release/104'
Your branch is up to date with 'origin/release/104'.
Inspiron-3670:~/ensembl-vep$ ./vep --help
Can't locate Bio/EnsEMBL/IO/Parser/VCF4.pm in @INC (you may need to install the Bio::EnsEMBL::IO::Parser::VCF4 module) (@INC contains: /home/jing/ensembl-vep/modules /home/jing/ensembl-vep /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /home/jing/ensembl-vep/modules/Bio/EnsEMBL/VEP/Parser/VCF.pm line 79.
BEGIN failed--compilation aborted at /home/jing/ensembl-vep/modules/Bio/EnsEMBL/VEP/Parser/VCF.pm line 79.
Compilation failed in require at /home/jing/ensembl-vep/modules/Bio/EnsEMBL/VEP/Parser.pm line 71.
BEGIN failed--compilation aborted at /home/jing/ensembl-vep/modules/Bio/EnsEMBL/VEP/Parser.pm line 71.
Compilation failed in require at /home/jing/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm line 83.
BEGIN failed--compilation aborted at /home/jing/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm line 83.
Compilation failed in require at ./vep line 20.
BEGIN failed--compilation aborted at ./vep line 20.
```

**Comment by NavenM** [comment] 2021-08-24 17:26
Hi Yue, 

it looks like you're missing ensembl-io from github. You can install it using the instructions for [API installation](https://m.ensembl.org/info/docs/api/api_git.html). You might also need the other repos listed there (e.g. ensembl, ensembl-variation, ensembl-funcgen...),  and make sure they're listed in your $PERL5LIB.

VEP should then work - you can test again with ./vep --help, or using VEP to run your intended command.

Let me know if that works for you or not.
Thanks,
Marc

**Comment by yueli8** [comment] 2021-08-25 15:42
Hello Marc,

Thank you so much for you response!

I have already finished all the API installation, but still failed when ran `./vep --help` in `Inspiron-3670:~/ensembl-vep$`. I think I have to install `Bio::EnsEMBL::IO::Parser::VCF4 module`. Would you please give me a linkage?

Thank you in advance for your great help!

With all the Best,

Yue

```
Inspiron-3670:~/src$ nano ~/.profile
Inspiron-3670:~/src$ . ~/.profile
Inspiron-3670:~/src$ echo $PERL5LIB
/home/jing/src/ensembl-io/modules:/home/jing/src/bioperl-1.6.924/:/home/jing/src/ensembl-tools/modules:/home/jing/src/ensembl-funcgen/modules:/home/jing/src/ensembl-compara/modules:/home/jing/src/ensembl-variation/modules:/home/jing/src/ensembl/modules:/home/jing/src/ensembl-io/modules
Inspiron-3670:~/src$ cd ensembl/misc-scripts/
Inspiron-3670:~/src/ensembl/misc-scripts$ ./ping_ensembl.pl
Installation is good. Connection to Ensembl works and you can query the human core database
```

```
Inspiron-3670:~/ensembl-vep$ ./vep --help
Can't locate Bio/EnsEMBL/IO/Parser/VCF4.pm in @INC (you may need to install the Bio::EnsEMBL::IO::Parser::VCF4 module) (@INC contains: /home/jing/ensembl-vep/modules /home/jing/ensembl-vep /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /home/jing/ensembl-vep/modules/Bio/EnsEMBL/VEP/Parser/VCF.pm line 79.
BEGIN failed--compilation aborted at /home/jing/ensembl-vep/modules/Bio/EnsEMBL/VEP/Parser/VCF.pm line 79.
Compilation failed in require at /home/jing/ensembl-vep/modules/Bio/EnsEMBL/VEP/Parser.pm line 71.
BEGIN failed--compilation aborted at /home/jing/ensembl-vep/modules/Bio/EnsEMBL/VEP/Parser.pm line 71.
Compilation failed in require at /home/jing/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm line 83.
BEGIN failed--compilation aborted at /home/jing/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm line 83.
Compilation failed in require at ./vep line 20.
BEGIN failed--compilation aborted at ./vep line 20.
```

**Comment by NavenM** [comment] 2021-08-25 16:53
Hi Yue,

Bio::EnsEmbl::IO::Parser::VCF4 is included when you install the ensembl-io API, which you can do using 
```
cd ~/src
git clone https://github.com/Ensembl/ensembl-io.git
```
If you get an `'enembl-io' already exists and is not an empty directory` message, then remove the directory and try again, the same as you did for ensembl-funcgen [here](https://github.com/Ensembl/ensembl-vep/issues/1038). 

If you then get a new error when running ./vep, let me know. Chances are it's caused by other missing modules, so you might also want to try reinstalling the other APIs too.

I hope that helps,
Marc

**Comment by jamie-m-a** [comment] 2021-12-01 11:33
Issue resolved, closing this one off.

**Closed by jamie-m-a** 2021-12-01 11:33 UTC
