### ISSUE TITLE
Haplosaurus fails with segmentation fault

### ISSUE THREAD

**Issue by borissim** [Ensembl/ensembl-vep#1594] opened 2024-01-29 12:30 UTC
## Describe the issue
Running Haplosaurus on a small VCF file with phased variants fails with segmentation fault. No other information about the error is given.

## Additional information
I used the VEP docker container and downloaded the cache locally.

### System
- VEP version: 110 
- VEP Cache version: 110
- Perl version: Used docker container
- OS: Ubuntu
- tabix installed ?

### Full VEP command line
```
vep@a25d170b7bab:~/.vep$ haplo --cache --offline --force_overwrite --json --fasta homo_sapiens/110_GRCh38/Homo_sapiens.GRCh38.dna.toplevel.fa.gz --species homo_sapiens --assembly GRCh38 -i input/fail.vcf -o haplo.json
```

### Full error message
Smartmatch is experimental at /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/File.pm line 472.
Segmentation fault

### Data files (if applicable)
```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	TUMOR
chr1	25805163	chr1_25805163_G_A	G	A	.	.	.	GT	1|0
chr1	25808753	chr1_25808753_C_CA	C	CA	.	.	.	GT	1|0
chr1	25811771	chr1_25811771_T_C	T	C	.	.	.	GT	1|0
chr1	25814082	chr1_25814082_C_A	C	A	.	.	.	GT	1|0
```

**Comment by likhitha-surapaneni** [comment] 2024-01-30 11:32
Hi @borissim , unfortunately I am not able to reproduce the issue with the input file and the command provided. Can you kindly retry doing a fresh pull of the docker container (the latest version is `release_111.0`) followed by installation of cache and fasta ([installation docs](https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#docker))?

**Comment by likhitha-surapaneni** [comment] 2024-04-05 10:04
Hi @borissim , I am closing this issue for now but please feel free to open a new issue if you are facing problems again. Thank you.

**Closed by likhitha-surapaneni** 2024-04-05 10:04 UTC
Labels: haplosaurus
