### ISSUE TITLE
ProteinSeqs plugin uninitialized value warning (possibly similar to issues #241, #327)

### ISSUE THREAD

**Issue by ab604** [Ensembl/ensembl-vep#432] opened 2019-04-09 07:42 UTC
### Issue
Hi, I've encountered a warning similar to those reported for issue #241, when using the ProteinSeqs plugin. The outputs look OK (I think) and I just wanted to check whether this can be ignored?

I've pasted an example below. I wasn't able to figure out which bit the `$id` variable in the plugin code was referring to, but would I be correct in thinking it means there is no sequence to translate for this pseudo-gene?

Many thanks,

Alistair 

### VEP command
`vep --cache --dir_plugins /home/ab604/.vep/Plugins -i $WORKSPACE/somatic/oes/final/$file.annotated.filtered.vcf --plugin ProteinSeqs,$file-reference.fa,$file-mutated.fa --no_stats --force`

### Installed cached reference 
`~/.vep/homo_sapiens/95_GRCh38/`

### VEP ProteinSeqs perl warning example:
`Use of uninitialized value $id in concatenation (.) or string at /home/ab604/.vep/Plugins/ProteinSeqs.pm line 145, <__ANONIO__> line 6508.`

### Line 6508 from vcf:
`chr13	18331991	.	A	G	.	PASS	AC=1;AF=0.25;AN=2;DP=129;ECNT=1;MBQ=30,30;MFRL=176,162;MMQ=60,60;MPOS=0;NALOD=-0.09256;NLOD=8.36;POPAF=4.51;SAAF=0.051,0.081,0.083;SAPP=0.012,0.01,0.977;TLOD=10.98;set=mutect;CSQ=G|non_coding_transcript_exon_variant|MODIFIER|AL356585.3|ENSG00000279231|Transcript|ENST00000625196.1|unprocessed_pseudogene|1/8||ENST00000625196.1%3An.59A>G||59|||||rs1214540329||1||1|SNV|Clone_based_ensembl_gene||YES|||||||||||||||||||||||||||||||||||||||||||	GT:AD:AF:DP:F1R2:F2R1	0/1:91,16:0.14953:107:40,3:37,4`

### perl code from ProteinSeqs plugin upto line 145
```
sub print_fasta {
    my ($self, $peptide, $id, $fh) = @_;

    # break the sequence into 80 characters per line
    
    $peptide =~ s/(.{80})/$1\n/g;
    
    # get rid of any trailing newline
    
    chomp $peptide;

    # print the sequence

    print $fh ">$id\n$peptide\n"; # This is line 145

}
```

**Comment by aparton** [comment] 2019-04-09 10:09
Hi Alistair,

I’ve had a quick look, it looks like the plugin isn’t supporting your input data correctly. Unfortunately, I’m unable to reproduce this issue with the VCF input, could you please try the following VEP command on your system to see if you get the same issue?

vep --cache --dir_plugins /home/ab604/.vep/Plugins -id '13 18331991 . A G' --plugin ProteinSeqs,$file-reference.fa,$file-mutated.fa --no_stats —force

If the above line does not give the same warning, could you please send me your VCF file/ a subset of your VCF file which does reproduce the issue on your system?

Kind Regards,
Andrew

**Comment by ab604** [comment] 2019-04-09 10:37
Hi Andrew,

Thanks for taking a look at this.

The command you sent ran without warning, but produced empty output with just this in the text file:

## ENSEMBL VARIANT EFFECT PREDICTOR v95.3
## Output produced at 2019-04-09 11:14:28
## Connected to homo_sapiens_core_95_38 on ensembldb.ensembl.org
## Using cache in /home/ab604/.vep/homo_sapiens/95_GRCh38
## Using API version 95, DB version 95
## ensembl version 95.4f83453
## ensembl-io version 95.78ccac5
## ensembl-variation version 95.858de3e
## ensembl-funcgen version 95.94439f4
## gnomAD version 170228

I've attached a sample of the vcf that I used for the issue and will still reproduce the problem on my machine, with the header output from the vep text file.

Use of uninitialized value $id in concatenation (.) or string at /home/ab604/.vep/Plugins/ProteinSeqs.pm line 145, <__ANONIO__> line 3984.

All the best,

Alistair

________________________________

**Comment by aparton** [comment] 2019-04-09 14:02
Hi Alistair,

It looks like something has gone wrong with you sending me your input file, could you please try again?

Kind Regards,
Andrew

**Comment by aparton** [comment] 2019-04-10 13:05
Hi Alistair,

Thanks for this. Turns out the offending variant was 'chr12 11891600 . GA G’. This deletion occurs in the stop codon and in a repeated region, and as our HGVSp outputs are described at the most the 3’ region possible, then the variant is shifted out of the protein coding region and as such no HGVSp being returned, leading to the warning message you were seeing.

I’ll get a fix organised and let you know when the code has been updated. In the meantime, the warning message isn’t critical, you can carry on your analysis as normal and just ignore it.

Kind Regards,
Andrew

**Comment by ab604** [comment] 2019-04-10 13:09
Brilliant, thanks Andrew.

Yes, I did a manual inspection on a few of the mutations and it looked like it was working. I have eight vcf files and only got that error a maximum of twice for each file. Good to know I can carry on without worrying.

Thanks again,

Alistair

**Comment by ens-lgil** [comment] 2019-05-24 15:23
I am closing this ticket, but if you have any more questions please feel free to reopen it.

Best regards,
Laurent

**Closed by ens-lgil** 2019-05-24 15:23 UTC
