### ISSUE TITLE
VEP MacOSX Mojave installation Error

### ISSUE THREAD

**Issue by cccnrc** [Ensembl/ensembl-vep#425] opened 2019-03-26 17:55 UTC
Dear all,

I have followed the instructions for VEP installation in MacOSX (https://useast.ensembl.org/info/docs/tools/vep/script/vep_download.html) but when I finally try to:

_perl INSTALL.pl --NO_TEST_

It goes all the way down until asking me to cache download, I select a cache (254) and then I got:

_NB: Remember to use --merged when running the VEP with this cache!
-downloading ftp://ftp.ensembl.org/pub/release-95/variation/VEP/homo_sapiens_merged_vep_95_GRCh37.tar.gz
Unable to close datastream at INSTALL.pl line 1208.
curl failed (000), trying to fetch using LWP::Simple
Use of uninitialized value in numeric eq (==) at /Users/cccnrc/perl5/perlbrew/perls/5.26.2/lib/5.26.2/HTTP/Tiny.pm line 606, <> line 3.
Use of uninitialized value in numeric eq (==) at /Users/cccnrc/perl5/perlbrew/perls/5.26.2/lib/5.26.2/HTTP/Tiny.pm line 606, <> line 3.
ERROR: Failed last resort of using HTTP::Tiny to download ftp://ftp.ensembl.org:21/pub/release-95/variation/VEP/homo_sapiens_merged_vep_95_GRCh37.tar.gz_

Any help would be really appreciated!

**Comment by aparton** [comment] 2019-03-27 10:29
Hi,

I’ve been unable to reproduce this issue this morning, however I have a couple of thoughts/suggestions:

- You can download the cache file manually, rather than through the installer, from ftp://ftp.ensembl.org/pub/release-95/variation/VEP/homo_sapiens_merged_vep_95_GRCh37.tar.gz <ftp://ftp.ensembl.org/pub/release-95/variation/VEP/homo_sapiens_merged_vep_95_GRCh37.tar.gz>. If you then move this cache file (& unzip) into /Users/cccnrc/.vep then it will be automatically picked up by VEP (or, you can specify the location of the cache file with the —dir flag at runtime)

(N.B. If you download the cache this way, please run convert_cache.pl before you run VEP. It will take a couple of hours, but will significantly speed up your annotations)

- I’m not sure why LWP::Simple failed, but it looks like HTTP::Tiny was failing when looking for which port to use, and Curl returned a timeout code, suggesting that your firewall is stopping your request from going out.

If you have any more questions, please let me know.

Kind Regards,
Andrew

**Comment by cccnrc** [comment] 2019-04-20 18:24
Dear Andrew, thank you very much for your suggestion. I did exactly as suggested and it worked. Thanks again

**Comment by Mfpfox** [comment] 2019-05-24 02:55
Hi, I am having an issue installing v96.  I have tried several things like removing curl from my conda env, clearing my DNS cache, adding LWP::Simple to my conda env... i still am unable to install all the plugins using the installer.  please help :/
I am on a mac using Mojave. 
error from Gwava : 
installing "Gwava"
LWP::Simple failed (401), trying to fetch using HTTP::Tiny
Use of uninitialized value in numeric eq (==) at /anaconda3/envs/perlyclone/lib/5.26.2/HTTP/Tiny.pm line 606.
Use of uninitialized value in numeric eq (==) at /anaconda3/envs/perlyclone/lib/5.26.2/HTTP/Tiny.pm line 606.
ERROR: Failed last resort of using HTTP::Tiny to download ftp://ftp.sanger.ac.uk:21/pub/resources/software/gwava/v1.0/VEP_plugin/Gwava.pm


here from trying to install API: 
(perlyclone) mp@m-mbp-2:~/Box Sync/CODE_DATA/ensembl-vep$ perl INSTALL.pl --NO_HTSLIB --NO_TEST
curl failed (000{
  "id": 55504797,
  "node_id": "MDEwOlJlcG9zaXRvcnk1NTUwNDc5Nw==",
  "name": "ensembl-vep",
  "full_name": "Ensembl/ensembl-vep",
  "private": false,
  "owner": {
    "login": "Ensembl",
    "id": 5832463,
    "node_id": "MDEyOk9yZ2FuaXphdGlvbjU4MzI0NjM=",
    "avatar_url": "https://avatars3.githubusercontent.com/u/5832463?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Ensembl",
    "html_url": "https://github.com/Ensembl",
    "followers_url": "https://api.github.com/users/Ensembl/followers",
    "following_url": "https://api.github.com/users/Ensembl/following{/other_user}",
    "gists_url": "https://api.github.com/users/Ensembl/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Ensembl/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Ensembl/subscriptions",
    "organizations_url": "https://api.github.com/users/Ensembl/orgs",
    "repos_url": "https://api.github.com/users/Ensembl/repos",
    "events_url": "https://api.github.com/users/Ensembl/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Ensembl/received_events",
    "type": "Organization",
    "site_admin": false
  },
  "html_url": "https://github.com/Ensembl/ensembl-vep",
  "description": "The Variant Effect Predictor predicts the functional effects of genomic variants",
  "fork": false,
  "url": "https://api.github.com/repos/Ensembl/ensembl-vep",
  "forks_url": "https://api.github.com/repos/Ensembl/ensembl-vep/forks",
  "keys_url": "https://api.github.com/repos/Ensembl/ensembl-vep/keys{/key_id}",
  "collaborators_url": "https://api.github.com/repos/Ensembl/ensembl-vep/collaborators{/collaborator}",
  "teams_url": "https://api.github.com/repos/Ensembl/ensembl-vep/teams",
  "hooks_url": "https://api.github.com/repos/Ensembl/ensembl-vep/hooks",
  "issue_events_url": "https://api.github.com/repos/Ensembl/ensembl-vep/issues/events{/number}",
  "events_url": "https://api.github.com/repos/Ensembl/ensembl-vep/events",
  "assignees_url": "https://api.github.com/repos/Ensembl/ensembl-vep/assignees{/user}",
  "branches_url": "https://api.github.com/repos/Ensembl/ensembl-vep/branches{/branch}",
  "tags_url": "https://api.github.com/repos/Ensembl/ensembl-vep/tags",
  "blobs_url": "https://api.github.com/repos/Ensembl/ensembl-vep/git/blobs{/sha}",
  "git_tags_url": "https://api.github.com/repos/Ensembl/ensembl-vep/git/tags{/sha}",
  "git_refs_url": "https://api.github.com/repos/Ensembl/ensembl-vep/git/refs{/sha}",
  "trees_url": "https://api.github.com/repos/Ensembl/ensembl-vep/git/trees{/sha}",
  "statuses_url": "https://api.github.com/repos/Ensembl/ensembl-vep/statuses/{sha}",
  "languages_url": "https://api.github.com/repos/Ensembl/ensembl-vep/languages",
  "stargazers_url": "https://api.github.com/repos/Ensembl/ensembl-vep/stargazers",
  "contributors_url": "https://api.github.com/repos/Ensembl/ensembl-vep/contributors",
  "subscribers_url": "https://api.github.com/repos/Ensembl/ensembl-vep/subscribers",
  "subscription_url": "https://api.github.com/repos/Ensembl/ensembl-vep/subscription",
  "commits_url": "https://api.github.com/repos/Ensembl/ensembl-vep/commits{/sha}",
  "git_commits_url": "https://api.github.com/repos/Ensembl/ensembl-vep/git/commits{/sha}",
  "comments_url": "https://api.github.com/repos/Ensembl/ensembl-vep/comments{/number}",
  "issue_comment_url": "https://api.github.com/repos/Ensembl/ensembl-vep/issues/comments{/number}",
  "contents_url": "https://api.github.com/repos/Ensembl/ensembl-vep/contents/{+path}",
  "compare_url": "https://api.github.com/repos/Ensembl/ensembl-vep/compare/{base}...{head}",
  "merges_url": "https://api.github.com/repos/Ensembl/ensembl-vep/merges",
  "archive_url": "https://api.github.com/repos/Ensembl/ensembl-vep/{archive_format}{/ref}",
  "downloads_url": "https://api.github.com/repos/Ensembl/ensembl-vep/downloads",
  "issues_url": "https://api.github.com/repos/Ensembl/ensembl-vep/issues{/number}",
  "pulls_url": "https://api.github.com/repos/Ensembl/ensembl-vep/pulls{/number}",
  "milestones_url": "https://api.github.com/repos/Ensembl/ensembl-vep/milestones{/number}",
  "notifications_url": "https://api.github.com/repos/Ensembl/ensembl-vep/notifications{?since,all,participating}",
  "labels_url": "https://api.github.com/repos/Ensembl/ensembl-vep/labels{/name}",
  "releases_url": "https://api.github.com/repos/Ensembl/ensembl-vep/releases{/id}",
  "deployments_url": "https://api.github.com/repos/Ensembl/ensembl-vep/deployments",
  "created_at": "2016-04-05T12:08:24Z",
  "updated_at": "2019-05-24T02:32:20Z",
  "pushed_at": "2019-05-23T21:01:40Z",
  "git_url": "git://github.com/Ensembl/ensembl-vep.git",
  "ssh_url": "git@github.com:Ensembl/ensembl-vep.git",
  "clone_url": "https://github.com/Ensembl/ensembl-vep.git",
  "svn_url": "https://github.com/Ensembl/ensembl-vep",
  "homepage": "https://www.ensembl.org/vep",
  "size": 67945,
  "stargazers_count": 141,
  "watchers_count": 141,
  "language": "Perl",
  "has_issues": true,
  "has_projects": false,
  "has_downloads": true,
  "has_wiki": true,
  "has_pages": false,
  "forks_count": 60,
  "mirror_url": null,
  "archived": false,
  "disabled": false,
  "open_issues_count": 39,
  "license": {
    "key": "apache-2.0",
    "name": "Apache License 2.0",
    "spdx_id": "Apache-2.0",
    "url": "https://api.github.com/licenses/apache-2.0",
    "node_id": "MDc6TGljZW5zZTI="
  },
  "forks": 60,
  "open_issues": 39,
  "watchers": 141,
  "default_branch": "release/96",
  "organization": {
    "login": "Ensembl",
    "id": 5832463,
    "node_id": "MDEyOk9yZ2FuaXphdGlvbjU4MzI0NjM=",
    "avatar_url": "https://avatars3.githubusercontent.com/u/5832463?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Ensembl",
    "html_url": "https://github.com/Ensembl",
    "followers_url": "https://api.github.com/users/Ensembl/followers",
    "following_url": "https://api.github.com/users/Ensembl/following{/other_user}",
    "gists_url": "https://api.github.com/users/Ensembl/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Ensembl/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Ensembl/subscriptions",
    "organizations_url": "https://api.github.com/users/Ensembl/orgs",
    "repos_url": "https://api.github.com/users/Ensembl/repos",
    "events_url": "https://api.github.com/users/Ensembl/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Ensembl/received_events",
    "type": "Organization",
    "site_admin": false
  },
  "network_count": 60,
  "subscribers_count": 24
}
200), trying to fetch using LWP::Simple

Hello! This installer is configured to install v96 of the Ensembl API for use by the VEP.
It will not affect any existing installations of the Ensembl API that you may have.

It will also download and install cache files from Ensembl's FTP server.

Checking for installed versions of the Ensembl API...done
It looks like you already have v96 of the API installed.
No version information was available for the following modules:
 - ensembl
 - ensembl-variation
 - ensembl-funcgen
 - ensembl-io
Updates may be available but you will need to perform these manually.

Skip to the next step (n) to install cache files

**Comment by ens-lgil** [comment] 2019-05-24 07:59
Dear @Mfpfoxm,

This might be due to the GitHub API rate limit which might have been already reached for your institute/IP which is set by default to 60 requests per hour: https://developer.github.com/v3/#rate-limiting
Please, could you try again to install VEP ?

Best regards,
Laurent

**Comment by ens-lgil** [comment] 2019-06-17 12:50
I am closing this issue, but if you have any more questions please feel free to reopen it.

Best regards,
Laurent

**Closed by ens-lgil** 2019-06-17 12:50 UTC
