### ISSUE TITLE
fatal: Not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by TMiguelT** [Ensembl/ensembl-vep#25] opened 2017-03-08 00:52 UTC
It seems like the test in `/vep/vep/t/version.t` checks the git revision using `git rev-parse --abbrev-ref HEAD`.

I don't know if some of the VEP code relies on this, but this test fails if:
* VEP was installed without using git (e.g. by installing a release archive from github)
* The INSTALL.pl script is run from a directory other than where VEP was cloned into (e.g. the parent directory)

In either of these cases the tests fail with:
```
/vep/vep/t/version.t ........................................ fatal: Not a git repository (or any of the parent directories): .git
#   Failed test 'get current git branch'
#   at /vep/vep/t/version.t line 31.
# Looks like you failed 1 test of 1.
/vep/vep/t/version.t ........................................ Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests 

Test Summary Report
-------------------
/vep/vep/t/version.t                                      (Wstat: 256 Tests: 1 Failed: 1)
```

Do we need this test? Should VEP be relying on git at all?

**Comment by willmclaren** [comment] 2017-03-08 09:17
Duplicate of https://github.com/Ensembl/ensembl-vep/issues/17, already resolved

**Closed by willmclaren** 2017-03-08 09:17 UTC
