### ISSUE TITLE
Running VEP with singularity

### ISSUE THREAD

**Issue by JingjingBai2021** [Ensembl/ensembl-vep#1484] opened 2023-08-22 06:32 UTC
## Describe the issue
I have downloaded the vep.sif. I am trying to install vep usin the following command.
singularity exec vep.sif INSTALL.pl -c vep_data -a cf -s homo_sapiens -y GRCh38

##Errors
ERROR: ld.so: object '/apps/software/jemalloc/5.1.0-GCCcore-7.3.0/lib/libjemalloc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/apps/software/jemalloc/5.1.0-GCCcore-7.3.0/lib/libjemalloc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/apps/software/jemalloc/5.1.0-GCCcore-7.3.0/lib/libjemalloc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/apps/software/jemalloc/5.1.0-GCCcore-7.3.0/lib/libjemalloc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/apps/software/jemalloc/5.1.0-GCCcore-7.3.0/lib/libjemalloc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/apps/software/jemalloc/5.1.0-GCCcore-7.3.0/lib/libjemalloc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/apps/software/jemalloc/5.1.0-GCCcore-7.3.0/lib/libjemalloc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/apps/software/jemalloc/5.1.0-GCCcore-7.3.0/lib/libjemalloc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
 - getting list of available cache files
ERROR: ld.so: object '/apps/software/jemalloc/5.1.0-GCCcore-7.3.0/lib/libjemalloc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/apps/software/jemalloc/5.1.0-GCCcore-7.3.0/lib/libjemalloc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
 - downloading https://ftp.ensembl.org/pub/release-110/variation/indexed_vep_cache/homo_sapiens_vep_110_GRCh38.tar.gz
Cannot write to Local file vep_data/tmp/homo_sapiens_vep_110_GRCh38.tar.gz: No space left on device
 at /opt/vep/src/ensembl-vep/INSTALL.pl line 1315.
ERROR: ld.so: object '/apps/software/jemalloc/5.1.0-GCCcore-7.3.0/lib/libjemalloc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/apps/software/jemalloc/5.1.0-GCCcore-7.3.0/lib/libjemalloc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
Cannot open Local file vep_data/tmp/CHECKSUMS: No space left on device
 at /opt/vep/src/ensembl-vep/INSTALL.pl line 1319.
ERROR: ld.so: object '/apps/software/jemalloc/5.1.0-GCCcore-7.3.0/lib/libjemalloc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/apps/software/jemalloc/5.1.0-GCCcore-7.3.0/lib/libjemalloc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
 - unpacking homo_sapiens_vep_110_GRCh38.tar.gz
ERROR: ld.so: object '/apps/software/jemalloc/5.1.0-GCCcore-7.3.0/lib/libjemalloc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/apps/software/jemalloc/5.1.0-GCCcore-7.3.0/lib/libjemalloc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
tar: homo_sapiens: Cannot mkdir: No space left on device
tar: homo_sapiens/110_GRCh38: Cannot mkdir: No such file or directory
tar: homo_sapiens: Cannot mkdir: No space left on device
tar: homo_sapiens/110_GRCh38/1: Cannot mkdir: No such file or directory
tar: homo_sapiens: Cannot mkdir: No space left on device
tar: homo_sapiens/110_GRCh38/1/1-1000000.gz: Cannot open: No such file or directory
tar: homo_sapiens: Cannot mkdir: No space left on device
tar: homo_sapiens/110_GRCh38/1/1-1000000_reg.gz: Cannot open: No such file or directory
tar: homo_sapiens: Cannot mkdir: No space left on device
tar: homo_sapiens/110_GRCh38/1/100000001-101000000.gz: Cannot open: No such file or directory
tar: homo_sapiens: Cannot mkdir: No space left on device
tar: homo_sapiens/110_GRCh38/1/100000001-101000000_reg.gz: Cannot open: No such file or directory
tar: homo_sapiens: Cannot mkdir: No space left on device
tar: homo_sapiens/110_GRCh38/1/10000001-11000000.gz: Cannot open: No such file or directory
tar: homo_sapiens: Cannot mkdir: No space left on device

**Comment by nakib103** [comment] 2023-08-22 10:43
Hello @JingjingBai2021,

One of the issue is pretty straightforward  -
"downloading https://ftp.ensembl.org/pub/release-110/variation/indexed_vep_cache/homo_sapiens_vep_110_GRCh38.tar.gz
Cannot write to Local file vep_data/tmp/homo_sapiens_vep_110_GRCh38.tar.gz: **No space left on device**"

It seems there is not enough space to download the cache file. You can either try to see if you can manage more space in your device. Alternative is to use the database but the performance would be slower - 
https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#database

The other error -
 "ERROR: ld.so: object '/apps/software/jemalloc/5.1.0-GCCcore-7.3.0/lib/libjemalloc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored."

does not seem to be fatal but you can try (re-)installing the `jemalloc` package as described here. -
https://unix.stackexchange.com/questions/677387/mariadb-amazon-linux-2-error-ld-so-object-usr-lib64-libjemalloc-so-1-fro

Best regards,
Nakib

**Comment by JingjingBai2021** [comment] 2023-08-22 11:27
Tanks for yor help!

**Comment by nakib103** [comment] 2023-09-12 07:52
Hi @JingjingBai2021,
I am closing this issue, if you face any further problems please create another one and let us know.

Best regards,
Nakib

**Closed by nakib103** 2023-09-12 07:52 UTC
