### ISSUE TITLE
Nextflow Failing with Missing Output File

### ISSUE THREAD

**Issue by sharra44** [Ensembl/ensembl-vep#1665] opened 2024-04-24 15:37 UTC
## Describe the issue
Attempting to run vep with nextflow, running into output file error which terminates process.

### System
- VEP version: 111 
- VEP Cache version: 111
- Perl version: [5.26.3
- OS: Almalinux
- tabix installed yes

### Full VEP command line
```
nextflow run -resume -bg nextflow/workflows/run_vep.nf --vcf nextflow/testing.vcf.gz --skip_check 1 --vep_config /home/anno/ensembl-vep/nextflow/vep_config/vep.ini --output_prefix testing-output --outdir /home/anno/ensembl-vep
```

### Full error message

```
ERROR ~ Error executing process > 'vep:runVEP (1)'

Caused by:
  Missing output file(s) `*.vcf.gz_summary.*` expected by process `vep:runVEP (1)`

Command executed:

  vep -i out.xaab.vcf.gz -o vep-testing-vep-out.xaab.vcf.gz --vcf --compress_output bgzip --format vcf --config vep.ini

  if [[ "tbi" == "tbi" ]]; then
    tabix -p vcf vep-testing-vep-out.xaab.vcf.gz
  else
    tabix -C -p vcf vep-testing-vep-out.xaab.vcf.gz
  fi

Command exit status:
  0
```

### Data files (if applicable)
Input file is a small section of a vcf (around 20,000 lines). Running command from ensembl-vep folder. Output file does not seem to be generated

**Comment by likhitha-surapaneni** [comment] 2024-04-24 15:54
Hi @sharra44 ,

Sorry to hear that you are facing issues with running VEP using Nextflow. 

- Is it possible to share the nextflow log file that got generated? 
- From the error, it seems like the expected intermediate files did not get generated. Is it possible to inspect the respective work directory to see if there is any `.command.err` file?

Thanks and regards,
Likhitha

**Comment by sharra44** [comment] 2024-04-24 16:04
Here is the log file- [nextflow.log](https://github.com/Ensembl/ensembl-vep/files/15097162/nextflow.log)
Here is a screenshot of the work dir referenced for the failed run:

**Comment by sharra44** [comment] 2024-04-29 14:49
Hi - Just wanted to follow up on this, as it is blocking our progress in implementing nextflow. Do you need anything further from me?

**Comment by likhitha-surapaneni** [comment] 2024-04-29 15:04
Hi @sharra44,

Apologies for the delay. I was trying to run with the above options but was not able to reproduce. Can I request you to please try running with the [test input](https://github.com/Ensembl/ensembl-vep/tree/release/111/nextflow/examples/clinvar-testset) and let us know if you are seeing the same issue? 

Thanks and regards,
Likhitha

**Comment by sharra44** [comment] 2024-04-29 15:20
Just tried - similar output
`cat .nextflow.log
Apr-29 15:19:13.290 [main] DEBUG nextflow.cli.Launcher - $> nextflow run -resume -bg nextflow/workflows/run_vep.nf --vcf /home/anno/ensembl-vep/nextflow/examples/clinvar-testset/input.vcf.gz --skip_check 1 --vep_config /home/anno/ensembl-vep/nextflow/vep_config/vep.ini
Apr-29 15:19:13.370 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 23.10.1
Apr-29 15:19:13.388 [main] DEBUG nextflow.plugin.PluginsFacade - Setting up plugin manager > mode=prod; embedded=false; plugins-dir=/root/.nextflow/plugins; core-plugins: nf-amazon@2.1.4,nf-azure@1.3.3,nf-cloudcache@0.3.0,nf-codecommit@0.1.5,nf-console@1.0.6,nf-ga4gh@1.1.0,nf-google@1.8.3,nf-tower@1.6.3,nf-wave@1.0.1
Apr-29 15:19:13.397 [main] INFO  o.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
Apr-29 15:19:13.398 [main] INFO  o.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
Apr-29 15:19:13.401 [main] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.4.1 in 'deployment' mode
Apr-29 15:19:13.410 [main] INFO  org.pf4j.AbstractPluginManager - No plugins
Apr-29 15:19:13.487 [main] DEBUG nextflow.cli.CmdRun - Applied DSL=2 from script declararion
Apr-29 15:19:13.505 [main] INFO  nextflow.cli.CmdRun - Launching `nextflow/workflows/run_vep.nf` [sad_ride] DSL2 - revision: 55c68e331b
Apr-29 15:19:13.505 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins default=[]
Apr-29 15:19:13.505 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins resolved requirement=[]
Apr-29 15:19:13.515 [main] DEBUG n.secret.LocalSecretsProvider - Secrets store: /root/.nextflow/secrets/store.json
Apr-29 15:19:13.521 [main] DEBUG nextflow.secret.SecretsLoader - Discovered secrets providers: [nextflow.secret.LocalSecretsProvider@5e742e4] - activable => nextflow.secret.LocalSecretsProvider@5e742e4
Apr-29 15:19:13.592 [main] DEBUG nextflow.Session - Session UUID: da08bdb0-fbf7-4b12-9f9a-0df6be433d5c
Apr-29 15:19:13.592 [main] DEBUG nextflow.Session - Run name: sad_ride
Apr-29 15:19:13.594 [main] DEBUG nextflow.Session - Executor pool size: 8
Apr-29 15:19:13.601 [main] DEBUG nextflow.file.FilePorter - File porter settings maxRetries=3; maxTransfers=50; pollTimeout=null
Apr-29 15:19:13.605 [main] DEBUG nextflow.util.ThreadPoolBuilder - Creating thread pool 'FileTransfer' minSize=10; maxSize=24; workQueue=LinkedBlockingQueue[10000]; allowCoreThreadTimeout=false
Apr-29 15:19:13.629 [main] DEBUG nextflow.cli.CmdRun -
  Version: 23.10.1 build 5891
  Created: 12-01-2024 22:01 UTC
  System: Linux 4.18.0-513.18.1.el8_9.x86_64
  Runtime: Groovy 3.0.19 on OpenJDK 64-Bit Server VM 17.0.10+7
  Encoding: UTF-8 (UTF-8)
  Process: 306083@ip-172-34-115-168.ec2.internal [172.34.115.168]
  CPUs: 8 - Mem: 62.2 GB (1.3 GB) - Swap: 0 (0)
Apr-29 15:19:13.656 [main] DEBUG nextflow.Session - Work-dir: /home/anno/ensembl-vep/work [xfs]
Apr-29 15:19:13.656 [main] DEBUG nextflow.Session - Script base path does not exist or is not a directory: /home/anno/ensembl-vep/nextflow/workflows/bin
Apr-29 15:19:13.665 [main] DEBUG nextflow.executor.ExecutorFactory - Extension executors providers=[]
Apr-29 15:19:13.674 [main] DEBUG nextflow.Session - Observer factory: DefaultObserverFactory
Apr-29 15:19:13.694 [main] DEBUG nextflow.cache.CacheFactory - Using Nextflow cache factory: nextflow.cache.DefaultCacheFactory
Apr-29 15:19:13.702 [main] DEBUG nextflow.util.CustomThreadPool - Creating default thread pool > poolSize: 9; maxThreads: 1000
Apr-29 15:19:13.787 [main] DEBUG nextflow.Session - Session start
Apr-29 15:19:14.751 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Apr-29 15:19:15.315 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
Apr-29 15:19:15.315 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Apr-29 15:19:15.320 [main] DEBUG nextflow.executor.Executor - [warm up] executor > local
Apr-29 15:19:15.325 [main] DEBUG n.processor.LocalPollingMonitor - Creating local task monitor for executor 'local' > cpus=8; memory=62.2 GB; capacity=8; pollInterval=100ms; dumpInterval=5m
Apr-29 15:19:15.327 [main] DEBUG n.processor.TaskPollingMonitor - >>> barrier register (monitor: local)
Apr-29 15:19:15.412 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
Apr-29 15:19:15.412 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Apr-29 15:19:15.417 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
Apr-29 15:19:15.417 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Apr-29 15:19:15.427 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
Apr-29 15:19:15.428 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Apr-29 15:19:15.437 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
Apr-29 15:19:15.437 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Apr-29 15:19:15.446 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
Apr-29 15:19:15.446 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Apr-29 15:19:15.448 [main] DEBUG nextflow.Session - Workflow process names [dsl2]: vep:checkVCF, vep:generateSplits, vep:splitVCF, generateSplits, splitVCF, vep:processInput, mergeVCF, runVEP, checkVCF, processInput, vep:runVEP, vep:mergeVCF
Apr-29 15:19:15.448 [main] DEBUG nextflow.Session - Igniting dataflow network (9)
Apr-29 15:19:15.453 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > vep:processInput
Apr-29 15:19:15.454 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > vep:checkVCF
Apr-29 15:19:15.455 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > vep:generateSplits
Apr-29 15:19:15.455 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > vep:splitVCF
Apr-29 15:19:15.455 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > vep:runVEP
Apr-29 15:19:15.456 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > vep:mergeVCF
Apr-29 15:19:15.456 [main] DEBUG nextflow.script.ScriptRunner - Parsed script files:
  Script_e26fcec198450058: /home/anno/ensembl-vep/nextflow/workflows/../nf_modules/run_vep.nf
  Script_19295249c30864c3: /home/anno/ensembl-vep/nextflow/workflows/../nf_modules/generate_splits.nf
  Script_8df3607e8da86b64: /home/anno/ensembl-vep/nextflow/workflows/run_vep.nf
  Script_82f54642a4383468: /home/anno/ensembl-vep/nextflow/workflows/../nf_modules/check_VCF.nf
  Script_65f27aeb90c486f5: /home/anno/ensembl-vep/nextflow/workflows/../nf_modules/process_input.nf
  Script_1f7644ba40341018: /home/anno/ensembl-vep/nextflow/workflows/../nf_modules/merge_VCF.nf
  Script_31c64cb787143375: /home/anno/ensembl-vep/nextflow/workflows/../nf_modules/split_VCF.nf
Apr-29 15:19:15.456 [main] DEBUG nextflow.script.ScriptRunner - > Awaiting termination
Apr-29 15:19:15.456 [main] DEBUG nextflow.Session - Session await
Apr-29 15:19:15.597 [Actor Thread 10] INFO  nextflow.processor.TaskProcessor - [44/42023c] Cached process > vep:processInput (1)
Apr-29 15:19:15.618 [Actor Thread 4] INFO  nextflow.processor.TaskProcessor - [fc/8f6ffe] Cached process > vep:checkVCF (1)
Apr-29 15:19:15.689 [Task submitter] DEBUG n.executor.local.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
Apr-29 15:19:15.691 [Task submitter] INFO  nextflow.Session - [f8/9f7060] Submitted process > vep:generateSplits (1)
Apr-29 15:19:15.717 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 3; name: vep:generateSplits (1); status: COMPLETED; exit: 0; error: -; workDir: /home/anno/ensembl-vep/work/f8/9f7060917616cae70d1b6933335a3c]
Apr-29 15:19:15.721 [Task monitor] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
  task: name=vep:generateSplits (1); work-dir=/home/anno/ensembl-vep/work/f8/9f7060917616cae70d1b6933335a3c
  error [nextflow.exception.MissingFileException]: Missing output file(s) `x*` expected by process `vep:generateSplits (1)`
Apr-29 15:19:15.740 [Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'vep:generateSplits (1)'

Caused by:
  Missing output file(s) `x*` expected by process `vep:generateSplits (1)`

Command executed:

  bcftools query -f'%CHROM      %POS
  ' input.vcf.gz | uniq | split -a 3 -l 100

Command exit status:
  0

Command output:
  (empty)

Command error:
  Failed to read from input.vcf.gz: unknown file type

Work dir:
  /home/anno/ensembl-vep/work/f8/9f7060917616cae70d1b6933335a3c

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
Apr-29 15:19:15.744 [Task monitor] DEBUG nextflow.Session - Session aborted -- Cause: Missing output file(s) `x*` expected by process `vep:generateSplits (1)`
Apr-29 15:19:15.744 [main] DEBUG nextflow.Session - Session await > all processes finished
Apr-29 15:19:15.759 [main] DEBUG nextflow.Session - Session await > all barriers passed
Apr-29 15:19:15.759 [Task monitor] DEBUG n.processor.TaskPollingMonitor - <<< barrier arrives (monitor: local) - terminating tasks monitor poll loop
Apr-29 15:19:15.765 [main] DEBUG n.trace.WorkflowStatsObserver - Workflow completed > WorkflowStats[succeededCount=0; failedCount=1; ignoredCount=0; cachedCount=2; pendingCount=0; submittedCount=0; runningCount=0; retriesCount=0; abortedCount=0; succeedDuration=0ms; failedDuration=2ms; cachedDuration=3ms;loadCpus=0; loadMemory=0; peakRunning=1; peakCpus=1; peakMemory=0; ]
Apr-29 15:19:15.773 [main] DEBUG nextflow.cache.CacheDB - Closing CacheDB done
Apr-29 15:19:15.788 [main] DEBUG nextflow.script.ScriptRunner - > Execution complete -- Goodbye`

**Comment by sharra44** [comment] 2024-04-29 15:21
For reference - the command I used is `nextflow run -resume -bg nextflow/workflows/run_vep.nf --vcf /home/anno/ensembl-vep/nextflow/examples/clinvar-testset/input.vcf.gz --skip_check 1 --vep_config /home/anno/ensembl-vep/nextflow/vep_config/vep.ini`
The vep.ini file looks like this:
`cache 1
dir_cache /root/.vep
species 'homo_sapiens'
format 'vcf'
no_stats 1
force_overwrite 1
assembly 'GRCh38'
af_gnomadg 1
symbol 1
variant_class 1
fasta /home/anno/fasta/Homo_sapiens_assembly38.fasta
check_ref 1
merged 1
buffer_size 5000
offline 1
flag_pick 1
vcf 1`

**Comment by likhitha-surapaneni** [comment] 2024-04-29 15:31
Hi @sharra44 ,

Thank you for providing `vep.ini` configuration. Can you please try removing `no_stats 1` and retry again? Currently Nextflow module expects statistics files as intermediate files. 

Kind regards,
Likhitha

**Comment by sharra44** [comment] 2024-04-29 21:07
This seemed to do the trick - thank you!!

**Comment by likhitha-surapaneni** [comment] 2024-04-30 08:37
Thank you @sharra44, I am closing the ticket for now. Please feel free to open a new issue if there are any other problems.

**Closed by likhitha-surapaneni** 2024-04-30 08:37 UTC
