### ISSUE TITLE
VEP 101 - MERGE CACHE VERSION - REFSEQ MISSING for some gene

### ISSUE THREAD

**Issue by jpofmars** [Ensembl/ensembl-vep#847] opened 2020-09-04 13:21 UTC
Dear Ensembl Team ,

here my issue : 

## Describe the issue
When I perform annotation with VEP **merged** **101** cache version on my VCF I get for some genes as  BRCA1 and RUNX1  only Ensembl transcript.
For other genes as TP53 for exemple it seems to be ok.

I perform the annotation with VEP (v101) on previous cache version 95 and for the same variants I get Ensembl and Refseq Transcrits.

I perform this test on 2 different systems (Mac, CentOs) with cache data downloaded separetely

### System
Versions:
  ensembl              : 101.856c8e8
  ensembl-funcgen      : 101.b918a49
  ensembl-io           : 101.943b6c2
  ensembl-variation    : 101.d5749e1
  ensembl-vep          : 101.0
- Perl version: 5.26.2
- OS:MacOS and CentOS
- tabix : yes

### Full VEP command line
```
vep -i ./new_fromDB_final.vcf --cache --no_stats --offline --hgvs --fasta Homo_sapiens.GRCh38.dna.primary_assembly.fa -a GRCh38 --merged --force_overwrite -o ./new_fromDB_final_vep.vcf --vcf --symbol --fork 12 --cache_version 101
```

### Full error message
No error 

I join a file with the result for one brca1 variant with cache version 101 and 95
[brca1_example.txt](https://github.com/Ensembl/ensembl-vep/files/5175003/brca1_example.txt)

Thank you for your help.

**Comment by at7** [comment] 2020-09-04 14:02
Hi @jpofmars,

unfortunately, we noticed a problem with our RefSeq data load for release 101. We recommend to revert to release 100 code and cache files if you are working with RefSeq transcripts. This will be fixed for our autumn release 102 and I will update you here as soon as the new release is out. I apologise for any inconvenience caused by this.

Best wishes,
Anja

**Comment by segoerge** [comment] 2020-12-02 06:41
Hi,

is this fixed in release 102 ? Could't find anything about this in the change log.

Best wishes,
Sebastian

**Comment by at7** [comment] 2020-12-02 08:54
Hello,
yes the missing RefSeq transcripts have been added back into the 102 cache files. I will close this issue but please reopen it if there are any related questions.

Best wishes,
Anja

**Comment by at7** [comment] 2021-02-17 14:46
Hello,
the new release 103 is out and the missing RefSeq transcripts have been added back into the 103 cache files. I will close this issue but please reopen it if there are any related questions.

Best wishes,
Anja

**Closed by at7** 2021-02-17 14:46 UTC
Labels: bug, release/102, release/103
