### ISSUE TITLE
VEP use refseq gff got error: Transcript has unexpected type of child record

### ISSUE THREAD

**Issue by daffay** [Ensembl/ensembl-vep#732] opened 2020-04-08 08:28 UTC
## Describe the issue
hello,I'm trying to use VEP annotate vcf file ,and I use  refseq gff file update refseq transcipts ; I got an error : Transcript has unexpected type of child record;

## Additional information
Please fill in the following sections to help us find the source of your issue as quickly as possible.

### System
- VEP version: 98.3
- VEP Cache version:  98
- Perl version: 5.24
- OS: CentOS
- tabix installed? yes

### VEP command line
```
./vep -i input.vcf -o output.vcf  \
--force --offline  --refseq --hgvs HGVSC,HGVSp --hgvsg --vcf \
--gff GRCh37_latest_genomic_Sorted.gff.gz  --synonyms GRCH37_refseq_chr_synoymes.txt \
--fasta=human_g1k_v37.fasta \
--polyphen b --sift b --keep_csq --symbol --assembly GRCh37 \

```

### Full error message
MSG: ERROR: Transcript has unexpected type of child record: $VAR1 = {
  'start' => '140344513',
  '_parent_id' => [
    'rna-NR_106964.1'
  ],
  '_children' => [
    {
      'source' => 'BestRefSeq',
      'strand' => '-1',
      'attributes' => {
        'gene' => 'MIR7114',
        'Parent' => 'rna-MIR7114-2',
        'product' => 'hsa-miR-7114-5p',
        'Dbxref' => 'GeneID:102466223,miRBase:MIMAT0028125,HGNC:HGNC:50157,miRBase:MI0022965',
        'gbkey' => 'ncRNA',
        'ID' => 'exon-MIR7114-2-1'
      },
      'phase' => undef,
      'end' => '140344533',
      '_id' => 'exon-MIR7114-2-1',
      'type' => 'exon',
      'md5' => 'd443fbcfba81729a3b2f55b8ffe526b5',
      'chr' => 'NC_000009.11',
      '_parent_id' => [
        'rna-MIR7114-2'
      ],
      'start' => '140344513'
    }
  ],
'chr' => 'NC_000009.11',
  'type' => 'miRNA',
  '_id' => 'rna-MIR7114-2',
  'md5' => '7b4366c8225d9e25f5c16e03633bb8a0',
  'end' => '140344533',
  'attributes' => {
    'ID' => 'rna-MIR7114-2',
    'gbkey' => 'ncRNA',
    'Dbxref' => 'GeneID:102466223,miRBase:MIMAT0028125,HGNC:HGNC:50157,miRBase:MI0022965',
    'product' => 'hsa-miR-7114-5p',
    'gene' => 'MIR7114',
    'Parent' => 'rna-NR_106964.1'
  },
  'phase' => undef,
  'source' => 'BestRefSeq',
  'strand' => '-1'
};

STACK Bio::EnsEMBL::VEP::AnnotationSource::File::BaseGXF::_create_transcript /datapool/home/chenx/software/VEP/ensembl-vep-release-98/modules/Bio/EnsEMBL/VEP
STACK Bio::EnsEMBL::VEP::AnnotationSource::File::BaseGXF::lazy_load_transcript /datapool/home/chenx/software/VEP/ensembl-vep-release-98/modules/Bio/EnsEMBL/V
STACK Bio::EnsEMBL::VEP::AnnotationType::Transcript::annotate_InputBuffer /datapool/home/chenx/software/VEP/ensembl-vep-release-98/modules/Bio/EnsEMBL/VEP/An
STACK Bio::EnsEMBL::VEP::Runner::_buffer_to_output /datapool/home/chenx/software/VEP/ensembl-vep-release-98/modules/Bio/EnsEMBL/VEP/Runner.pm:402
STACK Bio::EnsEMBL::VEP::Runner::next_output_line /datapool/home/chenx/software/VEP/ensembl-vep-release-98/modules/Bio/EnsEMBL/VEP/Runner.pm:364
STACK Bio::EnsEMBL::VEP::Runner::run /datapool/home/chenx/software/VEP/ensembl-vep-release-98/modules/Bio/EnsEMBL/VEP/Runner.pm:202
STACK toplevel /datapool/home/chenx/software/VEP/ensembl-vep-release-98/vep:224

**Comment by aparton** [comment] 2020-04-08 09:28
Hi @daffay,

Thanks for this report, could you please email a copy of your GFF file to helpdesk@ensembl.org so that I can take a closer look?

Kind Regards,
Andrew

**Comment by daffay** [comment] 2020-04-08 09:41
Hi @aparton,
thanks for the help; I will send you it .

**Comment by aparton** [comment] 2020-04-08 12:47
Hi,

Thanks for this report. Unfortunately, it looks as if our GFF code is not expecting entries of type 'miRNA' to have parents of type 'transcript'. It's expecting miRNA rows to be attached to the gene.

However, this behaviour should be supported. We'll improve our GFF file handling to support this, however I'm unable to provide an estimate of how long this will take. I'll let you know when this functionality is available.

As a workaround, I believe your GFF file is taken from NCBI? We intend to provide updates to our GRCh37 transcript set for Ensembl 100, scheduled for release at the end of the month. Using these new cache files should allow you annotate your variants in the same way without using our custom annotation functionality.

I'm sorry that I wasn't able to give you a more helpful response. I'll let you know when a fix is in place.

Kind Regards, 
Andrew

**Comment by daffay** [comment] 2020-04-08 13:19
Hi.
Thank you very much for your answer. Yes my gff is taken from NCBI.I'm very happy  you update GRCh37 transcript set for Ensemble 100. I will update until then .Thank you.
Best wishes
daffay

**Comment by aparton** [comment] 2020-04-30 12:24
Hi @daffay,

Just to let you know, Ensembl 100 has just been released, including the updated GRCh37 transcript set.

Kind Regards,
Andrew

**Comment by aparton** [comment] 2020-06-25 13:28
Hi,

I'm going to close this ticket now. If you have any further questions, please feel free to reopen it or create a new one.

Kind Regards,
Andrew

**Comment by rollf** [comment] 2020-06-26 06:08
Hi @aparton,

my understanding is that one can still not use any GFF with these problematic miRNA entries (as you described above) but for the specific case of the GCF_000001405.25_GRCh37.p13_genomic.gff.gz the problem is "solved" by using the appropriate cache from VEP 100, right? If that is the case, I think the ticket should stay open since the actual issue is not resolved.

Best,
Rolf

**Comment by anubhabkhan** [comment] 2021-07-09 11:30
Hey,

I face the exact same issue but I don't work on human datasets. Any suggestions on how I can resolve this :

-------------------- EXCEPTION --------------------
MSG: ERROR: Transcript has unexpected type of child record: $VAR1 = {
  'start' => '7449023',
  'end' => '7449045',
  'source' => 'BestRefSeq',
  'chr' => 'NC_009144.3',
  'type' => 'miRNA',
  'strand' => '1',
  'md5' => '8a14061eb0a6d49794ab56b766df8ada',
  '_id' => 'rna-MIR9043',
  '_parent_id' => [
    'rna-NR_128060.1'
  ],
  'phase' => undef,
  'attributes' => {
    'product' => 'eca-miR-9043',
    'gbkey' => 'ncRNA',
    'Dbxref' => 'GeneID:104796477,miRBase:MIMAT0034586,miRBase:MI0028210',
    'gene' => 'MIR9043',
    'Parent' => 'rna-NR_128060.1',
    'ID' => 'rna-MIR9043'
  },
  '_children' => [
    {
      'attributes' => {
        'gbkey' => 'ncRNA',
        'product' => 'eca-miR-9043',
        'Dbxref' => 'GeneID:104796477,miRBase:MIMAT0034586,miRBase:MI0028210',
        'gene' => 'MIR9043',
        'ID' => 'exon-MIR9043-1',
        'Parent' => 'rna-MIR9043'
      },
      '_parent_id' => [
        'rna-MIR9043'
      ],
      'phase' => undef,
      '_id' => 'exon-MIR9043-1',
      'chr' => 'NC_009144.3',
      'source' => 'BestRefSeq',
      'end' => '7449045',
      'start' => '7449023',
      'md5' => 'dcdd110d42331f4369e912e6991f356a',
      'strand' => '1',
      'type' => 'exon'
    }
  ]
};


STACK Bio::EnsEMBL::VEP::AnnotationSource::File::BaseGXF::_create_transcript /shared3/Anubhab/miniconda3/envs/vep/share/ensembl-vep-104.3-0/modules/Bio/EnsEMBL/VEP/AnnotationSource/File/BaseGXF.pm:507
STACK Bio::EnsEMBL::VEP::AnnotationSource::File::BaseGXF::lazy_load_transcript /shared3/Anubhab/miniconda3/envs/vep/share/ensembl-vep-104.3-0/modules/Bio/EnsEMBL/VEP/AnnotationSource/File/BaseGXF.pm:810
STACK Bio::EnsEMBL::VEP::AnnotationType::Transcript::annotate_InputBuffer /shared3/Anubhab/miniconda3/envs/vep/share/ensembl-vep-104.3-0/modules/Bio/EnsEMBL/VEP/AnnotationType/Transcript.pm:112
STACK Bio::EnsEMBL::VEP::Runner::_buffer_to_output /shared3/Anubhab/miniconda3/envs/vep/share/ensembl-vep-104.3-0/modules/Bio/EnsEMBL/VEP/Runner.pm:407
STACK Bio::EnsEMBL::VEP::Runner::next_output_line /shared3/Anubhab/miniconda3/envs/vep/share/ensembl-vep-104.3-0/modules/Bio/EnsEMBL/VEP/Runner.pm:369
STACK Bio::EnsEMBL::VEP::Runner::run /shared3/Anubhab/miniconda3/envs/vep/share/ensembl-vep-104.3-0/modules/Bio/EnsEMBL/VEP/Runner.pm:207
STACK toplevel /shared3/Anubhab/miniconda3/envs/vep/bin/vep:232
Date (localtime)    = Fri Jul  9 12:28:15 2021
Ensembl API version = 104

**Comment by aparton** [comment] 2021-07-09 19:58
Hi @anubhabkhan,

Can you please send me the section of your GFF file containing the relevant genes/transcripts/mirnas (surrounding rna-MIR9043, exon-MIR9043-1 rna-NR_128060.1) and I can take a closer look?

Kind Regards,
Andrew

**Comment by anubhabkhan** [comment] 2021-07-09 21:16
Hi Andrew,

I am bit new to this. I downloaded the .gff file from NCBI ftp server using the link (https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/002/863/925/GCF_002863925.1_EquCab3.0/GCF_002863925.1_EquCab3.0_genomic.gff.gz <https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/002/863/925/GCF_002863925.1_EquCab3.0/GCF_002863925.1_EquCab3.0_genomic.gff.gz>)
Then I bgzipped and indexed it using the steps described in vep manual.

Anubhab

**Comment by anubhabkhan** [comment] 2022-04-07 14:56
Hey Andrew, just checking if there are any updates on this? Do you think it is okay to simply delete the ncRNA and miRNA lines from vcf before running?

**Comment by dglemos** [comment] 2022-10-21 13:21
Hi,
As mentioned before. this error is caused by miRNA being directly attached to a transcript instead of a gene as supported by VEP. A workaround is either:
- using the VEP cache files for the annotation
- remove miRNA entries from the GFF file before running the VEP job
- if you prefer you can point to branch release/109 which includes a temporary fix for these specific GFF entries

We plan to support these types in the future however we cannot tell when that will be available. I will close the issue for now but we'll let you know if there is any update.

Best wishes,
Diana

**Closed by dglemos** 2022-10-21 13:21 UTC
Labels: custom annotation, GFF/GTF
