### ISSUE TITLE
A CHEK1 variant caused the program to break

### ISSUE THREAD

**Issue by GSYongWu** [Ensembl/ensembl-vep#791] opened 2020-07-02 05:03 UTC
## Additional information
Please fill in the following sections to help us find the source of your issue as quickly as possible.

### System
- VEP version: [100.1] 
- VEP Cache version: [100]
- Perl version: [e.g. 5.16]
- OS: [redhat]
- tabix installed 

### Full VEP command line
```
vep --offline --no_stats --buffer_size 10000 --fork 4 --ccds --uniprot --hgvs --symbol --shift_3prime 1 --numbers --canonical --protein --biotype --hgvsg --variant_class --shift_hgvs 1 --total_length --force_overwrite --allele_number --no_escape --vcf --dir vep100 --fasta hs37d5.fa --format vcf --input_file  test.in.vcf --output_file test.out.vep.vcf  --refseq --use_given_ref
```

### Full error message
> substr outside of string at /GPFS01/bitbucket/GSCAP2020/resources/public/softwares/vep/Bio/EnsEMBL/Variation/Utils/VariationEffect.pm line 825.
Died in forked process 7226

### Data files (if applicable)
They include:
- The input file
[test.in.txt](https://github.com/Ensembl/ensembl-vep/files/4862060/test.in.txt)

- The output file
- The custom file(s)
You can provide a sample of them

**Comment by dglemos** [comment] 2020-07-02 09:52
Hi, 
It seems that VEP is breaking with the flag `--shift_3prime 1`. We are looking into the issue and we'll let you know more.

**Comment by GSYongWu** [comment] 2021-04-23 05:59
Hi,
Has this problem been resolved in the new version? We have encountered this problem frequently recently, and we urgently want to use a new version to solve this problem.

**Comment by aparton** [comment] 2021-04-23 16:16
Hi @GSYongWu,

Unfortunately this issue is still present within VEP. We're currently investigating a solution, but I have no timescale on when this is likely to be available I'm afraid.

As a workaround, removing the `--shift_3prime` option will prevent the error from occuring, but I accept that this is less than ideal. 

Kind Regards,
Andrew

**Comment by magower** [comment] 2023-07-13 07:46
I also encountered the same problem in VEP 106 version, when my input variant was:
`8	11565775	11565774	-/CCTGCGAGGGAGAGAGAGGACACCGAAGCCGGGAGCTCGCAGGGACCAAGTCGGAGGCCAAGCGGTCTTAGGAAGACAAGTTGATGCGACTGATAAGGTCGCCATGCCTCTCAGTACGTCAGCAGTTGAACGTTCGGCAACTCCTTGGCTCACAGAACGACATGGCTACGATCCGACATGGTC`
Run with the following command：
`vep --fasta hg19/ucsc.hg19.fasta.gz --merged --af_1kg --af_gnomad --numbers --symbol --force_overwrite --max_af --hgvs --offline --dir_cache vep/106 --shift_3prime 1 --shift_length `
I got an error:
`substr outside of string at  ensembl-vep-106.1-0/Bio/EnsEMBL/Variation/Utils/VariationEffect.pm line 855, <__ANONIO__> line 1`

✅I checked the script and found that the error was caused by the CDS sequence obtained was too short to find the appropriate position when inserting the allele. I optimized the script：
line 851, `ensembl-vep-106.1-0/Bio/EnsEMBL/Variation/Utils/VariationEffect.pm` add:
`return 0 unless length($utr_and_translateable) > $cdna_start - 1;`

Now I can annotate the mutation normally！

**Comment by dglemos** [comment] 2024-10-28 18:18
Hi @GSYongWu, @magower,
We have improved this part of the VEP code, this issue should be resolved now.
Please update VEP to the latest version to ensure you're using the most up-to-date code.

Best wishes,
Diana

**Closed by dglemos** 2024-10-28 18:18 UTC
Labels: shift_3prime
