### ISSUE TITLE
Mismatching variation_feature_seq and variation_feature->start/end in Transcript plugin

### ISSUE THREAD

**Issue by YStrauch** [Ensembl/ensembl-vep#1030] opened 2021-08-04 11:08 UTC
## Describe the issue
I have two ways of describing the variant NM_000059.3:c.470_474del (see example VCF below): The second one is "left aligned" (I used bcftools norm). I triple checked that they have equivalent effects. Some tools I work with need left aligned variants, so I'd prefer the second representation.
However, my VEP plugin receives mismatching coordinates and reference sequences for the second one (first one works fine). The second one's variation_feature_seq is AGTCA but the coordinates are supposedly 32326144-32326148, which is one basepair too far upstream.

I've attached a minimal plugin to reproduce the issue I'm facing together with the in- and output VCFs. I hope that the mistake is not on my side.

### System
- VEP version: 104.1af1dce
- VEP Cache version: --database
- Perl version: v5.26.1
- OS: Docker container ensemblorg/ensembl-vep, host is MacOS
- tabix installed ? Yes

### Full VEP command line
```
vep --distance 5000 --hgvs --vcf --force_overwrite --plugin Example --species homo_sapiens --transcript_version --input_file /opt/vep/.vep/test_variant.vcf  --output_file /opt/vep/.vep/out_test_variant.vcf --database
```

### Full error message
One warning:
```
"my" variable $sth masks earlier declaration in same scope at
	/opt/vep/src/ensembl-vep/Bio/EnsEMBL/DBSQL/TranslationAdaptor.pm line 607, <__ANONIO__> line 7 (#1)
    (W misc) A "my", "our" or "state" variable has been redeclared in the
    current scope or statement, effectively eliminating all access to the
    previous instance.  This is almost always a typographical error.  Note
    that the earlier variable will still exist until the end of the scope
    or until all closure references to it are destroyed.
```

### Data files (if applicable)
test_variant.vcf:
```
##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
##reference=GRCh38
##contig=<ID=chr13>
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
chr13	32326145	NM_000059.3:c.470_474del	AGTCAG	G	.	.	.
chr13	32326143	NM_000059.3:c.470_474del	TAAGTC	T	.	.	.
```

Example.pm:
```
package Example;

use strict;
use warnings;
use diagnostics;
use List::Util qw(min max);

use Bio::EnsEMBL::Variation::Utils::BaseVepPlugin;
use base qw(Bio::EnsEMBL::Variation::Utils::BaseVepPlugin);

sub new {
    my $class = shift;
    my $self = $class->SUPER::new(@_);

    return $self;
}

sub feature_types {
    return ['Transcript'];
}

sub get_header_info {
    return {
        start => '$tva->variation_feature->start',
        end => '$tva->variation_feature->end',
        ref => '$tva->transcript_variation->get_reference_TranscriptVariationAllele->variation_feature_seq',
        ref_val => '$tva->variation_feature->{slice}->sub_Slice($start, $end, 1)->seq;',
    };
}

sub run {
    my ($self, $tva) = @_;
    my $vf = $tva->variation_feature;
    my $start = $vf->{start};
    my $end = $vf->{end};

    my $ref = $tva->transcript_variation->get_reference_TranscriptVariationAllele->variation_feature_seq;
    my $ref_val = $vf->{slice}->sub_Slice($start, $end, 1)->seq;

    # die("REF mismatch, expected '$ref' but sliced '$ref_val'") unless $ref eq $ref_val;

    return {
        start => $start,
        end => $end,
        ref => $ref,
        ref_val => $ref_val
    };
}

1;
```

out_test_variant.vcf
```
##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
##reference=GRCh38
##contig=<ID=chr13>
##VEP="v104" time="2021-08-04 10:45:12" db="homo_sapiens_core_104_38@ensembldb.ensembl.org" ensembl-io=104.1d3bb6e ensembl=104.1af1dce ensembl-variation=104.6154f8b ensembl-funcgen=104.59ae779 assembly="GRCh38.p13" gencode="GENCODE 38" genebuild="2014-07"
##INFO=<ID=CSQ,Number=.,Type=String,Description="Consequence annotations from Ensembl VEP. Format: Allele|Consequence|IMPACT|SYMBOL|Gene|Feature_type|Feature|BIOTYPE|EXON|INTRON|HGVSc|HGVSp|cDNA_position|CDS_position|Protein_position|Amino_acids|Codons|Existing_variation|DISTANCE|STRAND|FLAGS|SYMBOL_SOURCE|HGNC_ID|HGVS_OFFSET|end|ref|ref_val|start">
##end=$tva->variation_feature->end
##ref=$tva->transcript_variation->get_reference_TranscriptVariationAllele->variation_feature_seq
##ref_val=$tva->variation_feature->{slice}->sub_Slice($start, $end, 1)->seq;
##start=$tva->variation_feature->start
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
chr13	32326145	NM_000059.3:c.470_474del	AGTCAG	G	.	.	CSQ=G|frameshift_variant&splice_region_variant|HIGH|BRCA2|ENSG00000139618|Transcript|ENST00000380152.8|protein_coding|5/27||ENST00000380152.8:c.470_474del|ENSP00000369497.3:p.Lys157SerfsTer24|669-674|470-475|157-159|KSV/SX|aAGTCAGtg/aGtg|||1||HGNC|HGNC:1101||32326150|AGTCAG|AGTCAG|32326145,G|frameshift_variant&splice_region_variant|HIGH|BRCA2|ENSG00000139618|Transcript|ENST00000530893.6|protein_coding|5/10||ENST00000530893.6:c.101_105del|ENSP00000499438.1:p.Lys34SerfsTer24|668-673|101-106|34-36|KSV/SX|aAGTCAGtg/aGtg|||1|cds_end_NF|HGNC|HGNC:1101||32326150|AGTCAG|AGTCAG|32326145,G|frameshift_variant&splice_region_variant|HIGH|BRCA2|ENSG00000139618|Transcript|ENST00000544455.6|protein_coding|5/27||ENST00000544455.6:c.470_474del|ENSP00000439902.1:p.Lys157SerfsTer24|569-574|470-475|157-159|KSV/SX|aAGTCAGtg/aGtg|||1||HGNC|HGNC:1101||32326150|AGTCAG|AGTCAG|32326145,G|frameshift_variant&splice_region_variant&NMD_transcript_variant|HIGH|BRCA2|ENSG00000139618|Transcript|ENST00000614259.2|nonsense_mediated_decay|4/26||ENST00000614259.2:c.470_474del|ENSP00000506251.1:p.Lys157SerfsTer24|470-475|470-475|157-159|KSV/SX|aAGTCAGtg/aGtg|||1||HGNC|HGNC:1101||32326150|AGTCAG|AGTCAG|32326145,G|frameshift_variant&splice_region_variant|HIGH|BRCA2|ENSG00000139618|Transcript|ENST00000680887.1|protein_coding|5/27||ENST00000680887.1:c.470_474del|ENSP00000505508.1:p.Lys157SerfsTer24|595-600|470-475|157-159|KSV/SX|aAGTCAGtg/aGtg|||1||HGNC|HGNC:1101||32326150|AGTCAG|AGTCAG|32326145
chr13	32326143	NM_000059.3:c.470_474del	TAAGTC	T	.	.	CSQ=-|frameshift_variant&splice_region_variant|HIGH|BRCA2|ENSG00000139618|Transcript|ENST00000380152.8|protein_coding|5/27||ENST00000380152.8:c.470_474del|ENSP00000369497.3:p.Lys157SerfsTer24|668-672|469-473|157-158|KS/X|AAGTCa/a|||1||HGNC|HGNC:1101|1|32326148|AGTCA|AAGTC|32326144,-|frameshift_variant&splice_region_variant|HIGH|BRCA2|ENSG00000139618|Transcript|ENST00000530893.6|protein_coding|5/10||ENST00000530893.6:c.101_105del|ENSP00000499438.1:p.Lys34SerfsTer24|667-671|100-104|34-35|KS/X|AAGTCa/a|||1|cds_end_NF|HGNC|HGNC:1101|1|32326148|AGTCA|AAGTC|32326144,-|frameshift_variant&splice_region_variant|HIGH|BRCA2|ENSG00000139618|Transcript|ENST00000544455.6|protein_coding|5/27||ENST00000544455.6:c.470_474del|ENSP00000439902.1:p.Lys157SerfsTer24|568-572|469-473|157-158|KS/X|AAGTCa/a|||1||HGNC|HGNC:1101|1|32326148|AGTCA|AAGTC|32326144,-|frameshift_variant&splice_region_variant&NMD_transcript_variant|HIGH|BRCA2|ENSG00000139618|Transcript|ENST00000614259.2|nonsense_mediated_decay|4/26||ENST00000614259.2:c.470_474del|ENSP00000506251.1:p.Lys157SerfsTer24|469-473|469-473|157-158|KS/X|AAGTCa/a|||1||HGNC|HGNC:1101|1|32326148|AGTCA|AAGTC|32326144,-|frameshift_variant&splice_region_variant|HIGH|BRCA2|ENSG00000139618|Transcript|ENST00000680887.1|protein_coding|5/27||ENST00000680887.1:c.470_474del|ENSP00000505508.1:p.Lys157SerfsTer24|594-598|469-473|157-158|KS/X|AAGTCa/a|||1||HGNC|HGNC:1101|1|32326148|AGTCA|AAGTC|32326144
```

**Comment by aparton** [comment] 2021-08-05 17:32
Hi @YStrauch,

Thank you for this report. I can reproduce the issue, we'll take a closer look and then let you know when we know more about what's going on.

Kind Regards,
Andrew

**Comment by nakib103** [comment] 2024-09-04 15:59
Hello @YStrauch,

The first variant here is represented wrongly. In [VCF specification](https://samtools.github.io/hts-specs/VCFv4.4.pdf) the anchor base should be used before the variant not after -

> For simple insertions and deletions
in which either the REF or one of the ALT alleles would otherwise be null/empty, the REF and ALT Strings
must include the base before the variant (which must be reflected in the POS field), unless the variant occurs
at position 1 on the contig in which case it must include the base after the variant

The reason you are seeing 1bp shift in the second variant is that VEP converts VCF like co-oridnates representation to Ensembl like co-originates (see [here](https://www.ensembl.org/info/docs/tools/vep/vep_formats.html#vcf)). That is whythe anchor base is removed and position is shifted.

I will close this issue as this has been long. Hopefully I have answered your question but if you face any problem feel free to open a new one.

Best regards,
Nakib

**Closed by nakib103** 2024-09-04 15:59 UTC
