### ISSUE TITLE
spliceAI not giving output value while running using vep (Variant Ensemble Predictor)

### ISSUE THREAD

**Issue by sruthisrini** [Ensembl/ensembl-vep#1472] opened 2023-08-07 07:38 UTC
While generating the predictions using spliceAI from vep, I am not getting any values.
I used this command to generate the output,

/vep -i input.vcf -o output.vcf --cache --force_overwrite --tab --no_check_variants_order --force --plugin SpliceAI,snv=spliceai_scores.raw.snv.hg38.vcf.gz,indel=spliceai_scores.raw.indel.hg38.vcf.gz

Below, are the examples of entries in the output file.

ENSEMBL VARIANT EFFECT PREDICTOR v109.3
Output produced at 2023-08-07 09:05:43
Connected to homo_sapiens_core_109_38 on ensembldb.ensembl.org
Using cache in /.vep/homo_sapiens/109_GRCh38
Using API version 109, DB version 109
ensembl-io version 109.4946a86
ensembl version 109.10baaec
ensembl-funcgen version 109.cba2db8
ensembl-variation version 109.18a12b6
...
#Uploaded_variation Location Allele Gene Feature Feature_type Consequence cDNA_position CDS_position Protein_position Amino_acids Codons Existing_variation IMPACT DISTANCE STRAND FLAGS SpliceAI_pred
100017682 chr1:100017682 A ENSG00000117620 ENST00000370153 Transcript missense_variant,splice_region_variant 981 880 294 A/T Gca/Aca - MODERATE - -
100017682 chr1:100017682 A ENSG00000117620 ENST00000370155 Transcript splice_region_variant,3_prime_UTR_variant,NMD_transcript_variant 882 - - - - LOW - 1 - -

Is there any wrong in the input file? Could anyone help here?

**Comment by dglemos** [comment] 2023-08-08 12:31
Hi @sruthisrini,
Can you please send your input file?
It could be a problem when matching the alleles - the plugin is not going to fetch the scores if the alleles in the SpliceAI file are different from the input. 

In the SpliceAI file the ref allele is G:
```
> tabix spliceai_scores.raw.snv.hg38.vcf.gz 1:100017682-100017682
1	100017682	.	G	A	.	.	SpliceAI=A|SLC35A3|0.00|0.12|0.00|0.00|36|0|0|34
1	100017682	.	G	C	.	.	SpliceAI=C|SLC35A3|0.00|0.17|0.00|0.00|36|0|0|34
1	100017682	.	G	T	.	.	SpliceAI=T|SLC35A3|0.00|0.40|0.00|0.00|36|0|0|34
```

**Comment by sruthisrini** [comment] 2023-08-08 12:36
The original input file before annotation looks like this:

```
##fileformat=VCFv4.2
##fileDate=20220709
##reference=GRCh38
#CHROM EXON_START EXON_END	REF	ALT	QUAL	FILTER	INFO
1	100017682	100017682	G	A	.	.	.	
1	100059878	100059878	G	T	.	.	.	
1	100133150	100133150	G	A	.	.	.	
1	100133215	100133215	A	T	.	.	.	
1	100140182	100140182	G	C	.	.	.	
```

**Comment by dglemos** [comment] 2023-08-08 12:45
Unfortunately, I cannot reproduce the issue. My output includes the SpliceAI scores as expected.
Did VEP throw any error/warning message when you ran the command?

**Comment by dglemos** [comment] 2023-08-08 13:54
What do you get when you run the following command?
`tabix /Downloads/spliceai_scores.raw.snv.hg38.vcf.gz 1:100017682-100017682`

**Comment by dglemos** [comment] 2023-08-08 14:07
The output to the last command is supposed to be this one:
```
1	100017682	.	G	A	.	.	SpliceAI=A|SLC35A3|0.00|0.12|0.00|0.00|36|0|0|34
1	100017682	.	G	C	.	.	SpliceAI=C|SLC35A3|0.00|0.17|0.00|0.00|36|0|0|34
1	100017682	.	G	T	.	.	SpliceAI=T|SLC35A3|0.00|0.40|0.00|0.00|36|0|0|34
```

If you don't get an output then the SpliceAI file is missing these scores.
What is the size of spliceai_scores.raw.snv.hg38.vcf.gz and spliceai_scores.raw.indel.hg38.vcf.gz?

**Comment by sruthisrini** [comment] 2023-08-08 14:16
```
spliceai_scores.raw.snv.hg38.vcf.gz -> 1
spliceai_scores.raw.snv.hg38.vcf -> 975
spliceai_scores.raw.snv.hg38.vcf.gz.tbi -> 3844

spliceai_scores.raw.indel.hg38.vcf.gz.tbi -> 6647
spliceai_scores.raw.indel.hg38.vcf.gz -> 344737628
```
 
After seeing the length, I am bit confused if I did something wrong.

**Comment by dglemos** [comment] 2023-08-08 14:23
Your files look truncated.
spliceai_scores.raw.snv.hg38.vcf.gz is supposed to be 27G
spliceai_scores.raw.indel.hg38.vcf.gz is 65G
Probably something happened when you downloaded/copied the files. You should download the files again.

Let me know how it goes.

**Comment by sruthisrini** [comment] 2023-08-08 14:28
<img width="1335" alt="image" src="https://github.com/Ensembl/ensembl-vep/assets/29732975/0c7d2976-9f3f-45bc-b6d3-a715f189ee31">

I just found spliceai_scores.raw.snv.hg38.vcf.gz is 333 bytes and  spliceai_scores.raw.indel.hg38.vcf.gz is 65G.
I am downloading spliceai_scores.raw.snv.hg38.vcf.gz again. I will let you know once I download and run it again.

Thanks for your kind help!

**Comment by sruthisrini** [comment] 2023-08-08 16:18
I tried again and obtained the below output,

```
#Uploaded_variation	Location	Allele	Gene	Feature	Feature_type	Consequence	cDNA_position	CDS_position	Protein_position	Amino_acids	Codons	Existing_variation	IMPACT	DISTANCE	STRAND	FLAGS	SpliceAI_pred
100017682	1:100017682	A	ENSG00000117620	ENST00000370153	Transcript	missense_variant,splice_region_variant	981	880	294	A/T	Gca/Aca	-	MODERATE	-	1	-	SLC35A3|0.00|0.12|0.00|0.00|36|0|0|34
100017682	1:100017682	A	ENSG00000117620	ENST00000370155	Transcript	splice_region_variant,3_prime_UTR_variant,NMD_transcript_variant	882	-	-LOW	-	1	-	SLC35A3|0.00|0.12|0.00|0.00|36|0|0|34
100017682	1:100017682	A	ENSG00000117620	ENST00000422078	Transcript	downstream_gene_variant	-	-	-	-	-	-	MODIFIER	2341	1	-	SLC35A3|0.00|0.12|0.00|0.00|36|0|0|34
100017682	1:100017682	A	ENSG00000117620	ENST00000427993	Transcript	missense_variant,splice_region_variant	1055	754	252	A/T	Gca/Aca	-	MODERATE	-	1	-	SLC35A3|0.00|0.12|0.00|0.00|36|0|0|34
100017682	1:100017682	A	ENSG00000117620	ENST00000465289	Transcript	missense_variant,splice_region_variant	1060	754	252	A/T	Gca/Aca	-	MODERATE	-	1	-	SLC35A3|0.00|0.12|0.00|0.00|36|0|0|34
100017682	1:100017682	A	ENSG00000117620	ENST00000533028	Transcript	missense_variant,splice_region_variant	939	754	252	A/T	Gca/Aca	-	MODERATE	-	1	-	SLC35A3|0.00|0.12|0.00|0.00|36|0|0|34
100017682	1:100017682	A	ENSG00000117620	ENST00000638336	Transcript	intron_variant	-	-	-	-	-	-	MODIFIER	-	1SLC35A3|0.00|0.12|0.00|0.00|36|0|0|34
100017682	1:100017682	A	ENSG00000117620	ENST00000638338	Transcript	intron_variant	-	-	-	-	-	-	MODIFIER	-	1SLC35A3|0.00|0.12|0.00|0.00|36|0|0|34
```

This is how I am supposed to get the output for spliceAI right?

**Comment by dglemos** [comment] 2023-08-18 09:51
I'm going to close this issue but please open a new one if you find more issues.

Best wishes,
Diana

**Closed by dglemos** 2023-08-18 09:51 UTC
