### ISSUE TITLE
The annotation results in the SYMBOL and BIOTYPE  field are incorrect. 

### ISSUE THREAD

**Issue by JeWeizhong** [Ensembl/ensembl-vep#1542] opened 2023-10-30 04:31 UTC
### System
- VEP version: 110.1
- VEP Cache version: 110
- docker image: ensemblorg/ensembl-vep:release_110.1

### Full VEP command line
```
vep -i test1.vcf.gz -o test1.anno.vcf.gz --cache --species homo_sapiens --assembly GRCh38 --compress_output gzip --force_overwrite --offline --vcf --fork 8 --symbol --canonical --protein --distance 0 --variant_class --fasta hg38.fa --merge --hgvs --no_escape --numbers
```
Symbols in the SYMBOL field are empty, and the BIOTYPE is gene Symbol.
![image](https://github.com/Ensembl/ensembl-vep/assets/29620633/87e18264-fbb9-482e-ac45-06c266a82434)

**Comment by dglemos** [comment] 2023-10-30 13:14
Hi @JeWeizhong,
Is this the only example you found without the gene symbol?
For this specific variant 11 5225126 5225126 T/A, the biotype is `TEC` which stands for `To be Experimentally Confirmed`. You can find a description for this term in the glossary [here](https://www.ensembl.org/Help/Glossary).

Regarding the gene symbol, this field is empty because this gene does not have a symbol yet. You can check the gene page here: https://www.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000285498;r=11:5224309-5225461;t=ENST00000644706

**Comment by dglemos** [comment] 2023-10-30 13:33
Which software did you use?
These two genes do not overlap. The gene ENSG00000285498 overlaps region: `11:5,224,309-5,225,461`
Meanwhile gene HBB (ENSG00000244734) overlaps region: `11:5,225,464-5,229,395`

**Comment by JeWeizhong** [comment] 2023-10-30 14:19
> Which software did you use? These two genes do not overlap. The gene ENSG00000285498 overlaps region: `11:5,224,309-5,225,461` Meanwhile gene HBB (ENSG00000244734) overlaps region: `11:5,225,464-5,229,395`

I obtained the annotation results using snpEff

I suspect it may be due to using different genome annotation versions.The genomic interval I previously downloaded from Ensembl FTP for version 107 is 11:5224309-5225461.

vep:
![image](https://github.com/Ensembl/ensembl-vep/assets/29620633/0584f79a-b7b8-418e-afba-96f8223f1e24)

snpEff, GRCh38.105:
![image](https://github.com/Ensembl/ensembl-vep/assets/29620633/3e79d80c-1815-40e7-b355-aeeda7d6fb65)

Thinks.

**Comment by dglemos** [comment] 2023-10-30 15:55
In the command above you use the option `--distance 0` this is the distance VEP uses to calculate the distance up and/or downstream between the variant and the transcript (default 5000). The gene HBB is downstream of your variant however VEP cannot calculate this consequence if you set the distance to zero.
snpEff returned the downstream consequence for HBB probably because it uses a distance different from zero.

**Comment by dglemos** [comment] 2023-11-09 18:16
As the initial problem has been resolved, I'm going to close this ticket. Please feel free to re-open it if you have more questions.

Best wishes,
Diana

**Closed by dglemos** 2023-11-09 18:16 UTC
