### ISSUE TITLE
ALT=<DEL> lines missing in VEP output for DRAGEN format indel VCF

### ISSUE THREAD

**Issue by HaotingJia1** [Ensembl/ensembl-vep#1298] opened 2022-11-01 21:05 UTC
## Describe the issue
The output only has lines where ALT field is DUP. I want to get output for lines for DEL. Thank you.

### System
online VEP with all default options.

### Data files (if applicable)
input file:

> 
> ##fileformat=VCFv4.0
> ##FILTER=<ID=PASS,Description="All filters passed">
> ##ALT=<ID=CNV,Description="Copy number variant region">
> ##ALT=<ID=DEL,Description="Deletion relative to the reference">
> ##ALT=<ID=DUP,Description="Region of elevated copy number relative to the reference">
> ##contig=<ID=chr1,length=248956422>
> ##contig=<ID=chr10,length=133797422>
> ##contig=<ID=chr11,length=135086622>
> ##contig=<ID=chr12,length=133275309>
> ##contig=<ID=chr13,length=114364328>
> ##contig=<ID=chr14,length=107043718>
> ##contig=<ID=chr15,length=101991189>
> ##contig=<ID=chr16,length=90338345>
> ##contig=<ID=chr17,length=83257441>
> ##contig=<ID=chr18,length=80373285>
> ##contig=<ID=chr19,length=58617616>
> ##contig=<ID=chr2,length=242193529>
> ##contig=<ID=chr20,length=64444167>
> ##contig=<ID=chr21,length=46709983>
> ##contig=<ID=chr22,length=50818468>
> ##contig=<ID=chr3,length=198295559>
> ##contig=<ID=chr4,length=190214555>
> ##contig=<ID=chr5,length=181538259>
> ##contig=<ID=chr6,length=170805979>
> ##contig=<ID=chr7,length=159345973>
> ##contig=<ID=chr8,length=145138636>
> ##contig=<ID=chr9,length=138394717>
> ##contig=<ID=chrX,length=156040895>
> ##FILTER=<ID=cnvQual,Description="CNV with quality below 10">
> ##FILTER=<ID=cnvCopyRatio,Description="CNV with copy ratio within +/- 0.2 of 1.0">
> ##FORMAT=<ID=SM,Number=1,Type=Float,Description="Linear copy ratio of the segment mean">
> ##FORMAT=<ID=CN,Number=1,Type=Integer,Description="Estimated copy number">
> ##FORMAT=<ID=BC,Number=1,Type=Integer,Description="Number of bins in the region">
> ##FORMAT=<ID=PE,Number=2,Type=Integer,Description="Number of improperly paired end reads at start and stop breakpoints">
> #CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	c31465c8-4eb6-4b73-94c3-3e6157a9dc37
> chr1	46499	DRAGEN:LOSS:46499:56998	N	\<DEL>	34	PASS	.	SM:CN:BC:PE	0.650742:1:21:2,4
> chr1	68999	DRAGEN:LOSS:68999:96498	N	\<DEL>	45	PASS	.	SM:CN:BC:PE	0.6335:1:55:5,9
> chr1	180499	DRAGEN:GAIN:180499:184998	N	<DUP>	32	PASS	.	SM:CN:BC:PE	1.35488:3:9:57,7
> chr1	2651489	DRAGEN:GAIN:2651489:2656988	N	<DUP>	34	PASS	.	SM:CN:BC:PE	1.35803:3:11:227,271
> 

output:

> #Uploaded_variation	Location	Allele	Consequence	IMPACT	SYMBOL	Gene	Feature_type	Feature	BIOTYPE	EXON	INTRON	HGVSc	HGVSp	cDNA_position	CDS_position	Protein_position	Amino_acids	Codons	Existing_variation	DISTANCE	STRAND	FLAGS	SYMBOL_SOURCE	HGNC_ID	MANE_SELECT	MANE_PLUS_CLINICAL	TSL	APPRIS	SIFT	PolyPhen	AF	CLIN_SIG	SOMATIC	PHENO	PUBMED	MOTIF_NAME	MOTIF_POS	HIGH_INF_POS	MOTIF_SCORE_CHANGE	TRANSCRIPTION_FACTORS
> DRAGEN:GAIN:180499:184998	1:180499-180499	duplication	downstream_gene_variant	MODIFIER	WASH9P	ENSG00000279457	Transcript	ENST00000623083.4	unprocessed_pseudogene	-	-	-	-	-	-	-	-	-	-	4717	-1	-	HGNC	HGNC:53981	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-
> DRAGEN:GAIN:180499:184998	1:180499-180499	duplication	upstream_gene_variant	MODIFIER	DDX11L17	ENSG00000279928	Transcript	ENST00000624431.2	unprocessed_pseudogene	-	-	-	-	-	-	-	-	-	-	2196	1	-	HGNC	HGNC:55080	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-
> DRAGEN:GAIN:2651489:2656988	1:2651489-2651489	duplication	intron_variant,feature_elongation	MODIFIER	TTC34	ENSG00000215912	Transcript	ENST00000401095.9	protein_coding	-	6/8	-	-	-	-	-	-	-	-	-	-1	-	HGNC	HGNC:34297	NM_001242672.3	-	5	P1	-	-	-	-	-	-	-	-	-	-	-	-
> DRAGEN:GAIN:2651489:2656988	1:2651489-2651489	duplication	intron_variant,feature_elongation	MODIFIER	TTC34	ENSG00000215912	Transcript	ENST00000637179.1	protein_coding	-	4/6	-	-	-	-	-	-	-	-	-	-1	-	HGNC	HGNC:34297	-	-	5	-	-	-	-	-	-	-	-	-	-	-	-	-
>

**Comment by dglemos** [comment] 2022-11-02 09:06
Hi @HaotingJia1,
I cannot reproduce your output, all variants from your input are either incomplete or have invalid alleles.
VEP throws the following warning message:
```
WARNING: VCF line on line 1 looks incomplete, skipping:
chr1	46499	DRAGEN:LOSS:46499:56998	N	<DEL>	34	PASS	.	SM:CN:BC:PE	0.650742:1:21:2,4
WARNING: VCF line on line 2 looks incomplete, skipping:
chr1	68999	DRAGEN:LOSS:68999:96498	N	<DEL>	45	PASS	.	SM:CN:BC:PE	0.6335:1:55:5,9
WARNING: Invalid allele string N/32 on line 3 or possible parsing error
WARNING: Invalid allele string N/34 on line 4 or possible parsing error
```

Which VEP command did you run?

**Comment by HaotingJia1** [comment] 2022-11-02 17:33
Hi, thank you. i think the format is changed when i copy from my input file to here. What i did is to upload this `test.txt` file to https://useast.ensembl.org/Tools/VEP and hit run. The output only contains results of lines where ALT=<DUP>.

[test.txt](https://github.com/Ensembl/ensembl-vep/files/9922843/test.txt)

[test_ouput.txt](https://github.com/Ensembl/ensembl-vep/files/9922844/test_ouput.txt)

**Comment by dglemos** [comment] 2022-11-02 21:54
Thanks for sending the files, now I can reproduce the warning. The variants with type <DEL> are being skipped:
```
WARNING: VCF line on line 1 looks incomplete, skipping:
chr1	46499	DRAGEN:LOSS:46499:56998	N	<DEL>	34	PASS	.	SM:CN:BC:PE	0.650742:1:21:2,4
START-END: 69000-69000
WARNING: VCF line on line 2 looks incomplete, skipping:
chr1	68999	DRAGEN:LOSS:68999:96498	N	<DEL>	45	PASS	.	SM:CN:BC:PE	0.6335:1:55:5,9
```

For type DEL, VEP uses the `END` coordinate defined in the `INFO` field to determine the end of the deletion. Another way to know the end coordinate is to use the field `SVLEN`, however in your file none of these are defined meaning VEP is not able to determine the end coordinate.

You could edit these variants to include the end coordinate in the expected field, you could extract the info from the column `ID`. For example, the first variant has ID `DRAGEN:LOSS:46499:56998` probably `56998` is the end coordinate.

**Comment by dglemos** [comment] 2022-11-03 15:13
ALT is correct, what you need to do is add the end coordinate to the INFO column: `END=56998`
Something similar to:
`chr1	46499	DRAGEN:LOSS:46499:56998	N	<DEL>	34	PASS	END=56998	SM:CN:BC:PE	0.650742:1:21:2,4`

Here you can read more about the VCF format: https://samtools.github.io/hts-specs/VCFv4.2.pdf

**Comment by HaotingJia1** [comment] 2022-11-03 18:40
Thank you. I will try doing this.

**Comment by dglemos** [comment] 2022-11-29 10:40
Hi @HaotingJia1,
Did you try running VEP with an updated version of the input file?

**Comment by HaotingJia1** [comment] 2022-11-29 17:52
Yea I solved it thank you!

Best,
Haoting

**Comment by dglemos** [comment] 2022-11-29 18:00
I'm glad the issue is solved. I'm going to close the issue but feel free to open a new one if you have more questions.

Best wishes,
Diana

**Closed by dglemos** 2022-11-29 18:00 UTC

**Comment by zhangpicb** [comment] 2023-12-28 02:38
Dear @dglemos @HaotingJia1 

Sorry to reopen this issue

I don't know how to add END info to vcf INFO.
This is my imputed vcf,VEP skip DEL variants.

```
chr1    1248061 chr1_1248061_G_<DEL>_b38        G       <DEL>   -10     PASS    AF=0.2788;IMP;INFO=0.96;AC=56;AN=186    GT      1|0  
```

Thanks in advanced!

**Comment by nakib103** [comment] 2024-01-02 11:10
Hello @zhangpicb,

You can put the `END` in the `INFO` field. For example if there is a 100bp deletion from position than it would be 1248161 -
```
chr1    1248061 chr1_1248061_G_<DEL>_b38        G       <DEL>   -10     PASS    END=1248161;AF=0.2788;IMP;INFO=0.96;AC=56;AN=186    GT      1|0  
```

You can find more information in the VCF specification - https://samtools.github.io/hts-specs/VCFv4.2.pdf

The exact value of END you have to determine yourself based on the upstream process that produces these variants. 

Best regards,
Nakib
