### ISSUE TITLE
Different Effects of  The Same SNP

### ISSUE THREAD

**Issue by liangdy678** [Ensembl/ensembl-vep#1154] opened 2022-04-19 02:26 UTC
## Describe the issue
Sir，

We plan to predict the effect of the SNP( GRCh37: chrX-100085855-A-AG) via VEP Web interface, encountered some problems.

![图片1](https://user-images.githubusercontent.com/103975033/163904736-50128cb4-3a75-4c89-9721-cad7456babcc.png)

As we can see，insert the base [G] at any position (arrow) , results in a consistent effect .
So the SNP can be represented as [chrX-100085856-G-GG] or [chrX-100085857-G-GG] 
when we predict these snps above, some of the results are as follows：

X:100085855 [ frameshift_variant,   splice_region_variant ] NM_001306206.2:c.949+1dup
X:100085856 [ frameshift_variant,   splice_region_variant ] NM_001306206.2:c.949+1dup
X:100085857 [                splice_donor_variant                   ] NM_001306206.2:c.949+1dup

Could you please tell me  why conseqs of the first two are frameshit, I think that  None of transcripts seem to have frameshift mutations.

Thanks

## Additional information
Please fill in the following sections to help us find the source of your issue as quickly as possible.

### System
Web interface

**Comment by nakib103** [comment] 2022-04-19 11:45
Hello, I am closing this issue as it seems duplicate of this one - https://github.com/Ensembl/ensembl-vep/issues/1155.

**Closed by nakib103** 2022-04-19 11:45 UTC

**Comment by liangdy678** [comment] 2022-04-19 11:58
> Hello, I am closing this issue as it seems duplicate of this one - #1155.

ok, I am apologetic for  for the record duplication. o(╥﹏╥)o
