### ISSUE TITLE
issue with data  from gff flag when upgrading to VEP110 

### ISSUE THREAD

**Issue by atimms** [Ensembl/ensembl-vep#1570] opened 2023-12-01 16:23 UTC
## Describe the issue
The --gff flag doesn't annotate variants when using a cache and VEP 110. 

## Additional information
The same files and combination works with VEP107 and VEP109, and will work when not using a cache. The gff is listed in the header but is not present in any of the expected variants. This seems to be different behaviour between 110 and previous versions, I wondered if this is intentional and if there is a workaround to use a GFF with the cache in VEP 100.

### System
- VEP version: 110
- VEP Cache version: 110
using singularity built from biocontainer docker image

### Full VEP command line
```
vep \
--offline \
--cache \
--dir_cache ${vep_cache_dir} \
--refseq \
--use_given_ref \
--species homo_sapiens \
--assembly GRCh38 \
--fasta ${ref_fasta} \
--format vcf \
--vcf \
--variant_class \
--af_gnomadg \
--numbers \
--total_length \
--hgvs \
--symbol \
--canonical \
--exclude_predicted \
--distance 5000,250  \
--gff ${extra_transcripts_gff} \
--input_file ${vcf} \
--output_file ${vep110_vcf} 
```

### Full error message
No error message

**Comment by nuno-agostinho** [comment] 2024-01-08 12:34
Hi @atimms, sorry for the delay in replying.

I am not able to reproduce your issue using an Ensembl GFF file and a random input VCF. The variants are annotated as expected.

Could you please give me a set of example variants and the GFF file that you are having issues with? Thanks.

Best regards,
Nuno Agostinho

**Comment by atimms** [comment] 2024-01-08 17:23
Thanks for getting back to me.

I've attached the test VCF and gff file I was using. As I said before the annoitation working when using VEP107 but didn't when using VEP110.

Any help would be great.

Andrew

[off_menu_transcripts.hg38.gff.gz](https://github.com/Ensembl/ensembl-vep/files/13864178/off_menu_transcripts.hg38.gff.gz)
[small.vcf.gz](https://github.com/Ensembl/ensembl-vep/files/13864208/small.vcf.gz)

**Comment by nuno-agostinho** [comment] 2024-01-22 15:34
Hey @atimms,

Sorry for the delay in replaying.

This is a bug related with a change we made in VEP 110 to compare the chromosome name with the annotation. Unfortunately, the annotation uses the `chr` prefix (such as `chr16`) and the region is not considered as part of the same chromosome.

I will fix this as soon as possible. In the meantime, you can strip the `chr` prefix from your GFF annotation as a workaround.

Please tell me if the workaround works for you and if you found any other issues regarding custom annotation in VEP.

I am sorry for the inconvenience.

Best regards,
Nuno

**Comment by atimms** [comment] 2024-01-22 16:16
That's an easy resolution, thanks for letting me know what the issue was.

Andrew

**Comment by Sean-3B** [comment] 2024-03-06 07:49
Hello @nuno-agostinho,

I also had similar issue that the --custom option for gff annotation didn't work with VEP v111 using NCBI RefSeq GFF file.

Thanks to your answer in this issue, now I solved the problem by converting the NCBI chromosome ID (e.g. NC_000001.11) to chromosome number (e.g. 1).

But, I still need to preprocess NCBI gff file When I use it at VEP annotation. 

So, may I ask you to fix the VEP v111 to be able to use NCBI gff file?

Best regards,
Sean

**Comment by nuno-agostinho** [comment] 2024-03-06 10:12
Hi @atimms and @Sean-3B,

The bug fix was merged into our existing codebase and will be available in VEP 112.

@Sean-3B: unfortunately, this fix is not trivial to add to VEP 111. The workaround for now is to replace the chromosome names in GTF/GFF files until VEP 112 is released. Sorry for the inconvenience. Let me know if you need help with this.

Best regards,
Nuno

**Comment by barbarian1803** [comment] 2024-03-11 05:26
Hi,

I also have the same issue. I use GFF from Refseq I downloaded from here: https://ftp.ncbi.nlm.nih.gov/genomes/all/annotation_releases/9606/GCF_000001405.40-RS_2023_03/

The GFF use Refseq chromosome naming and I also provide synonym file but also has the same issue. Can you confirm if I have to change the chromosome name in the GFF file? 
Thank you.

**Comment by atimms** [comment] 2024-03-11 15:41
We resolved the issue by changing the chromosome names in the GFF file.

**Comment by nuno-agostinho** [comment] 2024-08-28 16:02
Hey @atimms, @barbarian1803 and @Sean-3B,

Hopefully with the current release of VEP 112, your issues have been fixed.

I will close this issue, but feel free to reply back if you are still facing related problems with the GFF annotation flag.

Thanks,
Nuno

**Closed by nuno-agostinho** 2024-08-28 16:02 UTC
Labels: GFF/GTF, e110
