### ISSUE TITLE
getting VEP to use Bio::DB::HTS on centos 7

### ISSUE THREAD

**Issue by ntm** [Ensembl/ensembl-vep#588] opened 2019-09-02 17:42 UTC
Hi,
installing VEP on Centos 7 currently requires
perl INSTALL.pl --NO_HTSLIB
because building BIO::DB::HTS fails.
Problem is just a wrong dependency in Bio::DB::HTS ("I want the latest even if no-one has it" where an older version is fine and ubiquitous).
This has been fixed upstream:
https://github.com/Ensembl/Bio-DB-HTS/commit/801e2ed8fb4a337bcfcf9d552173afdb63058f04

This fix can be easily propagated into ensembl-vep with the following tiny patch to INSTALL.pl :
-our $BIOHTS_VERSION  = '2.9';             # latest as of release/91
+our $BIOHTS_VERSION  = '3.01';             # latest as of release/97

It builds fine with this patch, and my very limited testing suggests it works.

Cheers,
Nicolas

**Comment by aparton** [comment] 2019-09-03 08:56
Hi Nicolas,

Thank you for this report. Unfortunately, our internal testing procedures have flagged some issues with upgrading to Bio::DB::HTS v3.01.

In this situation, we recommend updating your Module::Build to v0.42 or above. 

Kind Regards,
Andrew

**Comment by ntm** [comment] 2019-09-03 09:15
Thanks for your quick reply.
I wouldn't want to clobber core RHEL/Centos rpms on a production server, and doing so to fix an overzealous dependency doesn't feel right. But it's good to know that I shouldn't upgrade Bio::DB::HTS to v3.01 either. I guess we will just wait for the issues you mentioned to be fixed, and meanwhile we will keep using the slower external tabix calls.
Would you have any pointers to the issues you detected?
Best regards,
Nicolas

**Comment by aparton** [comment] 2019-09-10 06:56
Hi Nicolas,

I don't have any illuminating pointers I'm afraid, our internal pipelines were giving warnings and we're still investigating the root cause. I don't think it's anything too serious, but it's enough to stop us from upgrading at this stage.

Kind Regards,
Andrew

**Comment by aparton** [comment] 2019-10-21 19:25
Hi,

I'm going to close this issue now, however if you have any more questions please feel free to reopen it.

Kind Regards,
Andrew

**Closed by aparton** 2019-10-21 19:25 UTC
