### ISSUE TITLE
Wrong coordinates for insertions from vcf input

### ISSUE THREAD

**Issue by ddrichel** [Ensembl/ensembl-vep#1432] opened 2023-06-13 10:17 UTC
## Describe the issue
Coordinates for insertions relative to the reference should be as documented here:   http://www.ensembl.org/info/docs/tools/vep/vep_formats.html#input : 
"An insertion (of any size) is indicated by start coordinate = end coordinate + 1".
This makes sense, as the inserted sequence is not part of the reference sequence.
However, when vcf format is used, the coordinates are computed from POS and SVLEN, resulting in wrong coordinates - insertions extend beyond the insertion position, which consequently results in wrong annotations.

## Example
Example output for a vcf file containing a single Sniffles-called INS (CHROM 1, POS 146985757, SVLEN=17243):

#Uploaded_variation	Location	Allele	Gene	Feature	Feature_type	Consequence	cDNA_position	CDS_position	Protein_position	Amino_acids	Codons	Existing_variation	Extra
Sniffles2.INS.675FM0	chr1:146985758-147003000	insertion	ENSG00000234225	ENST00000425109	Transcript	splice_polypyrimidine_tract_variant,non_coding_transcript_exon_variant,intron_variant	230-?	-	-	-	-	-	IMPACT=LOW;STRAND=-1;OverlapBP=1070;OverlapPC=63.39
Sniffles2.INS.675FM0	chr1:146985758-147003000	insertion	ENSG00000268043	ENST00000439206	Transcript	splice_polypyrimidine_tract_variant,coding_sequence_variant,3_prime_UTR_variant,intron_variant	-	-	-	-	-	-	IMPACT=LOW;STRAND=1;OverlapBP=8844;OverlapPC=25.54
Sniffles2.INS.675FM0	chr1:146985758-147003000	insertion	ENSG00000234225	ENST00000455718	Transcript	splice_polypyrimidine_tract_variant,non_coding_transcript_exon_variant,intron_variant	185-?	-	-	-	-	-	IMPACT=LOW;STRAND=-1;OverlapBP=719;OverlapPC=79.62
Sniffles2.INS.675FM0	chr1:146985758-147003000	insertion	ENSG00000268043	ENST00000611443	Transcript	splice_polypyrimidine_tract_variant,coding_sequence_variant,3_prime_UTR_variant,intron_variant	-	-	-	-	-	-	IMPACT=LOW;STRAND=1;OverlapBP=10336;OverlapPC=22.09
Sniffles2.INS.675FM0	chr1:146985758-147003000	insertion	ENSG00000268043	ENST00000613714	Transcript	splice_polypyrimidine_tract_variant,coding_sequence_variant,3_prime_UTR_variant,intron_variant	-	-	-	-	-	-	IMPACT=LOW;STRAND=1;OverlapBP=8844;OverlapPC=25.54
Sniffles2.INS.675FM0	chr1:146985758-147003000	insertion	ENSG00000268043	ENST00000617844	Transcript	splice_polypyrimidine_tract_variant,coding_sequence_variant,3_prime_UTR_variant,intron_variant	-	-	-	-	-	-	IMPACT=LOW;STRAND=1;OverlapBP=10336;OverlapPC=22.09
Sniffles2.INS.675FM0	chr1:146985758-147003000	insertion	ENSG00000268043	ENST00000617931	Transcript	splice_polypyrimidine_tract_variant,coding_sequence_variant,3_prime_UTR_variant,intron_variant	-	-	-	-	-	-	IMPACT=LOW;STRAND=1;OverlapBP=10445;OverlapPC=18.18

Using the custom VEP format as input with corrected coordinates:
chr1	146985758	146985757	-/<INS>	+

Results in output:

#Uploaded_variation	Location	Allele	Gene	Feature	Feature_type	Consequence	cDNA_position	CDS_position	Protein_position	Amino_acids	Codons	Existing_variation	Extra
chr1_146985758_-/<INS>	chr1:146985757-146985758	<INS>	ENSG00000268043	ENST00000439206	Transcript	intron_variant	-	-	-	-	-	-	IMPACT=MODIFIER;STRAND=1
chr1_146985758_-/<INS>	chr1:146985757-146985758	<INS>	ENSG00000268043	ENST00000611443	Transcript	splice_donor_variant	-	-	-	-	-	-	IMPACT=HIGH;STRAND=1
chr1_146985758_-/<INS>	chr1:146985757-146985758	<INS>	ENSG00000268043	ENST00000613714	Transcript	intron_variant	-	-	-	-	-	-	IMPACT=MODIFIER;STRAND=1
chr1_146985758_-/<INS>	chr1:146985757-146985758	<INS>	ENSG00000268043	ENST00000617844	Transcript	splice_donor_variant	-	-	-	-	-	-	IMPACT=HIGH;STRAND=1
chr1_146985758_-/<INS>	chr1:146985757-146985758	<INS>	ENSG00000268043	ENST00000617931	Transcript	splice_donor_variant	-	-	-	-	-	-	IMPACT=HIGH;STRAND=1

### System
- VEP version: 109.3

### Full VEP command line
```
vep  --force_overwrite --database -i VEP_annotations/Sniffles2_INS_675FM0.vcf.gz -o VEP_annotations/Sniffles2_INS_675FM0.txt
```

**Comment by nakib103** [comment] 2023-06-16 10:36
Hello @ddrichel,

Thanks for your query!

The input format `chr1 146985758 146985757 -/ +` does not seem correct. 
To be able to reproduce this issue can you share the full input that you have used for custom VEP format?

Best regards,
Nakib

**Comment by ddrichel** [comment] 2023-06-17 10:35
Hi Nakib,

the query for the custom input was analogous to the input using vcf.
vep  --force_overwrite --database -i VEP_annotations/Sniffles2_INS_675FM0_VEP_input.txt -o VEP_annotations/Sniffles2_INS_675FM0_VEP_output.txt 

The content of Sniffles2_INS_675FM0_VEP_input.txt is just:
chr1 146985758 146985757 -/ +

It is possible that I misinterpreted the [documentation](http://www.ensembl.org/info/docs/tools/vep/vep_formats.html#input) and that the positions are off by one. The real problem is that the end position of the insertion, when read from vcf input, is off by >17kbp (basically SVLEN). This is a systematic problem that affects all the insertions in our data.

The point of the custom input was to show that the insertion is not, for instance,  exonic, although it is annotated as such if vcf input is used. This seems to be a simple error in VEP's logic. This would be valid for deletions, as they do affect reference sequence, and span reference sequence by length of the deletion. However, an insertion is a variant between two reference positions and does not span an interval in the reference. Its sequence length might be large, but its length, expressed in the reference genome coordinates, is zero (or one, depending on convention).

A vcf with the insertions from my example is here: 
[Sniffles2_INS_675FM0_HG00096.vcf.gz](https://github.com/Ensembl/ensembl-vep/files/11778624/Sniffles2_INS_675FM0_HG00096.vcf.gz)

Kind regards

Dmitriy

**Comment by nakib103** [comment] 2024-11-04 15:22
Hi @ddrichel,
I have some update on this issue.

We should not just change the consequence calculation to be based on the flanking bases in the reference sequence where the insertion happens, instead of checking overlapping of features over full length of insertion. Those features might or might not get affected by the insertion, we do not know what happens biologically, but it would allow everyone to consider those features in downstream analysis. Or, ignore them as in your use case.

The position reported in the output file can be the flanking bases in the reference sequence instead of the position affected in the alternate sequence to match with short insertions like you say. But in some form of output like VEP default format information like the length of inserted sequence will get lost without introducing another field. This is not a priority as we do not want to break the basic behaviour of VEP but can be looked into the future implementation of VEP.

I will close the issue for now.

**Closed by nakib103** 2024-11-04 15:22 UTC
Labels: bug, parser

**Comment by JGASmits** [comment] 2024-12-19 09:28
I'm happy to have found this issue since I also ran into it when annotating if mobile elements insertion (with a lenght of about 300bp). The same problem (if an insertion is ~300bp upstream of an exon, the SVLEN of the mobile element causes it to be labeled exonic instead of intronic. 

I'd like to mention that I think the "overlapping features" mentioned are a bit of a weird term when it comes to insertions. The consequences of insertions could affect features both upstream and downstream of an insertions, but only the ones downstream are reported by VEP right? Since it takes the chrom:start location and adds the SVLENGTH to it (but doesnt also subtract the SVLENGTH)?

I hope there will be a more elegant solution in a future implementation, but also understand there are always a lot of things to do and limited time and hours. I will build a code workaround for our usecase. Thanks for raising this issue and for your replies Nakib103!

Greetings Jos
