### ISSUE TITLE
Incomplete annotation (--custom, vcf)

### ISSUE THREAD

**Issue by ZhangXiujuan** [Ensembl/ensembl-vep#540] opened 2019-07-24 09:54 UTC
Hi,

There is an incomplete annotation。

My command line is：` vep -i test.vcf --custom clinvar.vcf.gz,ClinVar,vcf,exact,0,CLNSIG,CLNREVSTAT,CLNSIGCONF ` .

There was no error, But something was wrong.

If clinvar infomation is ` CLNREVSTAT=criteria_provided,_single_submitter;CLNDISDB=MedGen:C1866558,OMIM:601634|MedGen:CN169374`, will get an incomplete result `CLNREVSTAT=_single_submitter;CLNDISDB=OMIM:601634|MedGen:CN169374 `; 
while clinvar info is `CLNREVSTAT=criteria_provided,_multiple_submitters,_no_conflicts`, the result will be correct  `CLNREVSTAT=criteria_provided,_multiple_submitters,_no_conflicts`.

Is it the comma? I'm confused.

Any suggestion?

Thank you!

**Comment by aparton** [comment] 2019-07-25 09:26
Hi,

Thank you for this report, this looks like a bug that occurs when our custom annotation functionality returns a comma separated list.

I'll let you know when there's a fix in place.

Kind Regards,
Andrew

**Comment by ZhangXiujuan** [comment] 2019-08-27 08:44
Hi,
When using `--custom`,  there is a similar issue (`;` separated list) to the previous one (`,` separated list).

input str: `neuronal ceroid lipofuscinosis (INCL;CLN1).Hum Mutat.2000.15:273` ;
output result: `neuronal_ceroid_lipofuscinosis_(INCL` .

Is a bug?
Thanks.

**Comment by aparton** [comment] 2019-08-29 14:57
Hi, 

Hi,

A fix is in place and will be released as part of our upcoming release 98 - currently scheduled for release in September. 

I'm going to close this issue now. If you have any other questions or comments, please feel free to reopen it.

Kind Regards,
Andrew

**Closed by aparton** 2019-08-29 14:57 UTC

**Comment by mikpom** [comment] 2020-02-25 05:32
I realize that you seem to have fixed the issue, but I am facing very similar problems so reporting on it here. 
To minimally  reproduce the issue here is DB file 
[test_db.vcf.gz](https://github.com/Ensembl/ensembl-vep/files/4248180/test_db.vcf.gz)
and here is a vcf file
[sm.vcf.gz](https://github.com/Ensembl/ensembl-vep/files/4248183/sm.vcf.gz)

Though in DB VCF we have `SIFT_score=0.346,`. in the resulting annotation
`chr1_1049980_G/C        chr1:1049980    C       -       -       -       intergenic_variant      -       -       -       -       -       -       IMPACT=MODIFIER;DBNSFP=chr1:1049980-1049980;DBNSFP_FILTER=.;DBNSFP_SIFT_score=.`

Command line for annotation was 
`vep --force_overwrite --format vcf --offline -i sm.vcf.gz -o ~/tmp/vep --custom test_db.vcf.gz,DBNSFP,vcf,exact,0,SIFT_score`

Versions:
```

Versions:
  ensembl              : 99.d3e7d31
  ensembl-funcgen      : 99.0832337
  ensembl-io           : 99.441b05b
  ensembl-variation    : 99.642e1cd
  ensembl-vep          : 99.1

```

**Comment by aparton** [comment] 2020-02-25 14:59
Hi,

Thank you for your query. In short, adding the flag --custom_multi_allelic to your query will fix your issue.

In long, as your custom annotation data includes a comma-separated list, and the total number of possible alleles matches the number of values in the comma separated list, VEP assumes that each value within the comma separated list corresponds to a possible allele. We introduced the --custom_multi_allelic flag to overwrite this behaviour. I've just tested it with your sample files, and VEP will return all of the data within that field with this flag switched on.

If you have any other questions, please don't hesitate to open a new issue.

Kind Regards,
Andrew

**Comment by mikpom** [comment] 2020-02-26 05:08
Andrew, 
thanks for your prompt response. You solution does work.

However I want to note that INFO field `SIFT_score` has `Number=1` defined in the header. It makes splitting on commas look like a misbehaviour to me.

-Cheers,
Mikhail

**Comment by aparton** [comment] 2020-02-26 09:48
Hi Mikhail,

Thank you for your feedback. You're right, if VEP read this value from the number field then it would remove the need for the clin_sig_allele flag. We'll investigate including this in a future release.

Kind Regards,
Andrew
