### ISSUE TITLE
allele counts in gnomAD

### ISSUE THREAD

**Issue by mrymkdnz** [Ensembl/ensembl-vep#1578] opened 2023-12-27 13:51 UTC
Hello devs,
I'm curious why allele count and homozygous allele count information from gnomAD exomes and genomes is not available. Are you considering adding it in the v4 update?

**Comment by davmlaw** [comment] 2024-01-05 01:47
This is a duplicate of  gnomad v4 in VEP #1574

**Comment by nakib103** [comment] 2024-01-05 09:50
Hello @mrymkdnz,

Thanks for your query! 

You can get the allele count and other fields not reported by the `--af_gnomade` / `--af_gnomadg` default output using VEP `--custom` option. You can see and example here in the doc -
https://www.ensembl.org/info/docs/tools/vep/script/vep_example.html#gnomad 

Best regards,
Nakib

**Closed** 2024-01-12 13:45 UTC
