### ISSUE TITLE
VEP 109 tests failed with custom installation path

### ISSUE THREAD

**Issue by Stikus** [Ensembl/ensembl-vep#1357] opened 2023-02-15 10:12 UTC
## Describe the issue
Header checker don't work with custom installation path

### System
- VEP version: 109.2
- VEP Cache version: 109
- Perl version: 5.26.1
- OS: Ubuntu 18.04
- tabix installed

### Full VEP command line
```
cd "$SOFT/ensembl-vep-${VEP_VERSION}" &&     perl -e "use Bio::DB::HTS::Tabix" &&     perl -e "use Bio::DB::BigFile" &&     prove -v t/*.t
```

### Full error message
```
#15 107.8 Test Summary Report
#15 107.8 -------------------
#15 107.8 t/OutputFactory_Tab.t                            (Wstat: 256 Tests: 17 Failed: 1)
#15 107.8   Failed test:  8
#15 107.8   Non-zero exit status: 1
#15 107.8 t/OutputFactory_VCF.t                            (Wstat: 256 Tests: 56 Failed: 1)
#15 107.8   Failed test:  5
#15 107.8   Non-zero exit status: 1
#15 107.8 t/OutputFactory_VEP_output.t                     (Wstat: 256 Tests: 20 Failed: 1)
#15 107.8   Failed test:  10
#15 107.8   Non-zero exit status: 1
#15 107.8 Files=49, Tests=1889, 107 wallclock secs ( 0.17 usr  0.07 sys + 102.92 cusr  4.30 csys = 107.46 CPU)
#15 107.8 Result: FAIL
```

```
#15 69.96 #   Failed test 'headers - plugin'
#15 69.96 #   at t/OutputFactory_Tab.t line 121.
#15 69.96 #                   '## VEP command-line: vep --assembly GRCh38 --cache_version 84 --database 0 --dir [PATH]/ensembl-vep-109.2[PATH]/ --input_file [PATH]/ensembl-vep-109.2[PATH]/test.vcf --no_stats --offline --plugin TestPlugin --quiet --show_ref_allele --tab --version 109.2#Uploaded_variation	Location	Allele	Gene	Feature	Feature_type	Consequence	cDNA_position	CDS_position	Protein_position	Amino_acids	Codons	Existing_variation	REF_ALLELE	IMPACT	DISTANCE	STRAND	FLAGS	test'
#15 69.96 #     doesn't match '/\#\# VEP command-line: vep --assembly GRCh38 --cache_version 84 --database 0 --dir \[PATH\]/ (--dir_plugins /plugins )*--input_file \[PATH\]/test.vcf (--no_htslib --no_plugins )*--no_stats (--no_update )*--offline --plugin TestPlugin (--pluginsdir /plugins )*--quiet --show_ref_allele --tab\#Uploaded_variation\tLocation\tAllele\tGene\tFeature\tFeature_type\tConsequence\tcDNA_position\tCDS_position\tProtein_position\tAmino_acids\tCodons\tExisting_variation\tREF_ALLELE\tIMPACT\tDISTANCE\tSTRAND\tFLAGS\ttest/'
#15 77.78 # Looks like you failed 1 test of 17.
```

```
#15 78.19 #   Failed test 'headers'
#15 78.19 #   at t/OutputFactory_VCF.t line 51.
#15 78.19 # Using Regexp on $data->[4]
#15 78.19 #    got : '##VEP-command-line='vep --assembly GRCh38 --cache_version 84 --database 0 --dir [PATH]/ensembl-vep-109.2[PATH]/ --no_stats --offline --version 109.2''
#15 78.19 # expect : (?^:\#\#VEP-command-line='vep --assembly GRCh38 --cache_version 84 --database 0 --dir \[PATH\]/( --dir_plugins /plugins --no_htslib --no_plugins)* --no_stats( --no_update)* --offline( --pluginsdir /plugins)*')
#15 83.88 # Looks like you failed 1 test of 56.
```

```
#15 84.36 #   Failed test 'headers - plugin'
#15 84.36 #   at t/OutputFactory_VEP_output.t line 116.
#15 84.36 #                   '## VEP command-line: vep --assembly GRCh38 --cache_version 84 --database 0 --dir [PATH]/ensembl-vep-109.2[PATH]/ --input_file [PATH]/ensembl-vep-109.2[PATH]/test.vcf --no_stats --offline --plugin TestPlugin --quiet --version 109.2#Uploaded_variation	Location	Allele	Gene	Feature	Feature_type	Consequence	cDNA_position	CDS_position	Protein_position	Amino_acids	Codons	Existing_variation	Extra'
#15 84.36 #     doesn't match '/\#\# VEP command-line: vep --assembly GRCh38 --cache_version 84 --database 0 --dir \[PATH\]/ (--dir_plugins /plugins )*--input_file \[PATH\]/test.vcf (--no_htslib --no_plugins )*--no_stats (--no_update )*--offline --plugin TestPlugin (--pluginsdir /plugins )*--quiet\#Uploaded_variation\tLocation\tAllele\tGene\tFeature\tFeature_type\tConsequence\tcDNA_position\tCDS_position\tProtein_position\tAmino_acids\tCodons\tExisting_variation\tExtra/'
#15 88.66 # Looks like you failed 1 test of 20.
```

**Comment by nakib103** [comment] 2023-02-15 11:52
Hi @Stikus,

Thanks for flagging this issue. We are looking into it and give a fix soon.

Best regards,
Nakib

**Comment by Stikus** [comment] 2023-02-22 06:35
After 109.3 release tests start failing again with unusual errors:
```
#15 105.6 Test Summary Report
#15 105.6 -------------------
#15 105.6 t/AnnotationSource_File_GFF.t                    (Wstat: 2304 Tests: 21 Failed: 0)
#15 105.6   Non-zero exit status: 9
#15 105.6   Parse errors: No plan found in TAP output
#15 105.6 t/BaseVEP.t                                      (Wstat: 2304 Tests: 33 Failed: 0)
#15 105.6   Non-zero exit status: 9
#15 105.6   Parse errors: No plan found in TAP output
#15 105.6 t/Haplo_Parser_VCF.t                             (Wstat: 2304 Tests: 11 Failed: 0)
#15 105.6   Non-zero exit status: 9
#15 105.6   Parse errors: No plan found in TAP output
#15 105.6 t/OutputFactory.t                                (Wstat: 2304 Tests: 144 Failed: 0)
#15 105.6   Non-zero exit status: 9
#15 105.6   Parse errors: No plan found in TAP output
#15 105.6 t/Parser.t                                       (Wstat: 2304 Tests: 35 Failed: 0)
#15 105.6   Non-zero exit status: 9
#15 105.6   Parse errors: No plan found in TAP output
#15 105.6 t/Parser_Region.t                                (Wstat: 2304 Tests: 13 Failed: 0)
#15 105.6   Non-zero exit status: 9
#15 105.6   Parse errors: No plan found in TAP output
#15 105.6 t/Parser_VCF.t                                   (Wstat: 2304 Tests: 32 Failed: 0)
#15 105.6   Non-zero exit status: 9
#15 105.6   Parse errors: No plan found in TAP output
#15 105.6 t/Parser_VEP_input.t                             (Wstat: 2304 Tests: 10 Failed: 0)
#15 105.6   Non-zero exit status: 9
#15 105.6   Parse errors: No plan found in TAP output
#15 105.6 t/Runner.t                                       (Wstat: 2304 Tests: 52 Failed: 0)
#15 105.6   Non-zero exit status: 9
#15 105.6   Parse errors: No plan found in TAP output
```

**Comment by nakib103** [comment] 2023-02-22 10:54
Hi @Stikus,

We cannot reproduce this issue on our side. Our travis build is passing and I also tried locally and they are passing too. Do you get the same issue when running VEP?

One of the reason we can think of that you are getting this issue is that you don't have permission to `/dev/null` (or whichever file is returned by `File::Spec->devnull()`). Ideally you should have. Can you check if this is the case?

Best regards,
Nakib

**Comment by Stikus** [comment] 2023-02-27 07:34
We are running tests in docker container with `root` access but I'll check everything I can.

When running VEP after tests skip we got this output line (VEP don't fail):
```
  Command: '/soft/ensembl-vep-109.3/vep --fork 32 --input_file /inputs/input.vcf --format vcf --cache --dir_cache /ref/.vep --dir_plugins /soft/ensembl-vep-109.3/Plugins --assembly GRCh37 --offline --output_file /outputs/test1.annot-vep.vcf --vcf --force_overwrite --symbol --check_existing --terms SO --tsl --hgvs --hgvsg --transcript_version  --plugin Frameshift --plugin Wildtype    --no_stats --plugin ProteinSeqs,/outputs/test1.annot-vep.reference.fa,/outputs/test1.annot-vep.mutated.fa'.
  PID=194 (last job)
print() on closed filehandle TMP at /soft/ensembl-vep-109.3/Plugins/ProteinSeqs.pm line 74.
```

**Comment by nakib103** [comment] 2023-02-27 10:52
We actually did some more testing in our side and unfortunately tests fails when there are ENV variable with `VEP_` prefix. The latest docker container should not fail on this. Can you pull the latest image and see if it resolves the test issue?

**Comment by Stikus** [comment] 2023-02-27 15:38
We are using our own dockerfile - can you point what should we change to fix? We are cloning `release/109` branch from various `ensembl` repositories, including `ensembl-vep`.

**Comment by nakib103** [comment] 2023-02-27 16:52
You can use the `fix_docker` branch for `ensembl-vep` repo. For reference see the dockerfile there - https://github.com/Ensembl/ensembl-vep/blob/fix_docker/docker/Dockerfile

**Comment by Stikus** [comment] 2023-02-28 13:02
`fix_docker` branch fixed tests. Now we have this output:
```
  Command: '/soft/ensembl-vep-109.3/vep --fork 32 --input_file /inputs/input.vcf --format vcf --cache --dir_cache /ref/.vep --dir_plugins /soft/ensembl-vep-109.3/Plugins --assembly GRCh37 --offline --output_file /outputs/test1.annot-vep.vcf --vcf --force_overwrite --symbol --check_existing --terms SO --tsl --hgvs --hgvsg --transcript_version  --plugin Frameshift --plugin Wildtype    --no_stats --plugin ProteinSeqs,/outputs/test1.annot-vep.reference.fa,/outputs/test1.annot-vep.mutated.fa'.
  PID=194 (last job)
Unknown option: version
Ignoring unsupported option 'version' found via ENV variable or INI file
```

**Comment by nakib103** [comment] 2023-02-28 15:27
Great it seems to have solved the test problem. The warning is there to make aware that there are unsupported ENV variables which are not being read instead of silently discarding them.

This change will be available in `110` release.

**Comment by nakib103** [comment] 2023-03-27 10:52
I will close this issue for now. Please feel free to re-open or create another ticket if you face further issues.

**Closed by nakib103** 2023-03-27 10:52 UTC
Labels: bug, installation, docker/singularity

**Comment by Stikus** [comment] 2023-04-11 09:48
@nakib103 Any ETA for 110 release? We are waiting for fixes for 1.5 month now.

**Comment by nakib103** [comment] 2023-04-12 08:16
Hi @Stikus,

The ETA for e110 seems to be early June. Are you facing any particular issue with the current release?

The following is just warning messages so you can ignore them -

>   Unknown option: version
Ignoring unsupported option 'version' found via ENV variable or INI file

Best regards,
Nakib

**Comment by Stikus** [comment] 2023-04-17 15:23
@nakib103 can you give me any feedback about previous comment.

**Comment by nakib103** [comment] 2023-04-19 10:58
Hello @Stikus, 

Sorry for late reply. As you might have already saw we are prioritising solving the issue - https://github.com/Ensembl/ensembl-vep/issues/1034
