### ISSUE TITLE
Discrepancy in coding changes between VEP and Haplosaurus

### ISSUE THREAD

**Issue by tinyheero** [Ensembl/ensembl-vep#439] opened 2019-04-19 07:01 UTC
Using VEP (v96) I am getting a discrepancy in the predicted protein haplotype that I get from haplosaurus vs. VEP predicted coding sequencing. Given the following `test.vcf`:

```
##fileformat=VCFv4.2
#CHROM  POS ID  REF ALT QUAL  FILTER  INFO  FORMAT  sample
chr11 70333467  chr11:70333467_G>A  G A 40  PASS  mutation_type=somatic GT  0/1
```

Running VEP as follows:

```bash
vep \
        --input_file "test.vcf" \
        --output_file "test.vep.vcf" \
        --dir_cache "/home/f.chan/vep_data/GRCh37" \
        --fasta "/home/f.chan/vep_data/GRCh37/homo_sapiens_refseq/96_GRCh37/Homo_sapiens.GRCh37.75.dna.primary_assembly.fa.gz" \
        --cache \
        --offline \
        --refseq \
        --canonical \
        --biotype \
        --vcf \
        --pick \
        --pick_order biotype,rank,tsl,canonical,appris,ccds,length \
        --hgvs \
        --force_overwrite
```

Produces the following VEP VCF output:

```
##fileformat=VCFv4.2
##VEP="v96" time="2019-04-19 06:30:43" cache="/home/f.chan/vep_data/GRCh37/homo_sapiens_refseq/96_GRCh37" ensembl=96.7a35428 ensembl-variation=96.70d2777 ensembl-funcgen=96.9c3a0cd ensembl-io=96.6e65b30 1000genomes="phase3" COSMIC="86" ClinVar="201810" ESP="20141103" HGMD-PUBLIC="20174" assembly="GRCh37.p13" dbSNP="151" gencode="GENCODE 19" genebuild="2011-04" gnomAD="r2.1" polyphen="2.2.2" refseq="01_2015" regbuild="1.0" sift="sift5.2.2"
##INFO=<ID=CSQ,Number=.,Type=String,Description="Consequence annotations from Ensembl VEP. Format: Allele|Consequence|IMPACT|SYMBOL|Gene|Feature_type|Feature|BIOTYPE|EXON|INTRON|HGVSc|HGVSp|cDNA_position|CDS_position|Protein_position|Amino_acids|Codons|Existing_variation|DISTANCE|STRAND|FLAGS|SYMBOL_SOURCE|HGNC_ID|CANONICAL|REFSEQ_MATCH|GIVEN_REF|USED_REF|BAM_EDIT|HGVS_OFFSET">
#CHROM  POS ID  REF ALT QUAL  FILTER  INFO  FORMAT  sample
chr11 70333467  chr11:70333467_G>A  G A 40  PASS  mutation_type=somatic;CSQ=A|missense_variant|MODERATE|SHANK2|22941|Transcript|NM_012309.3|protein_coding|25/26||NM_012309.3:c.2785C>T|NP_036441.2:p.Pro929Ser|2863|2785|929|P/S|Ccg/Tcg|||-1||EntrezGene||||G|G|| GT  0/1
```

Note that the predicted HGVS protein coding consequence is `NP_036441.2:p.Pro929Ser`. When I run haplosaurus to generate the corresponding protein haplotype of this with the following command:

```bash
haplo \
        --input_file "test.vcf" \
        --output_file "test.haplo.tsv" \
        --dir_cache "/home/f.chan/vep_data/GRCh37" \
        --fasta "/home/f.chan/vep_data/GRCh37/homo_sapiens_refseq/96_GRCh37/Homo_sapiens.GRCh37.75.dna.primary_assembly.fa.gz" \
        --cache \
        --offline \
        --assembly "GRCh37" \
        --force_overwrite \
        --refseq \
        --dont_export aligned_sequences
```

I get the following haplosaurus results:

```
NM_133266.3 NM_133266.3:1167C>T   NP_573573.2:REF     chr11:70333467_G>A  sample:1
NM_012309.3 NM_012309.3:2785C>T   NP_036441.2:312del{1491}      chr11:70333467_G>A  sample:1
NM_012309.4 NM_012309.4:2784C>T   NP_036441.2:312del{1490}      chr11:70333467_G>A  sample:1
NM_133266.4 NM_133266.4:1167C>T   NP_573573.2:REF     chr11:70333467_G>A  sample:1
```

Here the protein haplotype is reported as `NP_036441.2:312del{1491}` for `NM_012309.3:2785C>T`.

**Comment by ens-lgil** [comment] 2019-04-23 13:51
Dear @tinyheero,

Thank you for reporting this discrepancy.
We are looking at this and we will get back to you when the cause of this difference will be found.

Best regards,
Laurent

**Comment by ens-lgil** [comment] 2019-04-24 10:43
Dear @tinyheero,

I had a look at NM_012309.3, NM_012309.4 and NP_036441.2 in the Ensembl database (this is where we extract the data for the VEP cache) and it looks like the issue comes from the mapping of this RefSeq to the GRCh37 reference sequence, as it doesn't match perfectly.
The mapping highlights some indels which introduce an early codon stop in NP_036441.2 (position 312). These sequence differences are independant from your variant:
```
MPRSPTSSEDEMAQSFSDYSVGSESDSSKEETIYDTIRATAEKPGGARTEESQGNTLVIRVVIHDLQQTKCIRFNPDATVWVAKQRILCTLTQSLKDVLNYGLFQPASNGRDGKFLDEERLLREYPQPVGEGVPSLEFRYKKRVYKQASLDEKQLAKLHTKTNLKKCMDHIQHRLVEKITKMLDRGLDPNFHDPETGETPLTLAAQLDDSVEVIKALKNGGAHLDFRAKDGMTALHKAARARNQVALKTLLELGASPDYKDSYGLTPLYHTAIVGGDPYCCELLLHEHATVCCKDENGWHEIHQMEHLLC*
```
While VEP is looking locally at a variant, Haplosaurus reports the whole resulting protein. That's why the HGVS is quite different in this special case where the protein product is truncated way before the location of your variant.

We are trying to improve the mappings and interpretation of these RefSeq sequences.

Best regards,
Laurent

**Comment by ens-lgil** [comment] 2019-05-24 15:22
I am closing this ticket, but if you have any more questions please feel free to reopen it.

Best regards,
Laurent

**Closed by ens-lgil** 2019-05-24 15:22 UTC
