### ISSUE TITLE
CADD-SV scores annotation error

### ISSUE THREAD

**Issue by prasundutta87** [Ensembl/ensembl-vep#1587] opened 2024-01-18 13:45 UTC
## Describe the issue
Hi. I have a Structural Variation VCF generated from PacBio data using pbsv and I want to annotate with CADD-SV scores which I downloaded from here-  https://kircherlab.bihealth.org/download/CADD-SV/v1.1/prescored_variants.tsv.gz

None of the records are being annotated using the CADD-SV scores. Its may be I am using the plugin wrongly, but please let me know if the error/warnings reflect anything obvious.

## Additional information
Please fill in the following sections to help us find the source of your issue as quickly as possible.

### System
- VEP version: 111
- VEP Cache version: 111
- Perl version: v5.32.1
- OS: CentOS Linux (HPC cluster)
- tabix installed YES

### Full VEP command line
```
vep \
-o multisample_cleaned_VEP.vcf.gz \
--assembly GRCh38 \
--format vcf \
--offline \
--dir_cache vep_cache \
--vcf \
--force_overwrite \
--max_sv_size 500000000 \
--symbol \
--regulatory \
--canonical \
--variant_class \
--fork 4 \
--hgvs \
--mane \
--fasta G38_ref.fa \
--compress_output gzip \
--nearest symbol \
--gene_phenotype \
--overlaps \
--plugin CADD,/gpfs3/well/gel/pdutta/vep_data_resources/CADD/prescored_variants.tsv.gz,type=within,reciprocal=1,overlap_cutoff=80


```

### Full error message

JUST PASTING ONE SET OF ERROR MESSAGE, THIS HAS REPEATED
> WARNING: 139811 : Use of uninitialized value $orig_a_alt in hash element at /gpfs3/well/gel/pdutta/conda_envs/envs/pacbio/share/ensembl-vep-111.0-0/Bio/EnsEMBL/Variation/Utils/Sequence.pm line 1171.
Use of uninitialized value $alt in numeric gt (>) at /gpfs3/well/gel/pdutta/conda_envs/envs/pacbio/share/ensembl-vep-111.0-0/Bio/EnsEMBL/Variation/Utils/Sequence.pm line 1230.
WARNING: Plugin 'CADD' went wrong: 
-------------------- EXCEPTION --------------------
MSG: Missing reference or alternate sequence
STACK Bio::EnsEMBL::Variation::Utils::Sequence::trim_sequences /gpfs3/well/gel/pdutta/conda_envs/envs/pacbio/share/ensembl-vep-111.0-0/Bio/EnsEMBL/Variation/Utils/Sequence.pm:967
STACK Bio::EnsEMBL::Variation::Utils::Sequence::get_matched_variant_alleles /gpfs3/well/gel/pdutta/conda_envs/envs/pacbio/share/ensembl-vep-111.0-0/Bio/EnsEMBL/Variation/Utils/Sequence.pm:1181
STACK CADD::run /users/brc/tid131/.vep/Plugins/CADD.pm:259
STACK (eval) /gpfs3/well/gel/pdutta/conda_envs/envs/pacbio/share/ensembl-vep-111.0-0/modules/Bio/EnsEMBL/VEP/OutputFactory.pm:2117
STACK Bio::EnsEMBL::VEP::OutputFactory::run_plugins /gpfs3/well/gel/pdutta/conda_envs/envs/pacbio/share/ensembl-vep-111.0-0/modules/Bio/EnsEMBL/VEP/OutputFactory.pm:2116
STACK Bio::EnsEMBL::VEP::OutputFactory::get_all_VariationFeatureOverlapAllele_output_hashes /gpfs3/well/gel/pdutta/conda_envs/envs/pacbio/share/ensembl-vep-111.0-0/modules/Bio/EnsEMBL/VEP/OutputFactory.pm:394
STACK Bio::EnsEMBL::VEP::OutputFactory::get_all_output_hashes_by_VariationFeature /gpfs3/well/gel/pdutta/conda_envs/envs/pacbio/share/ensembl-vep-111.0-0/modules/Bio/EnsEMBL/VEP/OutputFactory.pm:344
STACK Bio::EnsEMBL::VEP::OutputFactory::VCF::get_all_lines_by_InputBuffer /gpfs3/well/gel/pdutta/conda_envs/envs/pacbio/share/ensembl-vep-111.0-0/modules/Bio/EnsEMBL/VEP/OutputFactory/VCF.pm:315
STACK Bio::EnsEMBL::VEP::Runner::_buffer_to_output /gpfs3/well/gel/pdutta/conda_envs/envs/pacbio/share/ensembl-vep-111.0-0/modules/Bio/EnsEMBL/VEP/Runner.pm:422
STACK (eval) /gpfs3/well/gel/pdutta/conda_envs/envs/pacbio/share/ensembl-vep-111.0-0/modules/Bio/EnsEMBL/VEP/Runner.pm:671
STACK Bio::EnsEMBL::VEP::Runner::_forked_process /gpfs3/well/gel/pdutta/conda_envs/envs/pacbio/share/ensembl-vep-111.0-0/modules/Bio/EnsEMBL/VEP/Runner.pm:665
STACK Bio::EnsEMBL::VEP::Runner::_forked_buffer_to_output /gpfs3/well/gel/pdutta/conda_envs/envs/pacbio/share/ensembl-vep-111.0-0/modules/Bio/EnsEMBL/VEP/Runner.pm:496
STACK Bio::EnsEMBL::VEP::Runner::next_output_line /gpfs3/well/gel/pdutta/conda_envs/envs/pacbio/share/ensembl-vep-111.0-0/modules/Bio/EnsEMBL/VEP/Runner.pm:367
STACK Bio::EnsEMBL::VEP::Runner::run /gpfs3/well/gel/pdutta/conda_envs/envs/pacbio/share/ensembl-vep-111.0-0/modules/Bio/EnsEMBL/VEP/Runner.pm:208
STACK toplevel /gpfs3/well/gel/pdutta/conda_envs/envs/pacbio/bin/vep:46
Date (localtime)    = Thu Jan 18 12:54:48 2024
Ensembl API version = 111

### Data files (if applicable)
They include:
- The input file
- The output file
- The custom file(s)
You can provide a sample of them

**Comment by nuno-agostinho** [comment] 2024-01-19 15:17
Hi @prasundutta87, hope you are having a nice day!

Your command to use the CADD-SV plugin is not correct:
```
--plugin CADD,/gpfs3/well/gel/pdutta/vep_data_resources/CADD/prescored_variants.tsv.gz,type=within,reciprocal=1,overlap_cutoff=80
```

The parameters `type=within,reciprocal=1,overlap_cutoff=80` that you are using are options only available for [`--custom` annotation](https://www.ensembl.org/info/docs/tools/vep/script/vep_custom.html#custom_options). These parameters are NOT supported by the CADD plugin, as you can read in the [CADD plugin documentation](https://www.ensembl.org/info/docs/tools/vep/script/vep_plugins.html).

If you simply use instead:
```
--plugin CADD,/gpfs3/well/gel/pdutta/vep_data_resources/CADD/prescored_variants.tsv.gz
```

It should highlight the CADD scores for the SVs in your input. In case it still does not return any CADD scores, could you give me some examples that you are using so I can check what is happening? Thanks.

Best regards,
Nuno Agostinho

**Comment by prasundutta87** [comment] 2024-01-26 10:39
Hi @nuno-agostinho , thanks for your message. Let me try this out,

**Comment by nuno-agostinho** [comment] 2024-01-29 11:59
Hey @prasundutta87,

Can you please send me some examples of variants that reproduce the issues you are getting (including insertions and deletions that do not get annotated)? I can then check what is going on.

Best regards,
Nuno

**Comment by prasundutta87** [comment] 2024-01-29 12:12
Hi, these are some patient samples, and I am trying to figure out how to share the data. I am indeed delete the sequences from the VCF records, but if that is what is causing the issue, we might not be able to figure out if I remove them.

**Comment by nuno-agostinho** [comment] 2024-02-05 17:34
Hi @prasundutta87,

I understand that you are using private data, but I could not reproduce your issues with the data I used. Would it be possible to mock up some example data that reproduce those issues?

Anyway, I will continue trying to mock up some variants until I reproduce your issue. Hopefully I can fix this soon, but I still am not sure what is going on.

Best regards,
Nuno

**Comment by nuno-agostinho** [comment] 2024-02-05 17:35
Also, are you sure those insertions/deletions should be annotated for sure?

Thanks!

**Comment by prasundutta87** [comment] 2024-02-06 10:51
Hi @nuno-agostinho ,

Thanks for your message. The thing what I noticed that none of the INS and DUP were annotated and only DUP were annotated as mentioned before. I am now trying out v110 of VEP as well. v111 of VEP skips many SVs in general annotation (no custom) which v110 doesn't. But, that is a separate issue. Let me try something out at my end and will send some variants to you.

Regards,
Prasun

**Comment by nuno-agostinho** [comment] 2024-02-27 10:18
Hi @prasundutta87,

Do you have any update on this? Some example data would be great to try to fix the issue you describe. Thanks!

Kind regards,
Nuno

**Comment by nuno-agostinho** [comment] 2024-08-28 15:54
Hi @prasundutta87,

Since we were unable to reproduce the issue you reported, we will be closing this ticket for now.

However, if you are able to provide additional data or details that could help us replicate the problem, please feel free to share them. You can also send the information directly to us via email if you prefer not to share it on GitHub.

Best regards,
Nuno

**Closed by nuno-agostinho** 2024-08-28 15:54 UTC
Labels: plugin, structural variants
