### ISSUE TITLE
Run vep with reference genome not in the database

### ISSUE THREAD

**Issue by CWYuan08** [Ensembl/ensembl-vep#399] opened 2019-02-19 16:02 UTC
Hi there, 
I am wondering whether it is possible to run vep with reference genome not in the database? 
(the reference genome has an annotation file)

Best

**Comment by ens-lgil** [comment] 2019-02-19 16:07
Dear @CWYuan08,

It is possible to run VEP on a species/assembly which is not in Ensembl.
You need to provide a FASTA file (for the sequences) and a GFF/GTF file (for the annotations).
You can find more information here:
https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#gff

Best regards,
Laurent

**Comment by CWYuan08** [comment] 2019-03-12 14:04
Dear Laurent @ens-lgil 
Thank you. I have encountered problem when Installing VEP on my Mac (reported: "Can't locate DBI.pm in @INC (you may need to install the DBI module")
So I am now running it with  docker, the command I used was:
docker run -t -i ensemblorg/ensembl-vep ./vep ~/s.vcf -gff ~/Documents/data.gff.gz  -fasta ~/Documents/renamed.fa.gz

However, I encountered new problem: 
"MSG: ERROR: Specified FASTA file/directory ~/Documents/renamed.fa.gz not found"

I checked that the path was correct, why vep couldn't find my fasta file? 

Thank you again 
Ulrika

**Comment by ens-lgil** [comment] 2019-03-12 14:14
Dear @CWYuan08,

You need to use the mounted volume path in your Docker command (cf [VEP documentation](https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#docker)): 

```
docker run -t -i -v ~/Documents/:/opt/vep/.vep ensemblorg/ensembl-vep ./vep -i /opt/vep/.vep/s.vcf -o /opt/vep/.vep/s_output.txt --gff /opt/vep/.vep/data.gff.gz -fasta /opt/vep/.vep/renamed.fa.gz
```
In this example, the input file `s.vcf` needs to be moved into `~/Documents`
And I mounted the Docker container path `/opt/vep/.vep/` to you local directory `~/Documents` in order to allow access of the Docker VEP to your input, GFF and FASTA files.

Best regards,
Laurent

**Comment by CWYuan08** [comment] 2019-03-14 15:04
Dear Laurent @ens-lgil,

thank you for your help. I had another problem with tabix: (the annotation file is in gtf format) 
Command I used was:  tabix -p gff data.gtf.gz
I got: 
[E::get_intv] Failed to parse TBX_GENERIC, was wrong -p [type] used?
Do I need to convert the gtf file to gff?

Thanks a lot
Ulrika

**Comment by ens-lgil** [comment] 2019-03-14 16:51
Dear @CWYuan08,

Did you run the following commands to compress your file ?
```
grep -v "#" data.gtf | sort -k1,1 -k4,4n -k5,5n -t$'\t' | bgzip -c > data.gtf.gz
tabix -p gff data.gtf.gz
``` 
Best regards,
Laurent

**Comment by CWYuan08** [comment] 2019-03-14 18:10
Dear @ens-lgil,
Yes, I used this command to compress the file 
Thank u

**Comment by aparton** [comment] 2019-03-14 18:18
Hi Ulrika,

Did sorting and compressing the gtf in this way resolve your issue?

Kind Regards,
Andrew

**Comment by CWYuan08** [comment] 2019-03-14 21:35
Dear Andrew @aparton,
I processed with the command above, however, vep outputs only "intergenic variants",  e.g. in the vcf file:
#Uploaded_variation	Location	Allele	Gene	Feature	Feature_type	Consequence	cDNA_position	CDS_position	Protein_position	Amino_acids	Codons	Existing_variation	Extra
6	chrI:47403-47438	insertion	-	-	-	intergenic_variant	-	-	-	-	-	-	IMPACT=MODIFIER

is it because the annotation file is not well structured? it has following information
chr	Base	exon	start	end	.	-	.	gene_id;  transcript_id;, exon_number; gene_source; gene_biotype; transcript_source ; transcript_biotype ; exon_id 

thanks 
best,
Ulrika

**Comment by ens-lgil** [comment] 2019-03-15 09:04
Dear @CWYuan08,

Could you send us a sample of your GTF, please ?
This will help us to see if something required by VEP is missing in this file.
We have some documentation about the GFF/GTF particular attributes required by VEP: https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#gff_req

Best regards,
Laurent

**Comment by ens-lgil** [comment] 2019-03-20 16:39
Dear @CWYuan08,

I had a look at your GTF file and it seems that your data file is a mix between a `GFF` and a `GTF`, regarding the 9th column.
The 9th column should be in this format (cf.  [UCSC documentation](http://genome.ucsc.edu/FAQ/FAQformat.html#format4)):
```
gene_id "Em:U62317.C22.6.mRNA"; transcript_id "Em:U62317.C22.6.mRNA"; exon_number 1
```
but the 9th column of your GTF file has this format:
```
gene_id=Em:U62317.C22.6.mRNA;transcript_id=Em:U62317.C22.6.mRNA;exon_number=1
```

I quickly edited a sample of your GTF file to match the GTF requirement and I run the following command (from VEP docker):
```
./vep \
-i /opt/vep/.vep/input/test_worm.txt \
-o /opt/vep/.vep/output/output_test_worm.txt \
--custom /opt/vep/.vep/custom/data2_sample_no_equal.gff.gz,WGFF,gtf \
--fasta /opt/vep/.vep/fasta/Caenorhabditis_elegans.WBcel235.dna.toplevel.fa.gz
```
Where:
- `data2_sample_no_equal.gff.gz` is a sample of you GTF annotation file with the `=` character replaced by a `space` on each line.
- `test_worm.txt` is a couple of made up variants:
```
chrI	5225	5225	G/A	1
chrI	6196	6196	A/C	1
```
- `output_test_worm.txt` is the output result:
```
...
## WGFF : /opt/vep/.vep/custom/data2_sample_no_equal.gff.gz (overlap)
#Uploaded_variation	Location	Allele	Gene	Feature	Feature_type	Consequence	cDNA_position	CDS_position	Protein_position	Amino_acids	Codons	Existing_variation	Extra
chrI_5225_G/A	chrI:5225	A	WBGene00022277	Y74C9A.3	Transcript	downstream_gene_variant	-	-	-	-	-	-	IMPACT=MODIFIER;DISTANCE=724;STRAND=-1;SOURCE=WGFF
chrI_5225_G/A	chrI:5225	A	WBGene00023193	Y74C9A.6	Transcript	downstream_gene_variant	-	-	-	-	-	-	IMPACT=MODIFIER;DISTANCE=355;STRAND=-1;SOURCE=WGFF
chrI_6196_A/C	chrI:6196	C	WBGene00022277	Y74C9A.3	Transcript	splice_region_variant,intron_variant	-	-	-	-	-	-	IMPACT=LOW;STRAND=-1;SOURCE=WGFF
chrI_6196_A/C	chrI:6196	C	WBGene00023193	Y74C9A.6	Transcript	upstream_gene_variant	-	-	-	-	-	-	IMPACT=MODIFIER;DISTANCE=454;STRAND=-1;SOURCE=WGFF
```

The option for the custom annotation should be using the GTF flag to work properly (otherwise is uses the GFF parser): `--custom /opt/vep/.vep/custom/data2_sample_no_equal.gff.gz,WGFF,gtf`

So normally it should work if you fix the GTF file 9th column.

Best regards,
Laurent

**Comment by CWYuan08** [comment] 2019-03-20 17:53
Dear Laurent @ens-lgil,

thank you, I have run with your suggestions, but: I have warnings for example:
WARNING: Parent entries with the following IDs were not found or skipped due to invalid types: Y71G12B.33b, Y71G12B.33a, Y92H12BL.4
WARNING: Parent entries with the following IDs were not found or skipped due to invalid types: D1037.5
...
what does this mean? 

and the output html summary was empty, why this is? 
Thank you again,
with best regards,
Ulrika

**Comment by ens-lgil** [comment] 2019-03-21 08:59
Dear @CWYuan08,

About the warnings, this is because the transcripts entries Y71G12B.33b, Y71G12B.33a, Y92H12BL.4 and D1037 are missing in your GTF file and you have exons or other types of annotation refering to these transcripts (`transcript_id` attribute) in their 9th column.
VEP is building the annotations from the GFT file (gene -> transcript -> exon/CDS -> ...) using the different IDs.

About the empty HTML summary, I need to investigate it.

Best regards,
Laurent

**Comment by ens-lgil** [comment] 2019-03-22 14:31
Dear @CWYuan08,

I tried to run VEP, using you custom annotations fixed (i.e. replacing `=` by ` ` in the 9th column) and I got a summary page.
```
./vep \
-i /opt/vep/.vep/input/test_worm.txt \
-o /opt/vep/.vep/output/output_test_worm.txt \
--custom /opt/vep/.vep/custom/data2
![VEP_summary](https://user-images.githubusercontent.com/6085223/54829745-faf6a780-4cae-11e9-8427-81c9e54171e2.png)
.gff.gz,WGFF,gtf \
--fasta /opt/vep/.vep/fasta/Caenorhabditis_elegans.WBcel235.dna.toplevel.fa.gz
```

With the made up input file `test_worm.txt`:
```
chrI	5225	5225	G/A	1
chrI	6196	6196	A/C	1
chrI	7059	7059	C/A	1
chrI	13500	13500	T/A	1
chrI	47403	47403	A/G	1
```

See the attached screenshot:
![VEP_summary](https://user-images.githubusercontent.com/6085223/54829774-0cd84a80-4caf-11e9-9ed8-dcf6c706e79b.png)

Best regards,
Laurent

**Comment by CWYuan08** [comment] 2019-03-26 22:29
Dear Laurent @ens-lgil,

what is "![VEP_summary](https://user-images.githubusercontent.com/6085223/54829745-faf6a780-4cae-11e9-8427-81c9e54171e2.png)" you added in the command?
I used:  
'''docker run -t -i -v ~/Documents/:/opt/vep/.vep ensemblorg/ensembl-vep ./vep \-i /opt/vep/.vep/s.vcf \-o /opt/vep/.vep/s_output.txt \--custom /opt/vep/.vep/data4.gtf.gz,WGFF,gtf \--fasta /opt/vep/.vep/renamed.fa.gz'''
the html is again empty

thank you very much 
Best,
Ulrika

**Comment by CWYuan08** [comment] 2019-03-26 22:30
Dear Laurent @ens-lgil,
what is "![VEP_summary](https:...." you added in the command?
I used:
...
docker run -t -i -v ~/Documents/:/opt/vep/.vep ensemblorg/ensembl-vep ./vep -i /opt/vep/.vep/s.vcf -o /opt/vep/.vep/s_output.txt --custom /opt/vep/.vep/data4.gtf.gz,WGFF,gtf --fasta /opt/vep/.vep/renamed.fa.gz
...

the html is again empty

thank you very much
Best,
Ulrika

**Comment by ens-lgil** [comment] 2019-03-27 11:10
Dear @CWYuan08,

Sorry for the strange command line, this was a bad copy/paste inserted at the wrong place.

Usually the HTML report is empty if:
- There is no results in the output file
- There is an error in the VEP, stopping it running
Did you get an error message (not the warning messages) in the VEP prompt ?

Best regards,
Laurent

**Comment by CWYuan08** [comment] 2019-03-30 18:23
Dear Laurent,

The output file is fine, the warning.txt is empty and no error message appeared. The summary html is empty. 

Thank you 
Ulrika

**Comment by CWYuan08** [comment] 2019-03-30 18:24
Dear @ens-lgil Laurent,

The output file is fine, the warning.txt is empty and no error message appeared. The summary html is empty.

Thank you
Ulrika

**Comment by ens-lgil** [comment] 2019-04-01 13:40
Dear @CWYuan08,

Could you try to run VEP with this input data, please ?
```
chrI	5225	5225	G/A	1
chrI	6196	6196	A/C	1
chrI	7059	7059	C/A	1
chrI	13500	13500	T/A	1
chrI	47403	47403	A/G	1
chrI	1684925	1684925	T/A	1
chrI	3743717	3743717	A/G	1
```
It's just to see if the issue is based on your input data or if it's more a general problem with VEP and or your system/settings.
I run this example and I got the HTML summary report.

Best regards,
Laurent

**Comment by CWYuan08** [comment] 2019-04-08 11:27
Hi @ens-lgil,
this worked. I guess the issue is with my input data 

Thank you 
Ulrika

**Comment by ens-lgil** [comment] 2019-04-10 09:32
Dear @CWYuan08,

I think I found the cause of issue (I am posting it here so it will be easier to retrieve the solution):
When I ran your data, I got a message `Killed` after a couple of minutes and VEP stopped.
This is due to a memory space issue. Docker default settings is using **2Gb** of memory, so I changed it to **3Gb** and it worked.
To change the Docker settings, you can to go to :
```
Docker client -> Preferences -> Advanced tab -> Memory to 3Gib
```
or you can specify it in the command line with the [`--memory`](https://docs.docker.com/engine/reference/run/#user-memory-constraints) option:
```
docker run -t -i --memory 3G ensemblorg/ensembl-vep ./vep ~/s.vcf -gff ~/Documents/data.gff.gz -fasta ~/Documents/renamed.fa.gz
```

Hopefully, this should fix the VEP issue.

Best regards,
Laurent

**Comment by CWYuan08** [comment] 2019-04-10 13:14
Dear Laurent @ens-lgil,
thank you for all your support, finally it is working now!
Best,
Ulrika

**Comment by ens-lgil** [comment] 2019-04-10 13:17
I am glad that we finally managed to make it works! 

Best regards,
Laurent

**Comment by ens-lgil** [comment] 2019-04-12 12:12
I am closing this ticket. Feel free to reopen it if you have further questions.

**Comment by CWYuan08** [comment] 2019-06-21 15:25
@ens-lgil 
Hi laurent I have run a list of files with VEP (via Snakemake), but I had one file (out of 21) which VEP suddenly can't detect the format, I don't know why this is, they all have been processed by the same code, could you please help me on this? 
Could I email you the file? 

Thank you again 
With regards
Ulrika

**Comment by ens-lgil** [comment] 2019-06-21 15:38
Dear @CWYuan08,

No problem, I can have a look at the file like I did last time.

Best regards,
Laurent

**Comment by CWYuan08** [comment] 2019-06-21 15:48
Dear Laurent,

Here it is: 

And also I am wondering whether I can use --domains given I am running VEP with our worm genome? 

Thank you 
With regards
Ulrika

**Comment by ens-lgil** [comment] 2019-06-24 08:08
Dear @CWYuan08, 

As you are only using your FASTA and and your GTF file as annotation, the `--domains` option won't be useful: this option is used to pick up domain information (e.g. Pfam) from the VEP cache (when available) or from the Ensembl database (when available as well).

Best regards,
Laurent

**Comment by CWYuan08** [comment] 2019-06-24 11:29
Dear Laurent, 

Thank you, I got it. Did you have time to have a look of the file? 

Thank you again 
Best 
Ulrika

**Comment by ens-lgil** [comment] 2019-06-24 11:42
It seems that I didn't receive your email.

**Comment by CWYuan08** [comment] 2019-06-24 17:24
Hi Laurent, 

I attached it to this email, can you see it?

Thank you again 
Ulrika

**Comment by ens-lgil** [comment] 2019-06-25 08:31
Dear @CWYuan08,

I don't think you can add attachment when you send an email through GitHub.

Best regards,
Laurent

**Comment by ens-lgil** [comment] 2019-07-09 08:35
I am (re)closing this issue, but if you have any more questions please feel free to reopen it.

Best regards,
Laurent

**Closed by ens-lgil** 2019-07-09 08:35 UTC

**Comment by Pablog07** [comment] 2021-09-16 17:49
Greetings. I am currently using VEP for variant effect prediction on finwhale_joint vcfs which used the blue whale genome as reference. While using all these discussion to go straight-forward, I am currently experiencing a lot of warnings meesages of these type:

WARNING: Parent entries with the following IDs were not found or skipped due to invalid types: XM_036841208.1, XM_036841194.1, XM_036841213.1, XR_005018532.1, XM_036841205.1

The current annotation at Ensembl is Bamusv2.1, while at NCBI there is a chromosome-level anotation (BalMus1.pri.v3). I have been using both the .gtf and fasta files from this latter annotation, as well as the cache from the first one, which is at the scaffold level. I have checked the .gtf file to look for possible = instead of | | but it looks ok.

NC_045785.1	Gnomon	gene	38581	58296	.	+	.	gene_id "SAMD11"; transcript_id ""; db_xref "GeneID:118905126"; gbkey "Gene"; gene "SAMD11"; gene_biotype "protein_coding"; 
NC_045785.1	Gnomon	exon	38581	39515	.	+	.	gene_id "SAMD11"; transcript_id "XM_036871472.1"; db_xref "GeneID:118905126"; gbkey "mRNA"; gene "SAMD11"; model_evidence "Supporting evidence includes similarity to: 2 Proteins, and 100% coverage of the annotated genomic feature by RNAseq alignments, including 4 samples with support for all annotated introns"; product "sterile alpha motif domain containing 11, transcript variant X3"; exon_number "1"; 
NC_045785.1	Gnomon	exon	40616	40707	.	+	.	gene_id "SAMD11"; transcript_id "XM_036871472.1"; db_xref "GeneID:118905126"; gbkey "mRNA"; gene "SAMD11"; model_evidence "Supporting evidence includes similarity to: 2 Proteins, and 100% coverage of the annotated genomic feature by RNAseq alignments, including 4 samples with support for all annotated introns"; product "sterile alpha motif domain containing 11, transcript variant X3"; exon_number "2"; 

NC_045785.1	Gnomon	exon	43697	43875	.	+	.	gene_id "SAMD11"; transcript_id "XM_036871472.1"; db_xref "GeneID:118905126"; gbkey "mRNA"; gene "SAMD11"; model_evidence "Supporting evidence includes similarity to: 2 Proteins, and 100% coverage of the annotated genomic feature by RNAseq alignments, including 4 samples with support for all annotated introns"; product "sterile alpha motif domain containing 11, transcript variant X3"; exon_number "3"; 

NC_045785.1	Gnomon	exon	45208	45258	.	+	.	gene_id "SAMD11"; transcript_id "XM_036871472.1"; db_xref "GeneID:118905126"; gbkey "mRNA"; gene "SAMD11"; model_evidence "Supporting evidence includes similarity to: 2 Proteins, and 100% coverage of the annotated genomic feature by RNAseq alignments, including 4 samples with support for all annotated introns"; product "sterile alpha motif domain containing 11, transcript variant X3"; exon_number "4"; 

NC_045785.1	Gnomon	exon	49614	49738	.	+	.	gene_id "SAMD11"; transcript_id "XM_036871472.1"; 
db_xref "GeneID:118905126"; gbkey "mRNA"; gene "SAMD11"; model_evidence "Supporting evidence includes similarity to: 2 Proteins, and 100% coverage of the annotated genomic feature by RNAseq alignments, including 4 samples with support for all annotated introns"; product "sterile alpha motif domain containing 11, transcript variant X3"; exon_number "5";

And finally i have tried both with and without the --cache option to see if it is a non-recognition issue from the cache balaenoptera_musculus reference and the .gtf and .fasta reference. I run vep within a conda environment un cluster and my aim is to run arrays (each job with a different chromosome).

Would it be that this difference on annotations would explain such non recognition of transcripts?? Attached my command-line below. Hope you can help me. Best Regards!

Pablo Guevara  

vep \
--dir /u/project/rwayne/pguevara/software/miniconda3/envs/vep/cache \
--vcf --cache --offline --species balaenoptera_musculus \
--canonical --allow_non_variant --symbol --force_overwrite --dont_skip \
--custom ${WORKDIR}/GCF_009873245.2_mBalMus1.pri.v3_genomic_sorted.gtf.gz,,gtf \
-i VCFDIR/JointCalls_trial_06_B_${IDX}_VariantAnnotator.vcf.gz \
-o WORKDIR/variant_effect_output_${IDX}.txt \
--sf WORKDIR/variant_effect_output_${IDX}_summary.html \
--fasta WORKDIR/GCF_009873245.2_mBalMus1.pri.v3_genomic.fasta.gz
