### ISSUE TITLE
HGNC_ID column is empty using symbol

### ISSUE THREAD

**Issue by KevinMer** [Ensembl/ensembl-vep#898] opened 2020-12-09 13:46 UTC
## Describe the issue
Hi,

I have a problem with the symbol option. SYMBOL and SYMBOL_SOURCE contain informations but not the HGNC_ID which is empty.

Thanks a lot.

## Additional information
Please fill in the following sections to help us find the source of your issue as quickly as possible.

### System
- VEP version: [102] 
- VEP Cache version: [102]
- Perl version: [5.26.1]
- OS: [Ubuntu]
- tabix installed ? yes

### Full VEP command line
./vep -i /home/OutputFiles/VCF_PASS/193156_pass.vcf.gz --format vcf --species homo_sapiens --output_file /home/OutputFiles/VEPoutput/test.txt --tab --sf /home/OutputFiles/VEPoutput/test.html --fork 4 --dir_cache /home/Caches/ --cache --refseq --offline --fasta /home/Genome/hg38diag_25chrom.fasta --exclude_predicted --canonical --pubmed --use_given_ref --numbers --hgvsg --hgvs --variant_class --sift b --polyphen b --nearest gene --gene_phenotype --shift_hgvs 0 --minimal --allele_number --custom_multi_allelic --show_ref_allele --pick --symbol --uniprot --check_existing --af_gnomad --var_synonyms --custom /home/Clinvar/clinvar.vcf.gz,Clinvar,vcf,exact,0,CLNSIG,CLNREVSTAT,CLNDN --plugin SpliceAI,snv=/home/reference_data/spliceai_scores.raw.snv.hg38.vcf.gz,indel=/home/reference_data/spliceai_scores.raw.indel.hg38.vcf.gz --plugin CADD,/home/reference_data/whole_genome_SNVs.tsv.gz,/home/reference_data/gnomad.genomes.r3.0.indel.tsv.gz
./vep -i input.txt -o output.txt ...
```

**Comment by dglemos** [comment] 2020-12-09 18:28
Hi @KevinMer,
The HGNC id is only returned when it's available. Can you send an example of an input variant for which you expect an HGNC?

**Comment by KevinMer** [comment] 2020-12-10 07:10
Hi @dglemos,

thanks for your reply.

Here is an example of an input variant :

chr1	924533	.	A	G	1371.06	PASS	.	GT:AD:DP:GQ:PL	1/1:0,44:44:99:1385,131,0

For this one I get the following result :


chr1_924533_A/G | chr1:924533 | G | 148398 | NM_152486.4 | Transcript | upstream_gene_variant | - | - | - | - | - | rs112703963 | 1 | A | MODIFIER | 1198 | 1 | - | SNV | 1 | SAMD11 | EntrezGene
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

I checked on HGNC and SAMD11 has an HGNC ID. Besides, I have an amount of variants of approximately 30 000 with a lot of variants known in specific diseases in Clinvar.
So, I don't understand why the HGNC ID could be not available since these variants are well studied ?

Thanks in advance.

**Comment by dglemos** [comment] 2020-12-10 12:16
Thank you for sending a detailed example. It's very helpful to understand the issue. 
Unfortunately, I can't reproduce the issue. For chr1_924533_A/G I get `HGNC:28706`. 
Could you please run VEP with the minimal options? Something like this: 
`./vep -i /home/OutputFiles/VCF_PASS/193156_pass.vcf.gz --format vcf --species homo_sapiens --output_file /home/OutputFiles/VEPoutput/test.txt --dir_cache /home/Caches/ --offline --fasta /home/Genome/hg38diag_25chrom.fasta `

**Comment by KevinMer** [comment] 2020-12-10 14:24
I ran VEP with the minimal options (adding symbol) as you asked for and I can see the HGNC_ID in the results for all the variants.

Should I add options one by one until the HGNC_ID disappear ?

**Comment by dglemos** [comment] 2020-12-10 14:26
Yes, can you start testing the flags `--shift_hgvs`, `--hgvsg` and `--hgvs`?

**Comment by KevinMer** [comment] 2020-12-10 14:40
HGND_ID still present. What other flags you want me to add ?

**Comment by dglemos** [comment] 2020-12-10 14:51
I can reproduce the issue when using the `--refseq`. Can you test VEP with that flag?

**Comment by KevinMer** [comment] 2020-12-10 15:10
I confirm, HGND_ID has disappeared with the refseq flag. Is it a bug ?

**Comment by dglemos** [comment] 2020-12-10 17:17
It's not a bug, for the RefSeq data we get the gene symbols from EntrezGene. Unfortunately, we don't store the corresponding HGNC IDs in the RefSeq geneset at the moment. But you can get these IDs using the merged cache. This is the output I get using `--merged`:
`1_924533_A/G    1:924533        G       148398  NM_152486.4     Transcript      upstream_gene_variant   -       -       -       -       -       -       IMPACT=MODIFIER;DISTANCE=1198;STRAND=1;SYMBOL=SAMD11;SYMBOL_SOURCE=EntrezGene;HGNC_ID=HGNC:28706;SOURCE=RefSeq;GIVEN_REF=A;USED_REF=A`

**Comment by KevinMer** [comment] 2020-12-11 08:05
Fine, I will use the merged flag.

Do you envisage to store HGNC IDs in the geneset Refseq in future release ?

Thanks a lot for your help @dglemos ! Thanks to you I can now use the HGNC ID.

Have a nice day !

**Comment by dglemos** [comment] 2020-12-11 11:18
At the moment we don't have plans to include the HGNC IDs in the RefSeq cache as it depends on data from other teams. 
I'm glad the solution works for you. I'm going to close this ticket now but feel free to reopen it if you have more questions. 
Best wishes,
Diana

**Closed by dglemos** 2020-12-11 11:18 UTC
