### ISSUE TITLE
VEP error for structural variation VCF input

### ISSUE THREAD

**Issue by barbarian1803** [Ensembl/ensembl-vep#1694] opened 2024-06-06 06:29 UTC
## Describe the issue
When annotating an SV, VEP throw error.

### System
- VEP version: docker 112.0 
- VEP Cache version: 112

### Full error message
Can't locate object method "cdna_coords" via package "Bio::EnsEMBL::Variation::StructuralVariationOverlap" at /opt/vep/src/ensembl-vep/Bio/EnsEMBL/Variation/Utils/VariationEffect.pm line 673, <GEN2> line 3509.

I a not sure which part of the VCF file cause this. Maybe you can help me to narrow down the cause.

**Comment by likhitha-surapaneni** [comment] 2024-06-06 18:28
Hi @barbarian1803 ,

Sorry to hear that you are facing issues. Can you please provide us with an input file?

Thank you.

**Comment by barbarian1803** [comment] 2024-06-07 00:57
@likhitha-surapaneni Hi, I have narrow down the VCF file that throw this error. Attached is the file.
[test.vcf.gz](https://github.com/user-attachments/files/15688147/test.vcf.gz)

**Comment by kheemsk** [comment] 2024-07-10 17:22
Hi @likhitha-surapaneni , I am also having a similar issue. Any update on the problem or is there an easy solution? 
Thanks!

**Comment by duanjingqi** [comment] 2024-07-12 06:52
@likhitha-surapaneni I have the exactly same issue, and VEP109 reported the same error, it did not help at all. Please help me.  My test SV vcf. 
[test.sv.vcf.gz](https://github.com/user-attachments/files/16189777/test.sv.vcf.gz)

**Comment by likhitha-surapaneni** [comment] 2024-07-12 08:21
Hi @kheemsk and @duanjingqi ,
Sorry to hear that you are facing the same issue and thank you for your patience. We are currently looking into it and will keep you notified once we have an update.

Kind regards,
Likhitha

**Comment by duanjingqi** [comment] 2024-07-25 22:52
@likhitha-surapaneni Any update on the solution?

**Comment by davmlaw** [comment] 2024-08-01 08:21
As a workaround, you could try using --custom instead of StructuralVariationOverlap, try params like ```,type=overlap,overlap_cutoff=80,same_type=1```. If you need both ID and coords call it twice. You can do a bit of post-processing and if you need to do some combine the 2 custom annotations and do some filtering

**Comment by duanjingqi** [comment] 2024-08-01 15:47
@davmlaw @likhitha-surapaneni  More help is needed here. I am using vep 112. I don't see 'type', 'overlap_cutoff' and 'same_type' in the latest vep document. Are they available? 'custom' will have to take a tabix indexed file, which file should I give? If you can provide a code snippet, that would be really helpful.

**Comment by nuno-agostinho** [comment] 2024-08-09 15:19
Hey @barbarian1803, @kheemsk, and @duanjingqi,

The issue is related with using breakpoint variants while enabling the `--regulatory` flag. We patched this bug and the fix will be available in the next release (VEP 113).

In the meantime, please consider either:
- Filtering out breakpoint variants when using the `--regulatory` flag
- Not using `--regulatory` when analysing breakpoint variants

We understand that the workarounds are sub-optimal at the moment and we are sorry for the inconvenience.

I will now close this ticket, but please feel free to reply here if you want to discuss this further.

Best regards,
Nuno

**Closed by nuno-agostinho** 2024-08-09 15:19 UTC

**Comment by ramprasadn** [comment] 2024-09-30 11:43
@nuno-agostinho, could you give us an update on when the next release is expected to be available?

**Comment by nakib103** [comment] 2024-09-30 14:34
Hi @ramprasadn, the current estimation for the release date is to be in first half of October.

**Comment by ramprasadn** [comment] 2024-10-01 07:26
Thanks for letting us know @nakib103 !
