### ISSUE TITLE
filter_vep requires over 100Gb of memory

### ISSUE THREAD

**Issue by fgvieira** [Ensembl/ensembl-vep#580] opened 2019-08-26 12:34 UTC
Dear all,

I have a VCF with SV calls annotated with VEP (`StructuralVariantOverlap.pm`), and I am trying to filter it by gnomAD AF. However, at a certain position, it uses up all available memory (around 100Gb) and is killed by the OS.

I've tried to reproduce the error on a smaller file but couldn't, so I am guessing it is some kind of memory leak. I know it is difficult to pinpoint the issue without an example, but was hoping someone might have some insight...

thanks,

**Comment by dglemos** [comment] 2019-08-27 10:23
Hi @fgvieira,

Do you know at which variant it stops running? 
I can't see an apparent reason for that to happen, as you said it is difficult to find the issue without an example. Could you send the command you used to filter the file?

**Comment by fgvieira** [comment] 2019-08-27 10:54
Yes, it stops running at:
```
2       3144802 DUP00004094     T       <DUP>   .       PASS
```
but I do not think it is this variant that is causing it, as I created a VCF with just this variant and `filter_vep` worked fine. My guess would be that, since these are SVs and some can be quite large, there is some memory that it is not being freed as it should.

```
zcat FILE.vcf.gz | filter_vep --format vcf --filter "gnomAD-SV_AF < 0.05" --only_matched
```

**Comment by dglemos** [comment] 2019-09-05 13:21
There's no apparent reason why you're having memory issues filtering variants. We're looking into it but in the meantime, it would help if you could provide your input file.

**Comment by fgvieira** [comment] 2019-09-05 13:27
Unfortunately I cannot send the file (no patient consent), but I'll see if I can replicate it with a publicly available dataset.

**Comment by dglemos** [comment] 2019-10-21 16:08
Did you replicate the issue with a different dataset?

**Comment by fgvieira** [comment] 2019-10-22 08:18
Not yet.. I've been busy quite with lately with other projects and not sure when I'll be able to look into it... maybe we can just close it for now and I'll re-open it if necessary.

**Comment by dglemos** [comment] 2019-10-22 08:30
Sorry that I couldn’t give you a more helpful response. 
I'll close the issue for now. If you have the same problem in the future feel free to re-open this issue. 

Best regards,
Diana

**Comment by fgvieira** [comment] 2019-11-18 10:35
Dear all,

I'm re-opening this issue since I just saw this behavior again with VEP 98.3 when running `filter_vep`:
`filter_vep --input_file input_cnv_germline_annot.vcf.gz --gz --filter "gnomAD_SV_AF < 0.05 or not gnomAD_SV_AF" --only_matched`

It starts with a memory usage of ~3 Gb, but it keeps increasing until ~80Gb:
`27847 filipev   20   0   79.7g  79.6g   2428 R 100.0 63.3  10:28.14 perl filter_vep --input_file input_cnv_germline_ [...]`

The VCF has 7572 SV calls and is 31 Mb (421 Mb uncompressed). Is this expected?

**Comment by aparton** [comment] 2019-11-18 14:23
Hi,

Sorry to hear that you're still having this issue. Could you please either send the input vcf to helpdesk@ensembl.org (or submit it via https://www.ensembl.org/Help/Contact), and we can pick it up from there and take a look.

Kind Regards,
Andrew

**Comment by fgvieira** [comment] 2019-11-18 15:50
Hi Andrew,

sure, just sent it to helpdesk email

**Comment by dglemos** [comment] 2019-11-20 11:12
Hi @fgvieira,
Thanks for sending the file. However, it's too large for the helpdesk system. Could you load it somewhere (dropbox for instance) and send the url instead?

**Comment by fgvieira** [comment] 2019-11-20 14:54
Hi @dglemos 

I've uploaded it [here](https://fil.email/9sCVNLDs). Can you try to download it?
The link will only be active for 7 days though...

**Comment by dglemos** [comment] 2019-11-20 14:57
It works, thanks. 
I'll try to reproduce the issue and will let you know.

**Comment by dglemos** [comment] 2019-11-21 15:22
I run the same command with your file and I get the same memory issue. It looks like some of your variants have a lengthy CSQ field. For instance: 
`1  16945702  INV00000354  C` overlaps more than 3500 features and as a consequence this line has length=594206. Long lines are not well handled by `filter_vep`.  
We're looking into a way to improve this but in the meantime, as the gnomAD frequency is not in the CSQ field, you could set this field to `CSQ=` and merge it after the filtering.

**Comment by fgvieira** [comment] 2019-11-25 16:47
Hi @dglemos, the reason gnomAD frequency is not in the CSQ is mostly because VEP uses a lot of memory, so I had to use another program.

As for your suggestion, I am not sure what you mean... you suggest filtering the VCF while setting `--vcf_info_field` to the gnomAD field, and then incorporate the gnomAD info into the CSQ. Is that it?

**Comment by dglemos** [comment] 2019-11-27 13:36
As gnomAD frequencies are not stored in CSQ, I was suggesting to set CSQ to empty and run the filter. After the file is filtered you could add the CSQ again. In the meantime, a fix has been to merged into version 99. If you run your command again you should have a result without having memory issues.

**Comment by fgvieira** [comment] 2019-11-28 12:41
Just tried the new script and it seems to be using much less memory. :+1: 
Haven't compared the results, tough...

thanks!

**Comment by dglemos** [comment] 2019-11-28 13:40
Good to know it worked. If you find anything wrong with your results please let us know. 

Best regards,
Diana

**Closed** 2019-11-28 16:07 UTC
