### ISSUE TITLE
VEP Died in forked process: Can't locate object method "stable_id"

### ISSUE THREAD

**Issue by bigmw** [Ensembl/ensembl-vep#314] opened 2018-10-30 21:28 UTC
I ran ensembl-vep version 94.4 on my machine to annotate some big vcf file. To speed up the process, I used --fork option as in the following command:
vep  -format vcf  -i my.vcf  -o my.vep.vcf --vcf --offline --cache  --force_overwrite \
    --pick  --gencode_basic --regulatory --variant_class  --sift b --polyphen b --gene_phenotype \
--af_esp  --af_1kg --af_gnomad --no_headers --fork 4

And I got the following error after I ran the command for 0.5-1 hour.
Can't locate object method "stable_id" via package "Bio::EnsEMBL::Funcgen::MotifFeature" at /xxx/ensembl-vep/modules/Bio/EnsEMBL/VEP/OutputFactory.pm line 1614.
Died in forked process 11668

I tried the same command on separate vcf files of chromosomes 1 and 2, and I got errors both. So it is replicable on different input files.  I also tried to run without --fork, got the same error: Can't locate object method "stable_id"..

Please advise what I shall do. Thank you.

**Comment by at7** [comment] 2018-10-31 09:20
Thank you for the detailed report. Could you please confirm the version of your cache files? For release 94 we had to temporarily remove the motif features from the cache files. The number of motif features has increased so much that we couldn't scale the cache file creation fast enough. The data will be back in release/95. This is why I'm not expecting to see the error you are reporting unless you are using an older version of the cache files.
Thank you,
Anja

**Comment by bigmw** [comment] 2018-10-31 14:56
Hi Anja,
The cache version I used is 92_GRCh38, indeed it is an older version. Can’t vep use an older version of cache (annotaton)?
I was prompted to update vep recently, but not the cache. I assume it should be fine as the genome version remains the same (GRCh38).
Thanks.

**Comment by at7** [comment] 2018-10-31 15:02
Unfortunately, there have been too many changes between release/93 and release/94 that it is not possible to use release/94 VEP code with older versions of cache files. You could run without the  --regulatory flag. But we highly recommend to use the latest version of VEP cache files.

**Comment by bigmw** [comment] 2018-10-31 15:23
Okay, I will update to cache release 94, see if that solve the problem.

**Comment by bigmw** [comment] 2018-10-31 21:41
Update: the error was gone after I updated the cache to release 94.
A few issues though:
No allele frequency data was output enough tough I specified -af_esp --af_1kg --af_gnomad, this was fine with vep v92 but not v94
The old cache files were not removed after new version installed/converted, even though I specified so as below:
perl convert_cache.pl -species all -version 94_GRCh38 --remove
several variant filtering arguments not work properly including --most_severe, --summary (and potentially others too). Even though I didn’t use --symbol, it always throws error like:
MSG: ERROR: Can't use --most_severe and --symbol together

Hope these issues can be resolved soon. Thanks.

**Comment by at7** [comment] 2018-11-01 12:39
I'm sorry to hear that you are still having problems running VEP with the new cache files:

I will have to look into why --remove is not working. I give an update as soon as I know more.

I was running an example annotation for _1 230710048 230710048 A/G 1_ and I do get frequency annotations for the input variant.

Could you please share again your command for running VEP and run it only for the example variant and share your output?

Or could you share some input for which you are expecting frequency annotations?

I also would like to see your full command again in order to understand the reason for your incompatibility error message (Can't use --most_severe and --symbol). It might be caused by trying to run -most_severe and --summary together which is not possible. Using --summary  (Output only a comma-separated list of all observed consequences per variant. Transcript-specific columns will be left blank.) doesn't allow to determine the most_severe variant (Output only the most severe consequence per variant. ) You can really do one or the other.

**Comment by bigmw** [comment] 2018-11-01 14:39
My full command remained the same as above except with the new cache version:
vep -format vcf -i my.vcf -o my.vep.vcf --vcf --offline --cache --cache_version 94 --force_overwrite
--pick --gencode_basic --regulatory --variant_class --sift b --polyphen b --gene_phenotype
--af_esp --af_1kg --af_gnomad --no_headers --fork 4

I used the variant filtering arguments --most_severe or --summary in place of --pick above, and without –symbol. I noticed similar problem with release 92 too.

About the frequency data, I am sure the problem is not variant or input specific. Because I tried to run vep on essentially all exonic variants (millions of them!) in multiple chromosomes. None of the variant received a *_AF data, although most of them received an “rs” number. I didn’t see this problem with release 92. Below is a few example variants + vep output.

chr2	41602	chr2:41,602	T	C	255	PASS	VRT=1; Het=42; CSQ=C|3_prime_UTR_variant|MODIFIER|FAM110C|ENSG00000184731|Transcript|ENST00000327669|protein_coding|2/2||||972|||||rs200542783||-1||SNV|HGNC|HGNC:33340||||0.003|0|0|0|0|||8.139e-05|0.0009821|9.01e-05|0|0|0|8.958e-06|0.0001834|0|||||||	NA:FRQ	125568:0.00033448
chr2	41606	chr2:41,606	C	T	255	PASS	VRT=1; Het=4; CSQ=T|stop_lost|HIGH|FAM110C|ENSG00000184731|Transcript|ENST00000327669|protein_coding|2/2||||964|964|322|*/R|Tga/Aga|rs746302953||-1||SNV|HGNC|HGNC:33340|||||||||||1.221e-05|0|0|0|0|0|2.688e-05|0|0|||||||	NA:FRQ	125568:3.18552e-05
chr2	41612	chr2:41,612	C	T	255	PASS	VRT=1; Het=4; CSQ=T|missense_variant|MODERATE|FAM110C|ENSG00000184731|Transcript|ENST00000327669|protein_coding|2/2||||962|962|321|R/Q|cGa/cAa|rs373037350||-1||SNV|HGNC|HGNC:33340||deleterious_low_confidence(0)|benign(0)||||||0.00027|0.0001223|5.296e-05|0|9.048e-05|0|0.0002905|0|4.481e-05|0|0|||||||	NA:FRQ	125568:3.18552e-05

BTW, I am running vep on mac os high sierra now. The installation of vep on both mac an linux was not smooth. I heard similar complaint from other users. Vep is a great tool, only hope you guys could make it more stable and easier to install/run.

**Comment by bigmw** [comment] 2018-11-01 15:58
Never mind about the allele frequency data, I realized they are there as: 1.221e-05|0|0|0|0|0|2.688e-05|0|0. I was expecting it in name=value format like gnomAD_AF=0.10 etc, obviously it is not. 
other problems exist as described.

**Comment by at7** [comment] 2018-11-01 16:43
There are a few options which cannot be run together. It is not very clear from the documentation page and we will add an incompatibility table for next release. For now I can only share our [look up table](https://github.com/Ensembl/ensembl-vep/blob/release/94/modules/Bio/EnsEMBL/VEP/Config.pm#L384-L396) form the VEP code.

Could you please describe which parts of the installation you found difficult? We are constantly trying to improve the installation process. We also have a [docker image](https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#docker) which facilitates running VEP a lot.

**Comment by at7** [comment] 2018-11-16 11:22
I will close this issue. Please reopen it if you have further questions or start a new issue thread.

**Closed by at7** 2018-11-16 11:22 UTC
