### ISSUE TITLE
Use of uninitialized value in subtraction (-) and (+) at ..../VEP/AnnotationSource/Cache/VariationTabix.pm line 184, <VARS> line 1.

### ISSUE THREAD

**Issue by ChrisMoth** [Ensembl/ensembl-vep#882] opened 2020-11-11 18:01 UTC
## Describe the issue

When the --pubmed flag is given to vep, perl 5.32 now issues a warning about variable scope:

Use of uninitialized value in subtraction (-) at ...../Bio/EnsEMBL/VEP/AnnotationSource/Cache/VariationTabix.pm line 184, <VARS> line 1.
Use of uninitialized value in addition (+) at ...../Bio/EnsEMBL/VEP/AnnotationSource/Cache/VariationTabix.pm line 184, <VARS> line 1.

The warning goes away for me when I remove --pubmed.  But, I have not dug deeper to try and figure out why.

## Additional information
This is a nuisance I encountered.  I think it arrived with update to latest perl, which I install following your instructions.  I am NOT a PERL guru - but very experienced in Python and C++.  Looking at the code block, either there are slightly new scoping rules in PERL, or the PERL interpreter is being over-agressive.  I think it is worth your taking 2 minute to try and duplicate.  Maybe look at line 184 of VariantionTabix.pm and see if there is a way to better connect $max_length in the VAR: block to the enclosing scope.

Specifically,
### System
- VEP version: 100
- VEP Cache version: 100
- Perl version: [5.32
- OS: CentOS 7.6.1810  (/etc/redhat-release)
- tabix installed: YES  version 0.2.5 r1005

### Full VEP command line
```
vep -i onevariant.vcf --format vcf --cache --dir /dors/capra_lab/data/ensembl/vep_cache --offline   --buffer_size 100000 --pubmed --coding_only --vcf --db_version 100 --assembly GRCh38 --no_stats -o stdout

```

### Full error message
> Including the warnings, if available
Here is al the output I get back from VEP, nuisance warnings bolded:

##fileformat=VCFv4.1
##VEP="v100" time="2020-11-11 11:49:23" cache="/dors/capra_lab/data/ensembl/vep_cache/homo_sapiens/100_GRCh38" 1000genomes="phase3" COSMIC="90" ClinVar="201912" ESP="V2-SSA137" HGMD-PUBLIC="20194" assembly="GRCh38.p13" dbSNP="153" gencode="GENCODE 34" genebuild="2014-07" gnomAD="r2.1" polyphen="2.2.2" regbuild="1.0" sift="sift5.2.2"
##INFO=<ID=CSQ,Number=.,Type=String,Description="Consequence annotations from Ensembl VEP. Format: Allele|Consequence|IMPACT|SYMBOL|Gene|Feature_type|Feature|BIOTYPE|EXON|INTRON|HGVSc|HGVSp|cDNA_position|CDS_position|Protein_position|Amino_acids|Codons|Existing_variation|DISTANCE|STRAND|FLAGS|SYMBOL_SOURCE|HGNC_ID|CLIN_SIG|SOMATIC|PHENO|PUBMED">
#CHROM  POS     ID      REF     ALT
**Use of uninitialized value in subtraction (-) at /gpfs51/dors2/capra_lab/users/psbadmin/ensembl/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/Cache/VariationTabix.pm line 184, <VARS> line 1.**
**Use of uninitialized value in addition (+) at /gpfs51/dors2/capra_lab/users/psbadmin/ensembl/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/Cache/VariationTabix.pm line 184, <VARS> line 1.**
17      59028432        .       T       C       .       .       CSQ=C|missense_variant|MODERATE|TRIM37|ENSG00000108395|Transcript|ENST00000262294|protein_coding|19/24||||2659|2240|747|N/S|aAt/aGt|||-1||HGNC|HGNC:7523||||,C|missense_variant|MODERATE|TRIM37|ENSG00000108395|Transcript|ENST00000393065|protein_coding|18/23||||2503|2138|713|N/S|aAt/aGt|||-1||HGNC|HGNC:7523||||,C|missense_variant|MODERATE|TRIM37|ENSG00000108395|Transcript|ENST00000393066|protein_coding|19/25||||2700|2240|747|N/S|aAt/aGt|||-1||HGNC|HGNC:7523||||

### Data files (if applicable)
This trivial .vcf file is sufficient.
$ cat onevariant.vcf
#CHROM  POS     ID      REF     ALT
17      59028432        .       T       C

**Comment by dglemos** [comment] 2020-11-12 13:53
Hi @ChrisMoth,
I'm unable to replicate the warning message. The warning you're getting is caused by undef values `$existing->{start}` and `$existing->{end}` in L184 which shouldn't be empty. 
- Did you run the same command with a different Perl version? 
- Can you check what is inside variable [$existing](https://github.com/Ensembl/ensembl-vep/blob/10932fab1e9c113e8e5d317e1f668413390344ac/modules/Bio/EnsEMBL/VEP/AnnotationSource/Cache/VariationTabix.pm#L181)?

**Comment by dglemos** [comment] 2020-12-17 15:19
I'm going to close this issue but if you have more questions feel free to reopen it. 
Best wishes,
Diana

**Comment by ChrisMoth** [comment] 2020-12-17 17:21
Thanks for trying to replicate this.  I still get this loud warning, and will try to dig deeper in the new year.
________________________________

**Comment by dglemos** [comment] 2021-01-18 15:47
Hi @ChrisMoth,
Did you have a chance to look into this issue?

**Comment by dglemos** [comment] 2022-04-19 12:36
I'm going to close this issue but when you have a chance to have another look feel free to reopen it.

Best wishes,
Diana

**Closed by dglemos** 2022-04-19 12:36 UTC

**Comment by LightSun** [comment] 2023-08-01 03:33
@ChrisMoth Did you fixed this? I also met this problem.
