### ISSUE TITLE
Variant filtered although it is (far) below the threshold

### ISSUE THREAD

**Issue by Redmar-van-den-Berg** [Ensembl/ensembl-vep#1404] opened 2023-04-26 12:42 UTC
## Describe the issue
I'm using VEP to both annotate variants, and filter out those variants that are common in the population (population frequency above 5%). However, one of the filtered variants has a population frequency of `gnomade=0.000006365`

## Additional information
If I set the allele frequency for VEP to 1 ( `--freq_freq 1`), the variant does show up in the output as expected.

### System
- VEP version: docker://quay.io/biocontainers/ensembl-vep:108.2--pl5321h4a94de4_0
- VEP Cache version: 108
- Perl version: v5.32.1
- OS: Biocontainer on CentOS
- tabix installed: yes

### Full VEP command line
```bash
vep
    -i tet2.vcf
    --fasta GCA_000001405.15_GRCh38_no_alt_analysis_set.fna
    --offline
    --cache_version 108
    --everything
    --merged
    --dir data
    --af_gnomade
    --check_frequency
    --fork 8
    --allele_number
    --stats_text
    --json
    --force_overwrite
    --assembly GRCh38
    --format vcf
    --polyphen b
    --sift b
    --hgvs
    --af
    --freq_pop gnomADe
    --freq_freq 0.05
    --freq_gt_lt gt
    --freq_filter exclude
    --stats_file samplename/vep_stats.txt
    --output_file STDOUT
```

### Full error message
None

### Data files (if applicable)
They include:
The input VCF file: [tet2.vcf.zip](https://github.com/Ensembl/ensembl-vep/files/11332854/tet2.vcf.zip)
The VEP JSON output, generated with `--freq_freq 1`: [tet2_AF1_vep.json.zip](https://github.com/Ensembl/ensembl-vep/files/11332856/tet2_AF1_vep.json.zip)

**Comment by olaaustine** [comment] 2023-04-27 10:12
Hi @Redmar-van-den-Berg,
Thank you for your query and your detailed information. 
We have been able to reproduce this error. Thank you for bringing this to our notice.
We are taking a look at it.
Thank you 
Ola.

**Comment by Redmar-van-den-Berg** [comment] 2023-06-26 06:06
Hi @olaaustine, are there any updates on this issue? Is there anything I can do to help this along?

**Comment by olaaustine** [comment] 2023-06-26 13:18
Hi @Redmar-van-den-Berg,

We have successfully identified the issue. 

We would prioritise this fix.  Thank you for your patience.

This fix will only be available from our upcoming release/111. We would update this ticket when the fix has been applied.

Thank you,
Ola.

**Comment by olaaustine** [comment] 2023-06-27 13:47
Hi @Redmar-van-den-Berg, 
Hope this meets you well?
As a workaround, if you run VEP without the `--freq, --freq_pop gnomADe --freq_freq 0.05 --freq_gt_lt gt --freq_filter exclude` flag this would help with carrying your analyses in the meantime. 
```
vep
    -i tet2.vcf
    --fasta GCA_000001405.15_GRCh38_no_alt_analysis_set.fna
    --offline
    --cache_version 108
    --everything
    --merged
    --dir data
    --af_gnomade
    --check_frequency
    --fork 8
    --allele_number
    --stats_text
    --json
    --force_overwrite
    --assembly GRCh38
    --format vcf
    --polyphen b
    --sift b
    --hgvs
    --af
    --af_gnomade
    --vcf
    --output_file out.vcf
```
Using the [filter_vep](https://www.ensembl.org/info/docs/tools/vep/script/vep_filter.html) to filter the variants based on the frequency : 
`filter_vep --format vcf -i  out.vcf  --filter "gnomADe_AF < 0.05" -o filtered.vcf`

Thank you, 
Ola.

**Comment by Redmar-van-den-Berg** [comment] 2024-10-14 13:32
I just tested this in VEP release 112.0, and unfortunately this bug hasn't been fixed yet.

**Comment by olaaustine** [comment] 2024-10-16 14:23
Hi @Redmar-van-den-Berg, 
Hope you are well? 
Thank you for keeping track of this ticket. 
Following discussions within the team, we are not presently prioritising this as there is a workaround with the filter-vep 
Please feel free to open another ticket or reopen this ticket if you have any issues. 
Thank you 
Ola.

**Closed by olaaustine** 2024-10-16 14:23 UTC
Labels: bug

**Comment by Redmar-van-den-Berg** [comment] 2024-10-16 15:26
Hi @olaaustine, thank you for the update!

Especially in clinical settings, this bug has the potential to cause real harm to patients. VEP is used extensively in clinical settings, as is filtering out variants which are common in the general population. This combination makes this bug especially dangerous, as it will "disappear" clinically relevant variants. 

If the users are not aware that this bug exists, the fact that there is a workaround will unfortunately not help them. I would therefore ask you to reconsider the priority of this bug.

Secondly, I would like to ask your advice on how to use `filter-vep` as a workaround. Our pipeline uses the JSON output from VEP to enable further downstream processing of the variants. Is there a way to enable JSON format output for the `filter-vep` script?

**Comment by jamie-m-a** [comment] 2025-02-26 09:30
Hi @Redmar-van-den-Berg 

My apologies - I meant to reopen this when Ola escalated the ticket to me but I missed it. We share your concern about the filtering excluding a potentially clinically relevant variant and are actively investigating why it has happened. 

Typically we don't recommend filtering while annotating, but instead annotating first then filtering - as Ola suggested. However, the filter_vep script does not work on the json output, so if you are tied to using json output you would need a custom solution.

I will continue to investigate this, but at the moment I cannot give a timeline on a potential fix. In the meantime if you are able to work with VCF output rather than JSON, you can exclude the `--freq` flags when running VEP and filter the output of VEP using filter_VEP.

**Comment by Redmar-van-den-Berg** [comment] 2025-02-26 09:43
Hi @jamie-m-a ,

Thanks for your reply, I just happened to run into another variant that was filtered out by mistake yesterday so I decided to try to get some attention on this bug.

In case other people are interested, I ended up implementing my own script to filter JSON VEP records, [filter_vep.py](https://github.com/LUMC/HAMLET/blob/97d8138e03f9cf38c712c9846df9232f498a9448/includes/snv-indels/scripts/filter_vep.py). The full script itself is a specific to our use case, but the VEP class which does the actual filtering is reusable and fully tested.

**Comment by jamie-m-a** [comment] 2025-02-26 13:06
Hi @Redmar-van-den-Berg - I'm glad to hear you created a solution for your needs. Would you be able to pass the other example you found of an incorrectly filtered variant. I can use it to help find the bug and test solutions.

I'll keep you updated regarding a potential fix when we get there.

**Comment by Redmar-van-den-Berg** [comment] 2025-02-26 14:16
Here is the json output from VEP for the second example: [ASXL1-annot.json](https://github.com/user-attachments/files/18985375/ASXL1-annot.json)

I noticed that both variants are insertions.

**Comment by jamie-m-a** [comment] 2025-02-26 16:22
Thanks @Redmar-van-den-Berg - yes I believe it's do with our allele matching not working as intended due to an issue with variant minimisation.
