### ISSUE TITLE
Error Messages with VEP Cache Access 

### ISSUE THREAD

**Issue by ghost** [Ensembl/ensembl-vep#925] opened 2021-02-05 11:44 UTC
Hello Everybody, 
Our group are currently developing a script for variant calling within a gene on Rocket. As part of such we are including a VEP section for pathogenicity prediction etc. While this worked previously with an older version of VEP, we are now receiving error messages when using such with the pipeline effectively ending at the VCF stage.
Below is a copy of the script used, followed by the error message we receive

module load VEP/102.0-foss-2019a-Perl-5.28.1

vep --cache --cache_version 102 --offline --use_given_ref --format vcf --tab --SIFT b --PolyPhen b --biotype --numbers \
--dir_cache /nobackup/b7000371/WORKING_DATA/SourceFiles/VEPHSCache \
-i /nobackup/b7000371/WORKING_DATA/PMS2_Variants/vcf/SampleExonMIPs202012/${Sample}.vcf \
-o $NFVEPDir/${Sample}.txt

filter_vep -filter "(Gene is ENSG00000122512) and (Feature is ENST00000265849)" \
-i $NFVEPDir/${Sample}.txt \
-o $FVEPDir/${Sample}.txt

----------------------------------------------------------------------------------------------------------------------------------------------

MSG: ERROR: No cache found for homo_sapiens, version 102

STACK Bio::EnsEMBL::VEP::CacheDir::dir /mnt/storage/apps/eb/software/VEP/102.0-foss-2019a-Perl-5.28.1/modules/Bio/EnsEMBL/VEP/CacheDir.pm:328
STACK Bio::EnsEMBL::VEP::CacheDir::init /mnt/storage/apps/eb/software/VEP/102.0-foss-2019a-Perl-5.28.1/modules/Bio/EnsEMBL/VEP/CacheDir.pm:227
STACK Bio::EnsEMBL::VEP::CacheDir::new /mnt/storage/apps/eb/software/VEP/102.0-foss-2019a-Perl-5.28.1/modules/Bio/EnsEMBL/VEP/CacheDir.pm:111
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all_from_cache /mnt/storage/apps/eb/software/VEP/102.0-foss-2019a-Perl-5.28.1/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:115
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all /mnt/storage/apps/eb/software/VEP/102.0-foss-2019a-Perl-5.28.1/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:91
STACK Bio::EnsEMBL::VEP::BaseRunner::get_all_AnnotationSources /mnt/storage/apps/eb/software/VEP/102.0-foss-2019a-Perl-5.28.1/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:170
STACK Bio::EnsEMBL::VEP::Runner::init /mnt/storage/apps/eb/software/VEP/102.0-foss-2019a-Perl-5.28.1/modules/Bio/EnsEMBL/VEP/Runner.pm:132
STACK Bio::EnsEMBL::VEP::Runner::run /mnt/storage/apps/eb/software/VEP/102.0-foss-2019a-Perl-5.28.1/modules/Bio/EnsEMBL/VEP/Runner.pm:203
STACK toplevel /mnt/storage/apps/eb/software/VEP/102.0-foss-2019a-Perl-5.28.1/vep:229
Date (localtime)    = Fri Feb  5 11:31:20 2021
Ensembl API version = 102

----------------------------------------------------------------------------------------------------------------------------------------------

I have a personal copy of the homo_sapiens (V102) cache saved locally, and have tried running the script without the '--offline' option, but nothing seems to correct this issue. Does anybody know how to resolve this issue so that VEP will run effectively? 

Thanks

**Comment by aparton** [comment] 2021-02-05 13:57
Hi @PeterG188,

I suspect this is caused by VEP being unable to find your personal copy of the cache file. With your current set up then VEP will be looking for an unzipped 102 cache within the folder that you've specified in `--dir_cache`, i.e. it will be looking for `/nobackup/b7000371/WORKING_DATA/SourceFiles/VEPHSCache/homo_sapiens/102_GRCh38`. Does this folder exist?

If it does not, then unzipping your cache file in `/nobackup/b7000371/WORKING_DATA/SourceFiles/VEPHSCache` should setup the cache file as expected. Alternatively, you can do this with the VEP installer by running:
`perl INSTALL.pl --auto c --CACHEDIR /nobackup/b7000371/WORKING_DATA/SourceFiles/VEPHSCache --SPECIES homo_sapiens --ASSEMBLY GRCh38`

If there's anything else we can do to help, please let us know.

Kind Regards,
Andrew

**Comment by aparton** [comment] 2021-08-20 10:46
Hi,

I'm going to close this issue now. If you have any further questions, please feel free to reopen it or create a new issue.

Kind Regards,
Andrew

**Closed by aparton** 2021-08-20 10:46 UTC
Labels: installation
