### ISSUE TITLE
incorrect High impact

### ISSUE THREAD

**Issue by Artemlin6231** [Ensembl/ensembl-vep#1480] opened 2023-08-18 08:59 UTC
## Describe the issue
Incorrectly assigning the HIGH impact
## Additional information
We used VEP for annotating structural variants. When we used version 107, it assigned the "High" impact only to 67 structural variants in one of our samples, whereas with the new version, it assigned it to 917. We examined one of the deletions that VEP annotated as "High" with feature_truncation and intron_variant descriptions, but in IGV, we did not see any signals nearby this deletion indicating that it is indeed a functionally significant deletion(chr1:202391650-202392047 hg38). Similarly, with other structural variants with "High" impact assigned by VEP in the new version.
### System
- VEP version: 110.1
- VEP Cache version: [e.g. 98]
- Perl version: [e.g. 5.26]
- OS: [e.g. MacOS, Ubuntu, CentOS]
- tabix installed ?

### Full VEP command line
```
vep -i homo.vcf --gff ~{gff} --fasta ~{ref_fasta} -o homo -q --tab --symbol --max_sv_size 1000000
```

### Full error message
> Including the warnings, if available

### Data files (if applicable)
They include:
- The input file
- The output file
- The custom file(s)
You can provide a sample of them

**Comment by nuno-agostinho** [comment] 2023-08-18 09:49
Hi @Artemlin6231,

The impact of a consequence is based on the following table: https://www.ensembl.org/info/genome/variation/prediction/predicted_data.html.

You can see which consequences we currently consider as `high impact`, including `feature_truncation`: `The variant is assumed to have high (disruptive) impact in the protein, probably causing protein truncation, loss of function or triggering nonsense mediated decay` (definition from [Ensembl glossary](https://www.ensembl.org/Help/Glossary?id=535)).

If you think this is incorrect in your case, could you tell us why do you think so? Thanks for your time!

Best regards,
Nuno

**Comment by Artemlin6231** [comment] 2023-08-18 11:18
I believe that there should not be a feature_truncation flag, as there are no exons in this region(chr1:202391650-202392047)

**Comment by nuno-agostinho** [comment] 2023-08-18 11:22
Hi @Artemlin6231,

I understand that is so in the case that you have shown, but could you please confirm if that is also the case for other examples in your data?

I will try to understand why this is happening and fix this. I am sorry for the issue.

Thanks,
Nuno

**Comment by Artemlin6231** [comment] 2023-08-19 12:43
For example, deletions in chr1:21459928-21460197, chr1:24832213-24835018, chr1:57877552-57877863

**Comment by Artemlin6231** [comment] 2023-09-04 12:29
Are there any updates?

**Comment by nuno-agostinho** [comment] 2023-09-04 12:38
Hi @Artemlin6231,

As you previously suggested, VEP is classifying the variant consequences as `feature_truncation` (`high` impact), when it should be assigned a less severe consequence, probably `intron_variant` (`modifier` impact).

The issue is currently in our backlog, but should be a small change and I will try to fix it soon. Sorry for the inconvenience.

Kind regards,
Nuno

**Comment by EugeneEA** [comment] 2024-03-22 14:31
> Hi @Artemlin6231,
> 
> As you previously suggested, VEP is classifying the variant consequences as `feature_truncation` (`high` impact), when it should be assigned a less severe consequence, probably `intron_variant` (`modifier` impact).
> 
> The issue is currently in our backlog, but should be a small change and I will try to fix it soon. Sorry for the inconvenience.
> 
> Kind regards, Nuno

Hi, I've tested these variants (chr1:21459
[test.txt](https://github.com/Ensembl/ensembl-vep/files/14724014/test.txt)
928-21460197, chr1:24832213-24835018, chr1:57877552-57877863) with the latest VEP (release 112) and still get the `HIGH` score for them... here is a test vcf [test.txt](https://github.com/Ensembl/ensembl-vep/files/14724014/test.txt)

**Comment by EugeneEA** [comment] 2024-04-08 10:51
Hi @nuno-agostinho thanks a lot for the response, Indeed I'm getting the different results.
I build the docker container, using the https://github.com/Ensembl/ensembl-vep/blob/release/111/docker/Dockerfile
and changing the branch variable inside to `ARG BRANCH release/112` on line 27
was it incorrect?

**Comment by nuno-agostinho** [comment] 2024-04-08 16:00
Hi @EugeneEA,

Yes, that would be enough. Can you try creating the Docker image again (without cache) to check if it retrieves the latest version from that repo?

I tried it and everything is working.

Best,
Nuno

**Comment by nuno-agostinho** [comment] 2024-04-22 07:54
Hey @EugeneEA,

No need to apologise, we are here to help you!

Hopefully you got the Docker working correctly for you now. Tell me if there is any issue you face with this bug fix.

Have a wonderful day!

Cheers,
Nuno

**Comment by nuno-agostinho** [comment] 2024-06-25 09:58
Hi @Artemlin6231 and @EugeneEA,

The impact of the intron variant is now fixed in the released VEP 112 (https://github.com/Ensembl/ensembl-variation/pull/1041).

Hope that you got Docker to work correctly, @EugeneEA. Otherwise, you can always download the [latest Docker image for VEP 112](https://hub.docker.com/r/ensemblorg/ensembl-vep).

I will now close this issue has everything seems to be resolved. Please feel free to open a new issue in case you find new bugs or have any suggestions. Thank you both!

Cheers,
Nuno

**Closed by nuno-agostinho** 2024-06-25 09:58 UTC
