### ISSUE TITLE
VEP Docker: cannot write to FASTA lockfile

### ISSUE THREAD

**Issue by PimPolacko** [Ensembl/ensembl-vep#1041] opened 2021-08-25 06:46 UTC
I am using the Docker Container of VEP and trying to use that for annotation of a liftover database. I have a small input file with 4 entries, which I didn't yet manage to get annotated.
So now I am trying to test things more granular and tried one of the simple example commands from the documentation.
`./vep --cache -o stdout`
another test was with the addition of the cache directory
`./vep --cache dir_cache /opt/vep/.vep/ -o stdout`
I always get this error:
```
MSG: ERROR: Could not write to FASTA lock file /opt/vep/.vep/homo_sapiens/104_GRCh38/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz.vep.lock

STACK Bio::EnsEMBL::Variation::Utils::FastaSequence::_get_fasta_db /opt/vep/src/ensembl-vep/Bio/EnsEMBL/Variation/Utils/FastaSequence.pm:329
STACK Bio::EnsEMBL::Variation::Utils::FastaSequence::setup_fasta /opt/vep/src/ensembl-vep/Bio/EnsEMBL/Variation/Utils/FastaSequence.pm:212
STACK Bio::EnsEMBL::VEP::BaseVEP::fasta_db /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseVEP.pm:477
STACK Bio::EnsEMBL::VEP::Runner::init /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:134
STACK Bio::EnsEMBL::VEP::Runner::run /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:199
STACK toplevel ./vep:232
Date (localtime)    = Wed Aug 25 06:35:19 2021
Ensembl API version = 104
```

### System
- VEP Docker Container
- VEP version: 104
- VEP Cache version: 104
- Perl version: v5.26.1
- OS: Host = Ubuntu 20.04 VM
- tabix installed: yes

**Comment by at7** [comment] 2021-08-25 08:21
Hi @PimPolacko,
the error is usually caused by missing read/write access. In some linux distributions the Docker daemon requires root privileges (i.e. needs to prefix the command with sudo), which might cause read/write issues to the mounted volume.
One solution is to use the option :Z within the Docker -v option (only from docker 1.7.0). An other solution is to change the read/write access of the mounted volume ($HOME/vep_data). You can find instructions for how to do this [here](https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#docker). There is a section on `Read/Write access from the Docker container`.

Best regards,
Anja

**Comment by PimPolacko** [comment] 2021-08-25 08:22
I already changed all that and also tried with `sudo docker` to no avail.

**Comment by at7** [comment] 2021-08-25 08:49
Could you please send me your full docker command for running vep?

**Comment by PimPolacko** [comment] 2021-08-25 09:12
Sure:
`sudo docker run -t -i -v $HOME/vep_data:/opt/vep/.vep ensemblorg/ensembl-vep`

**Comment by at7** [comment] 2021-08-25 09:41
Thank you. That looks all good and you said that you tried with `:Z`. There might be a permission problem with the folder `homo_sapiens/104_GRCh38/`. Could you please run `chmod a+rwx $HOME/vep_data/homo_sapiens/104_GRCh38`?

Thank you,
Anja

**Comment by PimPolacko** [comment] 2021-08-25 12:44
OK, I have to admit I got fed up with the problem and decided to do the equivalent of the good old turning it off and on again. So I deleted essentially everything, Docker and cache etc and did a fresh download/install. That actually helped, but unfortunately I now have another problem. Should I open a new issue or can we continue here?

**Comment by at7** [comment] 2021-08-25 12:46
Please feel free to just continue and report your problem here.

**Comment by PimPolacko** [comment] 2021-08-25 12:54
Thanks, your help is really appreciated. But I have to warn you that the command I'm using now is the real deal, so it is packed with options and plugins. I run it as a perl script, which I will attach.
[run_vep_ens_hg38.zip](https://github.com/Ensembl/ensembl-vep/files/7047054/run_vep_ens_hg38.zip)

When I run this command including the `--offline` option, I get the following error:
```
WARNING: Failed to instantiate plugin dbNSFP: ERROR: Could not retrieve dbNSFP version from filename /opt/vep/.vep/Plugins/dbNSFP/dbNSFP.gz

WARNING: Failed to instantiate plugin GeneSplicer: ERROR: genesplicer binary not found


-------------------- EXCEPTION --------------------
MSG: ERROR: Cannot map to LRGs in offline mode

STACK Bio::EnsEMBL::VEP::Runner::post_setup_checks /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:744
STACK Bio::EnsEMBL::VEP::Runner::init /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:138
STACK Bio::EnsEMBL::VEP::Runner::run /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:199
STACK toplevel /opt/vep/src/ensembl-vep/vep:232
Date (localtime)    = Wed Aug 25 12:46:17 2021
Ensembl API version = 104
```

If I exclude the the  `--offline` option, I get the following error:
```
-------------------- EXCEPTION --------------------
MSG: ERROR: Assembly version specified by --assembly (GRCh38) and assembly version in coord_system table (GRCh37) do not match

 You can use --offline to avoid a database connection entirely

STACK Bio::EnsEMBL::VEP::BaseRunner::setup_db_connection /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:127
STACK Bio::EnsEMBL::VEP::Runner::init /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:123
STACK Bio::EnsEMBL::VEP::Runner::run /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:199
STACK toplevel /opt/vep/src/ensembl-vep/vep:232
Date (localtime)    = Wed Aug 25 12:48:11 2021
Ensembl API version = 104
```

**Comment by at7** [comment] 2021-08-25 16:40
The `--lrg` option requires a database connection. So as you already did you need to run without `--offline`. But from your command I could see that you are mixing up the two assemblies GRCh37 and GRCh38. If you work with GRCh38 you can omit the `--port 3337` flag.

The dbNSFP plugin requires that the dbNSFP version is part of the file name. Could you please update the dbNSFP file to dbNSFP4.1a.gz if for example you use version 4.1a. Remember to also update the name of the tabix file, dbNSFP4.1a.gz.tbi.

For the GeneSplicer error: Could you please check that `$HOME/vep_data/Plugins/GeneSplicer/sources/genesplicer` exists? It probably exists and I need to do some more checking why the error is thrown.

**Comment by PimPolacko** [comment] 2021-08-30 07:47
Sorry for not replying earlier, but I was in homeoffice and didnt't have access to the server.
I excluded `--port 3337` and changed dbNSFP.gz to dbNSFP3.5a.gz (same for tbi file).
I checked for the genesplicer binary and it does exist.
I wanted to do a check run, but the run got stuck and a rerun gave me this error:
```
-------------------- EXCEPTION --------------------
MSG: ERROR: Output file variant_effect_output.txt already exists. Specify a different output file with --output_file or overwrite existing file with --force_overwrite

STACK Bio::EnsEMBL::VEP::BaseRunner::get_output_file_handle /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:198
STACK Bio::EnsEMBL::VEP::Runner::run /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:201
STACK toplevel /opt/vep/src/ensembl-vep/vep:232
Date (localtime)    = Mon Aug 30 07:42:33 2021
Ensembl API version = 104
```
This is confusing me, as I have the `--output_file` option activated.

**Comment by at7** [comment] 2021-08-31 07:56
Your output file which you have specified with `--output_file` already exists. You need to tell VEP with `--force_overwrite` that it is ok to overwrite the file. So hopefully just adding `--force_overwrite` should fix the error.

**Comment by PimPolacko** [comment] 2021-08-31 08:23
Ok, I should've checked that earlier. After deleting the output file or changing the output name the docker vep tool gets stuck again. It just "runs" without finishing. If I abort the run nothing happens, no _warning.txt file in the output directory.
A rerun then shows the following error message:
```
-------------------- EXCEPTION --------------------
MSG: ERROR: Output file variant_effect_output.txt already exists. Specify a different output file with --output_file or overwrite existing file with --force_overwrite

STACK Bio::EnsEMBL::VEP::BaseRunner::get_output_file_handle /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:198
STACK Bio::EnsEMBL::VEP::Runner::run /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:201
STACK toplevel /opt/vep/src/ensembl-vep/vep:232
Date (localtime)    = Tue Aug 31 08:20:51 2021
Ensembl API version = 104
```
Which makes no sense, since I didn't specify the output file name to be "variant_effect_output.txt". It seems like vep is just writing an output file into `~/src/ensembl-vep` and ignoring my commands.

**Comment by at7** [comment] 2021-08-31 09:41
I did check you script again and I had to update a few things before I could run it successfully:
-- The call in the script needs to start with `system("docker run -t -i -v /your vep_data directory location/:/opt/vep/.vep ensemblorg/ensembl-vep ./vep \\
--species homo_sapiens \\...`
-- Also backticks didn't work for me and I replaced them with the system command
-- Finally I called the script from its actual location on my computer and didn't use the path from the docker volume
Maybe you could simplify your docker command and use only a few basic commands and then once it works can add back the options.
Here is how my system command looks:

From my updated script:
```
system("docker run -t -i -v $HOME/src/vep_issue_1041/:/opt/vep/.vep ensemblorg/ensembl-vep ./vep \\
--species homo_sapiens \\
--force_overwrite \\
--database \\
--assembly GRCh38 \\
--no_stats \\
--variant_class \\
--sift b \\
--polyphen b \\
--gene_phenotype \\
--total_length \\
--numbers \\
--domains \\
--hgvs \\
--hgvsg \\
--shift_hgvs 1 \\
--no_escape \\
--protein \\
--symbol \\
--ccds \\
--uniprot \\
--canonical \\
--biotype \\
--lrg \\
-i $opt_vepin \\
--output_file $opt_vepout ");
```
And then run the script
`cd $HOME/src/vep_issue_1041`
`perl run_vep_ens_hg38.pl /opt/vep/.vep/input/input.txt /opt/vep/.vep/output/hg38_test.txt`

**Comment by PimPolacko** [comment] 2021-08-31 11:21
Ok, to test a slimmed down version of the command, I copied your example and changed the path:
```
system("docker run -t -i -v /home/benedikt/vep_data/:/opt/vep/.vep ensemblorg/ensembl-vep ./vep \\
--species homo_sapiens \\
--force_overwrite \\
--database \\
--assembly GRCh38 \\
--no_stats \\
--variant_class \\
--sift b \\
--polyphen b \\
--gene_phenotype \\
--total_length \\
--numbers \\
--domains \\
--hgvs \\
--hgvsg \\
--shift_hgvs 1 \\
--no_escape \\
--protein \\
--symbol \\
--ccds \\
--uniprot \\
--canonical \\
--biotype \\
--lrg \\
-i $opt_vepin \\
--output_file $opt_vepout ");
```
The I run the script:
`perl ~/vep_data/scripts/test_vep.pl /opt/vep/.vep/input/vepin_hg38_testfile.txt /opt/vep/.vep/output/test_hg38.txt`

But the only thing I get ist:
```
IMPORTANT INFORMATION:

The VEP can read gene data from either a local cache or local/remote databases.

Using a cache is the fastest and most efficient way to use the VEP. The
included INSTALL.pl script can be used to fetch and set up cache files from the
Ensembl FTP server. Simply run "perl INSTALL.pl" and follow the instructions, or
see the documentation pages listed below.

If you have already set up a cache, use "--cache" or "--offline" to use it.

It is possible to use the public databases hosted at ensembldb.ensembl.org, but
this is slower than using the cache and concurrent and/or long running VEP jobs
can put strain on the Ensembl servers, limiting availability to other users.

To enable using databases, add the flag "--database".

Documentation
Installer: http://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#installer
Cache: http://www.ensembl.org/info/docs/tools/vep/script/index.html#cache

     at /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Config.pm line 699.
```

**Comment by at7** [comment] 2021-08-31 12:07
Could you please just run the docker command to see if that works?
It probably should be:
`docker run -t -i -v /home/benedikt/vep_data/:/opt/vep/.vep ensemblorg/ensembl-vep ./vep --database --id "rs699" --vcf --output_file /opt/vep/.vep/output/test_hg38.txt` and then check if the output file exists?

Thank you

**Comment by PimPolacko** [comment] 2021-08-31 12:27
Sure, I tried that "simple" command and it does work. I get a "test_hg38.txt" and a "test_hg38.txt_summary.html" file in the output folder.
Do you habe any idea, where vep or docker might have a problem?

**Comment by at7** [comment] 2021-08-31 14:36
It is good news that the docker command works. There seems to be a problem with the perl wrapper script. I will attach your script with the updates I made and it is working for me when I run it like this:
```
cd $HOME/vep_data
perl run_vep_ens_hg38_updated.pl /opt/vep/.vep/input/input.txt /opt/vep/.vep/output/hg38_test.txt
```
Please check that input and output directory exist in $HOME/vep_data.

Can you please try and run the script again? I will also attach my test input.

[run_vep_ens_hg38_updated.pl.zip](https://github.com/Ensembl/ensembl-vep/files/7084716/run_vep_ens_hg38_updated.pl.zip)
[input.txt.zip](https://github.com/Ensembl/ensembl-vep/files/7084701/input.txt.zip)

**Comment by PimPolacko** [comment] 2021-08-31 14:40
I will try that first thing tomorrow. Thanks again for the fantastic help.

**Comment by PimPolacko** [comment] 2021-09-01 09:44
Ok, I tried to add some lines and I didn't get far. The moment I change from `--database` to `--cache`, I get the message seen in my post above. 
https://github.com/Ensembl/ensembl-vep/issues/1041#issuecomment-909145124
This is weird because I installed it as shown in the documentation. It is in the following path: `$HOME/vep_data/homo_sapiens/104_GRCh38`
Attached you can find a .txt file showing the directory and files inside the cache directory.
[cache_directory_tree.txt](https://github.com/Ensembl/ensembl-vep/files/7089833/cache_directory_tree.txt)

**Comment by at7** [comment] 2021-09-01 10:44
Have you also added `--dir_cache $cachedir` back? Could you please share the updated list of options you are using now please? The VEP cache location looks all good to me.

Thank you

**Comment by PimPolacko** [comment] 2021-09-01 10:49
I tried with and without `--dir_cache $cachedir`, each time the same message.
```
system("docker run -t -i -v $ENV{HOME}/vep_data:/opt/vep/.vep ensemblorg/ensembl-vep ./vep \\
--fork $cores \\
--species homo_sapiens \\
--force_overwrite \\
#--database \\
--cache \\
--dir_cache $cachedir \\
--assembly GRCh38 \\
--no_stats \\
--variant_class \\
--sift b \\
--polyphen b \\
--gene_phenotype \\
--total_length \\
--numbers \\
--domains \\
--hgvs \\
--hgvsg \\
--shift_hgvs 1 \\
--no_escape \\
--protein \\
--symbol \\
--ccds \\
--uniprot \\
--canonical \\
--biotype \\
--lrg \\
-i $opt_vepin \\
--output_file $opt_vepout ");
```

**Comment by at7** [comment] 2021-09-01 11:05
The culprit is this line `#--database \\`. It must be interfering with the system command. Can you please delete the line and rerun the script?

**Comment by PimPolacko** [comment] 2021-09-01 12:45
I cannot thank you enough. I continued to add options and for the most part, it finally works.
There is just one option and 2 plugins that give some kind or error/message.
I will attach the perl script without the problematic entries here:
[run_vep_ens_hg38_test_change.zip](https://github.com/Ensembl/ensembl-vep/files/7091118/run_vep_ens_hg38_test_change.zip)
The input file is the same from here: https://github.com/Ensembl/ensembl-vep/issues/1041#issuecomment-909297188

`--format ensembl`
```
Use of uninitialized value $allele_string in pattern match (m//) at /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Parser/VEP_input.pm line 136, <__ANONIO__> line 2.
Use of uninitialized value $allele_string in hash element at /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Parser/VEP_input.pm line 147, <__ANONIO__> line 2.
Not a HASH reference at /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Parser.pm line 792, <__ANONIO__> line 2.
```
output file created, but empty except for header lines

`--plugin dbNSFP`
```
Use of uninitialized value $readme_file in concatenation (.) or string at /opt/vep/.vep/Plugins/dbNSFP.pm line 279.
```
output file created with entries

`--LOVD`
```
WARNING: 33 : Use of uninitialized value $gene in join or string at /opt/vep/.vep/Plugins/LOVD.pm line 114, <__ANONIO__> line 6.
Use of uninitialized value $acc in join or string at /opt/vep/.vep/Plugins/LOVD.pm line 114, <__ANONIO__> line 6.
Use of uninitialized value $dna in join or string at /opt/vep/.vep/Plugins/LOVD.pm line 114, <__ANONIO__> line 6.
```
output file created with entries, but also _warning.txt file

**Comment by at7** [comment] 2021-09-02 13:36
Hi,
I'm very happy that the setup is now working for you. Taking a look at the messages you now get.

-- For the dbNSFP message: this one is caused by a missing readme file in the directory where your dbNSFP is located. You should find a file called dbNSFP4.1a.readme.txt in the folder that you downloaded from the dbNSFP website (here it is for version 4.1a). Could you please copy the readme file into the same location as your dbNSFP file which you specify with the dbNSFP plugin command?

-- For the other two messages: this is most likely caused by using the wrong delimiter for the input file. If you are using still the input file I sent you then this file just uses spaces and if you specify the format with `--format ensembl` then the parser tries to separate by tab and not space. However, if you don't specify the format with `--format ensembl` then vep will identify the format and delimiter automatically and the error messages should go away. (Something to look into on our side and improve).

**Comment by PimPolacko** [comment] 2021-09-02 14:08
You were absolutely right. I added the  dbNSFP3.5a.readme.txt file and excluded `--format ensembl` and run the script without any issues. Weirdly enough, the `--plugin LOVD` was activated but didn't give any error.
I think I can finally say, that all my issues have been solved. Once again a huge thank you for your support.

**Comment by PimPolacko** [comment] 2021-09-07 14:26
I'm sorry to bother you again. After I tried the script with an initial real dataset, the LOVD errors showed up again. Here is the _warnings.txt:
[vep_INS_1_1000_out.txt_warnings.txt](https://github.com/Ensembl/ensembl-vep/files/7122230/vep_INS_1_1000_out.txt_warnings.txt)
Do you have any idea, what the problem is?
The input file looked like this:
[vep_INS_1_1000.txt](https://github.com/Ensembl/ensembl-vep/files/7122237/vep_INS_1_1000.txt)

**Comment by at7** [comment] 2021-09-08 08:30
Hi,
thank you for sending your input files. I was able to reproduce the problem. The warnings are caused by variants on LRGs. The LOVD plugin creates a malformed sequence name for LRG variants in the request to LOVD, and as a result we get back some empty values. We need to update the LOVD plugin accordingly. We will update you here when the plugin has been updated.
Best wishes,
Anja

**Comment by nuno-agostinho** [comment] 2022-04-05 15:34
Hi @PimPolacko,

I am happy to share with you that LOVD plugin will properly support LRG variants in release 107, so it seems all the issues you reported in this ticket were dealt with!

I'll close this ticket now, but do open a new one if you find any more problems. Thanks for your report!

All the best,
Nuno

**Closed by nuno-agostinho** 2022-04-05 15:34 UTC
Labels: docker/singularity
