### ISSUE TITLE
VEP runs out of RAM

### ISSUE THREAD

**Issue by danilovkiri** [Ensembl/ensembl-vep#804] opened 2020-07-14 15:59 UTC
## Describe the issue
I was able to run VEP on separate chromosome-specific VCFs with germline calls and REF HOM sites. However, once I decided to use custom annotation with PhyloP and PhastCons, I installed Bio::DB::BigFile as was requested by VEP interface. The installation of Bio::DB::BigFile caused a completely different approach to RAM memory usage. Now VEP uses all available 64GB of RAM and gets killed by the OS when trying to run on the same sets of VCF files which I was able to analyze successfully previously. Removing the `--custom` annotation arguments from CLI did not change the behaviour. Uninstallation of Bio::DB::BigFile did not have an effect either. Now I simply cannot run the tool which would be OK (and I would try to use another machine with terabytes of RAM) if I did not manage to run it previously.

## Additional information
The input VCF file contains 51M entries with 16M entries being non-HOM-REF. The memory usage grows within the first couple of minutes after running the command after the following message is displayed:
```
Will only load v100 databases
Species 'homo_sapiens' loaded from database 'homo_sapiens_core_100_38'
Species 'homo_sapiens' loaded from database 'homo_sapiens_cdna_100_38'
Species 'homo_sapiens' loaded from database 'homo_sapiens_otherfeatures_100_38'
Species 'homo_sapiens' loaded from database 'homo_sapiens_rnaseq_100_38'
homo_sapiens_variation_100_38 loaded
homo_sapiens_funcgen_100_38 loaded
No ancestral database found
No ontology database found
ensembl_taxonomy API not found - ignoring ncbi_taxonomy
Use of uninitialized value $ensembl_metadata_db in concatenation (.) or string at /home/wgs/Tools/ensembl-vep/Bio/EnsEMBL/Registry.pm line 2393.
ensembl_metadata API not found - ignoring
No production database or adaptor found
2020-07-14 18:45:36 - Auto-detected FASTA file in cache directory
WARNING: No input file format specified - detected vcf format
```

### System
- VEP version: 100 
- VEP Cache version: 100
- Perl version: 5.22.1
- OS: Ubuntu 16.04
- tabix installed YES

### Full VEP command line
```
/home/wgs/Tools/ensembl-vep/vep -i ./chr${chr}.vcf.gz -o ./chr${chr}.vep.txt.gz \
--canonical --mane --no_stats --tab --compress_output bgzip --sift b --polyphen b \
--gene_phenotype --regulatory --show_ref_allele --numbers --hgvs --hgvsg --symbol \
--protein --biotype --check_existing --af --af_gnomad --cache \
--force_overwrite -v
```

Any help is much appreciated.

**Comment by aparton** [comment] 2020-07-14 16:15
Hi @danilovkiri,

If you reduce the buffer size from the default of 5000 to 500 with the option `--buffer_size 500`, then it should resolve your issue. You can read more about the buffer_size option here: https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_buffer_size

If there's anything else we can do to help, please don't hesitate to ask.

Kind Regards,
Andrew

**Comment by danilovkiri** [comment] 2020-07-14 16:41
@aparton 

Thank you. I forgot to mention in the original post that I have tried this option (`--buffer_size 100`) and it does not have any influence on the memory usage at all. Besides, I did explicitly state that I was able to run VEP with the exact same arguments without specifying `--buffer_size` previously and it was OK. The memory usage roughly exceeded 3GB at that time. The only thing changed since then is the installation of Bio::DB::BigFile module.

**Comment by aparton** [comment] 2020-07-14 16:47
Hi @danilovkiri,

That's disappointing! I'll take a closer look to see if I can reproduce the error and get back to you when I've done so.

Can I check, was it version 100 that you used when the analysis was running successfully, or was it a previous version of VEP?

Kind Regards,
Andrew

**Comment by danilovkiri** [comment] 2020-07-14 16:51
Yes, it was the same version 100. Thank you.

**Comment by danilovkiri** [comment] 2020-07-14 21:44
Hi @aparton 

I've been running some test and found out that it has nothing to do with the Perl module. Sorry for misleading. The described memory-exhausting behaviour can be observed when running VEP on chr22-specific VCF file (also chr21, possibly several others). Some chromosome-specific VCF files are processed normally (e.g. chrX, chr11, chr18, chr1) with 2-3 GB RAM used per single Perl thread. I tried to find a specific variation which might be overlapping multiple features within chr22 but did not manage. I can share the chr22 VCF if necessary.

**Comment by aparton** [comment] 2020-07-15 16:00
Hi @danilovkiri,

I've been unable to reproduce this issue this afternoon, could you please send me a copy of your VCF file and I can take a closer look? You can either attach it to this issue, or email it to helpdesk@ensembl.org and I can pick it up from there.

Kind Regards,
Andrew

**Comment by danilovkiri** [comment] 2020-07-16 08:45
Hi @aparton 

Here is the [link](https://drive.google.com/file/d/13maEH1Vy_bxlsn7Zc2woaF7hM4RXCElV/view?usp=sharing). Thank you.

**Comment by danilovkiri** [comment] 2020-07-19 22:44
Hi @aparton 

Any news on the issue?

**Comment by aparton** [comment] 2020-07-20 11:05
HI @danilovkiri,

Nothing yet I'm afraid, we're still investigating. I'll let you know when I know more.

Kind Regards,
Andrew

**Comment by aparton** [comment] 2020-07-20 20:39
Hi @danilovkiri,

Thank you for your data file, I've been able to reproduce this issue this afternoon.

The issue is related to how VEP skips over invalid variants. In your data file, there are a collection of variants in the format `22 12345 . N .`, which VEP is unable to process without an alternate allele. VEP is recognising this, however it's moving onto the next variant without correctly disposing of the first, leading to the memory issues you're seeing. On occasions where there are a large quantity of invalid variants in a row then you're seeing this unwanted behaviour. 

I'll prepare a fix to prevent the excessive memory usage in this situation, however I'm unable to put a timeframe on when this will be available at this point.

I recommend sanitising your inputs to remove variants of this type, however you can workaround this issue by adding the flags `--allow_non_variant --dont_skip`, although this will print multiple warnings to screen when VEP is unable to process a variant as expected.

Kind Regards,
Andrew

**Comment by danilovkiri** [comment] 2020-07-21 09:17
@aparton Thank you so much!

**Comment by aparton** [comment] 2020-10-12 09:54
Hi,

I'm going to close this issue now. If you have any further questions, please feel free to reopen this issue or create a new one.

Kind Regards,
Andrew

**Closed by aparton** 2020-10-12 09:54 UTC

**Comment by yangyxt** [comment] 2022-01-15 03:18
Hi I just found my VEP command using tons of memory... with fork at 4. 
It's just insane that annotating a 1.5 Mb VCF file with around 30k variants would cause up to 200 GB peak memory....
I make sure my input vcf file is sorted bgzipped and tabix indexed.

And also I found that sometimes the top record more than 4 processes (like 6) derived by the vep and here is the screenshot:
![image](https://user-images.githubusercontent.com/40780228/149606866-8ec78be3-7f24-4397-9988-553259539b21.png)

For your reference, the original commands are shown below:
`vep -i input.vcf.gz \
	--format vcf \
	--use_given_ref \
	--assembly GRCh37 \
	--cache \
	--fork 4 \
	--buffer_size 3000 \
	--fasta /paedyl01/disk1/yangyxt/indexed_genome/ucsc.hg19.fasta ${mode} \
	--dir_cache /paedyl01/disk1/yangyxt/public_data/ensembl-vep/caches \
	--tab \
	--verbose \
	--dir_plugins /paedyl01/disk1/yangyxt/ngs_scripts/UTRannotator,/paedyl01/disk1/yangyxt/ngs_scripts/loftee,/paedyl01/disk1/yangyxt/ngs_scripts/VEP_plugins \
	-plugin LoF,loftee_path:/paedyl01/disk1/yangyxt/ngs_scripts/loftee,fast_length_calculation:slow,human_ancestor_fa:${human_ancestor_file},conservation_file:${conservation_file} \
	-plugin UTRannotator,/paedyl01/disk1/yangyxt/ngs_scripts/UTRannotator/uORF_5UTR_GRCh37_PUBLIC.txt \
	--custom ${vep_gerp_score},GERP,bigwig \
	--force_overwrite \
	--no_check_variants_order \
	-o vepoutput`

**Comment by yangyxt** [comment] 2022-01-17 02:38
> Hi I just found my VEP command using tons of memory... with fork at 4. It's just insane that annotating a 1.5 Mb VCF file with around 30k variants would cause up to 200 GB peak memory.... I make sure my input vcf file is sorted bgzipped and tabix indexed.
> 
> And also I found that sometimes the top record more than 4 processes (like 6) derived by the vep and here is the screenshot: ![image](https://user-images.githubusercontent.com/40780228/149606866-8ec78be3-7f24-4397-9988-553259539b21.png)
> 
> For your reference, the original commands are shown below: `vep -i input.vcf.gz --format vcf --use_given_ref --assembly GRCh37 --cache --fork 4 --buffer_size 3000 --fasta /paedyl01/disk1/yangyxt/indexed_genome/ucsc.hg19.fasta ${mode} --dir_cache /paedyl01/disk1/yangyxt/public_data/ensembl-vep/caches --tab --verbose --dir_plugins /paedyl01/disk1/yangyxt/ngs_scripts/UTRannotator,/paedyl01/disk1/yangyxt/ngs_scripts/loftee,/paedyl01/disk1/yangyxt/ngs_scripts/VEP_plugins -plugin LoF,loftee_path:/paedyl01/disk1/yangyxt/ngs_scripts/loftee,fast_length_calculation:slow,human_ancestor_fa:${human_ancestor_file},conservation_file:${conservation_file} -plugin UTRannotator,/paedyl01/disk1/yangyxt/ngs_scripts/UTRannotator/uORF_5UTR_GRCh37_PUBLIC.txt --custom ${vep_gerp_score},GERP,bigwig --force_overwrite --no_check_variants_order -o vepoutput`

Just to add more info here, I adjust the buffer size, from 100 to 1000, still, every time the trial ends with memory leakage, where I allow maximum 100 GB RAM usage. I also decrease the fork number from 4 to 2 and the memory still is not enough.

**Comment by nakib103** [comment] 2022-01-17 16:17
Hello @yangyxt ,

Thank you for your queries!

Can you try running in `--offline` mode if that resolves your issue?

I could not reproduce your issue. Can you please share -
- the input file and custom annotated file you are using
- the value of the variables so that I can have the exact command you are trying
- which version of VEP you are using?

Also, here you will find some ways you can run VEP faster - 
https://asia.ensembl.org/info/docs/tools/vep/script/vep_other.html#faster

**Comment by yangyxt** [comment] 2022-01-18 07:33
Hi, Thank you for the reply. I already run in offline mode but failed to paste the argument here. 

Any way I found the issue here. After I remove the custom annotation with a GERP bigwig file, using your conservation score plugin instead. The memory leakage does not happen again.

**Comment by nakib103** [comment] 2022-01-19 08:13
Hi @yangyxt ,

It is great to hear that you have solved the issue! Please feel free to reach us if you face any further issues in the future. 

Best regards,
Nakib

**Comment by aiqc** [comment] 2023-07-21 01:08
I just watched VEP chew through 30GB of RAM and crash.

I tried using `--allow_non_variant --dont_skip`, but it just kept leaking.

The weird part is that I have used this version of VEP (109), cache (109), and the same VCF file on a different computer with modest RAM... but that shouldn't matter because I am using Docker

**Comment by aiqc** [comment] 2023-07-21 01:11
I just watched VEP chew through 30GB of RAM (allocated to Docker) and crash. Whatever limit I set, it increases up until that point and crashes.

I tried using `--allow_non_variant --dont_skip`, but it just kept leaking.

The weird part is that I have used this version of VEP (109), cache (109), and the same VCF file on a different computer with modest RAM... but that shouldn't matter because I am using Docker.

The only weird thing to note is these warnings  when the container starts

```
Unknown option: no_update
Ignoring unsupported option 'no_update' found via ENV variable or INI file
Unknown option: no_htslib
Ignoring unsupported option 'no_htslib' found via ENV variable or INI file
Unknown option: pluginsdir
Ignoring unsupported option 'pluginsdir' found via ENV variable or INI file
Unknown option: no_plugins
Ignoring unsupported option 'no_plugins' found via ENV variable or INI file
```

**Comment by nakib103** [comment] 2023-07-21 16:49
@aiqc, thanks for pointing out the the memory advantage in using indexed cache over non-indexed cache.

We support non-indexed format as it does not require installation of htslib. But the documentation mention both indexed and non-indexed cache file links and points out that human and species with large variant data should used tabixed format. See - 
https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#cache

Can you share the link that pointed you to `current_variation` folder - maybe that part is not verbose enough.

Best regards,
Nakib
