### ISSUE TITLE
VEP crashing when retrieving display_codon when using --no_stats

### ISSUE THREAD

**Issue by david-a-parry** [Ensembl/ensembl-vep#818] opened 2020-07-31 14:13 UTC
## Describe the issue
When running VEP with the --no_stats and --everything flags it crashes when encountering a specific multiallelic variant. VEP processed several million variants prior to the problem variant, so it seems like an edge case. The test file provided contains the problem variant.

Running without the --no_stats flag solves the problem, so there is an easy workaround, but thought this probably worth reporting. Decomposing the variants into separate records also seems to avoid this issue. 

### System
- VEP version: 100.4
- VEP Cache version: 100
- Perl version: 5.30.0
- OS: Ubuntu 20.04
- tabix installed: yes

### Full VEP command line
```
./vep --input_file test_input.vcf.gz --vcf  --offline --no_stats --everything --assembly GRCh38
```

### Full error message
> substr outside of string at <path_omitted>/ensembl-vep/Bio/EnsEMBL/Variation/TranscriptVariationAllele.pm line 906, <$fh> line 3.
Use of uninitialized value in uc at  <path_omitted>/ensembl-vep/Bio/EnsEMBL/Variation/TranscriptVariationAllele.pm line 906, <$fh> line 3.
substr outside of string at  <path_omitted>/ensembl-vep/Bio/EnsEMBL/Variation/TranscriptVariationAllele.pm line 906, <$fh> line 3.

### Data files (if applicable)
They include:
- The input file
[test_input.vcf.gz](https://github.com/Ensembl/ensembl-vep/files/5007399/test_input.vcf.gz)

**Comment by aparton** [comment] 2020-07-31 14:26
Hi @david-a-parry,

Thanks for letting us know. I've been able to reproduce this issue, and I'll take a look at getting a fix in place. I'll let you know when we have a solution prepared.

Kind Regards,
Andrew

**Comment by a1aks** [comment] 2020-10-10 14:31
Has this been fixed?

My error is: 

Use of uninitialized value in addition (+) at /Users/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/Cache/VariationTabix.pm line 184, <VARS> line 1.
substr outside of string at /Users/ensembl-vep/Bio/EnsEMBL/Variation/TranscriptVariationAllele.pm line 906.
Died in forked process 34464

Furthermore:

ERROR: Failed to run the VEP annotator! Command: /Users/perl5/perlbrew/perls/5.26.2/bin/perl /Users/ensembl-vep/vep --species homo_sapiens --assembly GRCh38 --no_progress --no_stats --buffer_size 5000 --sift b --ccds --uniprot --hgvs --symbol --numbers --domains --gene_phenotype --canonical --protein --biotype --uniprot --tsl --variant_class --shift_hgvs 1 --check_existing --total_length --allele_number --no_escape --xref_refseq --failed 1 --vcf --flag_pick_allele --pick_order canonical,tsl,biotype,rank,ccds,length --dir /Users/ensembl-vep/downloaded_GRcH38/ --fasta /Users/ensembl-vep/downloaded_GRcH38/homo_sapiens/101_GRCh38/Homo_sapiens.GRCh38.dna.toplevel.fa --format vcf --input_file /Users/blahBlah.vcf --output_file /Users/blahBlah.vep.vcf --offline --pubmed --fork 4 --polyphen b --af --af_1kg --af_esp --af_gnomad --regulatory

**Comment by aparton** [comment] 2020-10-12 09:52
Hi @a1aks,

Unfortunately we do not currently have a fix in place for this issue. As a workaround, if you run VEP without the `--no_stats` flag then this should allow you to carry on with your analyses in the meantime.

Kind Regards,
Andrew

**Comment by a1aks** [comment] 2020-10-16 13:21
Hi Andrew,

Thank you for responding in such short notice. I had done the following especially "commenting the loop at line 900-906" in the TranscriptVariationAllele.pm file. Attached Screenshot.

After this it worked fine for me and I was able to discovery more variants in a single exon. I should and will use the --no_stats flag in the next set of samples and see how the results look like. 

Kind regards, 

Akshay

<img width="1005" alt="Screenshot 2020-10-16 at 8 19 18 AM" src="https://user-images.githubusercontent.com/814170/96263159-4dca3b00-0f88-11eb-81c9-c7db7e5676a1.png">

**Comment by Stikus** [comment] 2021-07-05 12:06
Any news about fix? We have encountered this issues in approx 2% of our runs.
```
substr outside of string at /soft/ensembl-vep-104.3/Bio/EnsEMBL/Variation/TranscriptVariationAllele.pm line 906, <$fh> line 2757660.
Died in forked process 10571
```

Furthermore - sometimes this error kills our docker container, sometimes just hangs it (and we manually kill it), cannot find any pattern.

**Comment by aparton** [comment] 2021-07-05 12:33
Hi @Stikus,

Unfortunately we do not have a fix in place for this issue yet. As a workaround, running your VEP command without the `--no_stats` option enabled should prevent this issue from happening in the short term.

Please let me know if there's anything else we can do to help.

Kind Regards,
Andrew

**Comment by matthdsm** [comment] 2022-06-17 05:25
Hi, 
Sorry to hammer this home, but we're running into the same issue since our update to v105. Any updates? This seems like a long standing issue.

Thanks

**Comment by nuno-agostinho** [comment] 2024-09-06 10:48
Hi @david-a-parry, @a1aks, @Stikus, @matthdsm,

I am going to close this issue given that I cannot reproduce this issue in newer versions of VEP.

If you are still facing similar problems in newer versions of VEP, please reply here with a reproducible example.  Sorry for the inconvenience.

Best,
Nuno

**Closed by nuno-agostinho** 2024-09-06 10:48 UTC
