### ISSUE TITLE
VEP 109.1 INSTALL.pl cannot install Ensembl API

### ISSUE THREAD

**Issue by Stikus** [Ensembl/ensembl-vep#1354] opened 2023-02-13 12:53 UTC
## Describe the issue
`INSTALL.pl` trying to download nonexistent link.

### System
- VEP version: 109.1
- VEP Cache version: 109
- Perl version: 5.26.1
- OS: Ubuntu 18.04
- tabix installed

### Full command line
```
perl INSTALL.pl --NO_TEST --NO_UPDATE --NO_HTSLIB --NO_BIOPERL -a ap --PLUGINSDIR "$SOFT/ensembl-vep-${VEP_VERSION}/Plugins" --PLUGINS ProteinSeqs,Downstream,Conservation,GO,G2P,CADD
```

### Full error message
```
#14 93.12 Downloading required Ensembl API files
#14 93.12  - fetching ensembl
#14 94.14 curl failed (404), trying to fetch using LWP::Simple
#14 97.31 LWP::Simple failed (404), trying to fetch using HTTP::Tiny
#14 99.10 ERROR: Failed last resort of using HTTP::Tiny to download https://github.com/Ensembl/ensembl/archive/release/109.1.zip

```

##### `VEP 107` install log (part)
```
#14 83.31 Downloading required Ensembl API files
#14 83.31  - fetching ensembl
#14 87.02  - unpacking ./Bio/tmp/ensembl.zip
#14 87.32  - moving files
#14 87.32  - getting version information
#14 88.00  - fetching ensembl-variation
#14 94.40  - unpacking ./Bio/tmp/ensembl-variation.zip
#14 94.95  - moving files
#14 94.95  - getting version information
#14 95.71  - fetching ensembl-funcgen
#14 97.07  - unpacking ./Bio/tmp/ensembl-funcgen.zip
#14 97.21  - moving files
#14 97.21  - getting version information
#14 98.82  - fetching ensembl-io
#14 100.3  - unpacking ./Bio/tmp/ensembl-io.zip
#14 100.4  - moving files
#14 100.4  - getting version information
#14 101.6 
```

##### `VEP 108` install log (part)
```
Downloading required Ensembl API files
 - fetching ensembl
 - unpacking ./Bio/tmp/ensembl.zip
 - moving files
 - getting version information
 - fetching ensembl-variation
 - unpacking ./Bio/tmp/ensembl-variation.zip
 - moving files
 - getting version information
 - fetching ensembl-funcgen
 - unpacking ./Bio/tmp/ensembl-funcgen.zip
 - moving files
 - getting version information
 - fetching ensembl-io
 - unpacking ./Bio/tmp/ensembl-io.zip
 - moving files
 - getting version information
```

Looks like this [line](https://github.com/Ensembl/ensembl-vep/blob/release/109/INSTALL.pl#L744) constructs URL:
```perl
my $url = $ENS_GIT_ROOT.$module.$ensembl_url_tail.$release_url_string.$archive_type;
```
`$release_url_string` equals `release/109.1`
```perl
my $release_url_string = looks_like_number($API_VERSION) ? 'release/'.$API_VERSION : $API_VERSION;
```
`$API_VERSION` equals `109.1`

Looks like before this release `$API_VERSION` was major version, without minor.

**Comment by nakib103** [comment] 2023-02-13 13:23
Hi @Stikus ,

Thanks for your query.

I could not re-produce the issue. The api download should not use the 109.1 version. Can you check the following - 
- What version you find in the following directory - 
```
cat ensembl-vep/.version/ensembl
```
- Do you have any env variable with name `$API_VERSION` that have 109.1 version as value, can you check - 
```
echo $API_VERSION
```

Best regards,
Nakib

**Comment by Stikus** [comment] 2023-02-13 14:10
Ye, I'm pretty sure that `$VEP_VERSION` causing problems:
```sh
root@8000e0e59f45:/soft/ensembl-vep-109.1# export VEP_VERSION=109.1                                                                                             
root@8000e0e59f45:/soft/ensembl-vep-109.1# perl INSTALL.pl --NO_TEST --NO_UPDATE --NO_HTSLIB --NO_BIOPERL -a ap --PLUGINSDIR "$SOFT/ensembl-vep-${VEP_VERSION}
/Plugins" --PLUGINS ProteinSeqs,Downstream,Conservation,GO,G2P,CADD                                                                                           
                                                                                                                                                              
Setting up directories                                                                                                                                        
                                                                                                                                                              
Downloading required Ensembl API files                                                                                                                        
 - fetching ensembl                                                                                                                                           
curl failed (404), trying to fetch using LWP::Simple                                                                                                          
LWP::Simple failed (404), trying to fetch using HTTP::Tiny                                                                                                    
ERROR: Failed last resort of using HTTP::Tiny to download https://github.com/Ensembl/ensembl/archive/release/109.1.zip              
``` 

```sh
root@8000e0e59f45:/soft/ensembl-vep-109.1# export VEP_VERSION=109                                                                                             
root@8000e0e59f45:/soft/ensembl-vep-109.1# perl INSTALL.pl --NO_TEST --NO_UPDATE --NO_HTSLIB --NO_BIOPERL -a ap --PLUGINSDIR "$SOFT/ensembl-vep-${VEP_VERSION}
/Plugins" --PLUGINS ProteinSeqs,Downstream,Conservation,GO,G2P,CADD                                                                                           
                                                                                                                                                              
Setting up directories                                                                                                                                        
                                                                                                                                                              
Downloading required Ensembl API files                                                                                                                        
 - fetching ensembl                                                                                                                                           
 - unpacking ./Bio/tmp/ensembl.zip                                                                                                                            
 - moving files                                                                                                                                               
 - getting version information                                                                                                                                
 - fetching ensembl-variation                                                                                                                                 
^C                                                                                                                                                            
```

**Comment by nakib103** [comment] 2023-02-13 15:42
Thanks @Stikus for the details. Yes, unfortunately install script is picking up the `VEP_VERSION` environment variable value and assigning it to `API_VERSION` which should not.

Current workaround is to not use `VEP_VERSION` or `VERSION` in the environment variable. We will give a fix for this shortly.

**Comment by Stikus** [comment] 2023-02-14 07:10
Thanks for quick response, I saw your PR and have a question:

I'm not very good in perl, but I think this [line](https://github.com/Ensembl/ensembl-vep/blob/release/109/INSTALL.pl#L257) is causing problems:
```perl
$API_VERSION  ||= $CURRENT_VERSION_DATA->{$VEP_MODULE_NAME}->{release};
```
Not this [line](https://github.com/Ensembl/ensembl-vep/blob/release/109/INSTALL.pl#L201):
```perl
$API_VERSION  ||=  $config->{VERSION};
```

Simple because we have both `$VERSION` and `$VEP_VERSION` environmental variables (`$VEPSION` is our modified tool version and it is different - `1.10.0` for example), but `VEP` tries to download exactly `$VEP_VERSION`.

**Comment by nakib103** [comment] 2023-02-14 09:13
Hi @Stikus,

Actually it is the `$API_VERSION  ||=  $config->{VERSION};` line that is causing the problem. This assignment to `$API_VERSION` is done earlier and take precedence. And the issue is actually happening because we need converting all the VEP variables and use them.

The other line (`$API_VERSION  ||= $CURRENT_VERSION_DATA->{$VEP_MODULE_NAME}->{release};`) won't be causing any issue as it only takes the major version and not the minor one.

**Comment by Stikus** [comment] 2023-02-14 09:28
Ok, I definitely can be wrong, but I was confused due to `$API_VERSION` was assigned to `109.1` (our env `$VEP_VERSION`) and not to `1.10.0` (our env `$VERSION`).

If you checked and this lines now working - all good:
```sh
export VEP_VERSION=109.1                                                                                             
perl INSTALL.pl --NO_TEST --NO_UPDATE --NO_HTSLIB --NO_BIOPERL -a ap --PLUGINSDIR "$SOFT/ensembl-vep-${VEP_VERSION}/Plugins" --PLUGINS ProteinSeqs,Downstream,Conservation,GO,G2P,CADD
```

**Closed** 2023-02-15 09:16 UTC
