### ISSUE TITLE
Haplosaurus fails to process stop gain variant in start of transcript

### ISSUE THREAD

**Issue by sveint** [Ensembl/ensembl-vep#1291] opened 2022-10-28 10:31 UTC
## Describe the issue
Haplosaurus fails to process a vcf if it contains variants generating very short matching sequences, in this case a stop gained variant in the very beginning of the transcript, leading to amino acid sequence being a single stop codon. A stop gain at the next amino acid position would seemingly also create the same issue.

## Additional information

The error `Can't call method "each_seq" on an undefined value` (see more below) happens here:
https://github.com/Ensembl/ensembl-variation/blob/release/108/modules/Bio/EnsEMBL/Variation/TranscriptHaplotype.pm#L451

`undefined` comes from here:
https://github.com/Ensembl/ensembl-variation/blob/release/108/modules/Bio/EnsEMBL/Variation/TranscriptHaplotype.pm#L507

Due to dpAlign.pairwise_alignment given here, returning `undefined` as the sequence is below length of 2:
https://metacpan.org/release/CJFIELDS/BioPerl-1.6.924/source/Bio/Tools/dpAlign.pm#L438

### System
- VEP version: 98
- VEP Cache version: 98
- Perl version: v5.16.3
- OS: CentOS7 in Docker
- tabix installed: yes

### Full VEP command line
```
./haplo -i input.vcf -o output.txt -gtf Homo_sapiens.GRCh38.90.sorted.gtf.gz -fasta Homo_sapiens.GRCh38.dna.genome.fa
```

### Full error message

The error message provided is the following:
```
--------------------- WARNING ---------------------
MSG: cannot align sequences with length less than 2
---------------------------------------------------
Can't call method "each_seq" on an undefined value at /software/ensembl-vep-98/ensembl-variation/modules/Bio/EnsEMBL/Variation/TranscriptHaplotype.pm
```

In addition, adding a few prints to see what the sequences were:
```
reference_seq: MTVSTDNLLVNKAISKSGQLPTSSNLEANISCSLNELTYNNLPANENQNLKEQNQTEKSLKSPSDTLDGRNENLQESEILSQPKSLSLEATSPLSAEKHSCTVPEGLLFPAEYYVRTTRSMSNCQRKVAVEAVIQSHLDVKKKGFKNKNKDASKNLNLSNEETDQSEIRMSGTCTGQPSSRTSQKLLSLTKVSSPAGPTEDNDLSRKAVAQAPGRRYTGKRKSACTPASDHCEPLLPTSSLSIVNRSKEEVTSHKYQHEKLFIQVKGKKSRHQKEDSLSWSNSAYLSLDDDAFTAPFHRDGMLSLKQLLSFLSITDFQLPDEDFGPLKLEKVKSCSEKPVEPFESKMFGERHLKEGSCIFPEELSPKRMDTEMEDLEEDLIVLPGKSHPKRPNSQSQHTKTGLSSSILLYTPLNTVAPDDNDRPTTDMCSPAFPILGTTPAFGPQGSYEKASTEVAGRTCCTPQLAHLKDSVCLASDTKQFDSSGSPAKPHTTLQVSGRQGQPTCDCDSVPPGTPPPIESFTFKENQLCRNTCQELHKHSVEQTETAELPASDSINPGNLQLVSELKNPSGSCSVDVSAMFWERAGCKEPCIITACEDVVSLWKALDAWQWEKLYTWHFAEVPVLQIVPVPDVYNLVCVALGNLEIREIRALFCSSDDESEKQVLLKSGNIKAVLGLTKRRLVSSSGTLSDQQVEVMTFAEDGGGKENQFLMPPEETILTFAEVQGMQEALLGTTIMNNIVIWNLKTGQLLKKMHIDDSYQASVCHKAYSEMGLLFIVLSHPCAKESESLRSPVFQLIVINPKTTLSVGVMLYCLPPGQAGRFLEGDVKDHCAAAILTSGTIAIWDLLLGQCTALLPPVSDQHWSFVKWSGTDSHLLAGQKDGNIFVYHYS* at /software/ensembl-vep-98/ensembl-variation/modules/Bio/EnsEMBL/Variation/TranscriptHaplotype.pm line 508, <__ANONIO__> line 51.
seq: * at /software/ensembl-vep-98/ensembl-variation/modules/Bio/EnsEMBL/Variation/TranscriptHaplotype.pm line 509, <__ANONIO__> line 51.
```

### Data files (if applicable)

Reproducible case:
```
##fileformat=VCFv4.2
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	T1
16	23635659	.	AT	A	.	.	.	GT	1/1
```

**Comment by diegomscoelho** [comment] 2022-10-28 14:42
Hi @sveint,

I was not able to reproduce your error. Can you provide me a link to your gtf and fasta? - Besides that, are you using VEP version 98? - If yes, can you test using version 108?

I used VEP version 108 with your VCF input + GTF (https://ftp.ensembl.org/pub/release-108/gtf/homo_sapiens/) + Fasta (https://ftp.ensembl.org/pub/release-108/fasta/homo_sapiens/dna/). Got this as result:

```sh
ENST00000261584 ENST00000261584:886delA frameshift,indel        ENSP00000261584:296del{891}     indel           .       T1:2
ENST00000568219 ENST00000568219:1delA   frameshift,indel        ENSP00000454703:1del{891}       indel           .       T1:2
ENST00000697374 ENST00000697374:1delA   frameshift,indel        ENSP00000513284:1del{891}       indel           .       T1:2
ENST00000697376 ENST00000697376:1delA   frameshift,indel        ENSP00000513285:1del{776}       indel           .       T1:2
ENST00000697377 ENST00000697377:1delA   frameshift,indel        ENSP00000513286:1del{837}       indel           .       T1:2
ENST00000561514 ENST00000561514:1delA   frameshift,indel        ENSP00000460666:1del{891}       indel           .       T1:2
ENST00000697379 ENST00000697379:1delA   frameshift,indel        ENSP00000513287:1del{891}       indel           .       T1:2
```

**Comment by diegomscoelho** [comment] 2022-11-14 09:35
Hi @sveint,

I'm closing this issue now. If you still have a question, please, feel free to comment here and I will reopen this issue for you.

Regards, @diegomscoelho

**Closed by diegomscoelho** 2022-11-14 09:35 UTC

**Comment by rrlove-cdc** [comment] 2023-11-07 22:44
I am having the same problem using a non-human species. Please let me know if I should move this to a separate issue:

## Describe the issue
VEP fails with the error message "Can't call method "each_seq" on an undefined value at \<path>ensembl-vep/Bio/EnsEMBL/Variation/TranscriptHaplotype.pm line 451, <__ANONIO__> line 75759."

Immediately preceding this is the warning "MSG: cannot align sequences with length less than 2."

The variant in question appears to delete a start codon.

## Additional information
Please fill in the following sections to help us find the source of your issue as quickly as possible.

### System
- VEP version: 110.1 
- VEP Cache version: 57 (this is the most recent release of Ensembl Metazoa)
- Perl version: v5.16.3
- OS: CentOS
- tabix installed ? Yes

### Full VEP command line
```
~/ensembl-vep/haplo \
-i inputs/haplosaurus_test.vcf \
-o outputs/haplosaurus_test.110723.txt \
--species anopheles_gambiae \
--cache \
--cache_version 57 \
--offline
```

### Full error message
\--------------------- WARNING ---------------------
MSG: cannot align sequences with length less than 2
\---------------------------------------------------
Can't call method "each_seq" on an undefined value at \<path>ensembl-vep/Bio/EnsEMBL/Variation/TranscriptHaplotype.pm line 451, <__ANONIO__> line 27.

### Data files (if applicable)

Contents of haplosaurus_test.vcf:

```
##fileformat=VCFv4.1
##fileDate=20231018
#CHROM  POS     ID      REF     ALT     QUAL    INFO    FILTER  FORMAT  samp1        samp2
3L      19867099        .       AT      A       13577.1 .       .       GT      1|1     0|1
```

**Comment by dglemos** [comment] 2023-11-08 09:26
Hi @rrlove-cdc,
Can you please create a new issue?
Thanks
