### ISSUE TITLE
Annotation of Manta VCF files

### ISSUE THREAD

**Issue by lindakohn** [Ensembl/ensembl-vep#437] opened 2019-04-17 11:06 UTC
I am using VEP to annotate SVs from Manta vcf files. For the translocations (MantaBND) only the first reported chr region gets a gene annoation. Is there a way to get gene annotations for both chromosomes involved in the translocation?

**Comment by dglemos** [comment] 2019-04-17 14:32
Hi @lindakohn,
could you provide an example of your input vcf and the vep command you used to run it.

**Comment by lindakohn** [comment] 2019-04-17 16:40
Below is an example of my input, which is actually a vcf without the header and the vep command:

vep --cache --dir $VEP_CACHE --tab --offline --assembly GRCh38 --format vcf --fork 4 --everything -i ${file}.txt -o ${file}_vep.txt

[manta.txt](https://github.com/Ensembl/ensembl-vep/files/3090582/manta.txt)

And the resulting output:

[manta_vep.txt](https://github.com/Ensembl/ensembl-vep/files/3090628/manta_vep.txt)

**Comment by lindakohn** [comment] 2019-04-18 08:04
Sorry, I see now that Manta actually reports breakend translocations on double rows so 'chr14 85914438' comes further down a second row, which means that it gets a gene annotatation by VEP. Sorry, my bad...

**Comment by dglemos** [comment] 2019-04-18 09:13
I'm glad that the problem is solved. I'm going to close this ticket, feel free to open if you have other questions.

**Closed** 2019-04-18 09:13 UTC
