### ISSUE TITLE
Changes in transcript names between VEP 106 and 108 

### ISSUE THREAD

**Issue by Stikus** [Ensembl/ensembl-vep#1350] opened 2023-02-09 11:32 UTC
## Describe the issue
Between `VEP 106` and `VEP 108` transcript names changed in mutated fasta (provided by plugin `ProteinSeq.pm`)

## Additional information
According to our analysis, transcript named in `VEP 106` were correct (e.g. `Leu288dup`) due to Leucine duplication and new names from `VEP 108` (e.g. `Leu288_Ala289insPhe`) are incorrect. We digged into plugin update (associated with https://github.com/Ensembl/VEP_plugins/issues/536) but found nothing about naming. Looks like [this line](https://github.com/Ensembl/VEP_plugins/blob/release/109/ProteinSeqs.pm#L113) is responsible for naming, and it comes from `VEP` itself (maybe cache), but not from plugin - that's why the issue is here.

### System
- VEP version: 108.2
- VEP Cache version: 108
- Perl version: 5.26.1
- OS: Ubuntu 18.04
- tabix installed

### Full VEP command line
```
/soft/ensembl-vep-108.2/vep --fork 32 --input_file /inputs/input.vcf --format vcf --cache --dir_cache /ref/.vep --dir_plugins /soft/ensembl-vep-108.2/Plugins --assembly GRCh37 --offline --output_file /outputs/test1.annot-vep.vcf --vcf --force_overwrite --symbol --check_existing --terms SO --tsl --hgvs --hgvsg --transcript_version  --plugin Frameshift --plugin Wildtype    --no_stats --plugin ProteinSeqs,/outputs/test1.annot-vep.reference.fa,/outputs/test1.annot-vep.mutated.fa
```

##### Difference between `reference.fa` and `mutated.fa (VEP 106)`
![image](https://user-images.githubusercontent.com/41360525/217795422-8bcc1091-e095-4108-8958-69fb7ab3181b.png)

##### Difference between `mutated.fa (VEP 106)` and `mutated.fa (VEP 108)` - `diff` result
```
1c1
< >ENSP00000233809.4:p.Leu21_Leu22insArgCys
---
> >ENSP00000233809.4:p.Leu21_Leu22insProLeu
49c49
< >ENSP00000335185.6:p.Leu288_Ala289insPhe
---
> >ENSP00000335185.6:p.Leu288dup
55c55
< >ENSP00000377803.1:p.Leu248_Ala249insPhe
---
> >ENSP00000377803.1:p.Leu248dup
61c61
< >ENSP00000377806.1:p.Leu288_Ala289insPhe
---
> >ENSP00000377806.1:p.Leu288dup
67c67
< >ENSP00000404911.1:p.Leu288_Ala289insPhe
---
> >ENSP00000404911.1:p.Leu288dup
```
##### Difference between `mutated.fa (VEP 106)` and `mutated.fa (VEP 108)` - visual compare
![image](https://user-images.githubusercontent.com/41360525/217794943-7e6328e0-5067-4be1-b860-b609e2fb8d8e.png)

##### `reference.fa` (part):
```
>ENSP00000335185
MSVQNSGWPHQEDSPKPQDPGPPANSDSDSGHLPGEDPEDTHAQGPAVLSLGSLCLDTNQAPNWTGLQTLLQQLPPQDID
ERYCLALGEEERAELQLFCARRKQEALGQGVARLVLPKLEGHTCEKCRELLKPGEYGVFAARAGEQRCWHQPCFACQACG
QALINLIYFYHDGQLYCGRHHAELLRPRCPACDQLIFSWRCTEAEGQRWHENHFCCQDCAGPLGGGRYALPGGSPCCPSC
FENRYSDAGSSWAGALEGQAFLGETGLDRTEGRDQTSVNSATLSRTLLAAAGGSSLQTQRGLPGSSPQQENRPGDKAEAP
KGQEQCRLETIRDPKDTPFSTCSSSSDSEPEGFFLGERLPQSWKTPGSLQAEDSNASKTHCTMC
>ENSP00000377803
MSPQGPAVLSLGSLCLDTNQAPNWTGLQTLLQQLPPQDIDERYCLALGEEERAELQLFCARRKQEALGQGVARLVLPKLE
GHTCEKCRELLKPGEYGVFAARAGEQRCWHQPCFACQACGQALINLIYFYHDGQLYCGRHHAELLRPRCPACDQLIFSWR
CTEAEGQRWHENHFCCQDCAGPLGGGRYALPGGSPCCPSCFENRYSDAGSSWAGALEGQAFLGETGLDRTEGRDQTSVNS
ATLSRTLLAAAGGSSLQTQRGLPGSSPQQENRPGDKAEAPKGQEQCRLETIRDPKDTPFSTCSSSSDSEPEGFFLGERLP
QSWKTPGSLQAEDSNASKTHCTMC
>ENSP00000377806
MSVQNSGWPHQEDSPKPQDPGPPANSDSDSGHLPGEDPEDTHAQGPAVLSLGSLCLDTNQAPNWTGLQTLLQQLPPQDID
ERYCLALGEEERAELQLFCARRKQEALGQGVARLVLPKLEGHTCEKCRELLKPGEYGVFAARAGEQRCWHQPCFACQACG
QALINLIYFYHDGQLYCGRHHAELLRPRCPACDQLIFSWRCTEAEGQRWHENHFCCQDCAGPLGGGRYALPGGSPCCPSC
FENRYSDAGSSWAGALEGQAFLGETGLDRTEGRDQTSVNSATLSRTLLAAAGGSSLQTQRGLPGSSPQQENRPGDKAEAP
KGQEQCRLETIRDPKDTPFSTCSSSSDSEPEGFFLGERLPQSWKTPGSLQAEDSNASKTHCTMC
>ENSP00000404911
MSVQNSGWPHQEDSPKPQDPGPPANSDSDSGHLPGEDPEDTHAQGPAVLSLGSLCLDTNQAPNWTGLQTLLQQLPPQDID
ERYCLALGEEERAELQLFCARRKQEALGQGVARLVLPKLEGHTCEKCRELLKPGEYGVFAARAGEQRCWHQPCFACQACG
QALINLIYFYHDGQLYCGRHHAELLRPRCPACDQLIFSWRCTEAEGQRWHENHFCCQDCAGPLGGGRYALPGGSPCCPSC
FENRYSDAGSSWAGALEGQAFLGETGLDRTEGRDQTSVNSATLSRTLLAAAGGSSLQTQRGLPGSSPQQENRPGDKAEAP
KGQEQCRLETIRDPKDTPFSTCSSSSDSEPEGFFLGERLPQSWKTPGSLQAEDSNASKTHCTMC
```

##### `mutated.fa` (part, `VEP 106`):
```
>ENSP00000335185.6:p.Leu288dup
MSVQNSGWPHQEDSPKPQDPGPPANSDSDSGHLPGEDPEDTHAQGPAVLSLGSLCLDTNQAPNWTGLQTLLQQLPPQDID
ERYCLALGEEERAELQLFCARRKQEALGQGVARLVLPKLEGHTCEKCRELLKPGEYGVFAARAGEQRCWHQPCFACQACG
QALINLIYFYHDGQLYCGRHHAELLRPRCPACDQLIFSWRCTEAEGQRWHENHFCCQDCAGPLGGGRYALPGGSPCCPSC
FENRYSDAGSSWAGALEGQAFLGETGLDRTEGRDQTSVNSATLSRTLLLAAAGGSSLQTQRGLPGSSPQQENRPGDKAEA
PKGQEQCRLETIRDPKDTPFSTCSSSSDSEPEGFFLGERLPQSWKTPGSLQAEDSNASKTHCTMC
>ENSP00000377803.1:p.Leu248dup
MSPQGPAVLSLGSLCLDTNQAPNWTGLQTLLQQLPPQDIDERYCLALGEEERAELQLFCARRKQEALGQGVARLVLPKLE
GHTCEKCRELLKPGEYGVFAARAGEQRCWHQPCFACQACGQALINLIYFYHDGQLYCGRHHAELLRPRCPACDQLIFSWR
CTEAEGQRWHENHFCCQDCAGPLGGGRYALPGGSPCCPSCFENRYSDAGSSWAGALEGQAFLGETGLDRTEGRDQTSVNS
ATLSRTLLLAAAGGSSLQTQRGLPGSSPQQENRPGDKAEAPKGQEQCRLETIRDPKDTPFSTCSSSSDSEPEGFFLGERL
PQSWKTPGSLQAEDSNASKTHCTMC
>ENSP00000377806.1:p.Leu288dup
MSVQNSGWPHQEDSPKPQDPGPPANSDSDSGHLPGEDPEDTHAQGPAVLSLGSLCLDTNQAPNWTGLQTLLQQLPPQDID
ERYCLALGEEERAELQLFCARRKQEALGQGVARLVLPKLEGHTCEKCRELLKPGEYGVFAARAGEQRCWHQPCFACQACG
QALINLIYFYHDGQLYCGRHHAELLRPRCPACDQLIFSWRCTEAEGQRWHENHFCCQDCAGPLGGGRYALPGGSPCCPSC
FENRYSDAGSSWAGALEGQAFLGETGLDRTEGRDQTSVNSATLSRTLLLAAAGGSSLQTQRGLPGSSPQQENRPGDKAEA
PKGQEQCRLETIRDPKDTPFSTCSSSSDSEPEGFFLGERLPQSWKTPGSLQAEDSNASKTHCTMC
>ENSP00000404911.1:p.Leu288dup
MSVQNSGWPHQEDSPKPQDPGPPANSDSDSGHLPGEDPEDTHAQGPAVLSLGSLCLDTNQAPNWTGLQTLLQQLPPQDID
ERYCLALGEEERAELQLFCARRKQEALGQGVARLVLPKLEGHTCEKCRELLKPGEYGVFAARAGEQRCWHQPCFACQACG
QALINLIYFYHDGQLYCGRHHAELLRPRCPACDQLIFSWRCTEAEGQRWHENHFCCQDCAGPLGGGRYALPGGSPCCPSC
FENRYSDAGSSWAGALEGQAFLGETGLDRTEGRDQTSVNSATLSRTLLLAAAGGSSLQTQRGLPGSSPQQENRPGDKAEA
PKGQEQCRLETIRDPKDTPFSTCSSSSDSEPEGFFLGERLPQSWKTPGSLQAEDSNASKTHCTMC
```

##### `mutated.fa` (part, `VEP 108`):
```
>ENSP00000335185.6:p.Leu288_Ala289insPhe
MSVQNSGWPHQEDSPKPQDPGPPANSDSDSGHLPGEDPEDTHAQGPAVLSLGSLCLDTNQAPNWTGLQTLLQQLPPQDID
ERYCLALGEEERAELQLFCARRKQEALGQGVARLVLPKLEGHTCEKCRELLKPGEYGVFAARAGEQRCWHQPCFACQACG
QALINLIYFYHDGQLYCGRHHAELLRPRCPACDQLIFSWRCTEAEGQRWHENHFCCQDCAGPLGGGRYALPGGSPCCPSC
FENRYSDAGSSWAGALEGQAFLGETGLDRTEGRDQTSVNSATLSRTLLLAAAGGSSLQTQRGLPGSSPQQENRPGDKAEA
PKGQEQCRLETIRDPKDTPFSTCSSSSDSEPEGFFLGERLPQSWKTPGSLQAEDSNASKTHCTMC
>ENSP00000377803.1:p.Leu248_Ala249insPhe
MSPQGPAVLSLGSLCLDTNQAPNWTGLQTLLQQLPPQDIDERYCLALGEEERAELQLFCARRKQEALGQGVARLVLPKLE
GHTCEKCRELLKPGEYGVFAARAGEQRCWHQPCFACQACGQALINLIYFYHDGQLYCGRHHAELLRPRCPACDQLIFSWR
CTEAEGQRWHENHFCCQDCAGPLGGGRYALPGGSPCCPSCFENRYSDAGSSWAGALEGQAFLGETGLDRTEGRDQTSVNS
ATLSRTLLLAAAGGSSLQTQRGLPGSSPQQENRPGDKAEAPKGQEQCRLETIRDPKDTPFSTCSSSSDSEPEGFFLGERL
PQSWKTPGSLQAEDSNASKTHCTMC
>ENSP00000377806.1:p.Leu288_Ala289insPhe
MSVQNSGWPHQEDSPKPQDPGPPANSDSDSGHLPGEDPEDTHAQGPAVLSLGSLCLDTNQAPNWTGLQTLLQQLPPQDID
ERYCLALGEEERAELQLFCARRKQEALGQGVARLVLPKLEGHTCEKCRELLKPGEYGVFAARAGEQRCWHQPCFACQACG
QALINLIYFYHDGQLYCGRHHAELLRPRCPACDQLIFSWRCTEAEGQRWHENHFCCQDCAGPLGGGRYALPGGSPCCPSC
FENRYSDAGSSWAGALEGQAFLGETGLDRTEGRDQTSVNSATLSRTLLLAAAGGSSLQTQRGLPGSSPQQENRPGDKAEA
PKGQEQCRLETIRDPKDTPFSTCSSSSDSEPEGFFLGERLPQSWKTPGSLQAEDSNASKTHCTMC
>ENSP00000404911.1:p.Leu288_Ala289insPhe
MSVQNSGWPHQEDSPKPQDPGPPANSDSDSGHLPGEDPEDTHAQGPAVLSLGSLCLDTNQAPNWTGLQTLLQQLPPQDID
ERYCLALGEEERAELQLFCARRKQEALGQGVARLVLPKLEGHTCEKCRELLKPGEYGVFAARAGEQRCWHQPCFACQACG
QALINLIYFYHDGQLYCGRHHAELLRPRCPACDQLIFSWRCTEAEGQRWHENHFCCQDCAGPLGGGRYALPGGSPCCPSC
FENRYSDAGSSWAGALEGQAFLGETGLDRTEGRDQTSVNSATLSRTLLLAAAGGSSLQTQRGLPGSSPQQENRPGDKAEA
PKGQEQCRLETIRDPKDTPFSTCSSSSDSEPEGFFLGERLPQSWKTPGSLQAEDSNASKTHCTMC
```

Attaching input.vcf as input.txt:
[input.txt](https://github.com/Ensembl/ensembl-vep/files/10696631/input.txt)

**Comment by likhitha-surapaneni** [comment] 2023-02-10 13:06
Hi @Stikus ,

Thank you for providing us a detailed report. We are trying to investigate the differences between both the versions which might have resulted in this difference in outputs. I was wondering if you also had to provide a reference FASTA file while running VEP as the option `--hgvs` relies on FASTA file when running with `--cache` or `--offline` options (https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_hgvs). If yes, can you please provide us with the reference file used? 

Kind regards,
Likhitha

**Comment by Stikus** [comment] 2023-02-10 13:45
Thanks for answer.
According to your link:

- Add genomic [HGVS](https://varnomen.hgvs.org/) nomenclature based on the input chromosome name. To generate HGVS identifiers when using [--cache](https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_cache) or [--offline](https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_offline) you must use a FASTA file and [--fasta](https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_fasta). Not used by default

As you can see in our command line - we do not use `--fasta` key (as far as I remember, we stopped using it many releases ago).

According to [docs](https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#fasta):

- FASTA files can be set up using the [installer](https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#installer); files set up using the installer are automatically detected by VEP when using [--cache](https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_cache) or [--offline](https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_offline); you should not need to use [--fasta](https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_fasta) to manually specify them.

So - my answer is: we don't use any custom fasta - only default, installed by VEP: `Homo_sapiens.GRCh37.75.dna.primary_assembly.fa.gz` in this case (`GRCh37`)

**Comment by likhitha-surapaneni** [comment] 2023-02-10 16:07
Hi @Stikus ,  
Thank you for your response.

We have run some tests on our end but unfortunately, could not reproduce different outputs for different versions. However, we notice some inconsistencies producing the `HGVSp` in VEP output and `mutated.fa` which might have caused the above issue. We are going to work on this further to fix it and will let you know once we have an update.

**Comment by Stikus** [comment] 2023-02-13 09:03
We've downloaded `VEP 107` to test the origin of this problem:

Here are the differences:
##### Difference between `mutated.fa` (`VEP 106`) and `mutated.fa` (`VEP 107`)
![image](https://user-images.githubusercontent.com/41360525/218411998-9718ee97-df67-42ce-ab4f-bbb3ef2c2535.png)
##### Difference between `reference.fa` and `mutated.fa` (`VEP 106`)
![image](https://user-images.githubusercontent.com/41360525/218414266-80b7e897-1f11-4086-b2c3-f15a6fb71554.png)

As you can see - naming problems appears in `VEP 107` already and naming in `VEP 106` seems correct (this is definitely not `Leu21_Leu22insArgCys` in `MLPRVGCPALPLPPPPLLPLLPLLLLLGASGGGGG`)

**Comment by Stikus** [comment] 2023-02-15 14:39
I've tested new `109` version - same result as `107` and `108` - FYI.

I've found one interesting thing - as you can see in this [issue comment](https://github.com/Ensembl/ensembl-vep/issues/1152#issuecomment-1118191444) - `106 GRCh38 VEP Cache` have dates `28-Feb-2022` but now:  
![image](https://user-images.githubusercontent.com/41360525/219057678-bafd2f74-0efe-4d78-ad80-04e6a9c1504c.png)  
`2022-07-01` - something changed? But [last 106 release](https://github.com/Ensembl/ensembl-vep/releases/tag/release%2F106.1) is dated `Apr 19, 2022`.

For now, I'm trying to look into [differences](https://github.com/Ensembl/ensembl-vep/compare/release/106.1...release/107.0#diff-b759a02f1be263ec97e5322e43db3b5f3c2c476ae37a8eaecc3e19554e3f3b2f) between `VEP 106` and `VEP 107` - trying to find code changes leading to current issue.

**Comment by Stikus** [comment] 2023-02-16 15:34
Our debug showed, that exactly one file change leads to this issue:
https://github.com/Ensembl/ensembl-variation/compare/release/106...release/107

![image](https://user-images.githubusercontent.com/41360525/219412416-8414ada0-b779-4e1a-a77e-ab6ece2f17d7.png)

If we use `VEP 106` docker image and swap this file from `VEP 107` - we have incorrect naming.

**Comment by dglemos** [comment] 2023-02-21 15:41
Hi @Stikus,
By default, VEP enables the flag `--shift_hgvs 1` however the code update you mention above affected the behaviour of this flag. We are working on a fix but in the meantime, the workaround is to run VEP with `--shift_hgvs 0`.

**Comment by likhitha-surapaneni** [comment] 2023-02-28 11:47
Hi @Stikus , 

Thank you for your patience. We have provided a fix and will be available in the next release (110). In the meantime, vep can be run with the option `--shift_hgvs 0`.

I am closing the ticket for now. Please feel free to open a new ticket if there are any further issues.

**Closed by likhitha-surapaneni** 2023-02-28 11:47 UTC
Labels: bug

**Comment by Stikus** [comment] 2023-02-28 13:26
We've tested `--shift_hgvs 0` - notation fixed, but there is small difference in `fasta`:  
![image](https://user-images.githubusercontent.com/41360525/221865168-0e033c10-2f1d-496e-bbef-31763db94116.png)

And a LOT of differences in `VCF` (and they seem correct):
![image](https://user-images.githubusercontent.com/41360525/221867209-705fb588-6802-4d45-bc3a-d510315cfec7.png)

**Comment by likhitha-surapaneni** [comment] 2023-03-01 10:49
Hi @Stikus ,

Thank you for the details provided.

Please note that the flag `shift_hgvs `is not an optimal solution - it’s just a temporary fix to get the same hgvs protein notation until we have a permanent fix in place for the upcoming release. The difference in VCF files with and without `shift_hgvs` enabled seems to be expected. As per the [description](https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#ident), when `shift_hgvs 0` option is provided,  3' shifting is disabled hence causing the differences in the hgvs notation between the two files. Regarding the different in the fasta sequence outputted by the plugin we’re going to have a look to understand what is happening and keep you updated on this.

Kind regards,
Likhitha

**Comment by serge2016** [comment] 2023-06-02 10:09
Dear @likhitha-surapaneni,
What about slightly different fasta sequences?

**Comment by Stikus** [comment] 2023-07-20 15:33
@likhitha-surapaneni release 110 finally here and we got nearly same results as with 109.3.

We still have `-` symbol in mutated `fasta`:
![image](https://github.com/Ensembl/ensembl-vep/assets/41360525/a0e60d5f-87b8-4762-9cad-7d805ee11ca0)

Why is it here?

Although we got several dozens of strange warnings we don't have before:
```
Use of uninitialized value in subtraction (-) at /soft/ensembl-vep-110.0/Bio/EnsEMBL/Variation/TranscriptVariationAllele.pm line 2187, <__ANONIO__> line 86.
Use of uninitialized value $preseq in substr at /soft/ensembl-vep-110.0/Bio/EnsEMBL/Variation/TranscriptVariationAllele.pm line 2187, <__ANONIO__> line 86.
```
Maybe you can give us a hint?
