### ISSUE TITLE
Analysis stop for some reason and then all variants were classified as "intergenic_variant"

### ISSUE THREAD

**Issue by arthurmelobio** [Ensembl/ensembl-vep#72] opened 2017-08-29 18:11 UTC
Hi, 
I have tried to functionally annotate SNPs using a own genome sequence fasta file as well the GTF file. The chromosome that I'm work with has ~712Mb. The annotation works normally until ~536Mb and then all others variants (11,524) called from 536Mb to 712 Mb were classified as "intergenic_variant". Something is not working correctly for the variantes called in the final part of the chromosome because the GTF file has features for these positions.

The input files used are:
VCF:
`##fileformat=VCFv4.0`
`#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO`
`chr5B	262960	.	T	C	.	.	.`
`chr5B	304590	.	G	A	.	.	.`
`chr5B	1255408	.	G	C	.	.	.`
`...`
`chr5B	536855576	.	A	G	.	.	.`
`chr5B	536855606	.	G	C	.	.	.`
`chr5B	536855648	.	A	G	.	.	.`
`...`
`chr5B	712003535	.	C	T	.	.	.`
`chr5B	712045694	.	C	A	.	.	.`
`chr5B	712045876	.	C	G	.	.	.`

GTF:
`chr5B	WEWseq_PGSB_v1	3UTR	74131	74468	.	-	.	"gene_id ""TRIDC5BG000010""; transcript_id ""TRIDC5BG000010.1""; gene_biotype ""expansin B2""";`
`chr5B	WEWseq_PGSB_v1	exon	74131	74895	.	-	.	"gene_id ""TRIDC5BG000010""; transcript_id ""TRIDC5BG000010.1""; gene_biotype ""expansin B2""";`
`chr5B	WEWseq_PGSB_v1	transcript	74131	74895	.	-	.	"gene_id ""TRIDC5BG000010""; transcript_id ""TRIDC5BG000010.1""; gene_biotype ""expansin B2""";`
`...`
`chr5B	WEWseq_PGSB_v1	3UTR	536786164	536786364	.	-	.	"gene_id ""TRIDC5BG055110""; transcript_id ""TRIDC5BG055110.1""; gene_biotype ""Histone superfamily protein""";`
`chr5B	WEWseq_PGSB_v1	CDS	536786365	536786763	.	-	0	"gene_id ""TRIDC5BG055110""; transcript_id ""TRIDC5BG055110.1""; gene_biotype ""Histone superfamily protein""";`
`chr5B	WEWseq_PGSB_v1	5UTR	536786764	536786765	.	-	.	"gene_id ""TRIDC5BG055110""; transcript_id ""TRIDC5BG055110.1""; gene_biotype ""Histone superfamily protein""";`
`...`
`chr5B	WEWseq_PGSB_v1	exon	712160383	712160875	.	+	.	"gene_id ""TRIDC5BG084350""; transcript_id ""TRIDC5BG084350.1""; gene_biotype ""Cytochrome c biogenesis Fc""";`
`chr5B	WEWseq_PGSB_v1	transcript	712160383	712160875	.	+	.	"gene_id ""TRIDC5BG084350""; transcript_id ""TRIDC5BG084350.1""; gene_biotype ""Cytochrome c biogenesis Fc""";`
`chr5B	WEWseq_PGSB_v1	CDS	712160606	712160875	.	+	0	"gene_id ""TRIDC5BG084350""; transcript_id ""TRIDC5BG084350.1""; gene_biotype ""Cytochrome c biogenesis Fc""";`

I have double checked a lot of things such chromosome names, tab-delimited and I can't see any inconsistence between files that I'm using and the format required for VEP.

Could someone help me to understand why all variants after the position 536,779,806 are assigned as "intergenic_variant".

Thank you.
Best,
Arthur

**Comment by sarahhunt** [comment] 2017-08-30 10:47
Hi @arthurmelobio,

It sounds like your installation of the code is fine if you are seeing the results you expect for the majority of the data, so I would suspect there is a problem with the files.

Is the fasta sequence definitely longer than 536Mb?

I see you are not specifying transcript biotypes, which could cause strange results, but this would impact all transcripts.

Can you supply full GTF data for a successful and a unsuccessful gene for comparison?

**Comment by arthurmelobio** [comment] 2017-08-30 15:49
Dear @sarahhunt,

Thank you very much 

for your replay.

Yes, the fasta sequence has 712.18 Mb.

Please, see the VEP input files (VCF, GTF and FASTA) as well the VEP output on link below:

https://www.dropbox.com/s/v7kc6v2c16l7h2t/VEP_Files.tar.gz?dl=0

Let's focus on these variants positions, so far. 

`##fileformat=VCFv4.0`
`##FILTER=<ID=PASS,Description="All filters passed">`
`##contig=<ID=chr5B,length=712180895>`
`##bcftools_viewVersion=1.2+htslib-1.2.1`
`#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO`
`chr5B	536779806	.	T	C	8.79264	.	.`
`chr5B	536855576	.	A	G	11.4963	.	.`
`chr5B	536912360	.	G	A	6.32957	.	.`
`chr5B	537255517	.	A	C	15.603	.	.`
`chr5B	537810799	.	A	G	8.07144	.	.`

The position 536779806 was the last successful annotated... VEP output line 52328. The next 536855576 seems "intergenic_variants" once we don't have features on GFT file for this position. The 1th problem that I can see is the pos 536912360. The GTF file for this regions looks like

`chr5B	WEWseq_PGSB_v1	five_prime_UTR	536911134	536911298	.	+	.	"gene_id ""TRIDC5BG055130""; transcript_id ""TRIDC5BG055130.2""; gene_name ""Protein of unknown function (DUF594)"""`
`chr5B	WEWseq_PGSB_v1	exon	536911134	536913920	.	+	.	"gene_id ""TRIDC5BG055130""; transcript_id ""TRIDC5BG055130.1""; gene_name ""Protein of unknown function (DUF594)"""`
`chr5B	WEWseq_PGSB_v1	exon	536911134	536913920	.	+	.	"gene_id ""TRIDC5BG055130""; transcript_id ""TRIDC5BG055130.2""; gene_name ""Protein of unknown function (DUF594)"""`

This is an example that I cannot understand why the variant was assigned as "intergenic_variants".
Any thought is really appreciated.

Thank you.
Best,
Arthur

**Comment by sarahhunt** [comment] 2017-08-31 12:59
Hi @arthurmelobio,

Thanks for the useful test data. We use tabix to extract the sequence features from GTF and the problem is that your sequence is longer than the default index can handle. You can specify a different indexing strategy like this:

tabix --csi -p gff Ref.annot.5B.gtf.gz

then the full file will be indexed and VEP can access all features. 

Best wishes,

Sarah

**Comment by arthurmelobio** [comment] 2017-09-01 15:39
Hi @sarahhunt,

Thank you very much for your answer.

One of our first thought was about memory and length of these files. So, I tried split both the GTF and VCF files but it still not working.

This tabix command doesn't fixed the problem. Even using it the analysis is stopping in the same moment. The key to solve this is the FASTA file! I simple divided the whole chromosome based on centromeric region, getting the short and long arm. So, all analysis was executed separately for each arm and it seems works well.

Thank you a lot for the help.

Best,
Arthur

**Comment by sarahhunt** [comment] 2017-09-01 16:26
Hi @arthurmelobio ,

Thanks for letting us know you've got it working!

All the best,
Sarah

**Closed by sarahhunt** 2017-09-01 16:26 UTC
