### ISSUE TITLE
Terrible Cache Data download speed 

### ISSUE THREAD

**Issue by MattWellie** [Ensembl/ensembl-vep#1501] opened 2023-09-18 07:40 UTC
## Describe the issue

I am trying to download the indexed Homo Sapiens GRCh38 cache files 

`https://ftp.ensembl.org/pub/release-110/variation/indexed_vep_cache/homo_sapiens_vep_110_GRCh38.tar.gz`

I have access to the FTP site to browse, but downloading appears to be capped at 233KB. This data would take a day and a half to download...

I am accessing from Australia, and have tried from my local machine and from a GCP instance; D/L speeds of both are garbage. 

Are there any mirrors of this data in GCP/AWS which I could attempt to access, or are there any possible issues I can troubleshoot to hit more feasible speeds. 

I tried the following and it got the target data size... then died with the 405 error without transferring a Byte . This was the same for other files on the same FTP site. A `curl` for the `https://` prefixed file path was working, but very slowly.

```bash
curl -O ftp://ftp.ensembl.org/pub/release-110/variation/indexed_vep_cache/homo_sapiens_vep_110_GRCh38.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0 19.7G    0     0    0     0      0      0 --:--:--  0:01:05 --:--:--     0
curl: (19) RETR response: 425
```

Not sure if this is at all similar to the issue #1494

This issue also seems to be experienced by some other users around the world
https://www.biostars.org/p/461523

**Comment by nakib103** [comment] 2023-09-19 08:22
Hi @MattWellie,

Thanks for your query!

Can you try using [Globus](https://www.globus.org/) to download the cache file as mentioned here -
https://www.ensembl.org/info/data/ftp/index.html

It should be significantly faster.

Best regards,
Nakib

**Comment by MattWellie** [comment] 2023-09-19 23:44
This data doesn't appear to be accessible via Globus

<img width="1590" alt="Screenshot 2023-09-20 at 9 42 50 am" src="https://github.com/Ensembl/ensembl-vep/assets/5886855/5f20e51b-7dd6-4ed8-a219-f273106996a8">

**Comment by MattWellie** [comment] 2023-09-20 03:05
Hold that thought, there appears to be two Globus projects

**Comment by nakib103** [comment] 2023-09-20 08:01
![image](https://github.com/Ensembl/ensembl-vep/assets/12125986/cda5c06d-38e0-436f-ab4d-3521f02096ed)

It would be the second one with `ebi.ac.uk` email. I just checked and also face the same issue that you mentioned but it seems to be transient. If you click "Try again" it just works.

**Comment by MattWellie** [comment] 2023-09-21 00:14
Sorry for banging on, but Globus is even slower than FTP... Surely there's a better way

<img width="292" alt="Screenshot 2023-09-21 at 10 12 43 am" src="https://github.com/Ensembl/ensembl-vep/assets/5886855/56138d34-4729-424e-87f7-d5dd48440664">

**Comment by rachitk** [comment] 2023-09-21 18:07
I would like to confirm that from the East Coast of the USA, I am consistently seeing download speeds of ~200KB/s - ~600KB/s when trying to download the VEP caches.

**Comment by barslmn** [comment] 2023-09-22 06:34
I had around ~700KB/s max while downloading from main ftp server.

**Comment by nakib103** [comment] 2023-09-22 11:22
We have contacted our internal network team and they are going to check about this issue. I will get back to you once I hear back from them.

**Comment by nakib103** [comment] 2023-10-02 12:47
Hello,

We get received reply from the our network team. They were unable re-produce the issue and confirmed no speed restriction is applied on their side. Are you still seeing the same speed at your end? If so, please can you check your network settings with your provider/institution about this issue.

Also, here is public docs regarding using Globus which might be helpful - 
https://embl.service-now.com/kb?id=kb_article_view&sysparm_article=KB0011060

Best regards,
Nakib

**Comment by nakib103** [comment] 2023-10-30 11:26
Hi,
I am closing this issue. If you face further problem feel free to open a new one.

Best regards,
Nakib

**Closed by nakib103** 2023-10-30 11:26 UTC

**Comment by lwtan90** [comment] 2024-01-25 00:53
Is it possible to host these cache files on AWS? It is a whooping 14 hours download time!
