### ISSUE TITLE
wrong indexed cache file on ftp server 

### ISSUE THREAD

**Issue by stefandiederich** [Ensembl/ensembl-vep#1165] opened 2022-04-25 13:55 UTC
Hi,
I just installed VEP version 106.1 and downloaded the indexed cache file for grch37 from `http://ftp.ensembl.org/pub/grch37/release-106/variation/indexed_vep_cache/homo_sapiens_vep_106_GRCh37.tar.gz`. By 'untaring' I saw that the folder is version 105. So there migth be some error with the uploaded file, or did I miss something?

Bests 
Stefan

**Comment by dglemos** [comment] 2022-04-25 14:02
Hi @stefandiederich,
We are having problems with the cache files for GRCh37 in the public FTP. 
As there are no updates in release 106 for assembly GRCh37 could you please use the version from 105 for now?

**Comment by davmlaw** [comment] 2022-05-27 02:38
Hi, I believe this is a dupe of https://github.com/Ensembl/ensembl-vep/issues/1152 and has since been resolved

**Comment by dglemos** [comment] 2022-05-27 06:57
Thanks for pointing it out, this issue is the same as #1152 
In the meantime, we have fixed the human GRCh37 cache files. You can find the files for release 106 under:
http://ftp.ensembl.org/pub/grch37/release-106/variation/indexed_vep_cache/
http://ftp.ensembl.org/pub/release-106/variation/indexed_vep_cache/

**Closed by dglemos** 2022-05-27 06:57 UTC
