### ISSUE TITLE
Substr outside of string in TranscriptVariationAllele.pm line 906

### ISSUE THREAD

**Issue by ckandoth** [Ensembl/ensembl-vep#1013] opened 2021-06-23 00:21 UTC
Same as issue #1006 but now with details on how to reproduce.

### System
- VEP version: 102.0
- VEP Cache version: 102
- Perl version: 5.26.2
- OS: Ubuntu
- tabix is installed

### Full VEP command line
```
~/mambaforge/bin/vep --species homo_sapiens --assembly GRCh38 --no_progress --no_stats --buffer_size 5000 --sift b --ccds --uniprot --hgvs --symbol --numbers --domains --gene_phenotype --canonical --protein --biotype --uniprot --tsl --variant_class --shift_hgvs 1 --check_existing --total_length --allele_number --no_escape --xref_refseq --failed 1 --vcf --flag_pick_allele --pick_order canonical,tsl,biotype,rank,ccds,length --dir /home/ckandoth/.vep --fasta /ngs/ref/GCA_000001405.15_GRCh38_full_plus_hs38d1_analysis_set.fna --format vcf --input_file test.vcf --output_file ./test.vep.vcf --force_overwrite --offline --pubmed --polyphen b --af --af_1kg --af_esp --af_gnomad --regulatory
```

### Full error message
```
Possible precedence issue with control flow operator at /home/ckandoth/mambaforge/lib/site_perl/5.26.2/Bio/DB/IndexedBase.pm line 805.
substr outside of string at /home/ckandoth/mambaforge/share/ensembl-vep-102.0-0/Bio/EnsEMBL/Variation/TranscriptVariationAllele.pm line 906, <__ANONIO__> line 3.
Use of uninitialized value in uc at /home/ckandoth/mambaforge/share/ensembl-vep-102.0-0/Bio/EnsEMBL/Variation/TranscriptVariationAllele.pm line 906, <__ANONIO__> line 3.
substr outside of string at /home/ckandoth/mambaforge/share/ensembl-vep-102.0-0/Bio/EnsEMBL/Variation/TranscriptVariationAllele.pm line 906, <__ANONIO__> line 3.
```

### Input VCF
```bash
##fileformat=VCFv4.2
##reference=GRCh38
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	TUMOR
chr10	80081665	rs113172526	C	CAA,CA	2482.52	PASS	.	GT:AD:DP	0/1:17,0,25:42
```

Based on the allele depths above, the `GT` field should really be `0/2`. I don't know if that is causing the VEP error. The error does not occur if the two ALT alleles are split into separate VCF lines:
```bash
##fileformat=VCFv4.2
##reference=GRCh38
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	TUMOR
chr10	80081665	rs113172526	C	CAA	2482.52	PASS	.	GT:AD:DP	0/0:17,0:42
chr10	80081665	rs113172526	C	CA	2482.52	PASS	.	GT:AD:DP	0/1:17,25:42
```

**Comment by aparton** [comment] 2021-06-24 12:26
Hi @ckandoth,

Thank you for this report. I'm able to reproduce the issue and we'll continue to investigate. 

The issue seems to be tied to the `--no_stats` flag. If you remove this option, then this should allow you to continue your analyses in the meantime.

Kind Regards,
Andrew

**Comment by Anahit19** [comment] 2021-06-26 14:54
Dear @ckandoth,

Thank you very much for your kind help!

**Comment by Stikus** [comment] 2021-07-05 12:33
Hello, we're experiencing the same problem with VEP 104.3.
```
substr outside of string at /soft/ensembl-vep-104.3/Bio/EnsEMBL/Variation/TranscriptVariationAllele.pm line 906, <$fh> line 2757660.
Died in forked process 10571
```

Our run command:
`/soft/ensembl-vep-104.3/vep --fork 96 --input_file /inputs/sample.PASSonly.vcf.gz --format vcf --cache --dir_cache /ref/.vep --dir_plugins /soft/ensembl-vep-104.3/Plugins --assembly GRCh38 --offline --output_file /trash/sample.PASSonly.annot-vep.vcf --vcf --no_stats --force_overwrite --symbol --check_existing --terms SO --tsl --hgvs --hgvsg --transcript_version --failed 1 --af --max_af --af_1kg --af_esp --af_gnomad --pubmed --sift b --polyphen b --variant_class --gene_phenotype --regulatory --numbers --domains --protein --canonical --ccds --uniprot --biotype --shift_hgvs 1 --xref_refseq --flag_pick_allele --no_escape --minimal --allele_number --total_length  --plugin CADD,/ref/CADD/1.6/GRCh38/whole_genome_SNVs.tsv.gz --custom /ref/ClinVar/GRCh38/clinvar_20210626.vcf.gz,ClinVar,vcf,exact,0,CLNDN,CLNDNINCL,CLNDISDB,CLNDISDBINCL,CLNHGVS,CLNREVSTAT,CLNSIG,CLNSIGCONF,CLNSIGINCL,CLNVC,CLNVCSO,CLNVI
`

And here is another issue about this problem: https://github.com/Ensembl/ensembl-vep/issues/818

**Comment by aparton** [comment] 2021-07-05 12:36
Hi @Stikus,

Thank you for bringing the duplicated issue to our attention. Unfortunately we do not have a fix in place for this issue yet. As a workaround, running your VEP command without the --no_stats option enabled should prevent this issue from happening in the short term.

Please let me know if there's anything else we can do to help.

Kind Regards,
Andrew

**Comment by aparton** [comment] 2021-07-05 12:39
Closing this issue now as it's a duplicate of #818.

**Closed by aparton** 2021-07-05 12:39 UTC
