### ISSUE TITLE
Possible precedence issue with control flow operator at ..../Bio/DB/IndexedBase.pm line 791.

### ISSUE THREAD

**Issue by pneerincx** [Ensembl/ensembl-vep#80] opened 2017-09-16 13:48 UTC
* VEP 90.5 source tar.gz downloaded from GitHub.
* Perl 5.22.0

Running
``./INSTALL.pl --AUTO acf --DESTDIR /vep_tests/code/ --CACHEDIR /vep_tests/data --SPECIES homo_sapiens --ASSEMBLY GRCh37``
results in the warning below printed each time IndexedBase.pm is loaded/used. This has been fixed in a more recent version of BioPerl...
```
Testing VEP installation
./t/OutputFactory_Tab.t .............................. Possible precedence issue with control flow operator at /vep_tests/code/Bio/DB/IndexedBase.pm line 791.
./t/OutputFactory_Tab.t .............................. ok    
./t/Utils.t .......................................... ok    
./t/OutputFactory.t .................................. Possible precedence issue with control flow operator at /vep_tests/code/Bio/DB/IndexedBase.pm line 791.
./t/OutputFactory.t .................................. ok     
./t/Parser_HGVS.t .................................... Possible precedence issue with control flow operator at /vep_tests/code/Bio/DB/IndexedBase.pm line 791.
./t/Parser_HGVS.t .................................... ok    
./t/bam_edit.t ....................................... Possible precedence issue with control flow operator at /vep_tests/code/Bio/DB/IndexedBase.pm line 791.
./t/bam_edit.t ....................................... ok    
./t/Config.t ......................................... Possible precedence issue with control flow operator at /vep_tests/code/Bio/DB/IndexedBase.pm line 791.
./t/Config.t ......................................... ok    
./t/TranscriptTree.t ................................. Possible precedence issue with control flow operator at /vep_tests/code/Bio/DB/IndexedBase.pm line 791.
./t/TranscriptTree.t ................................. ok    
./t/BaseVEP.t ........................................ Possible precedence issue with control flow operator at /vep_tests/code/Bio/DB/IndexedBase.pm line 791.
./t/BaseVEP.t ........................................ ok    
./t/AnnotationSource_File_VCF.t ...................... Possible precedence issue with control flow operator at /vep_tests/code/Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_File_VCF.t ...................... ok    
./t/AnnotationSource_File_GTF.t ...................... Possible precedence issue with control flow operator at /vep_tests/code/Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_File_GTF.t ...................... ok    
./t/AnnotationSource_Cache.t ......................... Possible precedence issue with control flow operator at /vep_tests/code/Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_Cache.t ......................... ok   
./t/AnnotationSource_File_BED.t ...................... Possible precedence issue with control flow operator at /vep_tests/code/Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_File_BED.t ...................... ok    
./t/OutputFactory_VEP_output.t ....................... Possible precedence issue with control flow operator at /vep_tests/code/Bio/DB/IndexedBase.pm line 791.
./t/OutputFactory_VEP_output.t ....................... ok    
./t/InputBuffer.t .................................... Possible precedence issue with control flow operator at /vep_tests/code/Bio/DB/IndexedBase.pm line 791.
./t/InputBuffer.t .................................... ok    
./t/AnnotationSource_Database_RegFeat.t .............. Possible precedence issue with control flow operator at /vep_tests/code/Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_Database_RegFeat.t .............. ok    
./t/AnnotationSource_Cache_RegFeat.t ................. Possible precedence issue with control flow operator at /vep_tests/code/Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_Cache_RegFeat.t ................. ok    
./t/Stats.t .......................................... Possible precedence issue with control flow operator at /vep_tests/code/Bio/DB/IndexedBase.pm line 791.
./t/Stats.t .......................................... ok    
./t/Parser_VCF.t ..................................... Possible precedence issue with control flow operator at /vep_tests/code/Bio/DB/IndexedBase.pm line 791.
./t/Parser_VCF.t ..................................... ok    
./t/AnnotationSource_Database_StructuralVariation.t .. Possible precedence issue with control flow operator at /vep_tests/code/Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_Database_StructuralVariation.t .. ok    
./t/AnnotationSource_Cache_Variation.t ............... Possible precedence issue with control flow operator at /vep_tests/code/Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_Cache_Variation.t ............... ok    
./t/VariantRecoder.t ................................. Possible precedence issue with control flow operator at /vep_tests/code/Bio/DB/IndexedBase.pm line 791.
./t/VariantRecoder.t ................................. ok    
./t/AnnotationSource_File_GFF.t ...................... Possible precedence issue with control flow operator at /vep_tests/code/Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_File_GFF.t ...................... ok    
./t/FilterSet.t ...................................... ok     
./t/AnnotationSource.t ............................... Possible precedence issue with control flow operator at /vep_tests/code/Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource.t ............................... ok    
./t/Parser_VEP_input.t ............................... Possible precedence issue with control flow operator at /vep_tests/code/Bio/DB/IndexedBase.pm line 791.
./t/Parser_VEP_input.t ............................... ok    
./t/AnnotationSource_File.t .......................... Possible precedence issue with control flow operator at /vep_tests/code/Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_File.t .......................... ok    
./t/CacheDir.t ....................................... Possible precedence issue with control flow operator at /vep_tests/code/Bio/DB/IndexedBase.pm line 791.
./t/CacheDir.t ....................................... ok    
./t/AnnotationSource_Database_Transcript.t ........... Possible precedence issue with control flow operator at /vep_tests/code/Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_Database_Transcript.t ........... ok    
./t/Runner.t ......................................... Possible precedence issue with control flow operator at /vep_tests/code/Bio/DB/IndexedBase.pm line 791.
./t/Runner.t ......................................... ok    
./t/Parser_ID.t ...................................... Possible precedence issue with control flow operator at /vep_tests/code/Bio/DB/IndexedBase.pm line 791.
./t/Parser_ID.t ...................................... ok   
./t/OutputFactory_VCF.t .............................. Possible precedence issue with control flow operator at /vep_tests/code/Bio/DB/IndexedBase.pm line 791.
./t/OutputFactory_VCF.t .............................. ok    
./t/Parser.t ......................................... Possible precedence issue with control flow operator at /vep_tests/code/Bio/DB/IndexedBase.pm line 791.
./t/Parser.t ......................................... ok    
./t/AnnotationSource_Database_Variation.t ............ Possible precedence issue with control flow operator at /vep_tests/code/Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_Database_Variation.t ............ ok    
./t/AnnotationSourceAdaptor.t ........................ Possible precedence issue with control flow operator at /vep_tests/code/Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSourceAdaptor.t ........................ ok    
./t/AnnotationSource_Cache_VariationTabix.t .......... Possible precedence issue with control flow operator at /vep_tests/code/Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_Cache_VariationTabix.t .......... ok    
./t/AnnotationSource_File_BigWig.t ................... Possible precedence issue with control flow operator at /vep_tests/code/Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_File_BigWig.t ................... ok    
./t/version.t ........................................ ok   
./t/OutputFactory_JSON.t ............................. Possible precedence issue with control flow operator at /vep_tests/code/Bio/DB/IndexedBase.pm line 791.
./t/OutputFactory_JSON.t ............................. ok    
./t/AnnotationSource_Cache_Transcript.t .............. Possible precedence issue with control flow operator at /vep_tests/code/Bio/DB/IndexedBase.pm line 791.
./t/AnnotationSource_Cache_Transcript.t .............. ok    
All tests successful.
Files=39, Tests=1629, 128 wallclock secs ( 0.38 usr  0.15 sys + 100.80 cusr 10.62 csys = 111.95 CPU)
Result: PASS
```

**Comment by willmclaren** [comment] 2017-09-18 08:21
Duplicate of https://github.com/Ensembl/ensembl-vep/issues/75

**Closed by willmclaren** 2017-09-18 08:21 UTC
