### ISSUE TITLE
GZip Broken Pipe If Compressed VCF Input

### ISSUE THREAD

**Issue by DarioS** [Ensembl/ensembl-vep#720] opened 2020-03-30 04:00 UTC
If I use a GZip-compressed VCF as input, I see `gzip: stdout: Broken pipe` and the VEP software doesn't return to the Linux command line. If I make a small, uncompressed VCF file with a couple of hundred lines, the effects text file is written to disk. If I use the whole somatic SNV VCF file, it seems to never finish and the CPU usage of the process is 5% or less. The output file is growing regularly, though, so I'm not sure why it's not using much CPU. The server is almost empty and has lots of spare capacity. How can the compressed file import be fixed? The installation of VEP seems to have went well, with no error messages displayed which would indicate a problem.

**Comment by helensch** [comment] 2020-03-30 12:25
Hi

VEP can read a compressed (gzipped) input file.  

Please could you provide:
- the version of VEP you are using
- the full VEP command being run

You report using a small uncompressed VCF successfully. Have you run using a small compressed (gzipped) VCF file successfully.

Helen

**Comment by DarioS** [comment] 2020-03-30 22:00
I have version 99.2 of VEP installed and server uses Debian 10. The command that I used is:

```
vep --tab --symbol --cache --dir_cache ensembl-vep/cache/ -i test.vcf.gz -o /tmp/test.txt
```

Even though I see the error message on the compressed file a few seconds after executing it, it outputs an apparently complete table of consequences anyway.

**Comment by aparton** [comment] 2020-03-31 17:04
Hi Dario,

I'm glad to hear that VEP outputs full data despite the warning.

I've had a look at this issue this afternoon and I'm unable to reproduce it with VEP 99 and Debian 10. Could it potentially be an issue with the VCF file itself? If you create a sample gzipped VCF file using the VCF file in ensembl-vep/examples/homo_sapiens_GRCh38.vcf, do you see the same issue?

Kind Regards, 
Andrew

**Comment by DarioS** [comment] 2020-03-31 23:00
It seems like a good guess. Compressing the file in the example directory and annotating it does not trigger the error message. I attach [a file](https://github.com/Ensembl/ensembl-vep/files/4411866/somatic.vcf.gz) which does trigger the error. Can you reproduce and pinpoint?

**Comment by aparton** [comment] 2020-04-02 12:00
Hi @DarioS,

I've had a look at your VCF file and I can reproduce the error. I'm not entirely sure what's going on here, your VCF file passes vcf-validator tests, there doesn't seem to be anything obviously faulty with the file.

If I test the .vcf.gz file with `gzip -tv somatic.vcf.gz` then I see multiple copies of the warning:
_gzip: somatic.vcf.gz: extra field of 6 bytes ignored_
However I suspect that's a red herring.

As a workaround, decompressing your input file before running VEP will solve your issue.

Kind Regards,
Andrew

**Comment by helensch** [comment] 2020-12-14 13:05
Hi 

I am going to close this issue now. If you have any further questions, please feel free to reopen it or create a new issue.

Regards
Helen

**Closed by helensch** 2020-12-14 13:05 UTC
