### ISSUE TITLE
Variant_recoder: Could not find start or end exon in transcript

### ISSUE THREAD

**Issue by gdeoli** [Ensembl/ensembl-vep#1019] opened 2021-07-08 23:57 UTC
## Describe the issue
I'm using variant_recoder in order to get the genomic positions from a list of hgvs. The entry NM_000257.4:c.327C>T got my attention, as I can successfully get a vcf using vep on the web, but when I attempt to use variant_recoder I got an error, stating that  it "Could not find start or end exon in transcript"
Can anyone help me to understand why this is happening?

### System
- VEP version: 104.3 
- Perl version: 5.30
- OS: Ubuntu
- tabix installed ?

### Full VEP command line
```
/variant_recoder --id "NM_000257.4:c.327C>T" --pretty --fields vcf_string,id,hgvsg,hgvsc
```

### Full error message
MSG: Could not find start or end exon in transcript

STACK Bio::EnsEMBL::DBSQL::TranslationAdaptor::fetch_all_by_Transcript_list /home/ubuntu/Gustavo/ensembl-vep/Bio/EnsEMBL/DBSQL/TranslationAdaptor.pm:917
STACK Bio::EnsEMBL::DBSQL::TranscriptAdaptor::fetch_all_by_Slice /home/ubuntu/Gustavo/ensembl-vep/Bio/EnsEMBL/DBSQL/TranscriptAdaptor.pm:653
STACK Bio::EnsEMBL::DBSQL::GeneAdaptor::fetch_all_by_Slice /home/ubuntu/Gustavo/ensembl-vep/Bio/EnsEMBL/DBSQL/GeneAdaptor.pm:712
STACK Bio::EnsEMBL::Slice::get_all_Genes /home/ubuntu/Gustavo/ensembl-vep/Bio/EnsEMBL/Slice.pm:1993
STACK Bio::EnsEMBL::VEP::AnnotationSource::Database::Transcript::get_features_by_regions_uncached /home/ubuntu/Gustavo/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/Database/Transcript.pm:234
STACK Bio::EnsEMBL::VEP::AnnotationSource::get_all_features_by_InputBuffer /home/ubuntu/Gustavo/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource.pm:134
STACK Bio::EnsEMBL::VEP::AnnotationType::Transcript::annotate_InputBuffer /home/ubuntu/Gustavo/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationType/Transcript.pm:101
STACK Bio::EnsEMBL::VEP::Runner::_buffer_to_output /home/ubuntu/Gustavo/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:407
STACK Bio::EnsEMBL::VEP::Runner::next_output_line /home/ubuntu/Gustavo/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:369
STACK Bio::EnsEMBL::VEP::VariantRecoder::_get_all_results /home/ubuntu/Gustavo/ensembl-vep/modules/Bio/EnsEMBL/VEP/VariantRecoder.pm:273
STACK Bio::EnsEMBL::VEP::VariantRecoder::recode_all /home/ubuntu/Gustavo/ensembl-vep/modules/Bio/EnsEMBL/VEP/VariantRecoder.pm:184
STACK main::main ./variant_recoder:104
STACK toplevel ./variant_recoder:97
Date (localtime)    = Thu Jul  8 23:46:12 2021
Ensembl API version = 104

**Comment by aparton** [comment] 2021-07-09 06:58
Hi @gdeoli,

Thank you for bringing this issue to our attention. I've been able to reproduce it, and I'll be in touch once we have investigated further.

Kind Regards,
Andrew

**Comment by nakib103** [comment] 2023-04-05 13:36
Hello, 

This issue have been resolved by https://github.com/Ensembl/ensembl-vep/pull/1078, so I am closing this issue.
Also to get `vcf_string` in the output you should also mention it specifically because this is a non-default field - 
```
./variant_recoder --id "NM_000257.4:c.327C>T" --pretty --fields vcf_string,id,hgvsg,hgvsc --vcf_string
```

Feel free to re-open this or create another issue if you are facing any further issues.

**Closed by nakib103** 2023-04-05 13:36 UTC
