### ISSUE TITLE
Use of uninitialized value $phase in numeric eq (==) at.... and empty Variant classes etc in html file

### ISSUE THREAD

**Issue by tiramisutes** [Ensembl/ensembl-vep#783] opened 2020-06-14 11:06 UTC
Hi,
I used follows a command to annotation the vcf file. The gff file has bgzipped and indexed as suggestion in https://uswest.ensembl.org/info/docs/tools/vep/script/vep_cache.html#gff .
```
vep -i input.vcf --gff data.gff.gz --fasta genome.fa.gz
```
But, there is many stdout like this:
```
Use of uninitialized value $phase in numeric eq (==) at /ensembl-vep-100.2-0/modules/Bio/EnsEMBL/VEP/AnnotationSource/File/BaseGXF.pm line 766.
Use of uninitialized value $phase in numeric eq (==) at /ensembl-vep-100.2-0/modules/Bio/EnsEMBL/VEP/AnnotationSource/File/BaseGXF.pm line 769.
```
And finally, the table of Variant classes, Consequences (most severe), Consequences (all), Coding consequences, Variants by chromosome, Position in protein are all empty in variant_effect_output.txt_summary.html file.

**Comment by aparton** [comment] 2020-06-15 09:58
Hi @tiramisutes,

VEP seems to be having an issue finding the exon phase for some variants. If you are able to send me a copy of your GFF file, then I can take a closer look.

You can either attach the gff file to this ticket, or email it to helpdesk@ensembl.org

Kind Regards,
Andrew

**Comment by tiramisutes** [comment] 2020-06-15 11:59
Hi,
Thanks for your replay. The following is gff file in my command.
```
AA	EVM	exon	13137	13160	.	-	.	ID=AAG000010.1.exon3;Parent=AAG000010.1
AA	EVM	three_prime_UTR 13137	13160	.	-	.	ID=AAG000010.1.utr3p2;Parent=AAG000010.1
AA	EVM	gene	13137	15599	.	-	.	ID=AAG000010;Name=AAG000010
AA	EVM	mRNA	13137	15599	.	-	.	ID=AAG000010.1;Parent=AAG000010
AA	EVM	three_prime_UTR 13844	13872	.	-	.	ID=AAG000010.1.utr3p1;Parent=AAG000010.1
AA	EVM	exon	13844	14084	.	-	.	ID=AAG000010.1.exon2;Parent=AAG000010.1
AA	EVM	CDS	 13873	14084	.	-	1	ID=cds.AAG000010.1;Parent=AAG000010.1
AA	EVM	CDS	 14168	14258	.	-	0	ID=cds.AAG000010.1;Parent=AAG000010.1
AA	EVM	exon	14168	15599	.	-	.	ID=AAG000010.1.exon1;Parent=AAG000010.1
AA	EVM	five_prime_UTR	14259	15599	.	-	.	ID=AAG000010.1.utr5p1;Parent=AAG000010.1
AA	EVM	CDS	 23156	23362	.	+	0	ID=cds.AAG000020.1;Parent=AAG000020.1
AA	EVM	exon	23156	23362	.	+	.	ID=AAG000020.1.exon1;Parent=AAG000020.1
AA	EVM	gene	23156	23362	.	+	.	ID=AAG000020;Name=AAG000020
AA	EVM	mRNA	23156	23362	.	+	.	ID=AAG000020.1;Parent=AAG000020
AA	EVM	five_prime_UTR	65260	67490	.	+	.	ID=AAG000030.1.utr5p1;Parent=AAG000030.1
AA	EVM	exon	65260	68219	.	+	.	ID=AAG000030.1.exon1;Parent=AAG000030.1
AA	EVM	gene	65260	68219	.	+	.	ID=AAG000030;Name=AAG000030
AA	EVM	mRNA	65260	68219	.	+	.	ID=AAG000030.1;Parent=AAG000030
AA	EVM	CDS	 67491	67811	.	+	0	ID=cds.AAG000030.1;Parent=AAG000030.1
AA	EVM	three_prime_UTR 67812	68219	.	+	.	ID=AAG000030.1.utr3p1;Parent=AAG000030.1
```

**Comment by aparton** [comment] 2020-06-25 13:23
Hi,

Apologies for the delay in getting back to you. I've been unable to reproduce this issue, could you please send me a copy of your input file and the fasta file you're using?

Kind Regards,
Andrew

**Comment by aparton** [comment] 2020-10-12 10:45
Hi,

I'm going to close this issue now. If you're able to send me on your input and fasta files, please reopen this ticket and I'm happy to take another look.

Kind Regards,
Andrew

**Closed by aparton** 2020-10-12 10:45 UTC
