### ISSUE TITLE
Cannot connect to the Ensembl MySQL server

### ISSUE THREAD

**Issue by Taalouane** [Ensembl/ensembl-vep#1563] opened 2023-11-24 12:31 UTC
Hi,

For several hours, it has been impossible to access your MySQL server on 'ensembldb.ensembl.org'. Would it be possible to verify this problem?

Note: yesterday I used VEP without any problem

```
DBI connect('host=ensembldb.ensembl.org;port=3306','anonymous',...) failed: Can't connect to MySQL server on 'ensembldb.ensembl.org' (111) at /opt/vep/src/ensembl-vep/Bio/EnsEMBL/Registry.pm line 1771.

-------------------- EXCEPTION --------------------
MSG: Cannot connect to the Ensembl MySQL server at ensembldb.ensembl.org:3306; check your settings & DBI error message: Can't connect to MySQL server on 'ensembldb.ensembl.org' (111)
STACK Bio::EnsEMBL::Registry::load_registry_from_db /opt/vep/src/ensembl-vep/Bio/EnsEMBL/Registry.pm:1771
STACK Bio::EnsEMBL::VEP::BaseVEP::registry /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseVEP.pm:252
STACK Bio::EnsEMBL::VEP::BaseRunner::setup_db_connection /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:120
STACK Bio::EnsEMBL::VEP::Runner::init /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:123
STACK Bio::EnsEMBL::VEP::Runner::run /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:199
STACK toplevel /opt/vep/src/ensembl-vep/vep:46
Date (localtime)    = Fri Nov 24 13:00:19 2023
Ensembl API version = 109
```

**Comment by nakib103** [comment] 2023-11-24 15:35
This is duplicate of https://github.com/Ensembl/ensembl-vep/issues/1562 - I will close this one. Once we have update I will post it on the other ticket.

Best regards,
Nakib

**Closed by nakib103** 2023-11-24 15:35 UTC

**Comment by Taalouane** [comment] 2023-11-24 15:40
The problem is solved. Thank you @nakib103 and for your team 👍
