### ISSUE TITLE
Contributing variants missing in JSON output

### ISSUE THREAD

**Issue by borissim** [Ensembl/ensembl-vep#671] opened 2020-01-10 15:17 UTC
## Describe the issue
Running Haplosaurus on:
```##fileformat=VCFv4.1
#genome: GRCh38
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	TUMOR
chr1	26425372	v2p-0	T	TG	.	.	.	GT	1|0
chr1	26425386	v2p-1	G	A	.	.	.	GT	1|0
```

The generated JSON file in the `protein_haplotypes` field reports an empty list for the `contributing_variants` for both protein haplotypes, even though both variants are applied in one. It is then harder to programmatically decide if and which haplotype contains a mutated protein sequence.

### System
- VEP version: 95
- VEP Cache version: 95
- Perl version: [e.g. 5.26]
- OS: Ubuntu

### Full VEP command line
```
perl haplo --cache --merged --offline --force_overwrite --json --dir /vep/vep_dist_95/cache --species homo_sapiens --assembly GRCh38 -i haplo_in.vcf -o haplo_out.json
```

## The generated JSON for one of the trainscripts:

```{"cds_haplotypes": [{"aligned_sequences": ["ATGGGCTCCGTGTCCAACCAGCAGTTTGCAGGTGGCTGCGCCAAGGCGGCAGAAGAGGCGCCCGAGGAGGCGCCGGAGGACGCGGCCCGGGCGGCGGACGAGCCTCAGCTGCTGCACGGTGCGGGCATCTGTAAGTGGTTCAACGTGCGCATGGGGTTCGGCTTCCTGTCCATGACCGCCCGCGCCGGGGTCGCGCTCGACCCCCCAGTGGATGTCTTTGTGCACCAGAGTAAGCTGCACATGGAAGGGTTCCGGAGCTTGAAGGAGGGTGAGGCAGTGGAGTTCACCTTTAAGAAGTCAGCCAAGGGTCTGGAATCCATCCGTGTCACCGGACCTGGTGGAGTATTCTGTATTGGGAGTGAGAGGCGGCCAAAAGGAAAGAGCATGCAGAAGCGCAGATCAAAAGGAGACAGGTGCTACAACTGTGGAGGTCTAGATCATCATGCCAAGGAATGCAAGCTGCCACCCCAGCCCAAGAAGTGCCACTTCTGCCAGAGCATCAGCCATATGGTAGCCTCATGTCCGCTGAAGGCCCAGCAGGGCCCTAGTGCACAGGGAAAGCCAACCTACTTTCGAGAGGAAGAAGAAGAAATCCACAGCCCTACCCTGCTCCCGGAGGCACAGAATTGA", "ATGGGCTCCGTGTCCAACCAGCAGTTTGCAGGTGGCTGCGCCAAGGCGGCAGAAGAGGCGCCCGAGGAGGCGCCGGAGGACGCGGCCCGGGCGGCGGACGAGCCTCAGCTGCTGCACGGTGCGGGCATCTGTAAGTGGTTCAACGTGCGCATGGGGTTCGGCTTCCTGTCCATGACCGCCCGCGCCGGGGTCGCGCTCGACCCCCCAGTGGATGTCTTTGTGCACCAGAGTAAGCTGCACATGGAAGGGTTCCGGAGCTTGAAGGAGGGTGAGGCAGTGGAGTTCACCTTTAAGAAGTCAGCCAAGGGTCTGGAATCCATCCGTGTCACCGGACCTGGTGGAGTATTCTGTATTGGGAGTGAGAGGCGGCCAAAAGGAAAGAGCATGCAGAAGCGCAGATCAAAAGGAGACAGGTGCTACAACTGTGGAGGTCTAGATCATCATGCCAAGGAATGCAAGCTGCCACCCCAGCCCAAGAAGTGCCACTTCTGCCAGAGCATCAGCCATATGGTAGCCTCATGTCCGCTGAAGGCCCAGCAGGGCCCTAGTGCACAGGGAAAGCCAACCTACTTTCGAGAGGAAGAAGAAGAAATCCACAGCCCTACCCTGCTCCCGGAGGCACAGAATTGA"], "contributing_variants": [], "count": 1, "diffs": [], "frequency": 0.5, "has_indel": 0, "hex": "2c92c1b1fa6fceb1dd79a1bf4aa7c2e6", "name": "ENST00000326279:REF", "other_hexes": {"8ce58ffa0e0292add7fddadbc52a45aa": 1}, "population_counts": {"_all": 1}, "population_frequencies": {"_all": 0.5}, "samples": {"TUMOR": 1}, "seq": "ATGGGCTCCGTGTCCAACCAGCAGTTTGCAGGTGGCTGCGCCAAGGCGGCAGAAGAGGCGCCCGAGGAGGCGCCGGAGGACGCGGCCCGGGCGGCGGACGAGCCTCAGCTGCTGCACGGTGCGGGCATCTGTAAGTGGTTCAACGTGCGCATGGGGTTCGGCTTCCTGTCCATGACCGCCCGCGCCGGGGTCGCGCTCGACCCCCCAGTGGATGTCTTTGTGCACCAGAGTAAGCTGCACATGGAAGGGTTCCGGAGCTTGAAGGAGGGTGAGGCAGTGGAGTTCACCTTTAAGAAGTCAGCCAAGGGTCTGGAATCCATCCGTGTCACCGGACCTGGTGGAGTATTCTGTATTGGGAGTGAGAGGCGGCCAAAAGGAAAGAGCATGCAGAAGCGCAGATCAAAAGGAGACAGGTGCTACAACTGTGGAGGTCTAGATCATCATGCCAAGGAATGCAAGCTGCCACCCCAGCCCAAGAAGTGCCACTTCTGCCAGAGCATCAGCCATATGGTAGCCTCATGTCCGCTGAAGGCCCAGCAGGGCCCTAGTGCACAGGGAAAGCCAACCTACTTTCGAGAGGAAGAAGAAGAAATCCACAGCCCTACCCTGCTCCCGGAGGCACAGAATTGA", "type": "cds"}, {"aligned_sequences": ["ATGGGCTCCGTGTCCAACCAGCAGTTTGCAGGTGGCTGCGCCAAGGCGGCAGAAGAGGCGCCCGAGGAGGCGCCGGAGGACGCGGCCCGGGCGGCGGACGAGCCTCAGCTGCTGCACGGTGCGGGCATCTGTAAGTGGTTCAACGTGCGCATGGGGTTCGGCTTCCTGTCCATGACCGCCCGCGCCGGGGTCGCGCTCGACCCCCCAGTGGATGTCTTTGTGCACCAGAGTAAGCTGCACATGGAAGGGTTCCGGAGCTTGAAGGAGGGTGAGGCAGTGGAGTTCACCTTTAAGAAGT-CAGCCAAGGGTCTGGAATCCATCCGTGTCACCGGACCTGGTGGAGTATTCTGTATTGGGAGTGAGAGGCGGCCAAAAGGAAAGAGCATGCAGAAGCGCAGATCAAAAGGAGACAGGTGCTACAACTGTGGAGGTCTAGATCATCATGCCAAGGAATGCAAGCTGCCACCCCAGCCCAAGAAGTGCCACTTCTGCCAGAGCATCAGCCATATGGTAGCCTCATGTCCGCTGAAGGCCCAGCAGGGCCCTAGTGCACAGGGAAAGCCAACCTACTTTCGAGAGGAAGAAGAAGAAATCCACAGCCCTACCCTGCTCCCGGAGGCACAGAATTGA", "ATGGGCTCCGTGTCCAACCAGCAGTTTGCAGGTGGCTGCGCCAAGGCGGCAGAAGAGGCGCCCGAGGAGGCGCCGGAGGACGCGGCCCGGGCGGCGGACGAGCCTCAGCTGCTGCACGGTGCGGGCATCTGTAAGTGGTTCAACGTGCGCATGGGGTTCGGCTTCCTGTCCATGACCGCCCGCGCCGGGGTCGCGCTCGACCCCCCAGTGGATGTCTTTGTGCACCAGAGTAAGCTGCACATGGAAGGGTTCCGGAGCTTGAAGGAGGGTGAGGCAGTGGAGTTCACCTTTAAGAAGTGCAGCCAAGGGTCTAGAATCCATCCGTGTCACCGGACCTGGTGGAGTATTCTGTATTGGGAGTGAGAGGCGGCCAAAAGGAAAGAGCATGCAGAAGCGCAGATCAAAAGGAGACAGGTGCTACAACTGTGGAGGTCTAGATCATCATGCCAAGGAATGCAAGCTGCCACCCCAGCCCAAGAAGTGCCACTTCTGCCAGAGCATCAGCCATATGGTAGCCTCATGTCCGCTGAAGGCCCAGCAGGGCCCTAGTGCACAGGGAAAGCCAACCTACTTTCGAGAGGAAGAAGAAGAAATCCACAGCCCTACCCTGCTCCCGGAGGCACAGAATTGA"], "contributing_variants": ["v2p-0", "v2p-1"], "count": 1, "diffs": [{"diff": "299insG"}, {"diff": "313G>A"}], "frequency": 0.5, "has_indel": 1, "hex": "32e25d546012671e300d4c16e6660e44", "name": "ENST00000326279:299insG,313G>A", "other_hexes": {"3f2def963f6d5616225aec05261e0feb": 1}, "population_counts": {"_all": 1}, "population_frequencies": {"_all": 0.5}, "samples": {"TUMOR": 1}, "seq": "ATGGGCTCCGTGTCCAACCAGCAGTTTGCAGGTGGCTGCGCCAAGGCGGCAGAAGAGGCGCCCGAGGAGGCGCCGGAGGACGCGGCCCGGGCGGCGGACGAGCCTCAGCTGCTGCACGGTGCGGGCATCTGTAAGTGGTTCAACGTGCGCATGGGGTTCGGCTTCCTGTCCATGACCGCCCGCGCCGGGGTCGCGCTCGACCCCCCAGTGGATGTCTTTGTGCACCAGAGTAAGCTGCACATGGAAGGGTTCCGGAGCTTGAAGGAGGGTGAGGCAGTGGAGTTCACCTTTAAGAAGTGCAGCCAAGGGTCTAGAATCCATCCGTGTCACCGGACCTGGTGGAGTATTCTGTATTGGGAGTGAGAGGCGGCCAAAAGGAAAGAGCATGCAGAAGCGCAGATCAAAAGGAGACAGGTGCTACAACTGTGGAGGTCTAGATCATCATGCCAAGGAATGCAAGCTGCCACCCCAGCCCAAGAAGTGCCACTTCTGCCAGAGCATCAGCCATATGGTAGCCTCATGTCCGCTGAAGGCCCAGCAGGGCCCTAGTGCACAGGGAAAGCCAACCTACTTTCGAGAGGAAGAAGAAGAAATCCACAGCCCTACCCTGCTCCCGGAGGCACAGAATTGA", "type": "cds"}], "protein_haplotypes": [{"aligned_sequences": ["MGSVSNQQFAGGCAKAAEEAPEEAPEDAARAADEPQLLHGAGICKWFNVRMGFGFLSMTARAGVALDPPVDVFVHQSKLHMEGFRSLKEGEAVEFTFKKSAKGLESIRVTGPGGVFCIGSERRPKGKSMQKRRSKGDRCYNCGGLDHHAKECKLPPQPKKCHFCQ-SISHMVASCPLKAQQGPSAQGKPTYFREEEEEIHSPTLLPEAQN*", "MGSVSNQQFAGGCAKAAEEAPEEAPEDAARAADEPQLLHGAGICKWFNVRMGFGFLSMTARAGVALDPPVDVFVHQSKLHMEGFRSLKEGEAVEFTFKK-----------------C--SQ----G-S---RI-------------H-------P-----CHRTWWSI--------L-------------YW-E----------------*"], "contributing_variants": [], "count": 1, "diffs": [{"diff": "100del{17}"}, {"diff": "118delIG"}, {"diff": "121E>Q"}, {"diff": "122del{4}"}, {"diff": "127delK"}, {"diff": "129delMQK"}, {"diff": "133R>I"}, {"diff": "134del{13}"}, {"diff": "148del{7}"}, {"diff": "156del{5}"}, {"diff": "163FCQ>RTW"}, {"diff": "166insW"}, {"diff": "169del{8}"}, {"diff": "178del{13}"}, {"diff": "192F>W"}, {"diff": "193delR"}, {"diff": "195del{16}"}], "flags": ["indel"], "frequency": 0.5, "has_indel": 1, "hex": "3f2def963f6d5616225aec05261e0feb", "name": "ENSP00000363314:100del{17},118delIG,121E>Q,122del{4},127delK,129delMQK,133R>I,134del{13},148del{7},156del{5},163FCQ>RTW,166insW,169del{8},178del{13},192F>W,193delR,195del{16}", "other_hexes": {"32e25d546012671e300d4c16e6660e44": 1}, "population_counts": {"_all": 1}, "population_frequencies": {"_all": 0.5}, "samples": {"TUMOR": 1}, "seq": "MGSVSNQQFAGGCAKAAEEAPEEAPEDAARAADEPQLLHGAGICKWFNVRMGFGFLSMTARAGVALDPPVDVFVHQSKLHMEGFRSLKEGEAVEFTFKKCSQGSRIHPCHRTWWSILYWE*", "type": "protein"}, {"aligned_sequences": ["MGSVSNQQFAGGCAKAAEEAPEEAPEDAARAADEPQLLHGAGICKWFNVRMGFGFLSMTARAGVALDPPVDVFVHQSKLHMEGFRSLKEGEAVEFTFKKSAKGLESIRVTGPGGVFCIGSERRPKGKSMQKRRSKGDRCYNCGGLDHHAKECKLPPQPKKCHFCQSISHMVASCPLKAQQGPSAQGKPTYFREEEEEIHSPTLLPEAQN*", "MGSVSNQQFAGGCAKAAEEAPEEAPEDAARAADEPQLLHGAGICKWFNVRMGFGFLSMTARAGVALDPPVDVFVHQSKLHMEGFRSLKEGEAVEFTFKKSAKGLESIRVTGPGGVFCIGSERRPKGKSMQKRRSKGDRCYNCGGLDHHAKECKLPPQPKKCHFCQSISHMVASCPLKAQQGPSAQGKPTYFREEEEEIHSPTLLPEAQN*"], "contributing_variants": [], "count": 1, "diffs": [], "flags": [], "frequency": 0.5, "has_indel": 0, "hex": "8ce58ffa0e0292add7fddadbc52a45aa", "name": "ENSP00000363314:REF", "other_hexes": {"2c92c1b1fa6fceb1dd79a1bf4aa7c2e6": 1}, "population_counts": {"_all": 1}, "population_frequencies": {"_all": 0.5}, "samples": {"TUMOR": 1}, "seq": "MGSVSNQQFAGGCAKAAEEAPEEAPEDAARAADEPQLLHGAGICKWFNVRMGFGFLSMTARAGVALDPPVDVFVHQSKLHMEGFRSLKEGEAVEFTFKKSAKGLESIRVTGPGGVFCIGSERRPKGKSMQKRRSKGDRCYNCGGLDHHAKECKLPPQPKKCHFCQSISHMVASCPLKAQQGPSAQGKPTYFREEEEEIHSPTLLPEAQN*", "type": "protein"}], "total_haplotype_count": 2, "total_population_counts": {"_all": 2}, "transcript_id": "ENST00000326279"}```

regards,
Boris

**Comment by at7** [comment] 2020-01-13 13:07
Dear @borissim,

thank you for the report. I can reproduce the error and have suggested a fix. I will let you know once the fix has been merged into our VEP code base.

Best wishes,
Anja

**Comment by at7** [comment] 2020-01-13 14:09
I have merged the bug fix into the release/99 branch. We are planning to have the 99 release this week. I will let you when the release is out. Could you upgrade your code base and cache files to the latest version after the release?

**Comment by borissim** [comment] 2020-01-13 14:16
Thanks Anja! 
I can test the latest release when it is out.

**Comment by at7** [comment] 2020-01-16 11:56
Hello,
the new release 99 is now available. Please install the latest version of VEP and try running your input again. Let me know if the problem isn't resolved.

Best wishes,
Anja

**Comment by borissim** [comment] 2020-02-25 14:02
Hi Anja,

The JSON result now contains only the first variant in the protein_haplotypes contributing_variants field.

`..."contributing_variants": ["v2p-0"]...`
Which is still better than [] before, but not completely correct.

The full JSON for one transcript:
`{"cds_haplotypes": [{"aligned_sequences": ["ATGGGCTCCGTGTCCAACCAGCAGTTTGCAGGTGGCTGCGCCAAGGCGGCAGAAGAGGCGCCCGAGGAGGCGCCGGAGGACGCGGCCCGGGCGGCGGACGAGCCTCAGCTGCTGCACGGTGCGGGCATCTGTAAGTGGTTCAACGTGCGCATGGGGTTCGGCTTCCTGTCCATGACCGCCCGCGCCGGGGTCGCGCTCGACCCCCCAGTGGATGTCTTTGTGCACCAGAGTAAGCTGCACATGGAAGGGTTCCGGAGCTTGAAGGAGGGTGAGGCAGTGGAGTTCACCTTTAAGAAGTCAGCCAAGGGTCTGGAATCCATCCGTGTCACCGGACCTGGTGGAGTATTCTGTATTGGGAGTGAGAGGCGGCCAAAAGGAAAGAGCATGCAGAAGCGCAGATCAAAAGGAGACAGGTGCTACAACTGTGGAGGTCTAGATCATCATGCCAAGGAATGCAAGCTGCCACCCCAGCCCAAGAAGTGCCACTTCTGCCAGAGCATCAGCCATATGGTAGCCTCATGTCCGCTGAAGGCCCAGCAGGGCCCTAGTGCACAGGGAAAGCCAACCTACTTTCGAGAGGAAGAAGAAGAAATCCACAGCCCTACCCTGCTCCCGGAGGCACAGAATTGA", "ATGGGCTCCGTGTCCAACCAGCAGTTTGCAGGTGGCTGCGCCAAGGCGGCAGAAGAGGCGCCCGAGGAGGCGCCGGAGGACGCGGCCCGGGCGGCGGACGAGCCTCAGCTGCTGCACGGTGCGGGCATCTGTAAGTGGTTCAACGTGCGCATGGGGTTCGGCTTCCTGTCCATGACCGCCCGCGCCGGGGTCGCGCTCGACCCCCCAGTGGATGTCTTTGTGCACCAGAGTAAGCTGCACATGGAAGGGTTCCGGAGCTTGAAGGAGGGTGAGGCAGTGGAGTTCACCTTTAAGAAGTCAGCCAAGGGTCTGGAATCCATCCGTGTCACCGGACCTGGTGGAGTATTCTGTATTGGGAGTGAGAGGCGGCCAAAAGGAAAGAGCATGCAGAAGCGCAGATCAAAAGGAGACAGGTGCTACAACTGTGGAGGTCTAGATCATCATGCCAAGGAATGCAAGCTGCCACCCCAGCCCAAGAAGTGCCACTTCTGCCAGAGCATCAGCCATATGGTAGCCTCATGTCCGCTGAAGGCCCAGCAGGGCCCTAGTGCACAGGGAAAGCCAACCTACTTTCGAGAGGAAGAAGAAGAAATCCACAGCCCTACCCTGCTCCCGGAGGCACAGAATTGA"], "contributing_variants": [], "count": 1, "diffs": [], "frequency": 0.5, "has_indel": 0, "hex": "2c92c1b1fa6fceb1dd79a1bf4aa7c2e6", "name": "ENST00000326279:REF", "other_hexes": {"8ce58ffa0e0292add7fddadbc52a45aa": 1}, "population_counts": {"_all": 1}, "population_frequencies": {"_all": 0.5}, "samples": {"TUMOR": 1}, "seq": "ATGGGCTCCGTGTCCAACCAGCAGTTTGCAGGTGGCTGCGCCAAGGCGGCAGAAGAGGCGCCCGAGGAGGCGCCGGAGGACGCGGCCCGGGCGGCGGACGAGCCTCAGCTGCTGCACGGTGCGGGCATCTGTAAGTGGTTCAACGTGCGCATGGGGTTCGGCTTCCTGTCCATGACCGCCCGCGCCGGGGTCGCGCTCGACCCCCCAGTGGATGTCTTTGTGCACCAGAGTAAGCTGCACATGGAAGGGTTCCGGAGCTTGAAGGAGGGTGAGGCAGTGGAGTTCACCTTTAAGAAGTCAGCCAAGGGTCTGGAATCCATCCGTGTCACCGGACCTGGTGGAGTATTCTGTATTGGGAGTGAGAGGCGGCCAAAAGGAAAGAGCATGCAGAAGCGCAGATCAAAAGGAGACAGGTGCTACAACTGTGGAGGTCTAGATCATCATGCCAAGGAATGCAAGCTGCCACCCCAGCCCAAGAAGTGCCACTTCTGCCAGAGCATCAGCCATATGGTAGCCTCATGTCCGCTGAAGGCCCAGCAGGGCCCTAGTGCACAGGGAAAGCCAACCTACTTTCGAGAGGAAGAAGAAGAAATCCACAGCCCTACCCTGCTCCCGGAGGCACAGAATTGA", "type": "cds"}, {"aligned_sequences": ["ATGGGCTCCGTGTCCAACCAGCAGTTTGCAGGTGGCTGCGCCAAGGCGGCAGAAGAGGCGCCCGAGGAGGCGCCGGAGGACGCGGCCCGGGCGGCGGACGAGCCTCAGCTGCTGCACGGTGCGGGCATCTGTAAGTGGTTCAACGTGCGCATGGGGTTCGGCTTCCTGTCCATGACCGCCCGCGCCGGGGTCGCGCTCGACCCCCCAGTGGATGTCTTTGTGCACCAGAGTAAGCTGCACATGGAAGGGTTCCGGAGCTTGAAGGAGGGTGAGGCAGTGGAGTTCACCTTTAAGAAGT-CAGCCAAGGGTCTGGAATCCATCCGTGTCACCGGACCTGGTGGAGTATTCTGTATTGGGAGTGAGAGGCGGCCAAAAGGAAAGAGCATGCAGAAGCGCAGATCAAAAGGAGACAGGTGCTACAACTGTGGAGGTCTAGATCATCATGCCAAGGAATGCAAGCTGCCACCCCAGCCCAAGAAGTGCCACTTCTGCCAGAGCATCAGCCATATGGTAGCCTCATGTCCGCTGAAGGCCCAGCAGGGCCCTAGTGCACAGGGAAAGCCAACCTACTTTCGAGAGGAAGAAGAAGAAATCCACAGCCCTACCCTGCTCCCGGAGGCACAGAATTGA", "ATGGGCTCCGTGTCCAACCAGCAGTTTGCAGGTGGCTGCGCCAAGGCGGCAGAAGAGGCGCCCGAGGAGGCGCCGGAGGACGCGGCCCGGGCGGCGGACGAGCCTCAGCTGCTGCACGGTGCGGGCATCTGTAAGTGGTTCAACGTGCGCATGGGGTTCGGCTTCCTGTCCATGACCGCCCGCGCCGGGGTCGCGCTCGACCCCCCAGTGGATGTCTTTGTGCACCAGAGTAAGCTGCACATGGAAGGGTTCCGGAGCTTGAAGGAGGGTGAGGCAGTGGAGTTCACCTTTAAGAAGTGCAGCCAAGGGTCTAGAATCCATCCGTGTCACCGGACCTGGTGGAGTATTCTGTATTGGGAGTGAGAGGCGGCCAAAAGGAAAGAGCATGCAGAAGCGCAGATCAAAAGGAGACAGGTGCTACAACTGTGGAGGTCTAGATCATCATGCCAAGGAATGCAAGCTGCCACCCCAGCCCAAGAAGTGCCACTTCTGCCAGAGCATCAGCCATATGGTAGCCTCATGTCCGCTGAAGGCCCAGCAGGGCCCTAGTGCACAGGGAAAGCCAACCTACTTTCGAGAGGAAGAAGAAGAAATCCACAGCCCTACCCTGCTCCCGGAGGCACAGAATTGA"], "contributing_variants": ["v2p-0", "v2p-1"], "count": 1, "diffs": [{"diff": "299insG"}, {"diff": "313G>A"}], "frequency": 0.5, "has_indel": 1, "hex": "32e25d546012671e300d4c16e6660e44", "name": "ENST00000326279:299insG,313G>A", "other_hexes": {"3f2def963f6d5616225aec05261e0feb": 1}, "population_counts": {"_all": 1}, "population_frequencies": {"_all": 0.5}, "samples": {"TUMOR": 1}, "seq": "ATGGGCTCCGTGTCCAACCAGCAGTTTGCAGGTGGCTGCGCCAAGGCGGCAGAAGAGGCGCCCGAGGAGGCGCCGGAGGACGCGGCCCGGGCGGCGGACGAGCCTCAGCTGCTGCACGGTGCGGGCATCTGTAAGTGGTTCAACGTGCGCATGGGGTTCGGCTTCCTGTCCATGACCGCCCGCGCCGGGGTCGCGCTCGACCCCCCAGTGGATGTCTTTGTGCACCAGAGTAAGCTGCACATGGAAGGGTTCCGGAGCTTGAAGGAGGGTGAGGCAGTGGAGTTCACCTTTAAGAAGTGCAGCCAAGGGTCTAGAATCCATCCGTGTCACCGGACCTGGTGGAGTATTCTGTATTGGGAGTGAGAGGCGGCCAAAAGGAAAGAGCATGCAGAAGCGCAGATCAAAAGGAGACAGGTGCTACAACTGTGGAGGTCTAGATCATCATGCCAAGGAATGCAAGCTGCCACCCCAGCCCAAGAAGTGCCACTTCTGCCAGAGCATCAGCCATATGGTAGCCTCATGTCCGCTGAAGGCCCAGCAGGGCCCTAGTGCACAGGGAAAGCCAACCTACTTTCGAGAGGAAGAAGAAGAAATCCACAGCCCTACCCTGCTCCCGGAGGCACAGAATTGA", "type": "cds"}], "protein_haplotypes": [{"aligned_sequences": ["MGSVSNQQFAGGCAKAAEEAPEEAPEDAARAADEPQLLHGAGICKWFNVRMGFGFLSMTARAGVALDPPVDVFVHQSKLHMEGFRSLKEGEAVEFTFKKSAKGLESIRVTGPGGVFCIGSERRPKGKSMQKRRSKGDRCYNCGGLDHHAKECKLPPQPKKCHFCQ-SISHMVASCPLKAQQGPSAQGKPTYFREEEEEIHSPTLLPEAQN*", "MGSVSNQQFAGGCAKAAEEAPEEAPEDAARAADEPQLLHGAGICKWFNVRMGFGFLSMTARAGVALDPPVDVFVHQSKLHMEGFRSLKEGEAVEFTFKK-----------------C--SQ----G-S---RI-------------H-------P-----CHRTWWSI--------L-------------YW-E----------------*"], "contributing_variants": ["v2p-0"], "count": 1, "diffs": [{"diff": "100del{17}"}, {"diff": "118delIG"}, {"diff": "121E>Q"}, {"diff": "122del{4}"}, {"diff": "127delK"}, {"diff": "129delMQK"}, {"diff": "133R>I"}, {"diff": "134del{13}"}, {"diff": "148del{7}"}, {"diff": "156del{5}"}, {"diff": "163FCQ>RTW"}, {"diff": "166insW"}, {"diff": "169del{8}"}, {"diff": "178del{13}"}, {"diff": "192F>W"}, {"diff": "193delR"}, {"diff": "195del{16}"}], "flags": ["indel"], "frequency": 0.5, "has_indel": 1, "hex": "3f2def963f6d5616225aec05261e0feb", "name": "ENSP00000363314:100del{17},118delIG,121E>Q,122del{4},127delK,129delMQK,133R>I,134del{13},148del{7},156del{5},163FCQ>RTW,166insW,169del{8},178del{13},192F>W,193delR,195del{16}", "other_hexes": {"32e25d546012671e300d4c16e6660e44": 1}, "population_counts": {"_all": 1}, "population_frequencies": {"_all": 0.5}, "samples": {"TUMOR": 1}, "seq": "MGSVSNQQFAGGCAKAAEEAPEEAPEDAARAADEPQLLHGAGICKWFNVRMGFGFLSMTARAGVALDPPVDVFVHQSKLHMEGFRSLKEGEAVEFTFKKCSQGSRIHPCHRTWWSILYWE*", "type": "protein"}, {"aligned_sequences": ["MGSVSNQQFAGGCAKAAEEAPEEAPEDAARAADEPQLLHGAGICKWFNVRMGFGFLSMTARAGVALDPPVDVFVHQSKLHMEGFRSLKEGEAVEFTFKKSAKGLESIRVTGPGGVFCIGSERRPKGKSMQKRRSKGDRCYNCGGLDHHAKECKLPPQPKKCHFCQSISHMVASCPLKAQQGPSAQGKPTYFREEEEEIHSPTLLPEAQN*", "MGSVSNQQFAGGCAKAAEEAPEEAPEDAARAADEPQLLHGAGICKWFNVRMGFGFLSMTARAGVALDPPVDVFVHQSKLHMEGFRSLKEGEAVEFTFKKSAKGLESIRVTGPGGVFCIGSERRPKGKSMQKRRSKGDRCYNCGGLDHHAKECKLPPQPKKCHFCQSISHMVASCPLKAQQGPSAQGKPTYFREEEEEIHSPTLLPEAQN*"], "contributing_variants": [], "count": 1, "diffs": [], "flags": [], "frequency": 0.5, "has_indel": 0, "hex": "8ce58ffa0e0292add7fddadbc52a45aa", "name": "ENSP00000363314:REF", "other_hexes": {"2c92c1b1fa6fceb1dd79a1bf4aa7c2e6": 1}, "population_counts": {"_all": 1}, "population_frequencies": {"_all": 0.5}, "samples": {"TUMOR": 1}, "seq": "MGSVSNQQFAGGCAKAAEEAPEEAPEDAARAADEPQLLHGAGICKWFNVRMGFGFLSMTARAGVALDPPVDVFVHQSKLHMEGFRSLKEGEAVEFTFKKSAKGLESIRVTGPGGVFCIGSERRPKGKSMQKRRSKGDRCYNCGGLDHHAKECKLPPQPKKCHFCQSISHMVASCPLKAQQGPSAQGKPTYFREEEEEIHSPTLLPEAQN*", "type": "protein"}], "total_haplotype_count": 2, "total_population_counts": {"_all": 2}, "transcript_id": "ENST00000326279"}
`
regards,
Boris

**Comment by at7** [comment] 2020-02-25 16:10
Hi Boris,

v2p-1 is not part of the contributing variants for the protein haplotype because the variant is synonymous with respect to the protein sequence. For a CDS haplotype it is simple to work out which variants have contributed; we simply log them while the sequence is being edited. For a protein haplotype we use information from the variant consequence to determine whether each variant contributes to the protein haplotype. We include variants if the variant consequence is one of: stop, missense, frameshift, inframe or initiator.
I hope that explains the results you are seeing. Please let me know if you have any more questions.

Best regards,
Anja

**Comment by borissim** [comment] 2020-02-26 14:50
Hi Anja, thanks for the quick reply.

I see what you mean, and I can understand the logic behind this implementation, however in this scenario the synonymous variant actually affects the result because it is downstream from the frameshifting insertion.

When only the frameshifting insertion is the input then the resulting protein sequence would be:
`MGSVSNQQFAGGCAKAAEEAPEEAPEDAARAADEPQLLHGAGICKWFNVRMGFGFLSMTARAGVALDPPVDVFVHQSKLHMEGFRSLKEGEAVEFTFKKCSQGS G IHPCHRTWWSILYWE`

When both the frameshifting insertion and the SNV are considered the resulting protein sequence is  
`MGSVSNQQFAGGCAKAAEEAPEEAPEDAARAADEPQLLHGAGICKWFNVRMGFGFLSMTARAGVALDPPVDVFVHQSKLHMEGFRSLKEGEAVEFTFKKCSQGS R IHPCHRTWWSILYWE`
resulting in a G/R change. Haplosaurus generates the correct protein sequence already. 

Anyway, that can probably be considered as another issue. The main issue reported here has been fix with the v99 release.

Thank you very much.

regards,
Boris

**Closed** 2020-02-26 14:51 UTC

**Comment by at7** [comment] 2020-02-26 15:29
Hi Boris,
thank you for your feedback. We will reevaluate how we determine contributing variants to protein haplotypes. I cannot promise by when this will be done but I can add your git contact to the ticket and we will inform you about any improvements.
Best wishes,
Anja

**Comment by borissim** [comment] 2020-02-26 15:31
Thanks Anja, that sounds good.
