### ISSUE TITLE
RefSeq annotation release

### ISSUE THREAD

**Issue by segoerge** [Ensembl/ensembl-vep#867] opened 2020-10-16 06:06 UTC
## Describe the issue
Dear VEP team,

we have a problem to infer the actual NCBI RefSeq annotation release, your cache files are using. I've seen your table in the documentation (http://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html - Data in cache), but I'm not able to make a connection between this dates stated there (2019-11-01 and 2020-03-24) and the data on the NCBI FTP (https://ftp.ncbi.nlm.nih.gov/refseq/H_sapiens/annotation/annotation_releases/). Regarding GRCh37, I can only find a version 105.20190906 from 2019-09-06. I've also checked all readme files, GFF headers, etc. for 2019-11-01, but I cannot find this date anywhere. I've also checked the GFF from here (https://ftp.ncbi.nlm.nih.gov/refseq/H_sapiens/annotation/GRCh37_latest/refseq_identifiers/), but there is also 2019-09-06 in the GFF header. You can find a 2019-11-05 in the README file here, but I think this is only the update date for the README file. I've also downloaded the indexed cache files for release 101 and took a look into the info.txt. There I only found some "01_2015" version of refseq. I have the same problems with GRCh38. Here there are more than one annotation releases in the first URL I've posted and I have no plan which one was taken for the cache generation.

I'm asking this, because it is really critical for us, to use the same RefSeq basis in all our tools. At the moment we are still using VEP with custom annotation over the NCBI GFF files, but we want to switch to the cache, because we found some genes that can be annotated correctly over your online VEP, but didn't work with our GFF file.

Best regard and thanks in advance for your time,

Sebastian

**Comment by dglemos** [comment] 2020-10-16 15:05
Hi @segoerge,
The date in our cache files is not the exact date from the RefSeq release. The date `2020-03-24` means that the RefSeq file was imported into Ensembl on 2020-03-24. 
The GRCh38 cache info is `refseq version 2020-03-24 16:45:50 - GCF_000001405.39_GRCh38.p13_genomic.gff` the file used for the annotation was the one with the closest date before the 24th March: https://ftp.ncbi.nlm.nih.gov/refseq/H_sapiens/annotation/annotation_releases/109.20200228/ 
For GRCh37 the header info should be `refseq version 2019-10-24 23:10:14 - GCF_000001405.25_GRCh37.p13_genomic.gff` instead of "01_2015". Starting from release 102, GRCh37 will include the correct data format. The file import should be the one from 2019-09-06. 

Best wishes,
Diana

**Comment by segoerge** [comment] 2020-10-19 06:52
Hi @dglemos,

thanks for your help! It would be very helpfull, if you could possibly also track the annotation release version (e.g. 109.20200228) in the cache description table of the Ensembl web documentation.

Best wishes,

Sebastian

**Comment by davmlaw** [comment] 2020-10-27 05:31
I think this is a duplicate of #833 - Feature request: VCF header should contain gene GTF version

**Comment by dglemos** [comment] 2020-11-05 14:31
My colleagues who load the RefSeq data are looking into this request to integrate the annotation release version. I'll let you know when we have any updates. 
Best wishes,
Diana

**Comment by dglemos** [comment] 2022-07-14 13:17
Hi @segoerge,
We have updated the Refseq release version in the vep cache file. 
In the current release 107, the version included in info.txt is the same as the Refseq version.

Best wishes,
Diana

**Closed by dglemos** 2022-07-14 13:17 UTC
