### ISSUE TITLE
VEP give  wrong Consequence for splice-donor variant

### ISSUE THREAD

**Issue by lituan** [Ensembl/ensembl-vep#519] opened 2019-07-01 10:03 UTC
Hi,

there is a variant chr12-52307550-TG-T ( NM_000020.2:c.525+1del  ) , vep gives 'frameshift_variant'  consequence for it, while clinvar gives 'splice donor' , I think clinvar is right, so is this a bug of vep?

https://www.ncbi.nlm.nih.gov/clinvar/variation/411315/

**Comment by ima23** [comment] 2019-07-01 10:32
Dear @lituan,

Thank you for the query. Can you please give me a few more details in what context the variant is annotated as `frameshift_variant` ? 
Indeed the variant from your ClinVar link rs1060503249 is a `slice donor` variant, and this is what is  annotated by VEP as seen also on the Ensembl page  for [rs1060503249](https://www.ensembl.org/Homo_sapiens/Variation/Mappings?db=core;r=12:51913271-51914271;v=rs1060503249;vdb=variation;vf=486577834). 

Best regards,
Irina

**Comment by lituan** [comment] 2019-07-02 00:28
Hi

I have a locale install of ensembl-vep (96), it gives frameshift_variant, then I use vep web interface to annotate this variant, it also gives frameshift_variant

and this link is my annotation result,   http://grch37.ensembl.org/Homo_sapiens/Tools/VEP/Results?db=core;tl=qh1A8xU7whOGSmFM-5434985

**Comment by ima23** [comment] 2019-07-02 08:27
Dear @lituan,

Thank you for the details and the link to the GRCh37 VEP Web run.
The variant in the web run and the rs1060503249 variant are two different variants. 
The first variant, from the web run link, is located at position 52307500 while the rsID variant is located at position 52307554 in GRCh37 ( Ensembl GRCh37 [rs1060503249](http://grch37.ensembl.org/Homo_sapiens/Variation/Explore?r=12:52307055-52308055;v=rs1060503249;vdb=variation;vf=410604550) .
The 4 bp position difference places the 52307554 variant within the coding region leading to the correct `frameshift_variant` consequence annotation.

Best regards,
Irina

**Comment by lituan** [comment] 2019-07-02 09:38
Dear Irina,

the two variant are same, the positions from 52307551 to 52307555 are all G, so the following variants are all the same
 chr12-52307550-TG-T
 chr12-52307551-GG-G
 chr12-52307552-GG-G
 chr12-52307553-GG-G
 chr12-52307554-GG-G
these variants are all annoted by vep as NM_000020.2:c.525+1del
it seems vep will shift variants when giving HGVSc, but do not shift variants when giving Consequence

Best regards
lituan

**Comment by ima23** [comment] 2019-07-02 12:34
Dear @lituan,

Thank you for the clear explanation. Yes, you are right, the variants have the same effect when 3' shifted. 
The consequence is currently calculated based on the input position while the HGVS notation is based on the translated sequence, in which case both variants lead to the same modification in the translated sequence and the same HGVS.
We are working on API updates which will report the consequence in the 3' most location which will match HGVS. These will be available later in the year.

Best regards,
Irina

**Comment by GSYongWu** [comment] 2020-01-03 05:51
Dear Irina,
Is it resolved now? I found the same problem in the v98.3 version, or are there any special parameters?

Best regards,
Yong

**Comment by aparton** [comment] 2020-01-03 16:24
Hi Yong,

This update is not currently available. It is currently scheduled to be available in April.

Kind Regards,
Andrew

**Comment by tskir** [comment] 2020-02-18 11:51
Hi @aparton, it looks like some behaviour which I observe is also related to this issue. Namely, the VEP (GRCh38) reports the most severe consequences as:
* **10:125798142:T:TC** → frameshift_variant
* **10:125798146:C:CC** → splice_acceptor_variant

...even though those two denote exactly the same variant.

Could you give a little more detail on how the update is planned to work — will this be an additional API parameter, or will the normalisation be applied to all input variants?

**Comment by aparton** [comment] 2020-02-18 14:48
Hi @tskir,

For release 100 (currently scheduled for release in late March/early April), insertions and deletions in repeated regions will be shifted as far as possible in the 3' direction before consequence calculations. Initially, this functionality will have to be switched on by adding an optional flag to your VEP command, however we expect that we will switch this behaviour to default in a future release.

If you have any more specific questions regarding this change, please don't hesitate to ask.

Kind Regards,
Andrew

**Comment by GSYongWu** [comment] 2020-04-29 04:25
Hi @aparton ,
Are there any changes to the plan for the April release?

**Comment by aparton** [comment] 2020-04-29 15:54
Hi @GSYongWu,

Ensembl 100 has just been released! After updating, you can now apply this normalisation by adding the option `--shift_3prime 1` to your VEP command.

If you have any more questions/issues, please feel free to open a new issue.

Kind Regards,
Andrew

**Comment by ima23** [comment] 2020-08-24 13:12
Hi @lituan,

 I will close this ticket now. The Ensembl 100 release updates annotated now the example as 'splice donor variant'. Please feel free to re-open the ticket if the issue is still there.

Kind regards,
Irina

**Closed by ima23** 2020-08-24 13:12 UTC
