### ISSUE TITLE
Ensembl-VEP installation

### ISSUE THREAD

**Issue by BeatrizMonterde** [Ensembl/ensembl-vep#1592] opened 2024-01-26 12:48 UTC
Hi, 

I have tried to install Ensembl-VEP on a cluster, following the specifications indicated in the website https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html

I was able to install the required dependencies before launching the VEP file. I reached the point where "perl vep" indicated me a detailed description on how to run the command.
However, I'm experiencing some troubles with my perl environment, as it's not able to locate a module that is already installed and I have added this pathway in the "PERL5LIB" variable on my "bashrc" file. What I found quite confusing as well, is that now I'm not able to use cpan/cpanm and I'm getting exactly the same error message:

(ensemblVEP1) [bmonterde@login(alma) ensembl-vep]$ perl vep
Can't locate Bio/EnsEMBL/Utils/Exception.pm in @INC (you may need to install the Bio::EnsEMBL::Utils::Exception module) (@INC contains: /data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/perl5/lib/perl5/x86_64-linux-thread-multi /data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/perl5/lib /data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/tools/ensembl-vep/htslib /data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/htslib /data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/perl5/lib/perl5/LWP /data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/tools/ensembl-vep/modules/Bio/EnsEMBL/VEP /data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/tools/ensembl-vep/Bio/EnsEMBL/Utils /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5) at /data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/tools/ensembl-vep/modules/Bio/EnsEMBL/VEP/Config.pm line 64.
BEGIN failed--compilation aborted at /data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/tools/ensembl-vep/modules/Bio/EnsEMBL/VEP/Config.pm line 64.
Compilation failed in require at /usr/lib64/perl5/lib.pm line 6.
BEGIN failed--compilation aborted at /usr/lib64/perl5/lib.pm line 6.
Compilation failed in require at vep line 18.
BEGIN failed--compilation aborted at vep line 18.

(ensemblVEP1) [bmonterde@login(alma) ensembl-vep]$ cpanm Bio::EnsEMBL::Utils::Exception
Can't locate Bio/EnsEMBL/Utils/Exception.pm in @INC (you may need to install the Bio::EnsEMBL::Utils::Exception module) (@INC contains: FatPacked::94171127552976=HASH(0x55a5ec9b1bd0) /data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/perl5/lib/perl5/x86_64-linux-thread-multi /data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/perl5/lib /data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/tools/ensembl-vep/htslib /data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/htslib /data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/perl5/lib/perl5/LWP /data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/tools/ensembl-vep/modules/Bio/EnsEMBL/VEP /data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/tools/ensembl-vep/Bio/EnsEMBL/Utils /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5) at /data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/tools/ensembl-vep/modules/Bio/EnsEMBL/VEP/Config.pm line 64.
BEGIN failed--compilation aborted at /data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/tools/ensembl-vep/modules/Bio/EnsEMBL/VEP/Config.pm line 64.
Compilation failed in require at /data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/perl5/bin/cpanm line 32.
BEGIN failed--compilation aborted at /data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/perl5/bin/cpanm line 32.
Compilation failed in require at /data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/perl5/bin/cpanm line 499.
BEGIN failed--compilation aborted at /data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/perl5/bin/cpanm line 499.

Could you please give me a clue of what may be causing this issue?

Many thanks

**Comment by olaaustine** [comment] 2024-01-26 13:39
Hi @BeatrizMonterde 
Hope you are well? 
Sorry you are having an issues with installing VEP. 
Can you add the dir ensembl-vep to your .bashrc directory by 
```
echo 'export PERL5LIB=${PERL5LIB}:/data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/tools/ensembl-vep/' >> ~/.bashrc
echo 'export PERL5LIB=${PERL5LIB}:/data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/tools/ensembl-vep/modules' >> ~/.bashrc
source ~/.bashrc
```
and run `perl INSTALL.pl` again. 
Thank you
Ola

**Comment by BeatrizMonterde** [comment] 2024-01-26 14:06
Hi Ola,

Many thanks for your reply. I just added the dir ensembl-vep to my .bashrc as indicated. When I'm trying to run "perl INSTALL.pl", I get the following error:

(ensemblVEP1) [bmonterde@node01(alma) ensembl-vep]$ perl INSTALL.pl 
Can't locate loadable object for module DBI in @INC (@INC contains: /data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/perl5/lib/perl5/x86_64-linux-thread-multi /data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/perl5/lib /data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/tools/ensembl-vep/htslib /data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/htslib /data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/perl5/lib/perl5/LWP /data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/tools/ensembl-vep/modules/Bio/EnsEMBL/VEP /data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/tools/ensembl-vep/Bio/EnsEMBL/Utils /data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/tools/ensembl-vep/ /data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/tools/ensembl-vep/modules /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5) at /data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/perl5/lib/perl5/x86_64-linux-thread-multi/DBI.pm line 284.
BEGIN failed--compilation aborted at /data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/perl5/lib/perl5/x86_64-linux-thread-multi/DBI.pm line 284.
Compilation failed in require at /data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/tools/ensembl-vep/Bio/EnsEMBL/DBSQL/DBConnection.pm line 74.
BEGIN failed--compilation aborted at /data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/tools/ensembl-vep/Bio/EnsEMBL/DBSQL/DBConnection.pm line 74.
Compilation failed in require at /data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/tools/ensembl-vep/Bio/EnsEMBL/DBSQL/DBAdaptor.pm line 69.
BEGIN failed--compilation aborted at /data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/tools/ensembl-vep/Bio/EnsEMBL/DBSQL/DBAdaptor.pm line 69.
Compilation failed in require at /data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/tools/ensembl-vep/Bio/EnsEMBL/Registry.pm line 137.
BEGIN failed--compilation aborted at /data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/tools/ensembl-vep/Bio/EnsEMBL/Registry.pm line 137.
Compilation failed in require at /data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/tools/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseVEP.pm line 58.
BEGIN failed--compilation aborted at /data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/tools/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseVEP.pm line 58.
Compilation failed in require at /usr/share/perl5/base.pm line 138.
	...propagated at /usr/share/perl5/base.pm line 160.
BEGIN failed--compilation aborted at /data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/tools/ensembl-vep/modules/Bio/EnsEMBL/VEP/Config.pm line 67.
Compilation failed in require at /usr/lib64/perl5/lib.pm line 6.
BEGIN failed--compilation aborted at /usr/lib64/perl5/lib.pm line 6.
Compilation failed in require at INSTALL.pl line 40.
BEGIN failed--compilation aborted at INSTALL.pl line 40.

Thanks so much again for your help

Best wishes,

Beatriz

**Comment by olaaustine** [comment] 2024-01-26 14:50
Hi @BeatrizMonterde,
Thank you for your response. 
Can you confirm that this [requirements](https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#:~:text=Show-,Requirements,-VEP%20requires%3A) is met ? 
Do you have all the modules installed on the cluster? 
Thank you very much. 
Ola.

**Comment by BeatrizMonterde** [comment] 2024-01-26 14:56
Could you tell me how can I check if these modules are correctly installed? 
I'm quite sure I was able to install Archive::Zip and CBD, but not DBD::mysql (I didn't think it would be relevant if I didn't run the program online). 

What I can tell you is that there's a CBD directory in: 
/data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/perl5/lib/perl5/x86_64-linux-thread-multi/

(ensemblVEP1) [bmonterde@node01(alma) x86_64-linux-thread-multi]$ ls
B         DBD     Encode     List          Test   dbixs_rev.pl
Bundle    DBI     Encode.pm  PadWalker.pm  Win32  encoding.pm
Clone.pm  DBI.pm  HTML       Set           auto   perllocal.pod

Let me know if you need anything else to discover what might be happening

Thanks so much for your help

Best wishes,

Beatriz

**Comment by BeatrizMonterde** [comment] 2024-01-26 17:22
Just to let you know the kind of error that's appearing now, whenever I try to run INSTALL.pl or cpan/cpanm, I get this message:

(ensemblVEP1) [bmonterde@node01(alma) ensembl-vep]$ perl INSTALL.pl 
Can't locate loadable object for module DBI in @INC (@INC contains: /data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/perl5/lib/perl5/x86_64-linux-thread-multi /data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/perl5/lib /data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/tools/ensembl-vep/htslib /data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/htslib /data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/perl5/lib/perl5/LWP /data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/tools/ensembl-vep/modules/Bio/EnsEMBL/VEP /data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/tools/ensembl-vep/Bio/EnsEMBL/Utils /data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/tools/ensembl-vep/modules /data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/tools/ensembl-vep/ /data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/perl5/lib/perl5/x86_64-linux-thread-multi/DBI /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5) at /data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/perl5/lib/perl5/x86_64-linux-thread-multi/DBI/DBI.pm line 284.
BEGIN failed--compilation aborted at /data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/perl5/lib/perl5/x86_64-linux-thread-multi/DBI/DBI.pm line 284.
Compilation failed in require at /data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/tools/ensembl-vep/Bio/EnsEMBL/DBSQL/DBConnection.pm line 74.
BEGIN failed--compilation aborted at /data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/tools/ensembl-vep/Bio/EnsEMBL/DBSQL/DBConnection.pm line 74.
Compilation failed in require at /data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/tools/ensembl-vep/Bio/EnsEMBL/DBSQL/DBAdaptor.pm line 69.
BEGIN failed--compilation aborted at /data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/tools/ensembl-vep/Bio/EnsEMBL/DBSQL/DBAdaptor.pm line 69.
Compilation failed in require at /data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/tools/ensembl-vep/Bio/EnsEMBL/Registry.pm line 137.
BEGIN failed--compilation aborted at /data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/tools/ensembl-vep/Bio/EnsEMBL/Registry.pm line 137.
Compilation failed in require at /data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/tools/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseVEP.pm line 58.
BEGIN failed--compilation aborted at /data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/tools/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseVEP.pm line 58.
Compilation failed in require at /usr/share/perl5/base.pm line 138.
	...propagated at /usr/share/perl5/base.pm line 160.
BEGIN failed--compilation aborted at /data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/tools/ensembl-vep/modules/Bio/EnsEMBL/VEP/Config.pm line 67.
Compilation failed in require at /usr/lib64/perl5/lib.pm line 6.
BEGIN failed--compilation aborted at /usr/lib64/perl5/lib.pm line 6.
Compilation failed in require at INSTALL.pl line 40.
BEGIN failed--compilation aborted at INSTALL.pl line 40.

**Comment by olaaustine** [comment] 2024-01-29 09:10
Hi @BeatrizMonterde, 
Hope this meets you well?
The perl module DBD::mysql  needs to be installed for as it is a requirements to use VEP as stated [here](https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#:~:text=Show-,Requirements,-VEP%20requires%3A).
It is the reason the compilation is failing. 
Thank you 
Ola

**Comment by BeatrizMonterde** [comment] 2024-01-29 16:07
Hi,

Many thanks for your reply. I am having some trouble while trying to install DBD::mysql though "cpanm". Here I am showing what the log contains:

cpanm (App::cpanminus) 1.7047 on perl 5.026003 built for x86_64-linux-thread-mul
ti
Work directory is /home/bmonterde/.cpanm/work/1706544290.1519979
You have make /usr/bin/make
You have LWP 6.73
You have /usr/bin/tar: tar (GNU tar) 1.30
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
You have /usr/bin/unzip
Searching DBD::mysql () on cpanmetadb ...
--> Working on DBD::mysql
Fetching http://www.cpan.org/authors/id/D/DV/DVEEDEN/DBD-mysql-5.003.tar.gz
-> OK
Unpacking DBD-mysql-5.003.tar.gz
Entering DBD-mysql-5.003
Checking configure dependencies from META.json
Checking if you have DBI 1.609 ... Yes (1.643)
Checking if you have ExtUtils::MakeMaker 6.58 ... Yes (7.34)
Checking if you have Devel::CheckLib 1.09 ... Yes (1.16)
Checking if you have Data::Dumper 0 ... Yes (2.167)
Configuring DBD-mysql-5.003
Running Makefile.PL
Can't exec "mysql_config": No such file or directory at Makefile.PL line 85.

Cannot find the file 'mysql_config'! Your execution PATH doesn't seem
not contain the path to mysql_config. Resorting to guessed values!

Alternatively, I tried to install it using "cpan"

cpan[1]> install DBD::mysql
Reading '/home/bmonterde/.cpan/Metadata'
  Database was generated on Mon, 29 Jan 2024 13:29:01 GMT
Running install for module 'DBD::mysql'
Checksum for /home/bmonterde/.cpan/sources/authors/id/D/DV/DVEEDEN/DBD-mysql-5.003.tar.gz ok
Scanning cache /home/bmonterde/.cpan/build for sizes
............................................................................DONE
Configuring D/DV/DVEEDEN/DBD-mysql-5.003.tar.gz with Makefile.PL
Can't exec "mysql_config": No such file or directory at Makefile.PL line 85.

Cannot find the file 'mysql_config'! Your execution PATH doesn't seem
not contain the path to mysql_config. Resorting to guessed values!


PLEASE NOTE:

For 'make test' to run properly, you must ensure that the
database user 'bmonterde' can connect to your MySQL server
and has the proper privileges that these tests require such
as 'drop table', 'create table', 'drop procedure', 'create procedure'
as well as others.

mysql> CREATE USER 'bmonterde'@'localhost' IDENTIFIED BY 's3kr1t';
mysql> GRANT ALL PRIVILEGES ON test.* TO 'bmonterde'@'localhost';

You can also optionally set the user to run 'make test' with:

perl Makefile.PL --testuser=username

Can't exec "mysql_config": No such file or directory at Makefile.PL line 420.
Can't find mysql_config. Use --mysql_config option to specify where mysql_config is located
Failed to determine directory of mysql.h. Use

  perl Makefile.PL --cflags=-I<dir>

to set this directory. For details see DBD::mysql::INSTALL,
section "C Compiler flags" or type

  perl Makefile.PL --help
Warning: No success on command[/usr/bin/perl Makefile.PL]
  DVEEDEN/DBD-mysql-5.003.tar.gz
  /usr/bin/perl Makefile.PL -- NOT OK
Failed during this command:
 DVEEDEN/DBD-mysql-5.003.tar.gz               : writemakefile NO '/usr/bin/perl Makefile.PL' returned status 512

Could you please help me to install correctly the module?

Best wishes,

Beatriz

**Comment by olaaustine** [comment] 2024-01-29 17:23
Hi @BeatrizMonterde, 
Because you are using a HPC environment, I will suggest you set up VEP using [docker](http://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#docker) or [singularity](https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#singularity).
Please let us know if this helps.
Thank you 
Ola

**Comment by olaaustine** [comment] 2024-01-31 13:53
Hi @BeatrizMonterde, 
Just a follow up to find out if you have been able to run VEP using docker or singularity. 
Please let us know if you have any issues setting it up. 
Thannk you 
Ola.

**Comment by BeatrizMonterde** [comment] 2024-01-31 14:25
Hi, 

Many thanks for getting in touch. I was finally able to install VEP on the HPC environment. However, now I am facing some issues while trying to annotate the test files. I used the "test.vcf" file provided within the installation and I am trying to annotate the variants with the reference genome GRCh38. However, it seems that the genomic coordinates of the VCF file are not recognised. 

Here I am showing you the command I used:

(ensemblVEP1) [bmonterde@login(alma) ensembl-vep]$ ./vep -i /home/bmonterde/tools/ensembl-vep/t/testdata/input/test.vcf -o test_annotated.vcf --offline --cache --dir_cache /home/bmonterde/.vep/ --assembly GRCh38 --fasta /data/reference-data/iGenomes/Homo_sapiens/GATK/GRCh38/Sequence/WholeGenomeFasta/Homo_sapiens_assembly38.fasta

And this is one of the warnings that appear on the terminal: 

WARNING: line 1 skipped (21 25585733 rs142513484 C T . . . GT 0|0): Chromosome 21 not found in annotation sources or synonyms; chromosome 21 does not overlap any features

I am not sure what might be causing the issue because according to the guidelines that can be found on the website, chromosomes should be indicated with numbers ("1" instead of "chr1") and I have checked that this is correct.

#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  HG00096
21      25585733        rs142513484     C       T       .       .       .     

Hope you can give me a clue of what might be happening,

Best wishes,

Beatriz

**Comment by olaaustine** [comment] 2024-02-01 11:16
Hi @BeatrizMonterde, 
Hope this meets you well? 
I have not been able to recreate this issue using VEP CLI and WEB VEP. 
I suspect the issue is the FASTA file you are using, is it possible to use a different FASTA file?
If possible also can you share the FASTA file?  
Let us know if this helps.
Thank you 
Ola.

**Comment by BeatrizMonterde** [comment] 2024-02-01 16:50
Hi Ola,

Many thanks for your reply. I see what you mean, there might be a problem with the FASTA file that I am using to annotate the variants. You can find it on the following link:
https://drive.google.com/file/d/1c-mL7RZMdiwOKYmtZPMssdPBRgwalQU0/view?usp=sharing
Please do let me know if you can download it. In the meantime, is there a possibility of having access to an FASTA file for the human reference genome (GRCh38) in the ensembl-vep directory? In that way, I could use an alternative FASTA file to check if the program is working in the HPC environment.

Many thanks for your help

Best wishes,

Beatriz

**Comment by olaaustine** [comment] 2024-02-01 17:12
Hi @BeatrizMonterde, 
The instructions to download our FASTA files can be seen [here](https://grch37.ensembl.org/info/docs/tools/vep/script/vep_cache.html#fasta)
Please follow these instructions to download the FASTA file for GRCh38. 
```
curl -O https://ftp.ensembl.org/pub/grch37/release-111/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
gzip -d Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
bgzip Homo_sapiens.GRCh38.dna.primary_assembly.fa
```
Please let us know if this helps. 
Thank you
Ola

**Comment by BeatrizMonterde** [comment] 2024-02-02 15:22
Hi Ola,

Many thanks for your reply. Unfortunately, the link provided is not working. Did you have the chance to test the FASTA file that I was using as reference genome?

Best,

Beatriz

**Comment by BeatrizMonterde** [comment] 2024-02-05 15:47
Hi Ola, 

Many thanks for your reply. I have downloaded and decompressed the fast file, but apparently there is still a problem with the nomenclature of the chromosomes. I do not know what could be the cause, as both the VCF and the FASTA files have chromosomes displayed with numbers ("1" instead of "chr1).

(ensemblVEP1) [bmonterde@node01(alma) ensembl-vep]$ ./vep -i /home/bmonterde/tools/ensembl-vep/t/testdata/input/test.vcf -o tested_annotated.vcf --offline --cache --dir_cache /home/bmonterde/.vep/ --assembly GRCh38 --fasta /data/scratch/DMP/UCEC/EVOLIMMU/bmonterde/Homo_sapiens.GRCh38.dna.primary_assembly.fa
WARNING: line 1 skipped (21 25585733 rs142513484 C T . . . GT 0|0): Chromosome 21 not found in annotation sources or synonyms; chromosome 21 does not overlap any features

**Comment by olaaustine** [comment] 2024-02-05 16:24
Hi @BeatrizMonterde,
Again following the steps, I was not able to recreate this issue.
To debug the issue with your annotation. Can you confirm that when you run the command, an index file is created, which is a file with an extension fa.fai.
If no, can you confirm that you have the module Bio::DB::HTS in your path?
If yes, can you run the command `grep "21" Homo_sapiens.GRCh38.dna.primary_assembly.fa.fai` and send us the output. 
Thank you very much. 
Ola.

**Comment by BeatrizMonterde** [comment] 2024-02-06 12:14
Hi Ola,

Many thanks for your reply.
Yes, I can confirm that an index files was generated after running the command. 

This is the ouput of the grep command on that file
(base) [bmonterde@node01(alma) bmonterde]$ grep "21" Homo_sapiens.GRCh38.dna.primary_assembly.fa.fai
2	242193529	1308554087	60	61
21	46709983	1620302526	60	61
4	190214555	1921057106	60	61
5	181538259	2114441960	60	61
9	138394717	2782218181	60	61
KI270442.1	392061	3142119164	60	61
GL000225.1	211173	3142803414	60	61
KI270743.1	210658	3143018174	60	61
GL000219.1	179198	3145360308	60	61
GL000216.2	176608	3145722420	60	61
GL000213.1	164239	3146774097	60	61
GL000218.1	161147	3147269937	60	61
GL000221.1	155397	3147755432	60	61
GL000214.1	137718	3148668466	60	61
KI270721.1	100316	3149273003	60	61
KI270748.1	93321	3149476155	60	61
KI270753.1	62944	3150217369	60	61
KI270711.1	42210	3150414836	60	61
KI270322.1	21476	3151136370	60	61
KI270521.1	7642	3151211309	60	61
KI270581.1	7046	3151219144	60	61
KI270590.1	4685	3151263210	60	61
KI270382.1	4215	3151277248	60	61
KI270420.1	2321	3151330512	60	61
KI270518.1	2186	3151340115	60	61
KI270530.1	2168	3151342403	60	61
KI270304.1	2165	3151344673	60	61
KI270418.1	2145	3151346940	60	61
KI270424.1	2140	3151349186	60	61
KI270388.1	1216	3151403999	60	61
KI270337.1	1121	3151411588	60	61
KI270385.1	990	3151421679	60	61

Hope it can help to figure out the problem

Best wishes,

Beatriz

**Comment by BeatrizMonterde** [comment] 2024-02-06 17:17
Hi Ola,
Many thanks for your reply. The folder directory corresponding to my cache is the following:
/home/bmonterde/.vep/homo_sapiens/111_GRCh38

And contains these files
(ensemblVEP1) [bmonterde@node01(alma) 111_GRCh38]$ ls
Homo_sapiens.GRCh38.dna.toplevel.fa.gz
Homo_sapiens.GRCh38.dna.toplevel.fa.gz.fai
Homo_sapiens.GRCh38.dna.toplevel.fa.gz.gzi

I don't know if I understood you properly on how to run the dir_cache command, but here's my ouput 

(ensemblVEP1) [bmonterde@node01(alma) ensembl-vep]$ perl vep --dir_cache /home/bmonterde/.vep/homo_sapiens/111_GRCh38/

IMPORTANT INFORMATION:

The VEP can read gene data from either a local cache or local/remote databases.

Using a cache is the fastest and most efficient way to use the VEP. The
included INSTALL.pl script can be used to fetch and set up cache files from the
Ensembl FTP server. Simply run "perl INSTALL.pl" and follow the instructions, or
see the documentation pages listed below.

If you have already set up a cache, use "--cache" or "--offline" to use it.

It is possible to use the public databases hosted at ensembldb.ensembl.org, but
this is slower than using the cache and concurrent and/or long running VEP jobs
can put strain on the Ensembl servers, limiting availability to other users.

To enable using databases, add the flag "--database".

Documentation
Installer: http://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#installer
Cache: http://www.ensembl.org/info/docs/tools/vep/script/index.html#cache

     at /home/bmonterde/tools/ensembl-vep/modules/Bio/EnsEMBL/VEP/Config.pm line 945.

Hope it can shed some light 

Many thanks again for your help

**Comment by olaaustine** [comment] 2024-02-12 10:24
Hi @BeatrizMonterde, 
Hope this meets you well? 
Your cache directory <homo_sapiens>/<111_GRCh38> should contain files such as chr_synonyms.txt. 
If thats not the case, please can you follow these instructions [here](https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#cache:~:text=%2D%2Ddir_cache.-,Indexed%20cache%20(https%3A//ftp.ensembl.org/pub/release%2D111/variation,.tar.gz%0Atar%20xzf%20homo_sapiens_vep_111_GRCh38.tar.gz,-Non%2Dindexed%20cache)
```
cd bmonterde/.vep
curl -O https://ftp.ensembl.org/pub/release-111/variation/indexed_vep_cache/homo_sapiens_vep_111_GRCh38.tar.gz
tar xzf homo_sapiens_vep_111_GRCh38.tar.gz
```
to download indexed cache and point to the directory when you run vep using the option `--dir_cache `
Please let us know if you still have any questions and if this helps. 
Thank you 
Ola.

**Comment by olaaustine** [comment] 2024-02-12 14:07
Hi @BeatrizMonterde, 
Thank you for letting us know the issues has been resolved. 
I will close this issue now. 
Please feel free to reopen another ticket if you have another issue. 
Thank you 
Ola

**Closed by olaaustine** 2024-02-12 14:07 UTC
