### ISSUE TITLE
2-variant VCF causes VEP failure

### ISSUE THREAD

**Issue by MattWellie** [Ensembl/ensembl-vep#1486] opened 2023-08-23 06:13 UTC
## Describe the issue

Identified a variant pair (?) which causes the annotation process to fail

## Additional information
Please fill in the following sections to help us find the source of your issue as quickly as possible.

### System
- VEP version: [105] 
- VEP Cache version: [105]
- OS: [Ubuntu]
- tabix installed ? Yes
- Perl version: [e.g. 5.26] unsure, I can check if it's important

### Full VEP command line

```
vep \
--format vcf \
--json \
-o ${BATCH_TMPDIR}/VEP-75rK7/output \
-i ${BATCH_TMPDIR}/Subset_VCF-kcDO1/output_vcf.vcf.gz \
--everything \
--allele_number \
--minimal \
--cache --offline --assembly GRCh38 \
--dir_cache /cpg-common-main/references/vep/105.0/mount/vep/ \
--dir_plugins $LOFTEE_PLUGIN_PATH \
--fasta $FASTA \
--plugin LoF,loftee_path:$LOFTEE_PLUGIN_PATH,gerp_bigwig:/cpg-common-main/references/vep/105.0/mount/gerp_conservation_scores.homo_sapiens.GRCh38.bw,human_ancestor_fa:/cpg-common-main/references/vep/105.0/mount/human_ancestor.fa.gz,conservation_file:/cpg-common-main/references/vep/105.0/mount/loftee.sql
```

### Full error message

```
Use of uninitialized value $pos in hash element at /root/micromamba/share/ensembl-vep-105.0-1/Bio/EnsEMBL/Variation/ProteinFunctionPredictionMatrix.pm line 343, <$fh> line 3434.
Use of uninitialized value $pos in concatenation (.) or string at /root/micromamba/share/ensembl-vep-105.0-1/Bio/EnsEMBL/Variation/ProteinFunctionPredictionMatrix.pm line 706, <$fh> line 3434.

-------------------- EXCEPTION --------------------
MSG: Invalid position: 
STACK Bio::EnsEMBL::Variation::ProteinFunctionPredictionMatrix::prediction_from_matrix /root/micromamba/share/ensembl-vep-105.0-1/Bio/EnsEMBL/Variation/ProteinFunctionPredictionMatrix.pm:706
STACK Bio::EnsEMBL::Variation::ProteinFunctionPredictionMatrix::get_prediction /root/micromamba/share/ensembl-vep-105.0-1/Bio/EnsEMBL/Variation/ProteinFunctionPredictionMatrix.pm:349
STACK Bio::EnsEMBL::Variation::TranscriptVariationAllele::_protein_function_prediction /root/micromamba/share/ensembl-vep-105.0-1/Bio/EnsEMBL/Variation/TranscriptVariationAllele.pm:1227
STACK Bio::EnsEMBL::Variation::TranscriptVariationAllele::sift_prediction /root/micromamba/share/ensembl-vep-105.0-1/Bio/EnsEMBL/Variation/TranscriptVariationAllele.pm:996
STACK Bio::EnsEMBL::VEP::OutputFactory::add_sift_polyphen /root/micromamba/share/ensembl-vep-105.0-1/modules/Bio/EnsEMBL/VEP/OutputFactory.pm:1669
STACK Bio::EnsEMBL::VEP::OutputFactory::TranscriptVariationAllele_to_output_hash /root/micromamba/share/ensembl-vep-105.0-1/modules/Bio/EnsEMBL/VEP/OutputFactory.pm:1593
STACK Bio::EnsEMBL::VEP::OutputFactory::get_all_VariationFeatureOverlapAllele_output_hashes /root/micromamba/share/ensembl-vep-105.0-1/modules/Bio/EnsEMBL/VEP/OutputFactory.pm:387
STACK Bio::EnsEMBL::VEP::OutputFactory::JSON::add_VariationFeatureOverlapAllele_info /root/micromamba/share/ensembl-vep-105.0-1/modules/Bio/EnsEMBL/VEP/OutputFactory/JSON.pm:300
STACK Bio::EnsEMBL::VEP::OutputFactory::JSON::get_all_output_hashes_by_InputBuffer /root/micromamba/share/ensembl-vep-105.0-1/modules/Bio/EnsEMBL/VEP/OutputFactory/JSON.pm:244
STACK Bio::EnsEMBL::VEP::OutputFactory::get_all_lines_by_InputBuffer /root/micromamba/share/ensembl-vep-105.0-1/modules/Bio/EnsEMBL/VEP/OutputFactory.pm:262
STACK Bio::EnsEMBL::VEP::Runner::_buffer_to_output /root/micromamba/share/ensembl-vep-105.0-1/modules/Bio/EnsEMBL/VEP/Runner.pm:421
STACK Bio::EnsEMBL::VEP::Runner::next_output_line /root/micromamba/share/ensembl-vep-105.0-1/modules/Bio/EnsEMBL/VEP/Runner.pm:369
STACK Bio::EnsEMBL::VEP::Runner::run /root/micromamba/share/ensembl-vep-105.0-1/modules/Bio/EnsEMBL/VEP/Runner.pm:207
STACK toplevel /root/micromamba/bin/vep:232
Date (localtime)    = Tue Jul 11 22:52:04 2023
Ensembl API version = 105
```

### Data files (if applicable) 

[repro_vcf.vcf.gz](https://github.com/Ensembl/ensembl-vep/files/12415781/repro_vcf.vcf.gz)

This contains two variant lines:

```
chr6	138804582	rs369363624	AAC	AACACAC,AACAC,AACACACACACACAC,A,AACACACAC,AACACACACAC
chr6	138814572	.	A	AT
```

These two variants together in the VCF causes VEP to explode. Each one independently can be annotated fine. We have overcome this by normalising the variants out onto separate rows. In the original VCF these variants were not adjacent, and it took some extensive reduction work to find the minimal variant representation to cause this failure.

Thanks!

**Comment by nakib103** [comment] 2023-08-23 14:29
Hello @MattWellie ,

Thanks for your query!

Unfortunately I cannot reproduce the issue. 
- Are you sure these are the two variants that is causing the issue? they are quite far from each other and not "originating at same position".
- Nevertheless, protein function matrix hold already calculated scores from database/cache and shows result if there is an amino acid substitution - see [here](https://www.ensembl.org/info/genome/variation/prediction/protein_function.html). Each variant record is looked at separately.

It seems like a different issue as it is failing to get the affected protein position. Can you try re-installing the cache and fasta and see if that resolves the issue?

Best regards,
Nakib

**Comment by MattWellie** [comment] 2023-08-24 00:16
Hey @nakib103,

Sorry, I was being a big ol' idiot yesterday and my eyes were skipping over most of the digits in those coordinates... I've updated the issue to clarify that the variants definitely do not share a start coordinate, but that was after you'd already assigned the ticket 🤦 

This VCF snippet I added to this issue was passed to us from another site, and it can reproducibly cause annotation failures at both locations. I'll check with them to see if we are using the exact same cache files.

In a local docker container I can successfully annotate this VCF with remote DB sources, so it could definitely be an issue with our cache files. Remote sources succeed in both our VEP 105 and `ensembl-vep:latest` (110) images.

**Comment by nakib103** [comment] 2023-08-24 08:29
Great to hear that you have identified the issue. Yes, please check if you are using the correct cache files.

You can follow the documentation to download cache file if need be -
https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#cache
You can either use the `INSTALL.pl` script to download the cache or do the downloading manually.

Best regards,
Nakib

**Comment by nakib103** [comment] 2023-09-12 07:53
Hi @MattWellie,
I am closing this issue, if you face any further problems please create another one and let us know.

Best regards,
Nakib

**Closed by nakib103** 2023-09-12 07:53 UTC
