### ISSUE TITLE
 Use of uninitialized value in subroutine entry at /opt/vep/src/ensembl-vep/Bio/EnsEMBL/Variation/Utils/BaseVepTabixPlugin.pm line 358, <__ANONIO__> line 15452.

### ISSUE THREAD

**Issue by antonkulaga** [Ensembl/ensembl-vep#912] opened 2020-12-31 23:23 UTC
I have got >800MB of logs with:
```
 Use of uninitialized value in subroutine entry at /opt/vep/src/ensembl-vep/Bio/EnsEMBL/Variation/Utils/BaseVepTabixPlugin.pm line 358, <__ANONIO__> line 15452.
```
Such error is not really exlainable.
The logs are: http://agingkills.eu:8001/data/cromwell-executions/vep_annotations/7bd129b5-c51b-469a-ac04-2c46dd59409a/call-vep/execution//stderr
The command is: http://agingkills.eu:8001/data/cromwell-executions/vep_annotations/7bd129b5-c51b-469a-ac04-2c46dd59409a/call-vep/execution//script

**Comment by antonkulaga** [comment] 2021-01-01 20:11
My current hypothesis that it may have something to do with Phenotypes plugin. But the log does not explicitly say it.

**Comment by aparton** [comment] 2021-01-04 17:26
Hi @antonkulaga,

I'm unable to reproduce this issue at my end I'm afraid. Could you please send me a sample of your input file that reproduces this issue and I can take a closer look?

Kind Regards,
Andrew

**Comment by antonkulaga** [comment] 2021-01-04 17:35
@aparton all the scripts and inputs are evaluable with the links I provided to you:  http://agingkills.eu:8001/data/cromwell-executions/vep_annotations/7bd129b5-c51b-469a-ac04-2c46dd59409a/call-vep Inputs are in the inputs folder, stdour/stderr and commands are in the execution folder

**Comment by nuno-agostinho** [comment] 2022-04-29 11:23
Hi @antonkulaga!

Could you please send the input/output again? The links are currently not working.

I am sorry for the inconvenience.

Thanks,
Nuno

**Comment by diegomscoelho** [comment] 2022-08-04 08:12
Hi @antonkulaga,

Closing this issue now since we don't have access anymore to logs and inputs. If you have this problem again, please feel free to reopen this issue.

Regards, @diegomscoelho

**Closed by diegomscoelho** 2022-08-04 08:12 UTC
