### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by EugenieD** [Ensembl/ensembl-vep#32] opened 2017-03-23 17:39 UTC
Installation (`perl INSTALL.pl`) fails with the following errors:

```
#   Failed test 'get current git branch'
#   at ./t/version.t line 31.
# Looks like you failed 1 test of 1.
./t/version.t ........................................ Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests 

Test Summary Report
-------------------
./t/version.t                                      (Wstat: 256 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
Files=37, Tests=1441, 126 wallclock secs ( 0.36 usr  0.17 sys + 113.54 cusr  9.03 csys = 123.10 CPU)
Result: FAIL
Failed 1/37 test programs. 1/1441 subtests failed.
```

adding --NO_HTSLIB doesn't help.

Please can anyone suggest what may be the problem?

Thank you!

P.S. perl v5.20.2; DBI package installed

**Comment by ens-lgil** [comment] 2017-03-28 09:37
@EugenieD, which version of ensembl-vep are you using ? release/87 ?
Did you downloaded the ensembl-vep git repository using the following commmands ?
*git clone git@github.com:Ensembl/ensembl-vep.git*
or 
*git clone https://github.com/Ensembl/ensembl-vep.git*

**Comment by willmclaren** [comment] 2017-04-03 11:13
Duplicate of https://github.com/Ensembl/ensembl-vep/issues/17

**Closed by willmclaren** 2017-04-03 11:13 UTC
