### ISSUE TITLE
Use of uninitialized value $ensembl_metadata_db nighmare

### ISSUE THREAD

**Issue by antonkulaga** [Ensembl/ensembl-vep#738] opened 2020-04-18 22:13 UTC
For some reason, vep always throws:
```
Use of uninitialized value $ensembl_metadata_db in concatenation (.) or string at /opt/vep/src/ensembl-vep/Bio/EnsEMBL/Registry.pm line 2363.
```
I have no idea what this error is about. I've tried to change parameters multiple times but without any success. It is also very weird that the vep does not terminate with proper code, so the docker container keeps running forever despite VEP beeing crashed

Here is how my command looks like
```
vep --verbose \
--input_file /cromwell-executions/annotations/a8ad0155-8c41-47c5-8eaa-6239629153a5/call-vep_annotation/inputs/-680350980/variants.vcf.gz -o antonkulaga_variant_annotations.tsv --tab --species homo_sapiens --fork 8 --everything --cache --dir_cache /cromwell-executions/annotations/a8ad0155-8c41-47c5-8eaa-6239629153a5/call-vep_annotation/inputs/-886638935/cache --dir_plugins /cromwell-executions/annotations/a8ad0155-8c41-47c5-8eaa-6239629153a5/call-vep_annotation/inputs/-886638935/plugins
```
I run it from Cromwell with ensemblorg/ensembl-vep:release_99.2 container. I also downloaded the cache which Ensembl recommended me to download ( i.e. human from ftp://ftp.ensembl.org/pub/release-99/variation/vep/ )

**Comment by aparton** [comment] 2020-04-20 10:26
Hi,

Thanks for this report. While I can't reproduce your issue currently, I think I can see what's going on and there are a few things to consider here.

1) The message that you're seeing is a warning rather than an error - VEP is unable to find an associated metadata database and is failing to print a warning message. This should be a purely cosmetic issue, and is not the reason why your VEP keeps running forever, so we'll need to get to the bottom of that one. I suspect that there is a connection issue caused by the Cromwell/Docker configuration, but there are a few things we can do to try and narrow it down.

Could you please send me the entire output of your verbose command (printed to STDOUT)?

2) As a workaround, you may be able to avoid accessing the database entirely. This can be done by adding a fasta file (with `--fasta filename.fa`) and specifying offline (`--offline`).

Kind Regards,
Andrew

**Comment by aparton** [comment] 2020-06-25 13:27
Hi,

I'm going to close this ticket now. If you have any further questions, please feel free to reopen it or create a new one.

Kind Regards,
Andrew

**Closed by aparton** 2020-06-25 13:27 UTC
