### ISSUE TITLE
VEP does not get CADD values for certain variants

### ISSUE THREAD

**Issue by m-blanes** [Ensembl/ensembl-vep#1187] opened 2022-05-23 06:52 UTC
## Describe the issue
VEP is working fine with SNPs and with most of INDELs, but for some INDELs it is not getting CADD values.

I have selected 3 of these INDELs in GRCh38 which CADD values (PHRED | RAW) are extracted from "All gnomad release 3.0 InDels to initiate a local setup" file from [CADD webpage](https://cadd.gs.washington.edu/download).

All of their CADD values appear empty in VEP output:
chr2	210556728	A	ATCT 15.45|1.455695
chr3	42210085	C	CGGAGGA 15.06|1.396511
chr5	61332326	G	GGGC 19.27|2.002242
gnomad.genomes.r3.0.indel.tsv.gz
## Additional information
This is not working for the system features which appear in the next section. But also I have tested it with an older VEP version (v98), and it does work fine for that version. I have attached both output files (for v104.3 and v98).

### System
- VEP version: 104.3
- VEP Cache version: 104
- Perl version: 5.30.3
- OS: Rocky Linux 8.4 (Green Obsidian)
- tabix installed: Yes

### Full VEP command line
```
vep \
	-i ${DIRoutput}/missing_FT3.vcf \
	-o ${DIRoutput}/missing_FT3.vep.vcf \
	--dir_plugins ${DIR_plugins}/.vep/Plugins \
	--dir_cache ${DIR_cache} \
	--cache_version 104 \
	--plugin CADD,${DIR_annotations}/whole_genome_SNVs.tsv.gz,${DIR_annotations}/InDels.tsv.gz \
    --vcf --fork 4 --force_overwrite --merged --cache --use_given_ref --distance 0 --symbol --check_existing --assembly $ASSEMBLY --offline --show_ref_allele \
	--hgvs --hgvsg \
	--fasta ${DIR_reference}/reference.fa \
	--pick --pick_order rank,canonical,appris,tsl,biotype,ccds,length,mane
```

### Full error message
There is no error message.

### Data files (if applicable)
They include:
- The input file: input.vcf
- The output file v104 (CADD values do not appear): output_v104.vep.vcf
- The output file v98 (CADD values do appear): output_v98.vep.vcf
[cadd_issue_vep.zip](https://github.com/Ensembl/ensembl-vep/files/8752112/cadd_issue_vep.zip)

**Comment by dglemos** [comment] 2022-05-23 15:19
Hi @m-blanes,
The issue is being caused by the options --hgvs and --hgvsg. We are working on a fix, I'll let you know when the fix is in place.

**Comment by m-blanes** [comment] 2022-05-24 06:13
Hi @dglemos, 
Thank you so much for your quick response and solving my doubt.
In that case, I will try to find a temporary solution until the fix is available.

**Comment by diegomscoelho** [comment] 2022-06-16 08:01
Hi @m-blanes,

This issue was fixed in our last PR - https://github.com/Ensembl/ensembl-variation/pull/814. This solution will be released at release/108.

Thanks for reporting this bug,

@diegomscoelho

**Closed by diegomscoelho** 2022-06-16 08:01 UTC
