### ISSUE TITLE
Use of uninitialized value warning issued by plugins/Conservation.pm

### ISSUE THREAD

**Issue by rraadd88** [Ensembl/ensembl-vep#1752] opened 2024-09-06 15:28 UTC
## Describe the issue

Warnings issued but the output is generated. Therefore not sure if the output is correct.

### System
- VEP version: 112
- VEP Cache version: 112
- Perl version: 5.34.0
- OS: Linux version 6.10.4-linuxkit (root@buildkitsandbox) (gcc (Alpine 13.2.1_git20240309) 13.2.1 20240309, GNU ld (GNU Binutils) 2.42) (docker in MacOS)
- tabix installed: yes

### Full VEP command line
```
vep -i input.txt -o test_conservation.txt --species homo_sapiens --assembly GRCh38 --cache --dir_cache /opt/vep/.vep --offline --plugin Conservation,/opt/vep/.vep/db/Conservation/gerp_conservation_scores.homo_sapiens.GRCh38.bw --force_overwrite
```

### Full error message

    Use of uninitialized value in subtraction (-) at /plugins/Conservation.pm line 214, <__ANONIO__> line 3.
    Use of uninitialized value in subtraction (-) at /plugins/Conservation.pm line 214, <__ANONIO__> line 3.
    Use of uninitialized value $values[0] in sprintf at /plugins/Conservation.pm line 250, <__ANONIO__> line 3.
    Use of uninitialized value in subtraction (-) at /plugins/Conservation.pm line 214, <__ANONIO__> line 3.
    Use of uninitialized value in subtraction (-) at /plugins/Conservation.pm line 214, <__ANONIO__> line 3.
    Use of uninitialized value $values[0] in sprintf at /plugins/Conservation.pm line 250, <__ANONIO__> line 3.
    Use of uninitialized value in subtraction (-) at /plugins/Conservation.pm line 214, <__ANONIO__> line 3.
    Use of uninitialized value in subtraction (-) at /plugins/Conservation.pm line 214, <__ANONIO__> line 3.
    Use of uninitialized value $values[0] in sprintf at /plugins/Conservation.pm line 250, <__ANONIO__> line 3.

### Data files (if applicable)
They include:
- The input file
[input.txt](https://github.com/user-attachments/files/16910002/input.txt)

- The output file
[test_conservation.txt](https://github.com/user-attachments/files/16910003/test_conservation.txt)

**Comment by olaaustine** [comment] 2024-09-09 10:15
Hi @rraadd88, 

Hope this meets you well? 
Thank you for sharing your input file. 
I have been able to reproduce this issue. 
The issue is those variant do not have Conservation score but still getting 0.0 assigned. As you can see in your output file, you have some variant with conservation score` Conservation=0.000` . 
This issue does not impact the output for variants that have a conservation score.
This issue has been rectified here [VEP plugins 734](https://github.com/Ensembl/VEP_plugins/pull/734)  and should be available in the next release.
Thank you 
Ola.

**Comment by olaaustine** [comment] 2024-09-10 08:11
Hi @rraadd88, 
I am going to close this ticket now. 
Please feel free to open another ticket if you have any other questions/issues. 
Thank you 
Ola.

**Closed by olaaustine** 2024-09-10 08:11 UTC
