### ISSUE TITLE
Use of uninitialized value in numeric lt (<) at 

### ISSUE THREAD

**Issue by worker000000** [Ensembl/ensembl-vep#896] opened 2020-12-04 12:19 UTC
linux ; docker vep; vep cache version 99

docker run  --rm --user  `id -u`:`id -g` -v /:/data ensemblorg/ensembl-vep vep  --input_file /data//data/neo/test/test_vep/vcf_merge/phased.vcf.gz  --output_file /data/test.vep.vcf  --dir_cache /data//database/vep_data_release_99/  --dir_plugins /data//database/vep_data_release_99/VEP_plugins-release-99 --symbol  --fasta /data/database/genomeV37/BWAIndex/human_g1k_v37.fasta  --offline  --cache  --transcript_version  --plugin Downstream  --plugin Wildtype  --force_overwrite --vcf --variant_class --gene_phenotype --hgvs --hgvsg --transcript_version  --vcf_info_field ANN  --refseq --assembly GRCh37 --format vcf --cache_version 99 --keep_csq

this gives me one warnning and maybe several errors.
1  I used my own reference to avoid the ref base difference. I do not know whether it is recommended. and should I do as 
 it tells "use_transcript_ref; use --use_given_ref to override this"

2  how the Use of uninitialized value comes out

thanks a lot

![image](https://user-images.githubusercontent.com/25199946/101162817-c5097a80-366d-11eb-8918-7eff7db4b4ae.png)

**Comment by dglemos** [comment] 2020-12-04 13:04
Hi,

1) The message `INFO: BAM-edited cache detected...` is not a warning. By default, VEP uses the reference allele provided in the input file to calculate consequences for the provided alternate allele(s). Using RefSeq cache enables `--use_transcript_ref` which forces VEP to replace the provided reference allele with sequence derived from the overlapped transcript. But you can choose to override this behavior with the option `--use_given_ref` to use the provided reference allele from the input. 

2) Can you send an example of your input file so we can understand what's happening with the plugin?

**Comment by 2236529177** [comment] 2020-12-05 04:22
after many tests of combinations with different arguments
I found it maybe caused by the arguments --hgvs --hgvsg. because after deleting it, the errors disappears. why this happens.

how can I send my vcf to you

thanks a lot

**Comment by 2236529177** [comment] 2020-12-09 16:11
any response?
thanks a lot

**Comment by dglemos** [comment] 2020-12-09 17:44
I'm looking into the issue now. In the meantime, you can send your input file to this address helpdesk [at] ensembl.org and refer to vep issue 896.

**Comment by dglemos** [comment] 2020-12-09 19:51
> 1 after many tests of combinations with different arguments
I found it maybe caused by the arguments --hgvs --hgvsg. because after deleting it, the errors disappears. why this happens.

Can you tell which errors you mean? Are they the message `Use of uninitialized value in numeric lt (<) at (...)`?

**Comment by 2236529177** [comment] 2020-12-10 01:03
thanks a lot
_errors emphasised in bold_

' **ERROR: There was a mismatch between the actual wildtype amino acid sequence (L) and the expected amino acid sequence (V). Did you use the same reference build version for VEP that you used for creating the VCF?**
OrderedDict([('chromosome_name', '2'), ('start', '38298202'), ('stop', '38298203'), ('reference', 'C'), ('variant', 'G'), ('gene_name', 'CYP1B1'), ('transcript_name', 'NM_000104.3'), ('transcript_support_level', 'NA'), ('amino_acid_change', 'V/L'), ('codon_change', 'Gtg/Ctg'), ('ensembl_gene_id', '1545'), ('hgvsc', ''), ('hgvsp', ''), ('wildtype_amino_acid_sequence', 'MGTSLSPNDPWPLNPLSIQQTTLLLLLSVLATVHVGQRLLRQRRRQLRSAPPGPFAWPLIGNAAAVGQAAHLSFARLARRYGDVFQIRLGSCPIVVLNGERAIHQALVQQGSAFADRPAFASFRVVSGGRSMAFGHYSEHWKVQRRAAHSMMRNFFTRQPRSRQVLEGHVLSEARELVALLVRGSADGAFLDPRPLTVVAVANVMSAVCFGCRYSHDDPEFRELLSHNEEFGRTVGAGSLVDVMPWLQYFPNPVRTVFREFEQLNRNFSNFILDKFLRHCESLRPGAAPRDMMDAFILSAEKKAAGDSHGGGARLDLENVPATITDIFGASQDTLSTALQWLLLLFTRYPDVQTRVQAELDQVVGRDRLPCMGDQPNLPYVLAFLYEAMRFSSFVPVTIPHATTANTSVLGYHIPKDTVVFVNQWSVNHDPLKWPNPENFDPARFLDKDGLINKDLTSRVMIFSVGKRRCIGEELSKMQLFLFISILAHQCDFRANPNEPAKMNFSYGLTIKPKSFKVNVTLRESMELLDSAVQNLQAKETCQ'), ('downstream_amino_acid_sequence', ''), ('fusion_amino_acid_sequence', ''), ('variant_type', 'missense'), ('protein_position', '432'), ('transcript_expression', 'NA'), ('gene_expression', 'NA'), ('normal_depth', 'NA'), ('normal_vaf', 'NA'), ('tdna_depth', '1477'), ('tdna_vaf', '0.998645903859174'), ('trna_depth', 'NA'), ('trna_vaf', 'NA'), ('index', '129.CYP1B1.NM_000104.3.missense.432V/L'), ('protein_length_change', '')]) '

I tried many vcfs, but the similar question happens, how can I prevent this?

**Comment by dglemos** [comment] 2020-12-10 12:03
The error is thrown by a tool that we don't support. If you have specific questions about that tool I recommend you to ask the team responsible for pvactools. But I can see that you are using the RefSeq cache. When using this cache for the variant `2 38298202 C/G` the amino acid change is NP_000095.2:p.**Leu**432Pro, however if you use the Ensembl cache the change is `ENSP00000260630.3:p.**Val**432Ala` and `ENSP00000384972.1:p.**Val**432Ala`. In this specific example, there is a mismatch between RefSeq and Ensembl sequences.  
Could you try running VEP with the Ensembl cache and see if the error is still there?

**Comment by 2236529177** [comment] 2020-12-10 13:57
thanks  a lot
yes, this tool need vep annotate first, I used vep annotation, there is no error,
but when pass vep annotation result to the tools, it gives such errors

I used all the files from ensemble, but I used human_g1k_v37.fasta as reference to call variant by varscan

here is my command  of vep 
`
docker run  --rm --user  `id -u`:`id -g` -v /:/data ensemblorg/ensembl-vep vep  --input_file /data/data/neo/test/test_vep/vcf_merge/phased.vcf.gz  --output_file /data/data/neo/test/test_vep/vcf_merge/test.vep.vcf --dir_cache /data/database/vep_data_release_99/  --dir_plugins /data/database/vep_data_release_99/VEP_plugins-release-99 --symbol  --fasta /data/database/genomeV37/BWAIndex/human_g1k_v37.fasta   --offline  --cache  --transcript_version  --plugin Downstream  --plugin Wildtype  --force_overwrite --vcf --variant_class   --transcript_version   --refseq --assembly GRCh37 --format vcf --cache_version 99 --keep_csq --use_given_ref --tsl --terms SO  --vcf --pick`

**Comment by 2236529177** [comment] 2020-12-10 14:29
when I want to use vep Homo_sapiens.GRCh37.dna.primary_assembly.fa. it has 2 errors
1 the order of the chromosome is not right, so I rewrite the genome by command
`perl -e 'use File::Temp qw/tempdir/; use IO::File; $d=tempdir; $fh; map{if(m/^\>(\S+)\s/){$fh=IO::File->new(">$d/$1.fa");} print $fh $_;}`cat Homo_sapiens.GRCh37.dna.primary_assembly.fa`; foreach $c(1..22,X,Y,MT){print `cat $d/$c.fa`}; print `cat $d/GL*`' > Homo_sapiens.GRCh37.dna.primary_assembly.reordered.fa
`
2 because I need to realign my bam to some  known indel.vcf. it gives errors like following,
![image](https://user-images.githubusercontent.com/25199946/101784916-18307100-3b37-11eb-8aab-3420f61cebc5.png)
<br> so i delete the **GL contig** and rerun, but the same error happens, really surprised, can you help me 

thanks a lot

**Comment by dglemos** [comment] 2020-12-10 15:03
I didn't see any email with your input file. Can you send it again to his email helpdesk [at] ensembl.org and refer to vep issue 896?

**Comment by 2236529177** [comment] 2020-12-10 16:21
thanks a lot
I have sent it yo you now by a gmail
![image](https://user-images.githubusercontent.com/25199946/101799163-cabc0000-3b46-11eb-92ad-6634e146bb34.png)

**Comment by dglemos** [comment] 2020-12-10 17:05
In your email, you forgot to annex the VEP input vcf (phased.vcf.gz). You only sent a file with the commands you run. 
I can see from your commands that you ran several tools we don't support (ex: pvactools and GATK4). If your errors are generated by tools other than VEP, then you should ask for help directly from the teams responsible for those tools.

**Comment by 2236529177** [comment] 2020-12-11 01:13
thanks a lot
could you refresh, I have send that file, here is the screeshoot
![image](https://user-images.githubusercontent.com/25199946/101848674-0aa7d500-3b91-11eb-8cd3-dad92cd6669c.png)

**Comment by 2236529177** [comment] 2020-12-11 08:04
Here I want to give a extremely important issue.
This time I used the vep Homo_sapiens.GRCh37.dna.primary_assembly.reordered.fa(the downloaded chromosome order is not right, so I reorder it) to use as reference to call variant by varscan, and I use the vep to annotate with the same release, but it really surprised me, the same error haeppens, I really can not understand this. because I think vep transcripts cache created by vep genome, hers is Homo_sapiens.GRCh37.dna.primary_assembly.reordered.fa. so why here still reports


ERROR: There was a mismatch between the actual wildtype amino acid sequence (L) and the expected amino acid sequence (V). Did you use the same reference build version for VEP that you used for creating the VCF?
OrderedDict([('chromosome_name', '2'), ('start', '38298202'), ('stop', '38298203'), ('reference', 'C'), ('variant', 'G'), ('gene_name', 'CYP1B1'), ('transcript_name', 'NM_000104.3'), ('transcript_support_level', 'NA'), ('amino_acid_change', 'V/L'), ('codon_change', 'Gtg/Ctg'), ('ensembl_gene_id', '1545'), ('hgvsc', ''), ('hgvsp', ''), ('wildtype_amino_acid_sequence', 'MGTSLSPNDPWPLNPLSIQQTTLLLLLSVLATVHVGQRLLRQRRRQLRSAPPGPFAWPLIGNAAAVGQAAHLSFARLARRYGDVFQIRLGSCPIVVLNGERAIHQALVQQGSAFADRPAFASFRVVSGGRSMAFGHYSEHWKVQRRAAHSMMRNFFTRQPRSRQVLEGHVLSEARELVALLVRGSADGAFLDPRPLTVVAVANVMSAVCFGCRYSHDDPEFRELLSHNEEFGRTVGAGSLVDVMPWLQYFPNPVRTVFREFEQLNRNFSNFILDKFLRHCESLRPGAAPRDMMDAFILSAEKKAAGDSHGGGARLDLENVPATITDIFGASQDTLSTALQWLLLLFTRYPDVQTRVQAELDQVVGRDRLPCMGDQPNLPYVLAFLYEAMRFSSFVPVTIPHATTANTSVLGYHIPKDTVVFVNQWSVNHDPLKWPNPENFDPARFLDKDGLINKDLTSRVMIFSVGKRRCIGEELSKMQLFLFISILAHQCDFRANPNEPAKMNFSYGLTIKPKSFKVNVTLRESMELLDSAVQNLQAKETCQ'), ('downstream_amino_acid_sequence', ''), ('fusion_amino_acid_sequence', ''), ('variant_type', 'missense'), ('protein_position', '432'), ('transcript_expression', 'NA'), ('gene_expression', 'NA'), ('normal_depth', 'NA'), ('normal_vaf', 'NA'), ('tdna_depth', '0'), ('tdna_vaf', '0.0'), ('trna_depth', 'NA'), ('trna_vaf', 'NA'), ('index', '37.CYP1B1.NM_000104.3.missense.432V/L'), ('protein_length_change', '')])


![image](https://user-images.githubusercontent.com/25199946/101878418-7fe3cc00-3bca-11eb-8321-10e7ed8f0816.png)


this error is the same as I used human_g1k_v37.fasta

does it mean vep may generate the wrong reference?

thanks a lot

**Comment by dglemos** [comment] 2020-12-11 11:11
I can see the files now. 
- Could you please run your VEP command again but this time using the flag `--use_given_ref` to allow VEP to use the provided reference allele from your input file? 
- After that try to run pvactools, this time with the new output from VEP.

**Comment by 2236529177** [comment] 2020-12-11 11:21
docker run --rm --user `id -u`:`id -g` -v /:/data ensemblorg/ensembl-vep vep --input_file /data//data/neo/test/test_vep/vcf_merge/new_genome_vcf/KR618V200516FFPE/varscan/new_genome/KR618V200516FFPE_phased.vcf.gz  --output_file /data//data/neo/test/test_vep/vcf_merge/new_genome_vcf/KR618V200516FFPE/varscan/new_genome/KR618V200516FFPE.vep.vcf --dir_cache /data/database/vep_data_release_99/  --dir_plugins /data/database/vep_data_release_99/VEP_plugins-release-99 --symbol  --fasta /data//database/vep_data_release_99/Homo_sapiens.GRCh37.dna.primary_assembly/Homo_sapiens.GRCh37.dna.primary_assembly.reordered.fa --offline  --cache  --transcript_version  --plugin Downstream  --plugin Wildtype  --force_overwrite --vcf --variant_class --transcript_version --refseq --assembly GRCh37 --format vcf --cache_version 99 --keep_csq --use_given_ref --tsl --terms SO  --vcf --pick

<br>
I always used --use_given_ref 

thanks a lot

**Comment by dglemos** [comment] 2020-12-11 12:14
I'm sorry I didn't notice you were already using the flag. Can you send your VEP output file?

**Comment by 2236529177** [comment] 2020-12-11 12:15
I have sent a new email to you, it contains more detailed information of the error.


the theme of the email is   **vep issue 896, thanks ma lot**

**Comment by 2236529177** [comment] 2020-12-11 12:18
> I'm sorry I didn't notice you were already using the flag. Can you send your VEP output file?

![image](https://user-images.githubusercontent.com/25199946/101902682-02ca4e00-3bee-11eb-91cc-b80f86c088d5.png)

**Comment by dglemos** [comment] 2020-12-11 12:29
I can see you are using the flag `--use_given_ref`. 
It would be helpful to see what is in your VEP output. Can you just send your VEP output file that contains the variant `2 38298203 C/G`?

**Comment by 2236529177** [comment] 2020-12-11 12:33
thanks  a lot
<br>
2	38298203	.	C	G	.	PASS	ADP=1477;HET=0;HOM=1;NC=0;WT=0;CSQ=G|missense_variant|MODERATE|CYP1B1|1545|Transcript|NM_000104.3|protein_coding|3/3||||1697|1294|432|V/L|Gtg/Ctg|||-1||SNV|EntrezGene|||||||MGTSLSPNDPWPLNPLSIQQTTLLLLLSVLATVHVGQRLLRQRRRQLRSAPPGPFAWPLIGNAAAVGQAAHLSFARLARRYGDVFQIRLGSCPIVVLNGERAIHQALVQQGSAFADRPAFASFRVVSGGRSMAFGHYSEHWKVQRRAAHSMMRNFFTRQPRSRQVLEGHVLSEARELVALLVRGSADGAFLDPRPLTVVAVANVMSAVCFGCRYSHDDPEFRELLSHNEEFGRTVGAGSLVDVMPWLQYFPNPVRTVFREFEQLNRNFSNFILDKFLRHCESLRPGAAPRDMMDAFILSAEKKAAGDSHGGGARLDLENVPATITDIFGASQDTLSTALQWLLLLFTRYPDVQTRVQAELDQVVGRDRLPCMGDQPNLPYVLAFLYEAMRFSSFVPVTIPHATTANTSVLGYHIPKDTVVFVNQWSVNHDPLKWPNPENFDPARFLDKDGLINKDLTSRVMIFSVGKRRCIGEELSKMQLFLFISILAHQCDFRANPNEPAKMNFSYGLTIKPKSFKVNVTLRESMELLDSAVQNLQAKETCQ	GT:ABQ:AD:ADF:ADR:AF:DP:FREQ:GQ:PVAL:RBQ:RD:RDF:RDR:SDP	1/1:37:0,0:732:743:0:0:99.86%25:99:0E0:37:1:1:0:1477

**Comment by dglemos** [comment] 2020-12-11 12:56
I'm not familiar with the Wildtype plugin but it seems to have an `L` in position 432 of the protein. Using the flag `--use_given_ref` VEP predicts a `V` in that position. Can you try running VEP again without `--use_given_ref` and see if pvactools still throws the error?

**Comment by 2236529177** [comment] 2020-12-11 16:00
thanks a lot
can you have a look at this issue https://github.com/griffithlab/pVACtools/issues/611
it talks about the issuse confusions in vep. here is some screen shot.
so the main question is for grch37, which release of vep cache and dna should I use
![image](https://user-images.githubusercontent.com/25199946/101925471-dd007180-3c0c-11eb-9170-885754909052.png)

**Comment by dglemos** [comment] 2020-12-16 17:08
We advise updating your VEP version to the latest version 102. 
As for the fast file, you could use [Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz](http://ftp.ensembl.org/pub/release-102/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz)  to align your reads and run VEP using the Ensembl transcript set instead of RefSeq. 
Here you can find the latest VEP caches: http://ftp.ensembl.org/pub/release-102/variation/indexed_vep_cache/ 

If you prefer to keep using GRCh37, you should be aware that Ensembl stopped updating the geneset on GRCh37 at release 75. Only the variation and regulation data are updated once or twice a year on GRCh37. This can introduce some limitations that's why we advise switching to GRCh38.

**Comment by worker000000** [comment] 2020-12-17 07:52
thanks a lot.

here geneset refer to what

> Ensembl stopped updating the geneset on GRCh37 at release 75

<br>
ftp://ftp.ensembl.org/pub/grch37/release-99/variation/vep/homo_sapiens_refseq_vep_99_GRCh37.tar.gz
ftp://ftp.ensembl.org/pub/grch37/release-99/fasta/homo_sapiens/dna/Homo_sapiens.GRCh37.dna.primary_assembly.fa.gz
<br>
ftp://ftp.ensembl.org/pub/grch37/release-99/variation/vep/homo_sapiens_vep_99_GRCh37.tar.gz  refer ro 

> Only the variation

bur what regulation refer to

> regulation data are updated

**Comment by dglemos** [comment] 2020-12-18 15:57
> here geneset refer to what

The transcript annotations. 

> bur what regulation refer to

Regulatory features are also included in the cache. The cache contains all transcript models, regulatory features and variant data for a species. Here you can see which data is stored in the cache files: https://m.ensembl.org/info/docs/tools/vep/script/vep_cache.html

**Comment by worker000000** [comment] 2020-12-19 15:11
thanks a lot.
I am still confused. I mean I can download 
homo_sapiens_vep_99_GRCh37.tar.gz
homo_sapiens_refseq_vep_99_GRCh37.tar.gz
homo_sapiens_merged_vep_99_GRCh37.tar.gz
all this labeled version 99

1  and you said transcript annotations  stopped updating the geneset on GRCh37 at release 75, so you mean from 75 to 102 , it is the same of this? 
2  and does  transcript annotations mean the file homo_sapiens_refseq_vep_99_GRCh37.tar.gz? in fact I do not know when I st thedir_cache, which file it used, I know homo_sapiens_vep_99_GRCh37.tar.gz must be used, and refseq and merged maybe used buy the option of vep command?

so cache in the following refer to which file, just one or two zip file?
```
The cache stores the following information:

Transcript location, sequence, exons and other attributes
Gene, protein, HGNC and other identifiers for each transcript (where applicable, limitations apply to RefSeq caches)
Locations, alleles and frequencies of existing variants
Regulatory regions
Predictions and scores for SIFT, PolyPhen
```

3  by the way, I can see cache contains a lot of database, but in fact I just download the three gz file， so does it contains all the file listed in the picture? 

![image](https://user-images.githubusercontent.com/25199946/102692522-ca122080-424e-11eb-886b-35b9d56040d9.png)

<br>
4 I tried to open file in the unzip files of the above , but it says it is binary, how can i open it?
<br >
5 when doing hgvs, it needs the fasta file, so it needs to generate the hgvs, but not read from the cache directly?

**Comment by dglemos** [comment] 2021-01-04 11:45
> homo_sapiens_vep_99_GRCh37.tar.gz
> homo_sapiens_refseq_vep_99_GRCh37.tar.gz
> homo_sapiens_merged_vep_99_GRCh37.tar.gz
> all this labeled version 99
> 
> 1 and you said transcript annotations stopped updating the geneset on GRCh37 at release 75, so you mean from 75 to 102 , it is the same of this?

The transcript annotations for GRCh37 have been the same since release 75 which means it's the same as release 99 and 102. Only the variation and regulation data are updated once or twice a year on GRCh37.


> 2 and does transcript annotations mean the file homo_sapiens_refseq_vep_99_GRCh37.tar.gz? in fact I do not know when I st thedir_cache, which file it used, I know homo_sapiens_vep_99_GRCh37.tar.gz must be used, and refseq and merged maybe used buy the option of vep command?

`homo_sapiens_vep_99_GRCh37.tar.gz` contains only Ensembl transcripts (used by default) 
`homo_sapiens_refseq_vep_99_GRCh37.tar.gz` contains only RefSeq transcripts -> VEP uses this cache if you specify `--refseq` 
`homo_sapiens_merged_vep_99_GRCh37.tar.gz` contains both RefSeq and Ensembl transcripts -> VEP uses this cache if you specify `--merged` 
Cache files documentation can be found here: https://m.ensembl.org/info/docs/tools/vep/script/vep_cache.html 

> so cache in the following refer to which file, just one or two zip file?

It's a general explanation of all the cache files. The RefSeq cache (`homo_sapiens_refseq_vep_99_GRCh37.tar.gz`) has some limitations explained here: https://m.ensembl.org/info/docs/tools/vep/script/vep_cache.html and https://m.ensembl.org/info/docs/tools/vep/script/vep_other.html#refseq_limitations 

> 4 I tried to open file in the unzip files of the above , but it says it is binary, how can i open it?

Is there any particular reason why you want to open it? 

> 5 when doing hgvs, it needs the fasta file, so it needs to generate the hgvs, but not read from the cache directly?

When using a cache, VEP needs to use a FASTA file to generate the HGVS identifiers. All the other data is fetched from the cache.

**Comment by dglemos** [comment] 2021-02-17 14:25
I'm going to close the ticket. If you have more questions feel free to open a new one.
Best wishes,
Diana

**Closed by dglemos** 2021-02-17 14:25 UTC
