### ISSUE TITLE
get no SIFT scores with --sift b in version 110 after having it on version 107

### ISSUE THREAD

**Issue by sagitaninta** [Ensembl/ensembl-vep#1544] opened 2023-10-31 08:32 UTC
## Describe the issue
I tried to get a list of impact and consequences and SIFT scores of a certain allele in coding sequences of _Bos taurus_. I did this for alternative alleles A, C, G, T in all coding sequences I got from a GFF3 file from version un Ensembl. 

When I did this using VEP version 107 a year ago, it worked just fine. But when I re-do this with the latest version of VEP, which is 110, I got no SIFT scores for ALL alleles. The impact and consequences are there though. Where are the SIFT scores?

## Additional information
The info.txt for the bos_taurus cache I downloaded said "sift b" so it should have the SIFT score information.
```
species bos_taurus
assembly        ARS-UCD1.2
sift    b
polyphen
source_sift     sift
source_genebuild        2018-12
source_assembly ARS-UCD1.2
variation_cols  chr,variation_name,failed,somatic,start,end,allele_string,strand,clin_sig,phenotype_or_disease,clin_sig_allele,pubmed,var_synonyms
source_dbSNP    150
var_type        tabix
```
I also tried running `vep -id rs1600654359 --assembly GRCh37 --database --sift b --polyphen b -o rs1600654359_vep_output.tab --tab` and got this message:
```
-------------------- EXCEPTION --------------------
MSG: Cannot connect to the Ensembl MySQL server at ensembldb.ensembl.org:3337; check your settings & DBI error message: Lost connection to MySQL server at 'reading authorization packet', system error: 104
STACK Bio::EnsEMBL::Registry::load_registry_from_db /home/mdn487/.conda/envs/ensembl-vep/share/ensembl-vep-110.1-0/Bio/EnsEMBL/Registry.pm:1771
STACK Bio::EnsEMBL::VEP::BaseVEP::registry /home/mdn487/.conda/envs/ensembl-vep/share/ensembl-vep-110.1-0/modules/Bio/EnsEMBL/VEP/BaseVEP.pm:283
STACK Bio::EnsEMBL::VEP::BaseRunner::setup_db_connection /home/mdn487/.conda/envs/ensembl-vep/share/ensembl-vep-110.1-0/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:120
STACK Bio::EnsEMBL::VEP::Runner::init /home/mdn487/.conda/envs/ensembl-vep/share/ensembl-vep-110.1-0/modules/Bio/EnsEMBL/VEP/Runner.pm:123
STACK Bio::EnsEMBL::VEP::Runner::run /home/mdn487/.conda/envs/ensembl-vep/share/ensembl-vep-110.1-0/modules/Bio/EnsEMBL/VEP/Runner.pm:200
STACK toplevel /home/mdn487/.conda/envs/ensembl-vep/bin/vep:46
Date (localtime)    = Tue Oct 31 09:03:48 2023
Ensembl API version = 110
---------------------------------------------------
```
Probably because I am running this in a server that can only be connected via VPN.

### System
- VEP version: 110
- VEP Cache version: 110
- Perl version: [e.g. 5.26]
- OS: Red Hat Enterprise Linux 8.8 (Ootpa)
- tabix installed

### Full VEP command line
```
./vep -i $input --offline --cache --dir .. --species "bos_taurus" --force_overwrite --sift b --tab --fields Location,Uploaded_variation,Allele,Consequence,CANONICAL,IMPACT,SIFT -o STDOUT | grep -v "##"
```

### Full error message
No error message, the command works just fine. The SIFT scores just are not there.

### Data files (if applicable)
The sample input file looks like this:
```
1       346890  346890  N/A
1       346891  346891  N/A
1       346923  346923  N/A
1       346924  346924  N/A
1       346925  346925  N/A
1       346926  346926  N/A
1       350302  350302  G/A
1       350320  350320  G/A
1       350335  350335  G/A
1       350344  350344  C/A
```
The output file of that command looks like this
```
#Location       Uploaded_variation      Allele  Consequence     CANONICAL       IMPACT  SIFT
1:346890        1_346890_N/A    A       splice_acceptor_variant -       HIGH    -
1:346890        1_346890_N/A    A       coding_sequence_variant -       MODIFIER        -
1:346891        1_346891_N/A    A       splice_acceptor_variant -       HIGH    -
1:346891        1_346891_N/A    A       coding_sequence_variant -       MODIFIER        -
1:346923        1_346923_N/A    A       splice_donor_variant    -       HIGH    -
1:346923        1_346923_N/A    A       splice_region_variant,coding_sequence_variant   -       LOW     -
1:346924        1_346924_N/A    A       splice_donor_variant    -       HIGH    -
1:346924        1_346924_N/A    A       splice_region_variant,coding_sequence_variant   -       LOW     -
1:346925        1_346925_N/A    A       splice_region_variant,coding_sequence_variant   -       LOW     -
1:346925        1_346925_N/A    A       splice_acceptor_variant -       HIGH    -
1:346926        1_346926_N/A    A       splice_region_variant,coding_sequence_variant   -       LOW     -
1:346926        1_346926_N/A    A       splice_acceptor_variant -       HIGH    -
1:350302        1_350302_G/A    A       upstream_gene_variant   -       MODIFIER        -
1:350302        1_350302_G/A    A       stop_gained     -       HIGH    -
1:350320        1_350320_G/A    A       upstream_gene_variant   -       MODIFIER        -
1:350320        1_350320_G/A    A       stop_gained     -       HIGH    -
1:350335        1_350335_G/A    A       upstream_gene_variant   -       MODIFIER        -
1:350335        1_350335_G/A    A       stop_gained     -       HIGH    -
1:350344        1_350344_C/A    A       upstream_gene_variant   -       MODIFIER        -
1:350344        1_350344_C/A    A       stop_gained     -       HIGH    -
```
Should the SIFT has score when impact is high? Why the score wasn't there if the impact is HIGH?

Thank you in advance for your time and kind assistance!

**Comment by nakib103** [comment] 2023-11-02 13:12
Hi @sagitaninta ,

Thanks for your query!
I can confirm that I can re-produce the issue you are having. We are looking into this issue and once we have update we will let you know.

Best regards,
Nakib

**Comment by nakib103** [comment] 2024-02-12 09:59
Hello @sagitaninta,

Sorry for late reply. I have looked more into this and the difference you are seeing are due to update in SIFT version. In Ensembl release e109 we have update our SIFT version from 5.2.2 to 6.2.1. There are some variants that had predictions before but with new version now they do not. You will also see changes between prediction too. We have a blog post sharing the statistics in human - 
https://www.ensembl.info/2023/01/25/polyphen-2-and-sift-scores-are-changing-in-release-109/

If you want the same SIFT results I would advise to use VEP v108 or earlier. But for latest SIFT results you should use the later versions.

Best regards,
Nakib

**Comment by sagitaninta** [comment] 2024-02-12 10:42
Hello Nakib, many thanks for coming back to me.

I would like to show you that I have problem opening the blog post, but I get the point.
![Screenshot 2024-02-12 at 11 40 14](https://github.com/Ensembl/ensembl-vep/assets/28356594/874a4895-1668-44b2-ab8e-b05a3d82c426)

Does this mean for the 111 that I think the latest Ensembl release right now, the SIFT is already updated? Or if I wanna use SIFT score of Bos taurus ARS-UCD1.2 genome I always need to go back to version <= 108?

**Comment by nakib103** [comment] 2024-02-12 10:55
Hi @sagitaninta,

Yes, e111 have the update SIFT version (v6.2.1). We are using this version from e109 and onwards. 
If you want to use earlier SIFT version (v5.2.2) you need to use <= e108.

Note: Bos taurus assembly also got updated to **ARS-UCD1.3** in e111.

Best regards,
Nakib

**Comment by sagitaninta** [comment] 2024-02-16 17:29
Wait, I have been using vep version 110 with GFF and cache of version 110 both. Shouldn't I already have SIFT v6.2.1 on this vep 110 I have just installed from [here](https://github.com/Ensembl/ensembl-vep/releases/tag/release%2F110.1)? But the SIFT scores still does not show in my input file anyways?

**Comment by nakib103** [comment] 2024-02-19 10:34
Hello @sagitaninta,

Yes, if you are using 110 than you should be getting the new v6.2.1 SIFT version scores. 
Sorry, I did not get your second question. What do you mean by SIFT scores not showing in the input file? 

Best regards,
Nakib

**Comment by sagitaninta** [comment] 2024-02-19 14:13
Oh sorry I mean using the input said in the first message in this issue (https://github.com/Ensembl/ensembl-vep/issues/1544#issue-1969910176), the output does not show any SIFT scores despite the site I was throwing in the input file was marked as HIGH in impact with vep 110. This is already done using bos taurus vep 110 cache and vep version 110 to get it and there is still no SIFT score.

**Comment by nakib103** [comment] 2024-02-19 15:12
Oh, okay. So, as I mentioned, in 110 you will be getting SIFT scores from the new v6.2.1 and they are different from the old scores. In some cases there are no predictions for a variant in the new version but it had prediction in old version. So it is expected you are not getting SIFT scores for some variant.

The impact HIGH does not relate with SIFT scores. It is related to consequence and each consequence have a specific impact ratings. You can find more information here - https://www.ensembl.org/info/genome/variation/prediction/predicted_data.html

**Comment by nakib103** [comment] 2024-03-25 14:31
Hello @sagitaninta,

I will close this issue for now. But if you face any further problems feel free to open a new one.

Best regards,
Nakib

**Closed by nakib103** 2024-03-25 14:31 UTC
